"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const repoRoot = path.resolve(__dirname, "..");
const embeddedPluginUi = fs.readFileSync(path.join(repoRoot, "public", "app-embedded-plugin-ui.js"), "utf8");
const wardrobeUi = fs.readFileSync(path.join(repoRoot, "public", "app-wardrobe-ui.js"), "utf8");
const automationUi = fs.readFileSync(path.join(repoRoot, "public", "app-automation-ui.js"), "utf8");
const composerContextUi = fs.readFileSync(path.join(repoRoot, "public", "app-composer-context-ui.js"), "utf8");
const wireStartUi = fs.readFileSync(path.join(repoRoot, "public", "app-wire-start-ui.js"), "utf8");
const navigationSearchUi = fs.readFileSync(path.join(repoRoot, "public", "app-navigation-search-ui.js"), "utf8");
const pluginTopicsUi = fs.readFileSync(path.join(repoRoot, "public", "app-plugin-topics-ui.js"), "utf8");
const sidebarTaskUi = fs.readFileSync(path.join(repoRoot, "public", "app-sidebar-task-ui.js"), "utf8");
const uploadSidebarUi = fs.readFileSync(path.join(repoRoot, "public", "app-upload-sidebar-ui.js"), "utf8");
const platformUi = fs.readFileSync(path.join(repoRoot, "public", "app-platform-ui.js"), "utf8");
const indexHtml = fs.readFileSync(path.join(repoRoot, "public", "index.html"), "utf8");
const stylesCss = fs.readFileSync(path.join(repoRoot, "public", "styles.css"), "utf8");

assert.match(indexHtml, /id="bottomCodexMode"/);
assert.match(indexHtml, /id="bottomFinanceMode"/);
assert.match(indexHtml, /id="bottomEmailMode"/);
assert.match(indexHtml, /id="bottomGrowthMode"/);
assert.match(indexHtml, /id="bottomMoiraMode"/);
assert.match(indexHtml, /app-embedded-plugin-ui\.js\?v=/);

assert.match(embeddedPluginUi, /"codex-mobile"/);
assert.match(embeddedPluginUi, /viewMode: "codex"/);
assert.match(embeddedPluginUi, /manifestPath: "\/api\/hermes-plugins\/codex-mobile\/manifest"/);
assert.match(embeddedPluginUi, /backResultEventType: "codex-mobile\.plugin\.back_result"/);
assert.match(embeddedPluginUi, /refreshRequiredEventType: "codex-mobile\.plugin\.refresh_required"/);
assert.match(embeddedPluginUi, /residentFrame: true/);
assert.match(embeddedPluginUi, /id: "finance"/);
assert.match(embeddedPluginUi, /viewMode: "finance"/);
assert.match(embeddedPluginUi, /manifestPath: "\/api\/hermes-plugins\/finance\/manifest"/);
assert.match(embeddedPluginUi, /navigationEventType: "finance\.plugin\.navigation"/);
assert.match(embeddedPluginUi, /backResultEventType: "finance\.plugin\.back_result"/);
assert.match(embeddedPluginUi, /refreshRequiredEventType: "finance\.plugin\.refresh_required"/);
assert.match(embeddedPluginUi, /id: "finance"[\s\S]*?residentFrame: true/);
assert.match(embeddedPluginUi, /id: "email"/);
assert.match(embeddedPluginUi, /viewMode: "email"/);
assert.match(embeddedPluginUi, /manifestPath: "\/api\/hermes-plugins\/email\/manifest"/);
assert.match(embeddedPluginUi, /navigationEventType: "email\.plugin\.navigation"/);
assert.match(embeddedPluginUi, /backResultEventType: "email\.plugin\.back_result"/);
assert.match(embeddedPluginUi, /refreshRequiredEventType: "email\.plugin\.refresh_required"/);
assert.match(embeddedPluginUi, /id: "email"[\s\S]*?residentFrame: true/);
assert.match(embeddedPluginUi, /id: "health"[\s\S]*?residentFrame: true/);
assert.match(embeddedPluginUi, /id: "note"[\s\S]*?residentFrame: true/);
assert.match(embeddedPluginUi, /id: "growth"/);
assert.match(embeddedPluginUi, /viewMode: "growth"/);
assert.match(embeddedPluginUi, /manifestPath: "\/api\/hermes-plugins\/growth\/manifest"/);
assert.match(embeddedPluginUi, /navigationEventType: "growth\.plugin\.navigation"/);
assert.match(embeddedPluginUi, /backResultEventType: "growth\.plugin\.back_result"/);
assert.match(embeddedPluginUi, /refreshRequiredEventType: "growth\.plugin\.refresh_required"/);
assert.match(embeddedPluginUi, /id: "growth"[\s\S]*?residentFrame: true/);
assert.match(embeddedPluginUi, /id: "moira"/);
assert.match(embeddedPluginUi, /viewMode: "moira"/);
assert.match(embeddedPluginUi, /manifestPath: "\/api\/hermes-plugins\/moira\/manifest"/);
assert.match(embeddedPluginUi, /navigationEventType: "moira\.plugin\.navigation"/);
assert.match(embeddedPluginUi, /backResultEventType: "moira\.plugin\.back_result"/);
assert.match(embeddedPluginUi, /refreshRequiredEventType: "moira\.plugin\.refresh_required"/);
assert.match(embeddedPluginUi, /id: "moira"[\s\S]*?residentFrame: true/);
assert.match(embeddedPluginUi, /function renderEmbeddedPluginView\(def\)/);
assert.match(embeddedPluginUi, /configureComposer\(\{ enabled: false, hidden: true, placeholder: `\$\{def\.title\} 插件` \}\)/);
assert.match(embeddedPluginUi, /function loadEmbeddedPluginManifest\(def, options = {}\)/);
assert.match(embeddedPluginUi, /appOrigin: window\.location\.origin/);
assert.match(embeddedPluginUi, /function embeddedPluginAppearanceForLaunch\(\)/);
assert.match(embeddedPluginUi, /const themeMode = \["system", "dark", "light"\]/);
assert.match(embeddedPluginUi, /themeMode === "system"[\s\S]*?prefers-color-scheme: dark[\s\S]*?\? "dark" : "light"/);
assert.match(embeddedPluginUi, /function embeddedPluginAppearanceKey\(appearance = embeddedPluginAppearanceForLaunch\(\)\)/);
assert.match(embeddedPluginUi, /function embeddedPluginManifestMatchesLaunchContext\(record, workspaceId, appearanceKey = embeddedPluginAppearanceKey\(\)\)/);
assert.match(embeddedPluginUi, /function embeddedPluginProxyEntryWorkspaceMatches\(entryUrl = "", workspaceId = ""\)/);
assert.match(embeddedPluginUi, /parsed\.pathname\.startsWith\("\/api\/hermes-plugins\/"\)/);
assert.match(embeddedPluginUi, /const entryWorkspaceId = parsed\.searchParams\.get\("workspaceId"\) \|\| parsed\.searchParams\.get\("workspace_id"\) \|\| ""/);
assert.match(embeddedPluginUi, /embeddedPluginProxyEntryWorkspaceMatches\(record\?\.manifest\?\.entry\?\.url, workspaceId\)/);
assert.match(embeddedPluginUi, /function embeddedPluginCurrentManifest\(def, appearanceKey = embeddedPluginAppearanceKey\(\)\)/);
assert.match(embeddedPluginUi, /rawFontSize === "standard"[\s\S]*\? "default"/);
assert.match(embeddedPluginUi, /appearanceTheme: appearance\.theme/);
assert.match(embeddedPluginUi, /appearanceFontSize: appearance\.fontSize/);
assert.match(embeddedPluginUi, /record\.manifestAppearanceKey = appearanceKey/);
assert.match(embeddedPluginUi, /embeddedPluginManifestMatchesLaunchContext\(record, workspaceId, appearanceKey\)/);
assert.match(embeddedPluginUi, /return embeddedPluginManifestMatchesLaunchContext\(record, workspaceId, appearanceKey\) \? record\.manifest : null/);
assert.match(embeddedPluginUi, /function embeddedPluginResidentShellMatchesLaunchContext\(def, workspaceId, appearanceKey = embeddedPluginAppearanceKey\(\)\)/);
assert.match(embeddedPluginUi, /if \(!def\?\.residentFrame\) return false/);
assert.match(embeddedPluginUi, /renderedWorkspaceId === String\(workspaceId \|\| "owner"\)\.trim\(\)/);
assert.match(embeddedPluginUi, /renderedAppearanceKey === String\(appearanceKey \|\| ""\)\.trim\(\)/);
assert.match(embeddedPluginUi, /embeddedPluginManifestMatchesLaunchContext\(record, state\.selectedWorkspaceId \|\| "owner"\)/);
assert.match(embeddedPluginUi, /if \(record\.shellNode\) discardEmbeddedPluginShell\(def\)/);
assert.match(embeddedPluginUi, /function resetEmbeddedPluginsForWorkspaceChange\(\)/);
assert.match(embeddedPluginUi, /Object\.values\(EMBEDDED_PLUGIN_DEFS\)\.forEach\(\(def\) => \{/);
assert.match(embeddedPluginUi, /discardEmbeddedPluginShell\(def\);[\s\S]*manifest: null/);
assert.match(embeddedPluginUi, /embeddedPluginHost\(def\)\.innerHTML = ""/);
assert.match(embeddedPluginUi, /setEmbeddedPluginHostVisible\(def, false\)/);
assert.match(embeddedPluginUi, /function embeddedPluginUsesLaunchToken\(manifest\)/);
assert.match(embeddedPluginUi, /codexPluginLaunch/);
assert.match(embeddedPluginUi, /function embeddedPluginHost\(def\)/);
assert.match(embeddedPluginUi, /main\.insertBefore\(host, conversation\)/);
assert.match(embeddedPluginUi, /function scheduleEmbeddedPluginLaunchHealthCheck\(def, frame, loadedAt = Date\.now\(\)\)/);
assert.match(embeddedPluginUi, /Number\(def\?\.launchHealthTimeoutMs \|\| 30000\)/);
assert.match(embeddedPluginUi, /function refreshEmbeddedPluginFrameFromFreshManifest\(def\)/);
assert.match(embeddedPluginUi, /function requestEmbeddedPluginHealthRefresh\(def, payload = {}\)/);
assert.match(embeddedPluginUi, /requestEmbeddedPluginHealthRefresh\(def\)/);
assert.match(embeddedPluginUi, /function ensureEmbeddedPluginNavigationBridge\(def\)/);
assert.match(embeddedPluginUi, /def\.navigationEventType/);
assert.match(embeddedPluginUi, /function normalizeEmbeddedPluginVoiceInputCapability\(def, payload = \{\}\)/);
assert.match(embeddedPluginUi, /function sendEmbeddedPluginVoiceInputAction\(action, payload = \{\}, def = embeddedPluginDefByView\(\)\)/);
assert.match(embeddedPluginUi, /voice_input\.capability_query/);
assert.match(embeddedPluginUi, /voice_input\.start_request/);
assert.match(embeddedPluginUi, /voice_input\.stop_request/);
assert.match(embeddedPluginUi, /voice_input\.commit_result/);
assert.match(embeddedPluginUi, /function embeddedPluginPreviewFullscreenRequested\(payload = \{\}\)/);
assert.match(embeddedPluginUi, /payload\.previewFullscreen[\s\S]*?payload\.fullscreenPreview[\s\S]*?payload\.imagePreviewFullscreen/);
assert.match(embeddedPluginUi, /data\.type === "hermes\.plugin\.preview" \|\| data\.type === "hermes\.plugin\.fullscreen" \|\| data\.type === `\$\{def\.id\}\.plugin\.preview`/);
assert.match(embeddedPluginUi, /function embeddedPluginPreviewFullscreenActive\(def = embeddedPluginDefByView\(\)\)/);
assert.match(embeddedPluginUi, /function embeddedPluginViewportPayload\(def, frame, reason = "layout"\)/);
assert.match(embeddedPluginUi, /type: "hermes\.plugin\.viewport"/);
assert.match(embeddedPluginUi, /appearance: embeddedPluginAppearanceForLaunch\(\)/);
assert.match(embeddedPluginUi, /visualViewportKeyboardMetrics/);
assert.match(embeddedPluginUi, /workspaceId: embeddedPluginCurrentWorkspaceId\(\)/);
assert.match(embeddedPluginUi, /footer:[\s\S]*?pluginContextBottom: embeddedPluginCssPx\("--plugin-context-main-bottom"\)/);
assert.match(embeddedPluginUi, /function embeddedPluginHostBottomSafeArea\(def, footerVisible, bottomLayout = \{\}\)/);
assert.match(embeddedPluginUi, /safeAreaBottom: hostBottomSafeArea/);
assert.match(embeddedPluginUi, /function sendEmbeddedPluginViewportMetrics\(def = embeddedPluginDefByView\(\), reason = "layout"\)/);
assert.match(embeddedPluginUi, /frame\.contentWindow\.postMessage\(embeddedPluginViewportPayload\(def, frame, reason\), origin\)/);
assert.match(embeddedPluginUi, /function resetEmbeddedPluginHostScroll\(reason = "layout"\)/);
assert.match(embeddedPluginUi, /window\.scrollTo\(0, 0\)/);
assert.match(embeddedPluginUi, /lastHostScrollResetAt = Date\.now\(\)/);
assert.match(embeddedPluginUi, /function scheduleEmbeddedPluginViewportBroadcast\(reason = "layout", delay = 0\)/);
assert.match(embeddedPluginUi, /function settleEmbeddedPluginViewportBroadcast\(reason = "layout"\)/);
assert.match(embeddedPluginUi, /\[0, 40, 80, 180, 360, 700, 1200\]\.forEach\(\(delay\) => \{/);
assert.match(embeddedPluginUi, /resetEmbeddedPluginHostScroll\(reason\);[\s\S]*sendEmbeddedPluginViewportMetrics\(def, reason\)/);
assert.match(embeddedPluginUi, /scheduleEmbeddedPluginViewportBroadcast\("host_visible", 0\)/);
assert.match(embeddedPluginUi, /scheduleEmbeddedPluginViewportBroadcast\("frame_attach", 0\)/);
assert.match(embeddedPluginUi, /sendEmbeddedPluginViewportMetrics\(def, "frame_load"\)/);
assert.match(embeddedPluginUi, /scheduleEmbeddedPluginViewportBroadcast\("frame_render", 0\)/);
assert.match(embeddedPluginUi, /function updateEmbeddedPluginBackResultState\(def, payload = {}\)/);
assert.match(embeddedPluginUi, /def\.backResultEventType/);
assert.match(embeddedPluginUi, /record\.canGoBack = false/);
assert.match(embeddedPluginUi, /record\.previewFullscreen = false/);
assert.match(embeddedPluginUi, /function requestEmbeddedPluginRefresh\(def, payload = {}\)/);
assert.match(embeddedPluginUi, /function embeddedPluginRefreshRequiredEventType\(def\)/);
assert.match(embeddedPluginUi, /def\?\.refreshRequiredEventType \|\| `\$\{def\?\.id \|\| "plugin"\}\.plugin\.refresh_required`/);
assert.match(embeddedPluginUi, /function embeddedPluginRouteFromRefreshPayload\(payload = {}\)/);
assert.match(embeddedPluginUi, /if \(record\.loading\) \{/);
assert.match(embeddedPluginUi, /refreshWarmupSuppressMs \|\| 10000/);
assert.match(embeddedPluginUi, /record\.frameCreatedAt = Date\.now\(\)/);
assert.match(embeddedPluginUi, /record\.renderedWorkspaceId = workspaceId/);
assert.match(embeddedPluginUi, /record\.renderedAppearanceKey = appearanceKey/);
assert.match(embeddedPluginUi, /const cooldownMs = Number\(def\?\.refreshCooldownMs \|\| 60000\)/);
assert.match(embeddedPluginUi, /record\.lastRefreshSuppressedAt = now/);
assert.match(embeddedPluginUi, /record\.lastRefreshRequestedAt = now/);
assert.match(embeddedPluginUi, /currentFrameUsesEntry/);
assert.match(embeddedPluginUi, /data\.type === embeddedPluginRefreshRequiredEventType\(def\)[\s\S]*requestEmbeddedPluginRefresh\(def, Object\.assign\(\{ force: true \}, data\)\)/);
assert.match(embeddedPluginUi, /record\.manifestFreshForFrame = false/);
assert.match(embeddedPluginUi, /record\.checked = false/);
assert.match(embeddedPluginUi, /state\.viewMode !== def\.viewMode[\s\S]*discardEmbeddedPluginShell\(def\)/);
assert.match(embeddedPluginUi, /refreshEmbeddedPluginFrameFromFreshManifest\(def\)/);
assert.match(embeddedPluginUi, /const hasShell = Boolean\(currentEmbeddedPluginShell\(def\)\)/);
assert.match(embeddedPluginUi, /const hasShell = Boolean\(currentEmbeddedPluginShell\(def\)\);[\s\S]*?if \(hasShell\) setEmbeddedPluginHostVisible\(def, true\);[\s\S]*?else showEmbeddedPluginLoadingSurface\(def\);/);
assert.match(embeddedPluginUi, /if \(!pluginManifest && embeddedPluginResidentShellMatchesLaunchContext\(def, workspaceId, appearanceKey\)\) \{[\s\S]*?attachEmbeddedPluginShell\(def, record\.renderedEntryUrl\)/);
assert.match(embeddedPluginUi, /function setEmbeddedPluginOpenRoute\(def, route = {}\)/);
assert.match(embeddedPluginUi, /if \(record\.openRoute\) record\.canGoBack = true;/);
assert.match(embeddedPluginUi, /function embeddedPluginEntryUrlForFrame\(def, manifest\)/);
assert.match(embeddedPluginUi, /parsed\.searchParams\.set\("pluginId", def\.id\)/);
assert.match(embeddedPluginUi, /\["pluginActionId", "pluginRoute", "pluginItemId", "pluginThreadId", "pluginTaskId", "sourceTurnId"\]\.forEach/);
assert.match(wardrobeUi, /function setWardrobePluginOpenRoute\(route = {}\)/);
assert.match(wardrobeUi, /if \(state\.wardrobePluginOpenRoute\) state\.wardrobePluginCanGoBack = true;/);
assert.match(wardrobeUi, /function wardrobePluginEntryUrlForFrame\(entryUrl = ""\)/);
assert.match(wardrobeUi, /\["pluginActionId", "pluginRoute", "pluginItemId", "pluginThreadId", "pluginTaskId", "sourceTurnId"\]\.forEach/);
assert.match(wardrobeUi, /parsed\.searchParams\.set\("pluginId", "wardrobe"\)/);
assert.match(wardrobeUi, /const entryUrl = wardrobePluginEntryUrlForFrame\(String\(pluginManifest\.entry\?\.url \|\| ""\)\)/);
assert.match(wardrobeUi, /currentFrameUsesEntry/);
assert.match(embeddedPluginUi, /function captureEmbeddedPluginReturnRoute\(def\)/);
assert.match(embeddedPluginUi, /function defaultEmbeddedPluginReturnRoute\(def\)/);
assert.match(embeddedPluginUi, /if \(def\?\.id !== "codex-mobile"\) return null/);
assert.match(embeddedPluginUi, /viewMode: "tasks",[\s\S]*?singleWindowMode: "chat",[\s\S]*?currentTaskGroupId: ""/);
assert.match(embeddedPluginUi, /function ensureEmbeddedPluginReturnRoute\(def\)/);
assert.match(embeddedPluginUi, /function rememberEmbeddedPluginReturnRoute\(def\)/);
assert.match(embeddedPluginUi, /function embeddedPluginOuterBackActive\(def = embeddedPluginDefByView\(\)\)/);
assert.match(embeddedPluginUi, /function restoreEmbeddedPluginReturnRoute\(def = embeddedPluginDefByView\(\)\)/);
assert.match(embeddedPluginUi, /embeddedPluginRecord\(def\.id\)\.returnRoute = route/);
assert.match(embeddedPluginUi, /parkEmbeddedPluginShell\(def\)/);
assert.match(embeddedPluginUi, /restoreTaskListThreadFromCache\(\{ stickToBottom: false, restoreScrollTop: route\.conversationScrollTop \}\)/);
assert.match(embeddedPluginUi, /loadSelectedView\(\{ forceTaskListReload: true, skipSingleWindowCache: false \}\)\.catch\(showError\)/);
assert.match(embeddedPluginUi, /renderActionInboxView\(\)/);
assert.match(embeddedPluginUi, /type: "hermes\.plugin\.back"/);
assert.match(embeddedPluginUi, /record\.backRequestSeq = seq/);
assert.match(embeddedPluginUi, /Number\(record\.navigationLastAt \|\| 0\) > requestedAt/);
assert.match(embeddedPluginUi, /const pluginContextBack = typeof pluginContextBackNavigationActive === "function" && pluginContextBackNavigationActive\(\)/);
assert.match(embeddedPluginUi, /if \(record\.returnRoute && !pluginContextBack\) \{[\s\S]*?restoreEmbeddedPluginReturnRoute\(def\)/);
assert.match(wardrobeUi, /state\.wardrobePluginBackRequestSeq = seq/);
assert.match(wardrobeUi, /Number\(state\.wardrobePluginNavigationLastAt \|\| 0\) > requestedAt/);
assert.match(wardrobeUi, /const pluginContextBack = typeof pluginContextBackNavigationActive === "function" && pluginContextBackNavigationActive\(\)/);
assert.match(embeddedPluginUi, /class="embedded-plugin-frame"/);
assert.match(embeddedPluginUi, /class="embedded-plugin-shell is-loading"/);
assert.match(embeddedPluginUi, /closest\("\.embedded-plugin-shell"\)\?\.classList\.remove\("is-loading"\)/);
assert.match(embeddedPluginUi, /sandbox="allow-same-origin allow-scripts allow-forms allow-downloads allow-modals"/);
assert.match(composerContextUi, /scheduleEmbeddedPluginViewportBroadcast\(active \? "host_keyboard" : "host_keyboard_clear", 0\)/);
assert.match(composerContextUi, /scheduleEmbeddedPluginViewportBroadcast\("plugin_context_viewport", 0\)/);
assert.match(embeddedPluginUi, /function embeddedPluginListState\(\)/);
assert.match(embeddedPluginUi, /async function refreshEmbeddedPluginList\(options = \{\}\)/);
assert.match(embeddedPluginUi, /\/api\/hermes-plugins\?\$\{params\.toString\(\)\}/);
assert.match(embeddedPluginUi, /function embeddedPluginNavigationAvailable\(def\)/);
assert.match(embeddedPluginUi, /function embeddedPluginCurrentWorkspaceId\(\)/);
assert.match(embeddedPluginUi, /function codexPluginNavigationAvailable\(\)/);
assert.match(embeddedPluginUi, /return Boolean\(state\.auth\?\.isOwner && embeddedPluginCurrentWorkspaceId\(\) === "owner"\)/);
assert.match(embeddedPluginUi, /if \(def\?\.id === "codex-mobile"\) return codexPluginNavigationAvailable\(\)/);
assert.match(embeddedPluginUi, /if \(state\.auth\?\.isOwner && embeddedPluginCurrentWorkspaceId\(\) === "owner"\) return true/);
assert.match(embeddedPluginUi, /embeddedPluginListedForWorkspace\(def\?\.id \|\| ""\)/);
assert.match(embeddedPluginUi, /function renderCodexPluginView\(\)/);
assert.match(embeddedPluginUi, /function updateCodexPluginNavigationAvailability\(\)/);
assert.match(embeddedPluginUi, /const available = codexPluginNavigationAvailable\(\)/);
assert.match(embeddedPluginUi, /function parkCodexPluginShell\(\)/);
assert.match(embeddedPluginUi, /function parkEmbeddedPluginShell\(def\) \{[\s\S]*?setEmbeddedPluginHostVisible\(def, false\);[\s\S]*?if \(!shell\) return false;/);
assert.match(embeddedPluginUi, /function codexPluginBackActive\(\)/);
assert.match(embeddedPluginUi, /function codexPluginOuterBackActive\(\)/);
assert.match(embeddedPluginUi, /function rememberCodexPluginReturnRoute\(\)/);
assert.match(embeddedPluginUi, /function ensureCodexPluginReturnRoute\(\)/);
assert.match(embeddedPluginUi, /function setCodexPluginOpenRoute\(route = {}\)/);
assert.match(embeddedPluginUi, /function restoreCodexPluginReturnRoute\(\)/);
assert.match(embeddedPluginUi, /function sendCodexPluginBack\(\)/);
assert.match(embeddedPluginUi, /function sendCodexPluginBackOrReturn\(\)/);
assert.doesNotMatch(embeddedPluginUi, /if \(!pluginContextBack && codexPluginOuterBackActive\(\)\) return restoreCodexPluginReturnRoute\(\)/);
assert.match(embeddedPluginUi, /function sendCodexPluginBackOrReturn\(\) \{[\s\S]*?if \(sendCodexPluginBack\(\)\) return true;[\s\S]*?if \(pluginContextBack\) return false;[\s\S]*?return restoreCodexPluginReturnRoute\(\);/);
assert.match(embeddedPluginUi, /function renderCodexPluginView\(\) \{[\s\S]*?ensureCodexPluginReturnRoute\(\);[\s\S]*?renderEmbeddedPluginView\(EMBEDDED_PLUGIN_DEFS\["codex-mobile"\]\)/);
assert.match(embeddedPluginUi, /function renderFinancePluginView\(\)/);
assert.match(embeddedPluginUi, /function updateFinancePluginNavigationAvailability\(\)/);
assert.match(embeddedPluginUi, /const available = embeddedPluginNavigationAvailable\(def\)/);
assert.match(embeddedPluginUi, /function financePluginBackActive\(\)/);
assert.match(embeddedPluginUi, /function financePluginOuterBackActive\(\)/);
assert.match(embeddedPluginUi, /function rememberFinancePluginReturnRoute\(\)/);
assert.match(embeddedPluginUi, /function setFinancePluginOpenRoute\(route = {}\)/);
assert.match(embeddedPluginUi, /function restoreFinancePluginReturnRoute\(\)/);
assert.match(embeddedPluginUi, /function sendFinancePluginBack\(\)/);
assert.match(embeddedPluginUi, /function sendFinancePluginBackOrReturn\(\)/);
assert.match(embeddedPluginUi, /function renderEmailPluginView\(\)/);
assert.match(embeddedPluginUi, /function updateEmailPluginNavigationAvailability\(\)/);
assert.match(embeddedPluginUi, /function emailPluginBackActive\(\)/);
assert.match(embeddedPluginUi, /function emailPluginOuterBackActive\(\)/);
assert.match(embeddedPluginUi, /function rememberEmailPluginReturnRoute\(\)/);
assert.match(embeddedPluginUi, /function setEmailPluginOpenRoute\(route = \{\}\)/);
assert.match(embeddedPluginUi, /function restoreEmailPluginReturnRoute\(\)/);
assert.match(embeddedPluginUi, /function sendEmailPluginBack\(\)/);
assert.match(embeddedPluginUi, /function sendEmailPluginBackOrReturn\(\)/);
assert.match(embeddedPluginUi, /function renderGrowthPluginView\(\)/);
assert.match(embeddedPluginUi, /function updateGrowthPluginNavigationAvailability\(\)/);
assert.match(embeddedPluginUi, /function growthPluginBackActive\(\)/);
assert.match(embeddedPluginUi, /function growthPluginOuterBackActive\(\)/);
assert.match(embeddedPluginUi, /function rememberGrowthPluginReturnRoute\(\)/);
assert.match(embeddedPluginUi, /function setGrowthPluginOpenRoute\(route = \{\}\)/);
assert.match(embeddedPluginUi, /function embeddedPluginOpenRouteFromCurrentUrl\(def\)/);
assert.match(embeddedPluginUi, /routeView === "learning" && taskCardId[\s\S]*pluginRoute: "card", pluginItemId: taskCardId/);
assert.match(embeddedPluginUi, /routeView === def\.viewMode && \(pluginActionId \|\| pluginRoute \|\| pluginItemId\)/);
assert.match(embeddedPluginUi, /function renderMoiraPluginView\(\)/);
assert.match(embeddedPluginUi, /function updateMoiraPluginNavigationAvailability\(\)/);
assert.match(embeddedPluginUi, /function moiraPluginBackActive\(\)/);
assert.match(embeddedPluginUi, /function moiraPluginOuterBackActive\(\)/);
assert.match(embeddedPluginUi, /function rememberMoiraPluginReturnRoute\(\)/);
assert.match(embeddedPluginUi, /function setMoiraPluginOpenRoute\(route = \{\}\)/);
assert.match(embeddedPluginUi, /function restoreMoiraPluginReturnRoute\(\)/);
assert.match(embeddedPluginUi, /function sendMoiraPluginBack\(\)/);
assert.match(embeddedPluginUi, /function sendMoiraPluginBackOrReturn\(\)/);
assert.match(embeddedPluginUi, /function renderEmbeddedPluginFrame\(def, manifest, entryUrl = embeddedPluginEntryUrlForFrame\(def, manifest\)\)/);
assert.match(embeddedPluginUi, /src="\$\{escapeHtml\(entryUrl\)\}"/);
assert.match(embeddedPluginUi, /function restoreGrowthPluginReturnRoute\(\)/);
assert.match(embeddedPluginUi, /function sendGrowthPluginBack\(\)/);
assert.match(embeddedPluginUi, /function sendGrowthPluginBackOrReturn\(\)/);
assert.doesNotMatch(embeddedPluginUi, /window\.open/);
assert.doesNotMatch(embeddedPluginUi, /target="_blank"/);
assert.doesNotMatch(embeddedPluginUi, /access_key|Authorization|Bearer/);

assert.match(automationUi, /const codex = state\.viewMode === "codex"/);
assert.match(automationUi, /const finance = state\.viewMode === "finance"/);
assert.match(automationUi, /const email = state\.viewMode === "email"/);
assert.match(automationUi, /const growth = state\.viewMode === "growth"/);
assert.match(automationUi, /const moira = state\.viewMode === "moira"/);
assert.match(automationUi, /parkCodexPluginShell\(\)/);
assert.match(automationUi, /parkFinancePluginShell\(\)/);
assert.match(automationUi, /parkEmailPluginShell\(\)/);
assert.match(automationUi, /parkGrowthPluginShell\(\)/);
assert.match(automationUi, /parkMoiraPluginShell\(\)/);
assert.match(automationUi, /renderCodexPluginView\(\)/);
assert.match(automationUi, /renderFinancePluginView\(\)/);
assert.match(automationUi, /renderEmailPluginView\(\)/);
assert.match(automationUi, /renderGrowthPluginView\(\)/);
assert.match(automationUi, /renderMoiraPluginView\(\)/);
assert.match(wireStartUi, /bottomCodexMode/);
assert.match(wireStartUi, /bottomFinanceMode/);
assert.match(wireStartUi, /bottomEmailMode/);
assert.match(wireStartUi, /bottomGrowthMode/);
assert.match(wireStartUi, /bottomMoiraMode/);
assert.match(wireStartUi, /resetEmbeddedPluginsForWorkspaceChange\(\)/);
assert.match(wireStartUi, /state\.selectedWorkspaceId = event\.target\.value;[\s\S]*resetEmbeddedPluginsForWorkspaceChange\(\)/);
assert.match(wireStartUi, /rememberCodexPluginReturnRoute\(\)/);
assert.match(wireStartUi, /rememberFinancePluginReturnRoute\(\)/);
assert.match(wireStartUi, /rememberEmailPluginReturnRoute\(\)/);
assert.match(wireStartUi, /rememberGrowthPluginReturnRoute\(\)/);
assert.match(wireStartUi, /rememberMoiraPluginReturnRoute\(\)/);
assert.match(navigationSearchUi, /codexPluginBackActive\(\)/);
assert.match(navigationSearchUi, /codexPluginOuterBackActive\(\)/);
assert.match(navigationSearchUi, /financePluginBackActive\(\)/);
assert.match(navigationSearchUi, /financePluginOuterBackActive\(\)/);
assert.match(navigationSearchUi, /emailPluginBackActive\(\)/);
assert.match(navigationSearchUi, /emailPluginOuterBackActive\(\)/);
assert.match(navigationSearchUi, /healthPluginBackActive\(\)/);
assert.match(navigationSearchUi, /healthPluginOuterBackActive\(\)/);
assert.match(navigationSearchUi, /growthPluginBackActive\(\)/);
assert.match(navigationSearchUi, /growthPluginOuterBackActive\(\)/);
assert.match(navigationSearchUi, /moiraPluginBackActive\(\)/);
assert.match(navigationSearchUi, /moiraPluginOuterBackActive\(\)/);
assert.match(navigationSearchUi, /function updateTopicPluginDockChrome\(taskList\)/);
assert.match(navigationSearchUi, /sidebarOpen = \$\("sidebar"\)\?\.classList\.contains\("open"\)/);
assert.match(navigationSearchUi, /pluginTopicDefForViewMode\(state\.viewMode\)/);
assert.match(navigationSearchUi, /pluginTopicBottomButtonId\(pluginContextDef\)/);
assert.match(navigationSearchUi, /const externalPluginContextNav = Boolean\(pluginContextDef && pluginContextButtonId\)/);
assert.match(navigationSearchUi, /const directoryContextNav = state\.viewMode === "projects" && Boolean\(state\.directoryPluginContextActive\)/);
assert.match(navigationSearchUi, /const pluginContextActive = externalPluginContextNav \|\| directoryContextNav;/);
assert.match(navigationSearchUi, /const pluginContextNav = false;/);
assert.match(navigationSearchUi, /plugin-context-nav-mode/);
assert.match(navigationSearchUi, /embeddedPluginPreviewFullscreenActive\(\)/);
assert.match(navigationSearchUi, /app\?\.classList\.toggle\("embedded-plugin-preview-fullscreen-active", embeddedPluginPreviewFullscreen\)/);
assert.match(navigationSearchUi, /const pluginBack = wardrobePluginBack \|\| wardrobePluginOuterBack/);
assert.match(navigationSearchUi, /codexPluginBack \|\| codexPluginOuterBack \|\| financePluginBack \|\| financePluginOuterBack \|\| emailPluginBack \|\| emailPluginOuterBack/);
assert.match(navigationSearchUi, /growthPluginBack \|\| growthPluginOuterBack \|\| moiraPluginBack \|\| moiraPluginOuterBack/);
assert.match(navigationSearchUi, /\|\| \(!pluginContextActive && pluginBack\);/);
assert.match(pluginTopicsUi, /const contextDef = pluginTopicDefById\(state\.pluginContextNavPluginId\)/);
assert.match(pluginTopicsUi, /mode === "tasks" && state\.currentTaskGroupId === pluginTopicGroupId\(contextDef\.id\)/);
assert.match(pluginTopicsUi, /if \(mode === "projects"\) return contextDef;/);
assert.match(pluginTopicsUi, /openPluginTopicApp\(pluginId, options = \{\}\)[\s\S]*?state\.pluginContextNavPluginId = def\.id;[\s\S]*?rememberWardrobePluginReturnRoute\(\)/);
assert.match(embeddedPluginUi, /pluginContextNavPluginId: state\.pluginContextNavPluginId \|\| ""/);
assert.match(embeddedPluginUi, /state\.pluginContextNavPluginId = route\.pluginContextNavPluginId \|\| ""/);
assert.match(wardrobeUi, /state\.pluginContextNavPluginId = route\.pluginContextNavPluginId \|\| ""/);
assert.match(platformUi, /function routePluginContextId\(params, routeView = "", taskGroupId = ""\)/);
assert.match(platformUi, /pluginContextIdFromTaskGroupId\(taskGroupId\)/);
assert.match(platformUi, /state\.pluginContextNavPluginId = pluginContextNavPluginId;/);
assert.match(wardrobeUi, /const keepPluginContextButton = typeof pluginTopicDefForViewMode === "function"[\s\S]*?pluginTopicBottomButtonId\(pluginTopicDefForViewMode\(state\.viewMode\)\) === "bottomWardrobeMode"/);
assert.match(embeddedPluginUi, /const keepPluginContextButton = typeof pluginTopicDefForViewMode === "function"[\s\S]*?pluginTopicBottomButtonId\(pluginTopicDefForViewMode\(state\.viewMode\)\) === def\.bottomButtonId/);
assert.match(embeddedPluginUi, /button\.hidden = !keepPluginContextButton/);
assert.match(wireStartUi, /state\.pluginContextNavPluginId = "";/);
assert.match(navigationSearchUi, /updateBottomNavLabel\("bottomTasksMode", ""\)/);
assert.match(navigationSearchUi, /updateBottomNavLabel\("bottomProjectsMode", ""\)/);
assert.doesNotMatch(navigationSearchUi, /const pluginContextBottomTabs = new Set/);
assert.match(navigationSearchUi, /function setBottomTabHidden\(node, hidden\)/);
assert.match(navigationSearchUi, /node\.setAttribute\("aria-hidden", hidden \? "true" : "false"\)/);
assert.match(navigationSearchUi, /setBottomTabHidden\(node, hiddenBottomTabs\.has\(id\)\)/);
assert.doesNotMatch(navigationSearchUi, /document\.querySelectorAll\("\.bottom-tab"\)\.forEach\(\(node\) => \{[\s\S]*?const visible = pluginContextBottomTabs\.has\(node\.id\);[\s\S]*?setBottomTabHidden\(node, !visible\);/);
assert.doesNotMatch(navigationSearchUi, /pluginContextBottomTabs\.forEach\(\(id\) => \{/);
assert.match(pluginTopicsUi, /function hideActivePluginHostsForPluginTopicNavigation\(\)/);
assert.match(pluginTopicsUi, /setWardrobePluginHostVisible\(false\)/);
assert.match(pluginTopicsUi, /setEmbeddedPluginHostVisible\(def, false\)/);
assert.match(pluginTopicsUi, /openPluginTopicChat\(pluginId, options = \{\}\)[\s\S]*?hideActivePluginHostsForPluginTopicNavigation\(\)/);
assert.match(pluginTopicsUi, /openPluginTopicDelivery\(pluginId\)[\s\S]*?hideActivePluginHostsForPluginTopicNavigation\(\)/);
assert.match(sidebarTaskUi, /sendCodexPluginBackOrReturn\(\)/);
assert.match(sidebarTaskUi, /sendFinancePluginBackOrReturn\(\)/);
assert.match(sidebarTaskUi, /sendEmailPluginBackOrReturn\(\)/);
assert.match(sidebarTaskUi, /sendHealthPluginBackOrReturn\(\)/);
assert.match(sidebarTaskUi, /sendGrowthPluginBackOrReturn\(\)/);
assert.match(sidebarTaskUi, /sendMoiraPluginBackOrReturn\(\)/);
assert.match(sidebarTaskUi, /updateTopicPluginDockChrome\(isTaskListView\(\)\)/);
assert.match(sidebarTaskUi, /function pluginContextBackNavigationActive\(\)/);
assert.match(sidebarTaskUi, /const pluginContextBack = pluginContextBackNavigationActive\(\)/);
assert.match(sidebarTaskUi, /function pluginContextBackTarget\(\)/);
assert.match(sidebarTaskUi, /return def && !def\.builtinKind \? "plugin-context-home" : ""/);
assert.match(sidebarTaskUi, /const pluginContextTarget = pluginContextBackTarget\(\)/);
assert.match(sidebarTaskUi, /if \(isTaskDetailView\(\)\) \{[\s\S]*?pluginTopicDefForCurrentTaskGroupId\(state\.currentTaskGroupId\)[\s\S]*?if \(pluginTopicDetail\) return pluginContextTarget;[\s\S]*?return "task";/);
assert.match(sidebarTaskUi, /if \(pluginContextTarget\) return pluginContextTarget;/);
assert.match(sidebarTaskUi, /if \(!pluginContextBack && typeof wardrobePluginOuterBackActive === "function" && wardrobePluginOuterBackActive\(\)\) return "wardrobe-plugin-outer"/);
assert.match(sidebarTaskUi, /if \(!pluginContextBack && typeof financePluginOuterBackActive === "function" && financePluginOuterBackActive\(\)\) return "finance-plugin-outer"/);
assert.match(sidebarTaskUi, /codexPluginOuterBackActive\(\)[\s\S]*return "codex-plugin-outer"/);
assert.ok(
  sidebarTaskUi.indexOf('return "codex-plugin"') < sidebarTaskUi.indexOf('return "codex-plugin-outer"'),
  "Codex iframe history should win before host return so thread detail backs to the plugin thread list first",
);
assert.match(sidebarTaskUi, /target === "codex-plugin-outer"[\s\S]*restoreCodexPluginReturnRoute\(\)/);
assert.match(sidebarTaskUi, /financePluginOuterBackActive\(\)[\s\S]*return "finance-plugin-outer"/);
assert.match(sidebarTaskUi, /target === "finance-plugin-outer"[\s\S]*restoreFinancePluginReturnRoute\(\)/);
assert.match(sidebarTaskUi, /emailPluginOuterBackActive\(\)[\s\S]*return "email-plugin-outer"/);
assert.match(sidebarTaskUi, /target === "email-plugin-outer"[\s\S]*restoreEmailPluginReturnRoute\(\)/);
assert.match(sidebarTaskUi, /healthPluginOuterBackActive\(\)[\s\S]*return "health-plugin-outer"/);
assert.match(sidebarTaskUi, /target === "health-plugin-outer"[\s\S]*restoreHealthPluginReturnRoute\(\)/);
assert.match(sidebarTaskUi, /growthPluginOuterBackActive\(\)[\s\S]*return "growth-plugin-outer"/);
assert.match(sidebarTaskUi, /target === "growth-plugin-outer"[\s\S]*restoreGrowthPluginReturnRoute\(\)/);
assert.match(sidebarTaskUi, /moiraPluginOuterBackActive\(\)[\s\S]*return "moira-plugin-outer"/);
assert.match(sidebarTaskUi, /target === "moira-plugin-outer"[\s\S]*restoreMoiraPluginReturnRoute\(\)/);
assert.match(sidebarTaskUi, /target === "plugin-context-home"[\s\S]*exitPluginContextToTopicHome\(\)/);
assert.match(pluginTopicsUi, /function exitPluginContextToTopicHome\(\)/);
assert.match(pluginTopicsUi, /state\.pluginContextNavPluginId = "";/);
assert.match(pluginTopicsUi, /state\.viewMode = "tasks";/);
assert.match(pluginTopicsUi, /state\.currentTaskGroupId = "";/);
const pluginContextExitBody = (pluginTopicsUi.match(/function exitPluginContextToTopicHome\(\) \{[\s\S]*?\n\}\n\nfunction renderPluginContextTopicHomeAfterExit/) || [""])[0];
assert.match(pluginContextExitBody, /state\.scrollFeedback = null;[\s\S]*state\.sidebarSwipe = null;/);
assert.match(pluginContextExitBody, /if \(typeof normalizeMobileViewportAfterViewChange === "function"\) normalizeMobileViewportAfterViewChange\(\);/);
assert.match(pluginContextExitBody, /if \(typeof applyViewMode === "function"\) applyViewMode\(\);/);
assert.match(pluginContextExitBody, /renderPluginContextTopicHomeAfterExit\(\)/);
assert.doesNotMatch(pluginContextExitBody, /openTaskList\(\)/);
assert.doesNotMatch(pluginContextExitBody, /loadSingleWindow\(/);
const pluginContextHomeBody = (pluginTopicsUi.match(/function renderPluginContextTopicHomeAfterExit\(\) \{[\s\S]*?\n\}\n\nfunction isPluginTopicTaskGroup/) || [""])[0];
assert.match(pluginContextHomeBody, /refreshPluginContextTopicHomeAfterColdRestore\(restoreScrollTop\)\.catch\(showError\)/);
assert.match(pluginContextHomeBody, /renderCurrentThread\(\{ stickToBottom: false, restoreScrollTop \}\)/);
assert.doesNotMatch(pluginContextHomeBody, /restoreTaskListThreadFromCache\(/);
assert.match(pluginTopicsUi, /async function refreshPluginContextTopicHomeAfterColdRestore\(restoreScrollTop = 0\)/);
assert.match(pluginTopicsUi, /api\("\/api\/single-window", \{/);
assert.match(pluginTopicsUi, /messageMode: "tasks",[\s\S]*?taskGroupId: "",[\s\S]*?messageLimit: TASK_MESSAGE_INITIAL_LIMIT/);
assert.match(uploadSidebarUi, /const startEdgeSwipe = \(event\) => \{[\s\S]*startSwipe\("edge", event\);[\s\S]*event\.preventDefault\(\);/);
assert.doesNotMatch(uploadSidebarUi, /startEdgeSwipe[\s\S]{0,260}state\.sidebarSwipe = null;/);
assert.match(platformUi, /view === "codex" \|\| view === "codex-mobile"/);
assert.match(platformUi, /view === "finance" \|\| view === "accounting" \|\| view === "ledger"/);
assert.match(platformUi, /view === "email" \|\| view === "mail" \|\| view === "mailbox"/);
assert.match(platformUi, /view === "health"/);
assert.match(platformUi, /view === "growth" \|\| view === "education"/);
assert.match(platformUi, /view === "moira"/);
assert.match(platformUi, /routeView === "codex"[\s\S]*setCodexPluginOpenRoute\(\{/);
assert.match(platformUi, /routeView === "wardrobe"[\s\S]*setWardrobePluginOpenRoute\(\{/);
assert.match(platformUi, /routeView === "finance"[\s\S]*setFinancePluginOpenRoute\(\{/);
assert.match(platformUi, /routeView === "email"[\s\S]*setEmailPluginOpenRoute\(\{/);
assert.match(platformUi, /routeView === "health"[\s\S]*setHealthPluginOpenRoute\(\{/);
assert.match(platformUi, /routeView === "growth"[\s\S]*setGrowthPluginOpenRoute\(\{/);
assert.match(platformUi, /routeView === "moira"[\s\S]*setMoiraPluginOpenRoute\(\{/);
assert.match(platformUi, /pluginThreadId: params\.get\("pluginThreadId"\) \|\| params\.get\("threadId"\) \|\| ""/);
assert.match(platformUi, /sourceTurnId: params\.get\("sourceTurnId"\) \|\| params\.get\("turnId"\) \|\| ""/);
assert.match(fs.readFileSync(path.join(repoRoot, "public", "app-thread-message-ui.js"), "utf8"), /if \(!enabled && typeof clearKeyboardViewportMetrics === "function"\) clearKeyboardViewportMetrics\(\);/);

assert.match(stylesCss, /\.embedded-plugin-host/);
assert.match(stylesCss, /\.embedded-plugin-frame/);
assert.match(stylesCss, /\.embedded-plugin-shell \{[\s\S]*?background: var\(--ui-page\);/);
assert.match(stylesCss, /\.embedded-plugin-shell\.is-loading::before \{[\s\S]*?background: var\(--ui-page\);/);
assert.match(stylesCss, /\.embedded-plugin-shell\.is-loading \.embedded-plugin-frame \{[\s\S]*?opacity: 0;/);
assert.match(stylesCss, /\.codex-mode \.conversation,[\s\S]*?\.email-mode \.conversation,[\s\S]*?\.health-mode \.conversation,[\s\S]*?\.note-mode \.conversation,[\s\S]*?\.growth-plugin-mode \.conversation,[\s\S]*?\.moira-mode \.conversation\s*\{[\s\S]*padding: 0;/);
assert.match(stylesCss, /\.embedded-plugin-host-active \.conversation\s*\{[\s\S]*display: none;/);
assert.match(stylesCss, /\.embedded-plugin-host-active \.topbar\s*\{[\s\S]*display: none !important;/);
assert.match(stylesCss, /\.wardrobe-plugin-host-active \.topbar\s*\{[\s\S]*display: none !important;/);
assert.match(stylesCss, /\.embedded-plugin-host-active \.main\s*\{[\s\S]*grid-template-rows: auto minmax\(0, 1fr\);/);
assert.match(stylesCss, /\.wardrobe-plugin-host-active \.main\s*\{[\s\S]*grid-template-rows: auto minmax\(0, 1fr\);/);
assert.match(stylesCss, /\.wardrobe-plugin-host-active:not\(\.plugin-context-nav-mode\) \.main,[\s\S]*?\.embedded-plugin-host-active:not\(\.plugin-context-nav-mode\) \.main\s*\{[\s\S]*?padding-top: var\(--plugin-context-main-top, 0\);/);
assert.match(stylesCss, /\.embedded-plugin-host-active \.embedded-plugin-host\s*\{[\s\S]*grid-row: 2;/);
assert.match(stylesCss, /\.wardrobe-plugin-host-active \.wardrobe-plugin-host\s*\{[\s\S]*grid-row: 2;/);
assert.doesNotMatch(stylesCss, /\.plugin-context-nav-mode \.bottom-nav\s*\{[\s\S]*grid-template-columns: repeat\(3, minmax/);
assert.doesNotMatch(stylesCss, /\.plugin-context-nav-mode #bottomTasksMode\s*\{[\s\S]*order: 1 !important;/);
assert.doesNotMatch(stylesCss, /\.plugin-context-nav-mode #bottomWardrobeMode,[\s\S]*#bottomFinanceMode,[\s\S]*#bottomEmailMode,[\s\S]*#bottomHealthMode,[\s\S]*#bottomNoteMode,[\s\S]*#bottomGrowthMode,[\s\S]*#bottomMoiraMode\s*\{[\s\S]*order: 2 !important;/);
assert.doesNotMatch(stylesCss, /\.plugin-context-nav-mode #bottomProjectsMode\s*\{[\s\S]*order: 3 !important;/);
assert.doesNotMatch(stylesCss, /\.main-back-visible\.plugin-context-nav-mode \.bottom-nav\s*\{[\s\S]*display: grid;/);
assert.match(stylesCss, /\.embedded-plugin-preview-fullscreen-active \.bottom-nav\s*\{[\s\S]*display: none !important;/);
assert.match(stylesCss, /\.plugin-context-nav-mode\.embedded-plugin-preview-fullscreen-active\.embedded-plugin-host-active \.main\s*\{[\s\S]*bottom: 0;/);
assert.match(stylesCss, /--plugin-context-bottom-nav-height: 54px/);
assert.match(stylesCss, /\.app\.main-back-visible\.plugin-context-nav-mode\.plugin-topic-detail-mode \.composer\s*\{[\s\S]*bottom: var\(--plugin-topic-composer-bottom-offset\);[\s\S]*padding-bottom: 5px;/);
assert.match(embeddedPluginUi, /settleMobileBottomNavReservation\("plugin_back_result", \[0, 80, 240, 520\]\)/);
assert.match(embeddedPluginUi, /settleMobileBottomNavReservation\("plugin_return_route", \[0, 80, 240, 520, 1000\]\)/);
assert.match(embeddedPluginUi, /settleMobileBottomNavReservation\(visible \? "plugin_host_visible" : "plugin_host_hidden", \[0, 80, 240\]\)/);
assert.match(embeddedPluginUi, /settleMobileBottomNavReservation\("plugin_back_request", \[0, 120, 360, 900, 1700\]\)/);
assert.match(embeddedPluginUi, /scheduleClientLayoutDiagnostics\(visible \? "plugin_host_visible" : "plugin_host_hidden", \[0, 300, 1200\]\)/);
assert.match(embeddedPluginUi, /scheduleClientLayoutDiagnostics\("plugin_back_request", \[0, 360, 1200\]\)/);
assert.doesNotMatch(stylesCss, /\.plugin-context-nav-mode \.bottom-tab-label\s*\{[\s\S]*display: none;/);
assert.match(stylesCss, /\.sidebar\.open ~ \.topic-plugin-dock\s*\{[\s\S]*display: none !important;/);
assert.match(stylesCss, /\.sidebar\.open ~ \.bottom-nav\s*\{[\s\S]*display: none !important;/);
assert.match(stylesCss, /\.nav-codex-icon::before/);
assert.match(stylesCss, /\.nav-plugins-icon::before/);
assert.match(stylesCss, /\.nav-finance-icon::before/);
assert.match(stylesCss, /\.nav-email-icon::before/);
assert.match(stylesCss, /\.topic-plugin-dock:not\(\[hidden\]\)\s*\{[\s\S]*display: block;/);
assert.match(stylesCss, /\.global-plugin-dock-mode \.topic-plugin-dock\s*\{[\s\S]*position: fixed;[\s\S]*bottom: calc\(var\(--topic-plugin-dock-bottom\) - var\(--topic-plugin-dock-nav-overlap\)\);/);
assert.match(stylesCss, /--topic-plugin-dock-bottom: var\(--topic-plugin-dock-bottom-runtime, var\(--mobile-bottom-nav-offset-height\)\);/);
assert.match(stylesCss, /--topic-plugin-dock-nav-overlap: 1px;/);
assert.match(stylesCss, /--topic-plugin-dock-reserved-height: var\(--topic-plugin-dock-reserved-height-runtime, calc\(var\(--topic-plugin-dock-bottom\) \+ var\(--topic-plugin-dock-height\)\)\);/);
assert.match(stylesCss, /\.plugin-app-strip\s*\{[\s\S]*display: flex;[\s\S]*flex-wrap: nowrap;[\s\S]*overflow-x: auto;/);
assert.match(stylesCss, /\.global-plugin-dock-mode \.plugin-app-strip\s*\{[\s\S]*width: 100%;/);
