"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const repoRoot = path.resolve(__dirname, "..");
const wardrobeUi = fs.readFileSync(path.join(repoRoot, "public", "app-wardrobe-ui.js"), "utf8");
const automationUi = fs.readFileSync(path.join(repoRoot, "public", "app-automation-ui.js"), "utf8");
const wireStartUi = fs.readFileSync(path.join(repoRoot, "public", "app-wire-start-ui.js"), "utf8");
const platformUi = fs.readFileSync(path.join(repoRoot, "public", "app-platform-ui.js"), "utf8");
const indexHtml = fs.readFileSync(path.join(repoRoot, "public", "index.html"), "utf8");
const stylesCss = fs.readFileSync(path.join(repoRoot, "public", "styles.css"), "utf8");

assert.match(indexHtml, /id="bottomWardrobeMode"/);
assert.match(indexHtml, /id="topWardrobeWatches"/);
assert.match(indexHtml, /data-wardrobe-section="maintenance"/);
assert.match(indexHtml, /app-wardrobe-ui\.js\?v=/);
assert.match(wardrobeUi, /function wardrobeDirectoryAttachment\(\)/);
assert.match(wardrobeUi, /const WARDROBE_DIRECTORY_PATTERN =/);
assert.match(wardrobeUi, /function itemLooksWardrobeDirectory\(item = {}\)/);
assert.match(wardrobeUi, /function wardrobeChildRouteText\(child = {}\)/);
assert.match(wardrobeUi, /const text = wardrobeChildRouteText\(child\)/);
assert.match(wardrobeUi, /WARDROBE_DIRECTORY_PATTERN\.test\(text\)/);
assert.doesNotMatch(wardrobeUi, /label: `\$\{project\.label \|\| project\.id \|\| ""} \/ \$\{child\.label \|\| child\.id \|\| ""}`/);
assert.match(wardrobeUi, /function renderWardrobeView\(\)/);
assert.match(wardrobeUi, /function loadWardrobePluginManifest\(options = {}\)/);
assert.match(wardrobeUi, /\/api\/hermes-plugins\/wardrobe\/manifest\?\$\{params\.toString\(\)\}/);
assert.match(wardrobeUi, /function renderWardrobePluginFrame\(manifest\)/);
assert.match(wardrobeUi, /class="wardrobe-plugin-frame"/);
assert.match(wardrobeUi, /sandbox="allow-same-origin allow-scripts allow-forms allow-downloads"/);
assert.doesNotMatch(wardrobeUi, /target="_blank"/);
assert.doesNotMatch(wardrobeUi, /window\.open/);
assert.match(wardrobeUi, /function loadWardrobeOverview\(options = {}\)/);
assert.match(wardrobeUi, /new URLSearchParams\(\{ workspaceId \}\)/);
assert.match(wardrobeUi, /params\.set\("q", filters\.q\)/);
assert.match(wardrobeUi, /params\.set\("brand", filters\.brand\)/);
assert.match(wardrobeUi, /params\.set\("section", currentWardrobeSection\(\)\)/);
assert.match(wardrobeUi, /function setWardrobeSection\(sectionId\)/);
assert.match(wardrobeUi, /function renderWardrobeWatchView\(projection = {}\)/);
assert.match(wardrobeUi, /function renderWardrobeMaintenanceView\(projection = {}\)/);
assert.match(wardrobeUi, /function renderWardrobeLooksView\(projection = {}\)/);
assert.match(wardrobeUi, /function renderWardrobeDashboard\(projection = null\)/);
assert.match(wardrobeUi, /function renderWardrobeToolbar\(projection = {}\)/);
assert.match(wardrobeUi, /function renderWardrobeItemTable\(items = \[\], title =/);
assert.match(wardrobeUi, /data-wardrobe-brand/);
assert.match(wardrobeUi, /data-wardrobe-item-code/);
assert.match(wardrobeUi, /wardrobeSearchInput/);
assert.doesNotMatch(wardrobeUi, /openTaskComposerForDirectoryAttachment\(attachment\)/);
assert.doesNotMatch(wardrobeUi, /setComposerText\(action\.prompt\)/);
assert.doesNotMatch(wardrobeUi, /WARDROBE_ACTIONS/);
assert.doesNotMatch(wardrobeUi, /<h2>\\u6211\\u7684\\u8863\\u6a71<\/h2>/);
assert.doesNotMatch(wardrobeUi, /write_item/);
assert.doesNotMatch(wardrobeUi, /write_history/);
assert.match(automationUi, /const wardrobe = state\.viewMode === "wardrobe"/);
assert.match(automationUi, /renderWardrobeView\(\)/);
assert.match(wireStartUi, /bottomWardrobeMode/);
assert.match(wireStartUi, /topWardrobeWatches/);
assert.match(wireStartUi, /setWardrobeSection\(section\)/);
assert.match(platformUi, /view === "wardrobe"/);
assert.match(stylesCss, /\.bottom-nav\.wardrobe-visible/);
assert.match(stylesCss, /\.nav-wardrobe-icon::before/);
assert.match(stylesCss, /\.wardrobe-dashboard/);
assert.match(stylesCss, /\.wardrobe-plugin-shell/);
assert.match(stylesCss, /\.wardrobe-plugin-frame/);
assert.match(stylesCss, /\.wardrobe-metrics/);
assert.match(stylesCss, /\.wardrobe-search-input/);
assert.match(stylesCss, /\.wardrobe-filter-chip/);
assert.match(stylesCss, /\.wardrobe-item-table/);
assert.match(stylesCss, /\.wardrobe-item-filter/);
assert.match(stylesCss, /\.wardrobe-section-title/);
assert.match(stylesCss, /\.wardrobe-mode \.composer/);
assert.doesNotMatch(stylesCss, /\.wardrobe-action-card/);
