"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const repoRoot = path.resolve(__dirname, "..");
const wardrobeUi = fs.readFileSync(path.join(repoRoot, "public", "app-wardrobe-ui.js"), "utf8");
const automationUi = fs.readFileSync(path.join(repoRoot, "public", "app-automation-ui.js"), "utf8");
const wireStartUi = fs.readFileSync(path.join(repoRoot, "public", "app-wire-start-ui.js"), "utf8");
const platformUi = fs.readFileSync(path.join(repoRoot, "public", "app-platform-ui.js"), "utf8");
const navigationSearchUi = fs.readFileSync(path.join(repoRoot, "public", "app-navigation-search-ui.js"), "utf8");
const sidebarTaskUi = fs.readFileSync(path.join(repoRoot, "public", "app-sidebar-task-ui.js"), "utf8");
const indexHtml = fs.readFileSync(path.join(repoRoot, "public", "index.html"), "utf8");
const stylesCss = fs.readFileSync(path.join(repoRoot, "public", "styles.css"), "utf8");

assert.match(indexHtml, /id="bottomWardrobeMode"/);
assert.match(indexHtml, /app-wardrobe-ui\.js\?v=/);

assert.match(wardrobeUi, /function wardrobeDirectoryAttachment\(\)/);
assert.match(wardrobeUi, /const WARDROBE_DIRECTORY_PATTERN =/);
assert.match(wardrobeUi, /function itemLooksWardrobeDirectory\(item = {}\)/);
assert.match(wardrobeUi, /function wardrobeChildRouteText\(child = {}\)/);
assert.match(wardrobeUi, /const text = wardrobeChildRouteText\(child\)/);
assert.match(wardrobeUi, /WARDROBE_DIRECTORY_PATTERN\.test\(text\)/);
assert.doesNotMatch(wardrobeUi, /label: `\$\{project\.label \|\| project\.id \|\| ""} \/ \$\{child\.label \|\| child\.id \|\| ""}`/);

assert.match(wardrobeUi, /function renderWardrobeView\(\)/);
assert.match(wardrobeUi, /function loadWardrobePluginManifest\(options = {}\)/);
assert.match(wardrobeUi, /\/api\/hermes-plugins\/wardrobe\/manifest\?\$\{params\.toString\(\)\}/);
assert.match(wardrobeUi, /appOrigin: window\.location\.origin/);
assert.match(wardrobeUi, /function renderWardrobePluginFrame\(manifest\)/);
assert.match(wardrobeUi, /function wardrobePluginUsesLaunchToken\(manifest = currentWardrobePluginManifest\(\)\)/);
assert.match(wardrobeUi, /function wardrobeLaunchTokenIsFreshForFrame\(\)/);
assert.match(wardrobeUi, /state\.wardrobePluginManifestFreshForFrame = wardrobePluginUsesLaunchToken\(state\.wardrobePluginManifest\)/);
assert.match(wardrobeUi, /loadWardrobePluginManifest\(\{ force: true \}\)/);
assert.match(wardrobeUi, /function wardrobePluginBlockedByPageSecurity\(manifest = currentWardrobePluginManifest\(\)\)/);
assert.match(wardrobeUi, /manifest\?\.embed\?\.blockedByFrameAncestors/);
assert.match(wardrobeUi, /pageProtocol === "https:" && entryProtocol === "http:"/);
assert.match(wardrobeUi, /function ensureWardrobePluginNavigationBridge\(\)/);
assert.match(wardrobeUi, /wardrobe\.plugin\.navigation/);
assert.match(wardrobeUi, /function parkWardrobePluginShell\(\)/);
assert.match(wardrobeUi, /function rememberWardrobePluginReturnRoute\(\)/);
assert.match(wardrobeUi, /function wardrobePluginOuterBackActive\(\)/);
assert.match(wardrobeUi, /function restoreWardrobePluginReturnRoute\(\)/);
assert.match(wardrobeUi, /state\.wardrobePluginReturnRoute = route/);
assert.match(wardrobeUi, /function wardrobePluginHost\(\)/);
assert.match(wardrobeUi, /function setWardrobePluginHostVisible\(visible\)/);
assert.match(wardrobeUi, /function attachWardrobePluginShell\(entryUrl\)/);
assert.match(wardrobeUi, /main\.insertBefore\(host, conversation\)/);
assert.match(wardrobeUi, /function scheduleWardrobePluginLaunchHealthCheck\(frame, loadedAt = Date\.now\(\)\)/);
assert.match(wardrobeUi, /function refreshWardrobePluginFrameFromFreshManifest\(\)/);
assert.match(wardrobeUi, /function showWardrobePluginLoadingSurface\(\)/);
assert.match(wardrobeUi, /clearKeyboardViewportMetrics/);
assert.match(wardrobeUi, /wardrobePluginNavigationLastAt/);
assert.match(wardrobeUi, /loadWardrobePluginManifest\(\{ force: true \}\)/);
assert.doesNotMatch(wardrobeUi, /Loading Wardrobe plugin/);
assert.match(wardrobeUi, /class="wardrobe-plugin-shell is-loading"/);
assert.match(wardrobeUi, /closest\("\.wardrobe-plugin-shell"\)\?\.classList\.remove\("is-loading"\)/);
assert.match(wardrobeUi, /type: "hermes\.plugin\.back"/);
assert.match(wardrobeUi, /function renderWardrobePluginSecurityNotice\(manifest\)/);
assert.match(wardrobeUi, /function renderWardrobePluginUnavailable\(manifest = currentWardrobePluginManifest\(\)\)/);
assert.match(wardrobeUi, /data-wardrobe-plugin-refresh/);
assert.match(wardrobeUi, /class="wardrobe-plugin-frame"/);
assert.match(wardrobeUi, /sandbox="allow-same-origin allow-scripts allow-forms allow-downloads"/);
assert.match(wardrobeUi, /\\u8863\\u6a71\\u63d2\\u4ef6\\u5165\\u53e3\\u8fd8\\u6ca1\\u6709\\u5141\\u8bb8\\u5f53\\u524d Hermes/);

assert.doesNotMatch(wardrobeUi, /target="_blank"/);
assert.doesNotMatch(wardrobeUi, /window\.open/);
assert.doesNotMatch(wardrobeUi, /function loadWardrobeOverview\(options = {}\)/);
assert.doesNotMatch(wardrobeUi, /\/api\/wardrobe\/overview/);
assert.doesNotMatch(wardrobeUi, /function setWardrobeSection\(sectionId\)/);
assert.doesNotMatch(wardrobeUi, /function renderWardrobeDashboard\(projection = null\)/);
assert.doesNotMatch(wardrobeUi, /data-wardrobe-brand/);
assert.doesNotMatch(wardrobeUi, /data-wardrobe-item-code/);
assert.doesNotMatch(wardrobeUi, /wardrobeSearchInput/);
assert.doesNotMatch(wardrobeUi, /openTaskComposerForDirectoryAttachment\(attachment\)/);
assert.doesNotMatch(wardrobeUi, /setComposerText\(action\.prompt\)/);
assert.doesNotMatch(wardrobeUi, /WARDROBE_ACTIONS/);
assert.doesNotMatch(wardrobeUi, /<h2>\\u6211\\u7684\\u8863\\u6a71<\/h2>/);
assert.doesNotMatch(wardrobeUi, /write_item/);
assert.doesNotMatch(wardrobeUi, /write_history/);

assert.match(automationUi, /const wardrobe = state\.viewMode === "wardrobe"/);
assert.match(automationUi, /parkWardrobePluginShell\(\)/);
assert.match(automationUi, /renderWardrobeView\(\)/);
assert.match(sidebarTaskUi, /wardrobePluginBackActive\(\)/);
assert.match(sidebarTaskUi, /wardrobePluginOuterBackActive\(\)[\s\S]*return "wardrobe-plugin-outer"/);
assert.match(sidebarTaskUi, /sendWardrobePluginBack\(\)/);
assert.match(sidebarTaskUi, /target === "wardrobe-plugin-outer"[\s\S]*restoreWardrobePluginReturnRoute\(\)/);
assert.match(navigationSearchUi, /const wardrobePluginBack = typeof wardrobePluginBackActive === "function" && wardrobePluginBackActive\(\)/);
assert.match(navigationSearchUi, /const wardrobePluginOuterBack = typeof wardrobePluginOuterBackActive === "function" && wardrobePluginOuterBackActive\(\)/);
assert.match(wireStartUi, /bottomWardrobeMode/);
assert.match(wireStartUi, /rememberWardrobePluginReturnRoute\(\)/);
assert.doesNotMatch(wireStartUi, /setWardrobeSection\(section\)/);
assert.doesNotMatch(indexHtml, /topWardrobe(?:Overview|Watches|Maintenance|Wear|Looks|Log)/);
assert.doesNotMatch(navigationSearchUi, /topWardrobe(?:Overview|Watches|Maintenance|Wear|Looks|Log)/);
assert.match(platformUi, /view === "wardrobe"/);

assert.match(stylesCss, /\.bottom-nav\.wardrobe-visible/);
assert.match(stylesCss, /\.nav-wardrobe-icon::before/);
assert.match(stylesCss, /\.wardrobe-plugin-shell\s*\{[\s\S]*?color-scheme: light dark;[\s\S]*?background: var\(--ui-page\);/);
assert.match(stylesCss, /\.wardrobe-plugin-frame\s*\{[\s\S]*?background: var\(--ui-page\);[\s\S]*?opacity: 1;[\s\S]*?transition: opacity 120ms ease;/);
assert.match(stylesCss, /\.wardrobe-plugin-shell\.is-loading::before\s*\{[\s\S]*?background: var\(--ui-page\);/);
assert.match(stylesCss, /\.wardrobe-plugin-shell\.is-loading \.wardrobe-plugin-frame\s*\{[\s\S]*?opacity: 0;/);
assert.match(stylesCss, /\.wardrobe-plugin-host-active \.conversation\s*\{[\s\S]*display: none;/);
assert.match(stylesCss, /\.wardrobe-plugin-host-active \.topbar\s*\{[\s\S]*display: none !important;/);
assert.match(stylesCss, /\.app\.wardrobe-plugin-host-active\s*\{[\s\S]*padding-bottom: 0;/);
assert.match(stylesCss, /\.wardrobe-plugin-host-active \.bottom-nav\s*\{[\s\S]*display: none !important;/);
assert.match(stylesCss, /\.wardrobe-plugin-host-active \.main\s*\{[\s\S]*grid-template-rows: minmax\(0, 1fr\);/);
assert.match(stylesCss, /\.wardrobe-mode \.conversation\s*\{[\s\S]*padding: 0;[\s\S]*overflow: hidden;[\s\S]*background: var\(--ui-page\);/);
assert.match(stylesCss, /\.wardrobe-plugin-notice/);
assert.match(stylesCss, /\.wardrobe-mode \.composer/);
assert.doesNotMatch(stylesCss, /\.wardrobe-action-card/);
