"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");

const assessmentExamService = require("../adapters/assessment-exam-service");
const assessmentExamWorkflowService = require("../adapters/assessment-exam-workflow-service");
const bridgeCommandProvider = require("../adapters/bridge-command-provider");
const conversationHistoryService = require("../adapters/conversation-history-service");
const routeRegistry = require("../adapters/api-route-registry");
const routeInventory = require("../adapters/api-route-inventory");
const documentPreviewService = require("../adapters/document-preview-service");
const directKanbanCreateService = require("../adapters/direct-kanban-create-service");
const directoryBrowserBoundaryService = require("../adapters/directory-browser-boundary-service");
const eventFanoutService = require("../adapters/event-fanout-service");
const artifactTextRegistrationService = require("../adapters/artifact-text-registration-service");
const fileArtifactAccessService = require("../adapters/file-artifact-access-service");
const fileArtifactResolverService = require("../adapters/file-artifact-resolver-service");
const fileResponseService = require("../adapters/file-response-service");
const fileResourceService = require("../adapters/file-resource-service");
const gatewayRunEventService = require("../adapters/gateway-run-event-service");
const gatewayRunInstructionService = require("../adapters/gateway-run-instruction-service");
const gatewayRunLifecycleService = require("../adapters/gateway-run-lifecycle-service");
const gatewayRunQueueService = require("../adapters/gateway-run-queue-service");
const gatewayRunStartService = require("../adapters/gateway-run-start-service");
const gatewayStatusProjection = require("../adapters/gateway-status-projection");
const groupChatSharedAttachmentService = require("../adapters/group-chat-shared-attachment-service");
const requestContext = require("../adapters/request-context-provider");
const resourceResolver = require("../adapters/resource-access-resolver");
const kanbanAssigneePolicy = require("../adapters/kanban-assignee-policy");
const kanbanCaseShareService = require("../adapters/kanban-case-share-service");
const kanbanCaseTopicService = require("../adapters/kanban-case-topic-service");
const kanbanMaintenanceService = require("../adapters/kanban-maintenance-service");
const kanbanOutputProjectionService = require("../adapters/kanban-output-projection-service");
const kanbanPlanCardCreationService = require("../adapters/kanban-plan-card-creation-service");
const kanbanPlanService = require("../adapters/kanban-plan-service");
const kanbanReadingWorkflowService = require("../adapters/kanban-reading-workflow-service");
const kanbanStudyArtifactService = require("../adapters/kanban-study-artifact-service");
const kanbanStudyPlanService = require("../adapters/kanban-study-plan-service");
const kanbanTaskDispatchPolicy = require("../adapters/kanban-task-dispatch-policy");
const kanbanStory = require("../adapters/kanban-story-provider");
const localAutomationBridgeService = require("../adapters/local-automation-bridge-service");
const localBridgeRuntimeService = require("../adapters/local-bridge-runtime-service");
const localBridgeWrapperService = require("../adapters/local-bridge-wrapper-service");
const localProcessRunnerService = require("../adapters/local-process-runner-service");
const localTodoBridgeService = require("../adapters/local-todo-bridge-service");
const localWorkspaceStoreService = require("../adapters/local-workspace-store-service");
const markdownRenderer = require("../adapters/markdown-renderer");
const naturalLanguageDraftService = require("../adapters/natural-language-draft-service");
const ownerElevationGrantService = require("../adapters/owner-elevation-grant-service");
const programmingAssessmentTemplateService = require("../adapters/programming-assessment-template-service");
const runtimeStateNormalizationService = require("../adapters/runtime-state-normalization-service");
const runtimeStatePersistenceService = require("../adapters/runtime-state-persistence-service");
const runtimeStateRepository = require("../adapters/runtime-state-repository");
const runtimeStateStoreService = require("../adapters/runtime-state-store-service");
const runtimeStateThreadService = require("../adapters/runtime-state-thread-service");
const semanticDirectoryAttachmentService = require("../adapters/semantic-directory-attachment-service");
const sharedDirectoryProjectionService = require("../adapters/shared-directory-projection-service");
const singleWindowMigrationService = require("../adapters/single-window-migration-service");
const singleWindowThreadService = require("../adapters/single-window-thread-service");
const systemRuntimeStatusService = require("../adapters/system-runtime-status-service");
const studyAssessmentService = require("../adapters/study-assessment-service");
const threadDirectCreateExecutionService = require("../adapters/thread-direct-create-execution-service");
const threadMessageCreateService = require("../adapters/thread-message-create-service");
const threadMessageRunRouteService = require("../adapters/thread-message-run-route-service");
const threadOwnerElevationRetryService = require("../adapters/thread-owner-elevation-retry-service");
const threadViewService = require("../adapters/thread-view-service");
const weixinFileForwardService = require("../adapters/weixin-file-forward-service");
const weixinForwardService = require("../adapters/weixin-forward-service");
const weixinIngressEventService = require("../adapters/weixin-ingress-event-service");
const weixinMarkdownForwardService = require("../adapters/weixin-markdown-forward-service");
const weixinOutboundDeliveryService = require("../adapters/weixin-outbound-delivery-service");
const weixinWindowMigrationService = require("../adapters/weixin-window-migration-service");
const webPushDeliveryService = require("../adapters/web-push-delivery-service");
const workspaceDisplayPathService = require("../adapters/workspace-display-path-service");
const workspacePublicProjectionService = require("../adapters/workspace-public-projection-service");
const sqliteStore = require("../adapters/mobile-sqlite-store");
const accessKeyApiRoutes = require("../server-routes/access-key-api-routes");
const automationApiRoutes = require("../server-routes/automation-api-routes");
const directoryBrowserApiRoutes = require("../server-routes/directory-browser-api-routes");
const directoryMutationApiRoutes = require("../server-routes/directory-mutation-api-routes");
const directoryShareApiRoutes = require("../server-routes/directory-share-api-routes");
const eventStreamApiRoutes = require("../server-routes/event-stream-api-routes");
const fileArtifactApiRoutes = require("../server-routes/file-artifact-api-routes");
const kanbanCardApiRoutes = require("../server-routes/kanban-card-api-routes");
const kanbanStudyApiRoutes = require("../server-routes/kanban-study-api-routes");
const mobileApiDispatcher = require("../server-routes/mobile-api-dispatcher");
const ownerElevationApiRoutes = require("../server-routes/owner-elevation-api-routes");
const publicApiRoutes = require("../server-routes/public-api-routes");
const pushApiRoutes = require("../server-routes/push-api-routes");
const resourceApiRoutes = require("../server-routes/resource-api-routes");
const runtimeConfigApiRoutes = require("../server-routes/runtime-config-api-routes");
const singleWindowGroupChatApiRoutes = require("../server-routes/single-window-group-chat-api-routes");
const systemApiRoutes = require("../server-routes/system-api-routes");
const threadMessageRunApiRoutes = require("../server-routes/thread-message-run-api-routes");
const threadReadUploadApiRoutes = require("../server-routes/thread-read-upload-api-routes");
const threadTaskApiRoutes = require("../server-routes/thread-task-api-routes");
const todoApiRoutes = require("../server-routes/todo-api-routes");
const todoPublicProjectionService = require("../adapters/todo-public-projection-service");
const weixinApiRoutes = require("../server-routes/weixin-api-routes");
const workspaceApiRoutes = require("../server-routes/workspace-api-routes");

function fileText(file) {
  return fs.readFileSync(file, "utf8");
}

function assertAppearsInOrder(text, labels) {
  let previousIndex = -1;
  for (const label of labels) {
    const index = text.indexOf(label);
    assert.notEqual(index, -1, `missing ${label}`);
    assert.ok(index > previousIndex, `${label} should appear after prior marker`);
    previousIndex = index;
  }
}

function testRefactorModulesExportStableContracts() {
  assert.equal(typeof assessmentExamService.generateVerifiedAmc8AssessmentQuestions, "function");
  assert.equal(typeof assessmentExamService.generateVerifiedMathAssessmentQuestions, "function");
  assert.equal(typeof assessmentExamService.buildAssessmentExamReportMarkdown, "function");
  assert.equal(typeof assessmentExamService.gradeAssessmentExam, "function");
  assert.equal(typeof assessmentExamService.normalizeAssessmentExam, "function");
  assert.equal(typeof assessmentExamWorkflowService.createAssessmentExamWorkflowService, "function");
  assert.equal(typeof bridgeCommandProvider.createBridgeCommandProvider, "function");
  assert.equal(typeof bridgeCommandProvider.runJsonBridgeCommand, "function");
  assert.equal(typeof conversationHistoryService.createConversationHistoryService, "function");
  assert.equal(typeof routeRegistry.createApiRouteRegistry, "function");
  assert.equal(typeof routeInventory.createHermesMobileApiRouteInventory, "function");
  assert.equal(typeof documentPreviewService.createDocumentPreviewService, "function");
  assert.equal(typeof documentPreviewService.extractDocxTextFromBuffer, "function");
  assert.equal(typeof directKanbanCreateService.createDirectKanbanCreateService, "function");
  assert.equal(typeof directoryBrowserBoundaryService.createDirectoryBrowserBoundaryService, "function");
  assert.equal(typeof eventFanoutService.createEventFanoutService, "function");
  assert.equal(typeof eventFanoutService.payloadWorkspaceId, "function");
  assert.equal(typeof artifactTextRegistrationService.createArtifactTextRegistrationService, "function");
  assert.equal(typeof fileArtifactAccessService.createFileArtifactAccessService, "function");
  assert.equal(typeof fileArtifactResolverService.createFileArtifactResolverService, "function");
  assert.equal(typeof fileResponseService.createFileResponseService, "function");
  assert.equal(typeof fileResourceService.extractArtifactPaths, "function");
  assert.equal(typeof fileResourceService.publicFileMetadata, "function");
  assert.equal(typeof fileResourceService.previewStrategyForFile, "function");
  assert.equal(typeof gatewayRunEventService.createGatewayRunEventService, "function");
  assert.equal(typeof gatewayRunInstructionService.createGatewayRunInstructionService, "function");
  assert.equal(typeof gatewayRunLifecycleService.createGatewayRunLifecycleService, "function");
  assert.equal(typeof gatewayRunLifecycleService.livenessDecisionAfterCheck, "function");
  assert.equal(typeof gatewayRunQueueService.createGatewayRunQueueService, "function");
  assert.equal(typeof gatewayRunStartService.createGatewayRunStartService, "function");
  assert.equal(typeof gatewayStatusProjection.createGatewayStatusProjection, "function");
  assert.equal(typeof gatewayStatusProjection.gatewayPoolStatusHealthy, "function");
  assert.equal(typeof groupChatSharedAttachmentService.createGroupChatSharedAttachmentService, "function");
  assert.equal(typeof publicApiRoutes.createPublicApiRoutes, "function");
  assert.equal(typeof requestContext.buildRequestContext, "function");
  assert.equal(typeof resourceResolver.resolveResourceAccess, "function");
  assert.equal(typeof kanbanAssigneePolicy.createKanbanAssigneePolicy, "function");
  assert.equal(typeof kanbanCaseShareService.createKanbanCaseShareService, "function");
  assert.equal(typeof kanbanCaseTopicService.createKanbanCaseTopicService, "function");
  assert.equal(typeof kanbanMaintenanceService.createKanbanMaintenanceService, "function");
  assert.equal(typeof kanbanOutputProjectionService.createKanbanOutputProjectionService, "function");
  assert.equal(typeof kanbanPlanCardCreationService.createKanbanPlanCardCreationService, "function");
  assert.equal(typeof kanbanPlanService.createKanbanPlanService, "function");
  assert.equal(typeof kanbanReadingWorkflowService.createKanbanReadingWorkflowService, "function");
  assert.equal(typeof kanbanStudyArtifactService.createKanbanStudyArtifactService, "function");
  {
    const artifactService = kanbanStudyArtifactService.createKanbanStudyArtifactService();
    assert.equal(typeof artifactService.assessmentExamReportDirectory, "function");
    assert.equal(typeof artifactService.caseDeliverableDirectory, "function");
  }
  assert.equal(typeof kanbanStudyPlanService.createKanbanStudyPlanService, "function");
  assert.equal(typeof kanbanTaskDispatchPolicy.createKanbanTaskDispatchPolicy, "function");
  assert.equal(typeof kanbanStory.groupKanbanCaseCards, "function");
  assert.equal(typeof kanbanStory.visibleKanbanCaseCards, "function");
  assert.equal(typeof kanbanStory.kanbanCardEffectiveCaseIndex, "function");
  assert.equal(typeof localAutomationBridgeService.createLocalAutomationBridgeService, "function");
  assert.equal(typeof localBridgeRuntimeService.createLocalBridgeRuntimeService, "function");
  assert.equal(typeof localBridgeWrapperService.createLocalBridgeWrapperService, "function");
  assert.equal(typeof localProcessRunnerService.createLocalProcessRunnerService, "function");
  assert.equal(typeof localTodoBridgeService.createLocalTodoBridgeService, "function");
  assert.equal(typeof localTodoBridgeService.parseLocalTodoDue, "function");
  assert.equal(typeof localWorkspaceStoreService.createLocalWorkspaceStoreService, "function");
  assert.equal(typeof localWorkspaceStoreService.workspaceIdSlug, "function");
  assert.equal(typeof markdownRenderer.renderMarkdownDocument, "function");
  assert.equal(typeof markdownRenderer.renderWeixinMarkdownForwardHtml, "function");
  assert.equal(typeof naturalLanguageDraftService.createNaturalLanguageDraftService, "function");
  assert.equal(typeof naturalLanguageDraftService.extractJsonObject, "function");
  assert.equal(typeof ownerElevationGrantService.createOwnerElevationGrantService, "function");
  assert.equal(typeof programmingAssessmentTemplateService.buildProgrammingAssessmentLogMarkdown, "function");
  assert.equal(typeof programmingAssessmentTemplateService.buildProgrammingAssessmentPromptLines, "function");
  assert.equal(typeof runtimeStateNormalizationService.createRuntimeStateNormalizationService, "function");
  assert.equal(typeof runtimeStateNormalizationService.normalizeStringList, "function");
  assert.equal(typeof runtimeStatePersistenceService.createRuntimeStatePersistenceService, "function");
  assert.equal(typeof runtimeStatePersistenceService.stateMessageCount, "function");
  assert.equal(typeof runtimeStateRepository.createRuntimeStateRepository, "function");
  assert.equal(typeof runtimeStateStoreService.createRuntimeStateStoreService, "function");
  assert.equal(typeof runtimeStateStoreService.mergeRuntimeStateWithDefaults, "function");
  assert.equal(typeof runtimeStateStoreService.shouldRefuseMessageCountOverwrite, "function");
  assert.equal(typeof runtimeStateThreadService.createRuntimeStateThreadService, "function");
  assert.equal(typeof semanticDirectoryAttachmentService.createSemanticDirectoryAttachmentService, "function");
  assert.equal(typeof sharedDirectoryProjectionService.createSharedDirectoryProjectionService, "function");
  assert.equal(typeof singleWindowMigrationService.createSingleWindowMigrationService, "function");
  assert.equal(typeof singleWindowThreadService.createSingleWindowThreadService, "function");
  assert.equal(typeof systemRuntimeStatusService.createSystemRuntimeStatusService, "function");
  assert.equal(typeof studyAssessmentService.deriveSubmissionWorkflowState, "function");
  assert.equal(typeof studyAssessmentService.normalizeKanbanAssessmentPlan, "function");
  assert.equal(typeof studyAssessmentService.normalizeKanbanAssessmentSubjectId, "function");
  assert.equal(typeof threadDirectCreateExecutionService.createThreadDirectCreateExecutionService, "function");
  assert.equal(typeof threadMessageCreateService.createThreadMessageCreateService, "function");
  assert.equal(typeof threadMessageRunRouteService.createThreadMessageRunRouteService, "function");
  assert.equal(typeof threadOwnerElevationRetryService.createThreadOwnerElevationRetryService, "function");
  assert.equal(typeof threadViewService.createThreadViewService, "function");
  assert.equal(typeof weixinFileForwardService.createWeixinFileForwardService, "function");
  assert.equal(typeof weixinFileForwardService.fileResultFromResolvedForwardSource, "function");
  assert.equal(typeof weixinForwardService.createWeixinForwardService, "function");
  assert.equal(typeof weixinForwardService.compactWeixinForwardTarget, "function");
  assert.equal(typeof weixinIngressEventService.createWeixinIngressEventService, "function");
  assert.equal(typeof weixinMarkdownForwardService.materializeWeixinForwardFile, "function");
  assert.equal(typeof weixinMarkdownForwardService.renderMarkdownForwardPdf, "function");
  assert.equal(typeof weixinOutboundDeliveryService.createWeixinOutboundDeliveryService, "function");
  assert.equal(typeof weixinWindowMigrationService.createWeixinWindowMigrationService, "function");
  assert.equal(typeof webPushDeliveryService.createWebPushDeliveryService, "function");
  assert.equal(typeof workspaceDisplayPathService.createWorkspaceDisplayPathService, "function");
  assert.equal(typeof workspacePublicProjectionService.createWorkspacePublicProjectionService, "function");
  assert.equal(sqliteStore.CURRENT_SCHEMA_VERSION >= 2, true);
  assert.equal(typeof publicApiRoutes.createPublicApiRoutes, "function");
  assert.equal(typeof systemApiRoutes.createSystemApiRoutes, "function");
  assert.equal(typeof runtimeConfigApiRoutes.createRuntimeConfigApiRoutes, "function");
  assert.equal(typeof pushApiRoutes.createPushApiRoutes, "function");
  assert.equal(typeof eventStreamApiRoutes.createEventStreamApiRoutes, "function");
  assert.equal(typeof ownerElevationApiRoutes.createOwnerElevationApiRoutes, "function");
  assert.equal(typeof weixinApiRoutes.createWeixinApiRoutes, "function");
  assert.equal(typeof workspaceApiRoutes.createWorkspaceApiRoutes, "function");
  assert.equal(typeof accessKeyApiRoutes.createAccessKeyApiRoutes, "function");
  assert.equal(typeof resourceApiRoutes.createResourceApiRoutes, "function");
  assert.equal(typeof singleWindowGroupChatApiRoutes.createSingleWindowGroupChatApiRoutes, "function");
  assert.equal(typeof automationApiRoutes.createAutomationApiRoutes, "function");
  assert.equal(typeof threadMessageRunApiRoutes.createThreadMessageRunApiRoutes, "function");
  assert.equal(typeof directoryBrowserApiRoutes.createDirectoryBrowserApiRoutes, "function");
  assert.equal(typeof directoryMutationApiRoutes.createDirectoryMutationApiRoutes, "function");
  assert.equal(typeof directoryShareApiRoutes.createDirectoryShareApiRoutes, "function");
  assert.equal(typeof threadReadUploadApiRoutes.createThreadReadUploadApiRoutes, "function");
  assert.equal(typeof threadTaskApiRoutes.createThreadTaskApiRoutes, "function");
  assert.equal(typeof todoApiRoutes.createTodoApiRoutes, "function");
  assert.equal(typeof todoPublicProjectionService.createTodoPublicProjectionService, "function");
  assert.equal(typeof kanbanCardApiRoutes.createKanbanCardApiRoutes, "function");
  assert.equal(typeof kanbanStudyApiRoutes.createKanbanStudyApiRoutes, "function");
  assert.equal(typeof mobileApiDispatcher.createMobileApiDispatcher, "function");
  assert.equal(typeof fileArtifactApiRoutes.createFileArtifactApiRoutes, "function");
}

function testServerUsesRequestContextAndSqliteCaseShareMigration() {
  const entrypoint = fileText("server.js");
  const server = fileText("mobile-server-runtime.js");
  const dispatcher = fileText("server-routes/mobile-api-dispatcher.js");
  const threadRouteService = fileText("adapters/thread-message-run-route-service.js");
  assert.match(entrypoint, /require\("\.\/mobile-server-runtime"\)/);
  assert.match(server, /createPublicApiRoutes/);
  assert.match(fileText("adapters/local-bridge-wrapper-service.js"), /bridgeCommandProvider\.runJsonCommand/);
  assert.match(fileText("adapters/local-bridge-runtime-service.js"), /createLocalBridgeWrapperService/);
  assert.match(server, /createConversationHistoryService/);
  assert.match(server, /conversationHistoryService\.buildConversationHistory/);
  assert.match(server, /conversationHistoryService\.deriveTitle/);
  assert.match(server, /createGatewayRunInstructionService/);
  assert.match(server, /gatewayRunInstructionService\.buildHermesInstructions/);
  assert.match(server, /createGatewayRunLifecycleService/);
  assert.match(server, /createGatewayRunQueueService/);
  assert.match(server, /getGatewayRunQueueService\(\)\.addThreadActiveRun/);
  assert.match(server, /gatewayRunLifecycleService\.livenessDecisionAfterCheck/);
  assert.match(server, /createGatewayRunStartService/);
  assert.match(server, /getGatewayRunStartService\(\)\.startRunForThread/);
  assert.match(server, /createDirectKanbanCreateService/);
  assert.match(server, /directKanbanCreateService\.detectDirectTodoCreateIntentForWeb/);
  assert.match(server, /directKanbanCreateService\.verifyDirectTodoCreateResult/);
  assert.match(server, /createLocalWorkspaceStoreService/);
  assert.match(server, /getLocalWorkspaceStoreService\(\)\.upsertLocalWorkspace/);
  assert.match(server, /createGroupChatSharedAttachmentService/);
  assert.match(server, /getGroupChatSharedAttachmentService\(\)\.ensureSharedArtifactCopies/);
  assert.match(server, /createMobileApiDispatcher/);
  assert.match(server, /mobileApiDispatcher\.handle\(req, res\)/);
  assert.match(dispatcher, /publicApiRoutes\.handle\(req, res, url\)/);
  assert.match(server, /createSystemApiRoutes/);
  assert.match(dispatcher, /key: "systemApiRoutes"/);
  assert.match(server, /createSystemRuntimeStatusService/);
  assert.match(server, /getSystemRuntimeStatusService\(\)\.runtimeModelConfigInfo/);
  assert.match(server, /createGatewayStatusProjection/);
  assert.match(server, /gatewayStatusProjection\.publicGatewayPoolStatusForAuth/);
  assert.match(server, /createFileArtifactAccessService/);
  assert.match(server, /fileArtifactAccessService\.registerUploadArtifact/);
  assert.match(server, /createFileArtifactResolverService/);
  assert.match(server, /fileArtifactResolverService\.resolveArtifactForRequest/);
  assert.match(server, /createFileResponseService/);
  assert.match(server, /fileResponseService\.sendResolvedFilePreview/);
  assert.match(server, /createRuntimeConfigApiRoutes/);
  assert.match(dispatcher, /key: "runtimeConfigApiRoutes"/);
  assert.match(server, /createPushApiRoutes/);
  assert.match(dispatcher, /key: "pushApiRoutes"/);
  assert.match(server, /createEventFanoutService/);
  assert.match(server, /eventFanoutService\.broadcast/);
  assert.match(server, /createEventStreamApiRoutes/);
  assert.match(server, /eventStreamApiRoutes\.handle\(req, res, url\)/);
  assert.match(server, /createWeixinApiRoutes/);
  assert.match(dispatcher, /weixinApiRoutes\.handle\(req, res, url/);
  assert.match(server, /createWeixinIngressEventService/);
  assert.match(server, /getWeixinIngressEventService\(\)\.start\(body\)/);
  assert.match(server, /createWeixinOutboundDeliveryService/);
  assert.match(server, /getWeixinOutboundDeliveryService\(\)\.ackDelivery/);
  assert.match(server, /createSingleWindowThreadService/);
  assert.match(fileText("adapters/single-window-thread-service.js"), /migrateWeixinMessagesToDedicatedThread/);
  assert.match(server, /createWebPushDeliveryService/);
  assert.match(server, /webPushDeliveryService\.sendPushNotification/);
  assert.match(server, /webPushDeliveryService\.notifyTaskTerminal/);
  assert.match(server, /webPushDeliveryService\.notifyGroupChatMentions/);
  assert.match(server, /createOwnerElevationApiRoutes/);
  assert.match(dispatcher, /key: "ownerElevationApiRoutes"/);
  assert.match(server, /createOwnerElevationGrantService/);
  assert.match(server, /getOwnerElevationGrantService\(\)\.publicStatus\(auth\)/);
  assert.match(server, /getOwnerElevationGrantService\(\)\.consumeOnce\(auth, token\)/);
  assert.match(server, /createWorkspaceApiRoutes/);
  assert.match(dispatcher, /key: "workspaceApiRoutes"/);
  assert.match(server, /createWorkspacePublicProjectionService/);
  assert.match(server, /getWorkspacePublicProjectionService\(\)\.publicWorkspace/);
  assert.match(server, /createAccessKeyApiRoutes/);
  assert.match(dispatcher, /key: "accessKeyApiRoutes"/);
  assert.match(server, /createResourceApiRoutes/);
  assert.match(server, /createSharedDirectoryProjectionService/);
  assert.match(server, /getSharedDirectoryProjectionService\(\)\.publicProjectsForWorkspace/);
  assert.match(server, /getSharedDirectoryProjectionService\(\)\.shareableRootProjectForPath/);
  assert.match(dispatcher, /key: "resourceApiRoutes"/);
  assert.match(server, /createSingleWindowGroupChatApiRoutes/);
  assert.match(dispatcher, /key: "singleWindowGroupChatApiRoutes"/);
  assert.match(fileText("adapters/single-window-thread-service.js"), /migratePrivateSingleWindowGroups/);
  assert.match(fileText("adapters/single-window-thread-service.js"), /createSingleWindowMigrationService/);
  assert.match(fileText("adapters/single-window-thread-service.js"), /createWeixinWindowMigrationService/);
  assert.match(server, /createThreadMessageRunApiRoutes/);
  assert.match(dispatcher, /key: "threadMessageRunApiRoutes"/);
  assert.match(server, /createThreadMessageRunRouteService/);
  assert.match(server, /getThreadMessageRunRouteService\(\)\.handleThreadMessageCreate/);
  assert.match(server, /createThreadMessageCreateService/);
  assert.match(server, /getThreadMessageCreateService\(\)/);
  assert.match(threadRouteService, /service\.prepareThreadMessageCreate/);
  assert.match(server, /createThreadDirectCreateExecutionService/);
  assert.match(threadRouteService, /executeDirectCreate/);
  assert.match(fileText("adapters/thread-direct-create-execution-service.js"), /executeDirectKanbanCreate/);
  assert.match(fileText("adapters/thread-direct-create-execution-service.js"), /executeDirectTodoCreate/);
  assert.match(server, /createThreadOwnerElevationRetryService/);
  assert.match(threadRouteService, /retryOwnerElevation/);
  assert.match(server, /createAutomationApiRoutes/);
  assert.match(dispatcher, /key: "automationApiRoutes"/);
  assert.match(server, /createLocalBridgeRuntimeService/);
  assert.match(server, /getLocalBridgeRuntimeService\(\)\.runTodoBridge\(payload\)/);
  assert.match(server, /getLocalBridgeRuntimeService\(\)\.runCronBridge\(payload\)/);
  assert.match(server, /getLocalBridgeRuntimeService\(\)\.runDirectoryBridge\(payload\)/);
  assert.match(server, /getLocalBridgeRuntimeService\(\)\.runProcessText\(command, args, options\)/);
  const bridgeRuntime = fileText("adapters/local-bridge-runtime-service.js");
  assert.match(bridgeRuntime, /createLocalAutomationBridgeService/);
  assert.match(bridgeRuntime, /createLocalBridgeWrapperService/);
  assert.match(bridgeRuntime, /createLocalProcessRunnerService/);
  assert.match(bridgeRuntime, /createLocalTodoBridgeService/);
  assert.match(server, /createRuntimeStateNormalizationService/);
  assert.match(server, /getRuntimeStateNormalizationService\(\)\.normalizeState/);
  assert.match(server, /createRuntimeStateThreadService/);
  assert.match(server, /getRuntimeStateThreadService\(\)\.findThreadForRequest/);
  assert.match(server, /createDirectoryBrowserBoundaryService/);
  assert.match(server, /getDirectoryBrowserBoundaryService\(\)\.resolveBrowserPathAsync/);
  assert.match(server, /createDirectoryBrowserApiRoutes/);
  assert.match(dispatcher, /key: "directoryBrowserApiRoutes"/);
  assert.match(server, /createDirectoryMutationApiRoutes/);
  assert.match(dispatcher, /key: "directoryMutationApiRoutes"/);
  assert.match(server, /createDirectoryShareApiRoutes/);
  assert.match(dispatcher, /key: "directoryShareApiRoutes"/);
  assert.match(server, /createThreadReadUploadApiRoutes/);
  assert.match(dispatcher, /key: "threadReadUploadApiRoutes"/);
  assert.match(server, /createThreadTaskApiRoutes/);
  assert.match(dispatcher, /key: "threadTaskApiRoutes"/);
  assert.match(server, /createTodoApiRoutes/);
  assert.match(dispatcher, /key: "todoApiRoutes"/);
  assert.match(server, /createTodoPublicProjectionService/);
  assert.match(server, /getTodoPublicProjectionService\(\)\.publicTodo/);
  assert.match(server, /createKanbanCardApiRoutes/);
  assert.match(dispatcher, /key: "kanbanCardApiRoutes"/);
  assert.match(server, /createKanbanStudyApiRoutes/);
  assert.match(dispatcher, /key: "kanbanStudyApiRoutes"/);
  assert.match(server, /createFileArtifactApiRoutes/);
  assert.match(dispatcher, /key: "fileArtifactApiRoutes"/);
  assert.match(server, /createArtifactTextRegistrationService/);
  assert.match(server, /getArtifactTextRegistrationService\(\)\.registerArtifactsFromText/);
  assert.match(server, /buildRequestContext/);
  assert.match(dispatcher, /req\.hermesRequestContext/);
  assert.match(server, /createKanbanCaseShareService/);
  assert.match(fileText("adapters/kanban-case-share-service.js"), /function syncToSqlite/);
  assert.match(fileText("adapters/kanban-case-share-service.js"), /function shareForCaseDirectoryPath/);
  assert.match(server, /createKanbanMaintenanceService/);
  assert.match(server, /kanbanMaintenanceService\.maybeReconcileDependencyBlocks/);
  assert.match(server, /kanbanMaintenanceService\.readCardListCache/);
  assert.match(server, /createKanbanPlanService/);
  assert.match(server, /kanbanPlanService\.normalizePlan/);
  assert.match(server, /kanbanPlanService\.singleCardCasePayload/);
  assert.match(server, /createNaturalLanguageDraftService/);
  assert.match(server, /naturalLanguageDraftService\.interpretAutomationNaturalLanguage/);
  assert.match(server, /naturalLanguageDraftService\.interpretKanbanNaturalLanguage/);
  assert.match(server, /naturalLanguageDraftService\.planKanbanMultiAgent/);
  assert.match(server, /createKanbanAssigneePolicy/);
  assert.match(server, /normalizeKanbanNotificationAssignee/);
  assert.match(server, /createKanbanCaseTopicService/);
  assert.match(server, /getKanbanCaseTopicService\(\)\.ensureTopicThread/);
  assert.match(server, /createKanbanOutputProjectionService/);
  assert.match(server, /getKanbanOutputProjectionService\(\)\.publicKanbanCardDetail/);
  assert.match(server, /createKanbanPlanCardCreationService/);
  assert.match(server, /getKanbanPlanCardCreationService\(\)\.createKanbanStudyPlanCards/);
  assert.match(server, /createKanbanStudyArtifactService/);
  assert.match(server, /caseDirectoryPathForCase: \(\.\.\.args\) => kanbanCaseShareService\.caseDirectoryPathForCase\(\.\.\.args\)/);
  assert.match(server, /kanbanStudyArtifactService\.publicReadingSubmissionSummary/);
  assert.match(server, /createKanbanReadingWorkflowService/);
  assert.match(server, /kanbanReadingWorkflowService\.submitKanbanReadingSubmission/);
  assert.match(fileText("adapters/kanban-reading-workflow-service.js"), /artifactService\.caseDeliverableDirectory/);
  assert.match(server, /kanbanReadingWorkflowService\.getKanbanReadingQuiz/);
  assert.match(server, /kanbanReadingWorkflowService\.submitKanbanReadingQuiz/);
  assert.match(server, /createGatewayRunEventService/);
  assert.match(server, /getGatewayRunEventService\(\)\.applyHermesRunEvent/);
  assert.match(server, /createRuntimeStatePersistenceService/);
  assert.match(server, /getRuntimeStatePersistenceService\(\)\.saveState/);
  assert.match(server, /createAssessmentExamWorkflowService/);
  assert.match(server, /artifactService: kanbanStudyArtifactService/);
  assert.match(fileText("adapters/assessment-exam-workflow-service.js"), /assessmentExamService\.normalizeAssessmentExam/);
  assert.match(fileText("adapters/assessment-exam-workflow-service.js"), /assessmentExamService\.generateVerifiedMathAssessmentQuestions/);
  assert.match(fileText("adapters/assessment-exam-workflow-service.js"), /assessmentExamService\.gradeAssessmentExam/);
  assert.match(fileText("adapters/assessment-exam-workflow-service.js"), /assessmentExamService\.buildAssessmentExamReportMarkdown/);
  assert.match(fileText("adapters/assessment-exam-workflow-service.js"), /programmingAssessmentTemplateService\.buildProgrammingAssessmentLogMarkdown/);
  assert.match(fileText("adapters/assessment-exam-workflow-service.js"), /artifactService\.assessmentExamReportDirectory/);
  assert.match(fileText("adapters/assessment-exam-workflow-service.js"), /artifactService\.publicAssessmentExam/);
  assert.match(server, /getAssessmentExamWorkflowService\(\)\.startKanbanAssessmentExam/);
  assert.match(server, /getAssessmentExamWorkflowService\(\)\.submitKanbanAssessmentExam/);
  assert.match(server, /studyAssessmentService\.normalizeKanbanAssessmentPlan/);
  assert.match(server, /createSemanticDirectoryAttachmentService/);
  assert.match(fileText("adapters/semantic-directory-attachment-service.js"), /projectForTaskDirectoryAttachment/);
  assert.match(server, /createDocumentPreviewService/);
  assert.match(server, /documentPreviewService\.extractDocxText/);
  assert.match(server, /documentPreviewService\.textFilePreview/);
  assert.match(server, /fileResourceService\.extractArtifactPaths/);
  assert.match(server, /createWeixinForwardService/);
  assert.match(server, /weixinForwardService\.targetsForWorkspace/);
  assert.match(server, /createWeixinFileForwardService/);
  assert.match(server, /weixinFileForwardService\.createWeixinFileForwardDelivery/);
  assert.match(server, /weixinMarkdownForwardService\.materializeWeixinForwardFile/);
  assert.match(fileText("adapters/kanban-case-share-service.js"), /function syncToSqlite/);
  assertAppearsInOrder(dispatcher, [
    'key: "threadReadUploadApiRoutes"',
    'key: "threadTaskApiRoutes"',
    'key: "singleWindowGroupChatApiRoutes"',
    'key: "threadMessageRunApiRoutes"',
  ]);
}

function testPackageRunsArchitectureContracts() {
  const pkg = JSON.parse(fileText("package.json"));
  const runner = fileText("scripts/run-checks.js");
  assert.equal(pkg.scripts.check, "node scripts/run-checks.js --check");
  assert.equal(pkg.scripts.test, "node scripts/run-checks.js --test");
  assert.match(runner, /gitFiles\(\["ls-files", "-z", "--", pathspec\]\)/);
  assert.match(runner, /gitFiles\(\["ls-files", "--others", "--exclude-standard", "-z", "--", pathspec\]\)/);
  assert.match(runner, /runSyntaxChecks\(\)/);
  assert.match(runner, /trackedAndUntracked\("\*\.js"\)/);
  assert.match(runner, /trackedAndUntracked\("tests\/\*\.test\.js"\)/);
  assert.match(runner, /\["--check", file\]/);
  assert.match(runner, /security-invariants-check\.js/);
  assert.match(runner, /privacy-scan\.js/);
  assert.match(runner, /python -m py_compile/);
  assert.ok(pkg.scripts.check.length < 80);
  assert.ok(pkg.scripts.test.length < 80);
}

function testServiceFirstArchitectureContract() {
  const doc = fileText("docs/ARCHITECTURE_BOUNDARY.md");
  assert.match(doc, /Service-First Rule/);
  assert.match(doc, /adapters\/<domain>-service\.js/);
  assert.match(doc, /tests\/<domain>-service\.test\.js/);
  assert.match(doc, /`server\.js` is the thin process entrypoint/);
  assert.match(doc, /`mobile-server-runtime\.js` is the transitional runtime composition root/);
  assert.match(doc, /must not own new business behavior/);
  assert.match(doc, /3,000 lines/);
  assert.match(doc, /5,000 lines/);
  assert.match(doc, /430/);

  const server = fileText("server.js");
  const runtime = fileText("mobile-server-runtime.js");
  const serverLineCount = server.split(/\r?\n/).length;
  const serverTopLevelFunctionCount = (server.match(/^function\s+/gm) || []).length;
  const runtimeLineCount = runtime.split(/\r?\n/).length;
  const runtimeTopLevelFunctionCount = (runtime.match(/^function\s+/gm) || []).length;
  assert.ok(serverLineCount <= 3000, `server.js line budget exceeded: ${serverLineCount} > 3000`);
  assert.ok(serverTopLevelFunctionCount <= 5, `server.js top-level function budget exceeded: ${serverTopLevelFunctionCount} > 5`);
  assert.ok(runtimeLineCount <= 5000, `mobile-server-runtime.js line budget exceeded: ${runtimeLineCount} > 5000`);
  assert.ok(runtimeTopLevelFunctionCount <= 430, `mobile-server-runtime.js top-level function budget exceeded: ${runtimeTopLevelFunctionCount} > 430`);
}

function testRefactorPlanTracksTwelveWorkPackages() {
  const doc = fileText("docs/ARCHITECTURE_REFACTOR_PLAN.zh-CN.md");
  assert.match(doc, /4\.1/);
  assert.match(doc, /4\.12/);
  assert.match(doc, /Request context/i);
  assert.match(doc, /Resource access resolver/i);
  assert.match(doc, /SQLite/i);
  assert.match(doc, /Markdown renderer/i);
}

testRefactorModulesExportStableContracts();
testServerUsesRequestContextAndSqliteCaseShareMigration();
testPackageRunsArchitectureContracts();
testServiceFirstArchitectureContract();
testRefactorPlanTracksTwelveWorkPackages();

console.log("architecture refactor boundary tests passed");
