"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");
const { readAppShellSource } = require("./app-shell-test-helper");

const repoRoot = path.resolve(__dirname, "..");
const serverJs = fs.readFileSync(path.join(repoRoot, "mobile-server-runtime.js"), "utf8");
const runtimeEnvironmentJs = fs.readFileSync(path.join(repoRoot, "adapters", "mobile-runtime-environment-service.js"), "utf8");
const systemRuntimeStatusServiceJs = fs.readFileSync(path.join(repoRoot, "adapters", "system-runtime-status-service.js"), "utf8");
const appJs = readAppShellSource(repoRoot);
const indexHtml = fs.readFileSync(path.join(repoRoot, "public", "index.html"), "utf8");
const stylesCss = fs.readFileSync(path.join(repoRoot, "public", "styles.css"), "utf8");

assert.match(runtimeEnvironmentJs, /const REASONING_EFFORT_OPTIONS = Object\.freeze\(\[/);
assert.match(runtimeEnvironmentJs, /shortLabel: "Xhigh"/);
assert.match(systemRuntimeStatusServiceJs, /function parseAgentRuntimeConfigFromYaml\(text\)/);
assert.match(serverJs, /function runtimeModelConfigInfo\(\)/);
assert.match(systemRuntimeStatusServiceJs, /function assistantLabelForRuntimeConfig\(info = \{\}\)/);
assert.match(serverJs, /model:\s*\{\s*default: info\.defaultModel/s);
assert.match(serverJs, /return dedupe\(\[\.\.\.gatewayPoolConfigPathCandidates\(\), \.\.\.base\]\)\.filter\(configPathReadableForRuntimeInfo\);/);

assert.equal(appJs.includes("AI_MENTION_OPTIONS"), false);
assert.match(appJs, /const COMPOSER_MODEL_OPTIONS = Object\.freeze\(\[/);
assert.match(appJs, /id: "grok-4\.3"/);
assert.match(appJs, /label: "Grok4\.3"/);
assert.match(appJs, /provider: "xai-oauth"/);
assert.match(appJs, /mentionText: "@Grok4\.3"/);
assert.match(appJs, /function composerAiMentionOptions\(\)/);
assert.ok(appJs.includes("mentionText: `@${label}`"));
assert.ok(appJs.includes('const label = "ChatGPT"'));
assert.ok(appJs.includes('workspaceId: "assistant-xhigh"'));
assert.ok(appJs.includes('mentionText: `@${label} X high`'));
assert.match(appJs, /function composerModelOptionForMention\(primary, secondary = ""\)/);
assert.match(appJs, /function selectedDefaultComposerModelOption\(\)/);
assert.match(appJs, /function selectedComposerModel\(text = getComposerText\(\)\)/);
assert.match(appJs, /function selectedComposerProvider\(text = getComposerText\(\)\)/);
assert.match(appJs, /group-mention-name/);
assert.match(appJs, /group-mention-meta/);
assert.equal(appJs.includes("group-mention-id"), false);
assert.equal(stylesCss.includes("group-mention-id"), false);
assert.match(stylesCss, /\.composer \.group-mention-option\s*\{[^}]*grid-template-columns:\s*minmax\(0, 1fr\);/s);
assert.match(stylesCss, /\.composer \.group-mention-option\s*\{[\s\S]*?min-height:\s*36px;/);
assert.match(stylesCss, /\.group-mention-name\s*\{[\s\S]*?font-size:\s*15px;/);
assert.match(appJs, /return \[chatGptXhigh, \.\.\.grokOptions\]\.slice\(0, 2\)/);
assert.doesNotMatch(appJs, /if \(option\.value === defaultEffort\) continue/);
assert.match(appJs, /if \(effort === "xhigh"\) return "Xhigh"/);
assert.match(appJs, /function composerAiMentionInfo\(text\)/);
assert.match(appJs, /function composerMentionAvailable\(\)/);
assert.match(appJs, /return state\.viewMode === "single" \|\| state\.viewMode === "tasks"/);
assert.match(appJs, /function suppressTransientActivations\(ms = 700\)/);
assert.match(appJs, /function suppressTransientActivationEvent\(event\)/);
assert.match(appJs, /suppressTransientActivations\(700\)/);
assert.match(appJs, /document\.addEventListener\("click", \(event\) => \{\s+suppressTransientActivationEvent\(event\);/);
assert.match(appJs, /if \(suppressTransientActivationEvent\(event\)\) return;\s+if \(event\.pointerType === "mouse"\) return;/);
assert.match(appJs, /function ownerElevationComposerAvailable\(\)/);
assert.match(appJs, /state\.auth\?\.isOwner && state\.selectedWorkspaceId === "owner"/);
assert.match(appJs, /function ownerElevationMentionOptions\(\)/);
assert.match(appJs, /mentionText: "#高权限本次"/);
assert.match(appJs, /function activateOwnerElevationOnce\(options = \{\}\)/);
assert.match(appJs, /\/api\/owner-elevation\/once/);
assert.match(appJs, /ownerElevationOnceToken/);
assert.match(appJs, /body\.ownerElevationOnceToken = state\.ownerElevationOnceToken/);
assert.match(appJs, /stripOwnerElevationOnceTags\(text\)/);
assert.match(appJs, /if \(member\.ownerElevationOnce\) clearOwnerElevationOnce\(\);/);
assert.equal(appJs.includes('showPushToast("本次高权限已授权"'), false);
assert.match(appJs, /const ownerElevationOnceTag = ownerElevationComposerAvailable\(\) \? ownerElevationOnceTagInfo\(text\) : null/);
assert.match(appJs, /const ok = await activateOwnerElevationOnce\(\{ confirm: false \}\)/);
assert.match(appJs, /function composerGatewayPermissionLabel\(\)/);
assert.match(appJs, /function activeRunGatewayPermissionLabel\(\)/);
assert.match(appJs, /function messageUsesHighPermissionGateway\(message = \{\}\)/);
assert.doesNotMatch(appJs, /Gateway 权限 高（运行中）/);
assert.doesNotMatch(appJs, /Gateway 权限 低（运行中）/);
assert.match(appJs, /\? \{ label: "Gateway 权限 高", tone: "active" \}/);
assert.match(appJs, /Gateway 权限 高（本次）/);
assert.match(appJs, /Gateway 权限 高（限时）/);
assert.match(appJs, /Gateway 权限 低/);
assert.equal(appJs.includes('showPushToast(body ? `${title}: ${body}` : title, "success")'), false);
assert.match(appJs, /Do not duplicate real Web Push notifications with an in-app toast/);
assert.match(appJs, /function applyReasoningInfo\(info = \{\}\)/);
assert.match(appJs, /state\.assistantLabel = String\(info\.assistantLabel/);
assert.match(appJs, /function renderUsage\(usage, message = \{\}\)/);
assert.match(appJs, /\["Model", usageModelLabel\(usage, message, apiCallRows\)\]/);
assert.match(appJs, /\["Reasoning", usageReasoningLabel\(usage, message, apiCallRows\)\]/);
assert.match(appJs, /function selectedComposerReasoningEffort\(text = getComposerText\(\)\)/);
assert.match(appJs, /const aiMention = composerAiMentionInfo\(text\)/);
assert.match(appJs, /const reasoningEffort = selectedComposerReasoningEffort\(text\)/);
assert.match(appJs, /if \(reasoningEffort\) body\.reasoning_effort = reasoningEffort/);
assert.match(appJs, /const model = selectedComposerModel\(text\)/);
assert.match(appJs, /if \(model\) body\.model = model/);
assert.match(appJs, /const provider = selectedComposerProvider\(text\)/);
assert.match(appJs, /if \(provider\) body\.provider = provider/);
assert.match(appJs, /hermesDefaultComposerModel/);
assert.match(appJs, /data-default-model-option/);
assert.match(stylesCss, /\.default-model-options/);
assert.match(stylesCss, /\.default-model-option\.active/);
assert.match(indexHtml, /id="composerSearchSource"/);
assert.match(indexHtml, /id="composerSourceMenu"/);
assert.match(indexHtml, /app-composer-source-ui\.js/);
assert.match(stylesCss, /\.composer-source-button/);
assert.match(stylesCss, /\.composer-source-menu/);
assert.match(indexHtml, /data-composer-source-toggle="x"/);
assert.match(indexHtml, /data-composer-source-toggle="web"/);
assert.doesNotMatch(indexHtml, /id="composerSearchSource"[^>]*>本地/);
assert.match(stylesCss, /\.composer \.composer-source-button\s*\{[^}]*width:\s*26px;[\s\S]*?min-height:\s*26px;/);
assert.match(stylesCss, /\.composer-source-web-icon/);
assert.match(stylesCss, /\.composer\s*\{[^}]*grid-template-columns:\s*40px 54px minmax\(0, 1fr\) minmax\(50px, auto\);/s);
assert.match(stylesCss, /#composerSearchSource\s*\{[^}]*grid-column:\s*2;/s);
assert.match(stylesCss, /#messageInput\s*\{[^}]*grid-column:\s*3;/s);
assert.match(stylesCss, /#sendMessage\s*\{[^}]*grid-column:\s*4;[\s\S]*?min-width:\s*58px;[\s\S]*?padding:\s*0 10px;/);
assert.match(stylesCss, /@media \(max-width: 1099px\)[\s\S]*?\.composer\s*\{[^}]*grid-template-columns:\s*40px 50px minmax\(0, 1fr\) 52px;/);
assert.match(appJs, /composerSearchSource: "local"/);
assert.match(appJs, /COMPOSER_SEARCH_SOURCE_VISIBLE_OPTIONS/);
assert.match(appJs, /COMPOSER_SEARCH_SOURCE_OPTIONS\.filter\(\(option\) => option\.source !== COMPOSER_SEARCH_SOURCE_LOCAL\)/);
assert.match(appJs, /function selectedComposerSearchSourceInfo\(text = getComposerText\(\)\)/);
assert.match(appJs, /function composerSearchSourceAutoHint\(text = ""\)/);
assert.match(appJs, /function composerSearchSourceBodyFields\(text = getComposerText\(\)\)/);
assert.match(appJs, /source_mode: info\.sourceMode/);
assert.match(appJs, /const searchSourceFields = composerSearchSourceBodyFields\(text\)/);
assert.match(appJs, /if \(searchSourceFields\) Object\.assign\(body, searchSourceFields\)/);
assert.match(appJs, /function resetComposerSearchSource\(\)/);
assert.match(appJs, /resetComposerSearchSource\(\)/);
assert.match(appJs, /state\.composerSearchSource === normalized[\s\S]*\? COMPOSER_SEARCH_SOURCE_LOCAL[\s\S]*: normalized/);
assert.match(appJs, /querySelectorAll\("\[data-composer-source-toggle\]"\)/);
assert.match(appJs, /button\.classList\.toggle\("auto-detected", autoDetected\)/);
assert.match(stylesCss, /\.composer \.composer-source-button\.auto-detected/);
const chooseComposerSearchSourceBody = appJs.match(/function chooseComposerSearchSource\(source\) \{[\s\S]*?\n\}/)?.[0] || "";
assert.doesNotMatch(chooseComposerSearchSourceBody, /\.focus\(/);
assert.match(indexHtml, /<textarea id="messageInput"/);
assert.match(appJs, /if \(input && "value" in input\) return String\(input\.value/);
assert.match(appJs, /input\.setRangeText\(text, start, end, "end"\)/);
assert.match(appJs, /state\.composerComposing = true/);
assert.match(appJs, /state\.composerSendAfterComposition = true/);
assert.match(appJs, /function scheduleComposerSendAfterCompositionFallback\(\)/);
assert.match(appJs, /state\.composerComposing = false;\s+state\.composerSendAfterComposition = false;\s+updateComposerAction\(\);\s+updateGroupMentionMenu\(\);\s+void sendMessage\(\);/);
assert.match(appJs, /clearComposerSendAfterCompositionFallback\(\);/);
assert.match(stylesCss, /resize: none/);
assert.match(appJs, /const SHARE_IMAGE_WIDTH = 1440/);
assert.match(appJs, /const SHARE_IMAGE_SCALE = 3/);
assert.match(appJs, /const SHARE_IMAGE_MAX_PIXELS = 48000000/);
assert.match(appJs, /function shareImageRenderScale\(layout\)/);
assert.match(appJs, /ctx\.scale\(scale, scale\)/);
assert.match(appJs, /streamingMessageRenderScheduled: new Set\(\)/);
assert.match(appJs, /streamingMessageRenderLastAt: new Map\(\)/);
assert.match(appJs, /expandedLongMessageIds: new Set\(\)/);
assert.match(appJs, /runProgressTicker: 0/);
assert.match(appJs, /STREAMING_MESSAGE_RENDER_THROTTLE_MS/);
assert.match(appJs, /function renderStreamingMessageContent\(message\)/);
assert.match(appJs, /content\.outerHTML = renderText\(message\.content \|\| "", message\)/);
assert.match(appJs, /content\.textContent = cleanDisplayText\(message\.content \|\| ""\)/);
assert.match(appJs, /function scheduleStreamingMessageRender\(message\)/);
assert.match(appJs, /ACTIVE_MESSAGE_RICH_RENDER_LIMIT/);
assert.match(appJs, /function shouldRenderLongMessagePreview\(text, message = \{\}\)/);
assert.match(appJs, /function renderLongMessagePreview\(text, aliases, message = \{\}\)/);
assert.match(appJs, /function wireLongMessageButtons\(root\)/);
assert.match(appJs, /wireLongMessageButtons\(conversation\)/);
assert.match(appJs, /if \(!scheduleStreamingMessageRender\(message\)\) scheduleRenderCurrentThread\(\)/);
assert.match(appJs, /function renderRunProgressPanel\(thread, runIds, options = \{\}\)/);
assert.doesNotMatch(appJs, /function renderRunProgressPanel\(thread, runIds(?:, options = \{\})?\) \{\s*return "";/);
assert.match(appJs, /function runProgressOffsetLabel\(startMs, eventMs\)/);
assert.match(appJs, /runEventTimeLabel\(event, startMs\)/);
assert.doesNotMatch(appJs, /toLocaleTimeString/);
assert.match(appJs, /function renderMessageRunProgress\(thread, message = \{\}\)/);
assert.match(appJs, /renderMessageRunProgress\(state\.currentThread, message\)/);
assert.match(appJs, /runProgressRenderScheduled: new Set\(\)/);
assert.match(appJs, /function scheduleRunProgressRenderForRun\(runId\)/);
assert.match(appJs, /if \(!scheduleRunProgressRenderForRun\(event\.runId \|\| payload\.runId \|\| ""\)\) scheduleRenderCurrentThread\(\)/);
const appendRunEventBody = appJs.match(/function appendRunEventToCurrentThread\(payload\) \{[\s\S]*?\n\}/)?.[0] || "";
assert.doesNotMatch(appendRunEventBody, /renderThreads\(\)/);
assert.doesNotMatch(appendRunEventBody, /scheduleRenderCurrentThread\(\);\s*$/);
assert.match(appJs, /function syncRunProgressTicker\(root = document\)/);
assert.match(appJs, /syncRunProgressTicker\(conversation\)/);
assert.match(appJs, /timeoutMs: 6000/);
assert.doesNotMatch(appJs, /conversation\.innerHTML = `\$\{historyPager\}\$\{progressPanel\}/);
assert.match(stylesCss, /\.long-message-preview/);
assert.match(stylesCss, /\.long-message-toggle/);

assert.equal(indexHtml.includes("taskReasoningSelect"), false);
assert.equal(stylesCss.includes("taskReasoningSelect"), false);
assert.equal(stylesCss.includes("reasoning-visible"), false);
assert.equal(appJs.includes('$("#taskReasoningSelect")'), false);
assert.equal(appJs.includes('"taskReasoningSelect"'), false);

console.log("composer AI mention UI tests passed");
