"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const repoRoot = path.resolve(__dirname, "..");
const appJs = fs.readFileSync(path.join(repoRoot, "public", "app.js"), "utf8");
const indexHtml = fs.readFileSync(path.join(repoRoot, "public", "index.html"), "utf8");
const stylesCss = fs.readFileSync(path.join(repoRoot, "public", "styles.css"), "utf8");

assert.match(appJs, /VIRTUAL_GROUP_AI_MEMBER/);
assert.match(appJs, /function groupChatMentionsAi\(text\)/);
assert.match(appJs, /body\.messageKind = aiMention\.mentionsAi \? "ai" : "plain"/);
assert.match(appJs, /return \[virtualAssistantMember\(\), \.\.\.realMembers\]/);
assert.match(appJs, /groupChatMentionMembers\(state\.currentThread, \{ includeAi: false \}\)/);
assert.match(appJs, /groupChatAvailable: false/);
assert.match(appJs, /groupChatThread: null/);
assert.match(appJs, /weixinChatAvailable: false/);
assert.match(appJs, /weixinChatThread: null/);
assert.match(appJs, /function mergeChatScopeThread\(existingThread, incomingThread\)/);
assert.match(appJs, /function chatScopeThread\(thread, scope\)/);
assert.match(appJs, /state\.groupChatAvailable/);
assert.match(appJs, /result\.groupChatThread/);
assert.match(appJs, /state\.groupChatAvailable = Boolean\(result\.groupChatAvailable \|\| selectedWorkspaceInThreadGroup\(state\.currentThread\)\)/);
assert.match(appJs, /function upsertCachedChatScopeMessage\(threadId, message, threadSummary = null\)/);
assert.match(indexHtml, /id="chatScopeHeader"/);
assert.match(appJs, /function renderChatScopeHeader\(thread\)/);
assert.match(appJs, /function wireChatScopeHeader\(root\)/);
assert.match(appJs, /function unreadChatScopeCount\(thread, scope\)/);
assert.match(appJs, /if \(!\(single && state\.singleWindowMode === "chat"\)\) renderChatScopeHeader\(null\);/);
assert.match(appJs, /const CHAT_SCOPE_SESSION_STARTED_AT = Date\.now\(\)/);
assert.match(appJs, /return Number\.isFinite\(value\) && value > 0 \? value : CHAT_SCOPE_SESSION_STARTED_AT/);
assert.match(appJs, /Missing read markers intentionally fall back to the page-load timestamp/);
assert.doesNotMatch(appJs, /setChatScopeReadAt\(scope, latest \|\| Date\.now\(\)\)/);
assert.match(appJs, /hermesChatScopeRead:/);
assert.match(appJs, /chat-scope-header-badge/);
assert.match(appJs, /scopeButton\("chat", "\\u804a\\u5929"/);
assert.match(appJs, /scopeButton\("group", "\\u7fa4"/);
assert.match(indexHtml, /id="topManageGroupMembers"/);
assert.match(indexHtml, /id="topToggleWeixinChat"/);
assert.match(appJs, /function selectChatScope\(scope\)/);
assert.match(appJs, /function selectWeixinChat\(open = true\)/);
assert.match(appJs, /await selectChatScope\(isGroupChatView\(\) \? "chat" : "group"\)/);
assert.match(appJs, /toggleGroupChat\.hidden = true/);
assert.match(appJs, /\$\("topToggleWeixinChat"\)\?\.addEventListener\("click"/);
assert.doesNotMatch(appJs, /data-open-group-members/);
assert.doesNotMatch(appJs, /function renderGroupMemberStrip/);
assert.doesNotMatch(appJs, /function renderChatScopeSwitcher/);
assert.doesNotMatch(appJs, /function wireChatScopeSwitcher/);
assert.doesNotMatch(stylesCss, /\.chat-scope-switcher/);
assert.doesNotMatch(stylesCss, /\.group-member-strip/);
assert.match(stylesCss, /\.chat-scope-header/);
assert.match(stylesCss, /\.chat-scope-segment/);
assert.match(stylesCss, /\.chat-scope-header-button\.active/);
assert.match(stylesCss, /\.chat-scope-header-badge/);

assert.equal(indexHtml.includes("chatAiToggle"), false);
assert.equal(appJs.includes("chatAiToggle"), false);
assert.equal(stylesCss.includes("chat-ai-toggle"), false);

console.log("group-chat UI tests passed");
