"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const repoRoot = path.resolve(__dirname, "..");
const serverJs = fs.readFileSync(path.join(repoRoot, "server.js"), "utf8");
const appJs = fs.readFileSync(path.join(repoRoot, "public", "app.js"), "utf8");
const stylesCss = fs.readFileSync(path.join(repoRoot, "public", "styles.css"), "utf8");
const fileViewer = fs.readFileSync(path.join(repoRoot, "public", "file-viewer.html"), "utf8");
const adapterJs = fs.readFileSync(path.join(repoRoot, "adapters", "automation-provider.js"), "utf8");
const cronBridge = fs.readFileSync(path.join(repoRoot, "cron_bridge.py"), "utf8");

assert.match(serverJs, /AUTOMATION_PUSH_DELIVERABLE_EXTENSIONS = new Set\(\["\.md", "\.pdf"/);
assert.match(serverJs, /Write final document deliverables as Markdown by default/);
assert.match(serverJs, /Markdown\/PDF\/Office file/);
assert.match(serverJs, /const localPath = artifact\.localPath \|\| artifact\.path/);
assert.match(serverJs, /stat = fs\.statSync\(localPath\)/);
assert.match(serverJs, /function compactArtifactsForMessage\(message, thread = null\)/);
assert.match(serverJs, /function attachUploadedArtifactsToMessage\(thread, message\)/);
assert.match(serverJs, /artifact\.messageId = message\.id/);
assert.match(serverJs, /function findArtifactReferenceById\(artifactId\)/);
assert.match(serverJs, /reference = findArtifactReferenceById\(artifactId\)/);
assert.match(serverJs, /const threadUploadRoot = thread\?\.id \? path\.join\(DATA_DIR, "uploads", thread\.id\) : ""/);
assert.match(serverJs, /HERMES_MOBILE_SOURCE_MARKDOWN_SEARCH_LIMIT/);
assert.match(serverJs, /function findSourceMarkdownForArtifact\(thread, value\)/);
assert.match(serverJs, /source_md_\$\{crypto\.createHash\("sha1"\)/);
assert.match(serverJs, /\/api\/files\?\$\{params\.toString\(\)\}/);
assert.match(serverJs, /\/api\/app-update\/status/);
assert.match(serverJs, /\/api\/app-update\/apply/);
assert.match(serverJs, /gitRepositoryStatus/);
assert.match(serverJs, /merge", "--ff-only"/);

assert.match(appJs, /function isMarkdownArtifact\(artifact\)/);
assert.match(appJs, /function displayArtifacts\(artifacts\)/);
assert.match(appJs, /query\.set\("workspaceId", state\.selectedWorkspaceId\)/);
assert.match(appJs, /query\.set\("threadId", state\.currentThreadId\)/);
assert.match(appJs, /const markdownDocuments = artifacts\.filter\(isMarkdownArtifact\)/);
assert.match(appJs, /markdownStems\.has\(artifactStem\(artifact\)\)/);
assert.match(appJs, /displayArtifacts\(artifacts\)\.map/);
assert.match(appJs, /return "markdown"/);
assert.match(appJs, /return "html"/);
assert.match(appJs, /if \(kind === "markdown"\) return "MD"/);
assert.match(appJs, /if \(kind === "html"\) return "HTML"/);
assert.match(appJs, /if \(kind === "html"\) return url/);
assert.match(appJs, /function checkAppUpdate\(reason = "login"\)/);
assert.match(appJs, /function applyAppUpdateFromBadge\(\)/);
assert.match(appJs, /function isSelfUpdateUnsupported\(result\)/);
assert.match(appJs, /function appUpdateToastKind\(result\)/);
assert.match(appJs, /当前安装方式不支持应用内更新。/);
assert.match(appJs, /owner-admin-sheet/);
assert.match(appJs, /owner-workspace-card/);
assert.match(appJs, /data-workspace-config-section/);
assert.match(appJs, /localWorkspaceSection[\s\S]+workspaceCreateForm[\s\S]+deploymentWorkspaceSection/);
assert.match(appJs, /data-update-available/);

assert.match(stylesCss, /\.group-mention-menu[\s\S]+max-height: min\(360px/);
assert.match(stylesCss, /@media \(max-width: 760px\)[\s\S]+\.group-mention-menu[\s\S]+max-height: min\(340px/);

assert.match(fileViewer, /function renderMarkdownDocument\(text\)/);
assert.match(fileViewer, /class="markdown-table-wrap"/);
assert.match(fileViewer, /data-label="\$\{escapeHtml\(label\)\}"/);
assert.match(fileViewer, /td::before[\s\S]+content: attr\(data-label\)/);
assert.match(fileViewer, /@media \(max-width: 640px\)/);
assert.match(fileViewer, /url\.pathname === "\/api\/files\/preview"/);
assert.match(fileViewer, /url\.pathname = "\/api\/files"/);
assert.match(fileViewer, /function markdownExportHtml\(options = \{\}\)/);
assert.match(fileViewer, /function shareGeneratedMarkdownFile\(format\)/);
assert.match(fileViewer, /function printMarkdownAsPdf\(\)/);
assert.match(fileViewer, /function openMarkdownPrintWindow\(\)/);
assert.match(fileViewer, /window\.open\("about:blank", "_blank"\)/);
assert.match(fileViewer, /markdownExportHtml\(\{ autoPrint: true \}\)/);
assert.match(fileViewer, /URL\.createObjectURL\(blob\)/);
assert.match(fileViewer, /Share raw \.md explicitly/);
assert.match(fileViewer, /data-markdown-share="group"/);
assert.match(fileViewer, /function forwardMarkdownToGroup\(\)/);
assert.match(fileViewer, /\/api\/single-window/);
assert.match(fileViewer, /taskGroupId: "group-chat"/);
assert.match(fileViewer, /messageKind: "plain"/);
assert.match(fileViewer, /new TextEncoder\(\)\.encode\(text\)/);
assert.match(fileViewer, /if \(isMarkdownDocument\(\)\) \{/);
assert.match(fileViewer, /loadTextPreview\("Markdown preview", \{ markdown: true \}\)/);
assert.match(fileViewer, /return "HTML"/);
assert.match(fileViewer, /if \(src && kind === "HTML"\) \{/);
assert.match(fileViewer, /location\.replace\(originalUrlFor\(src\)\)/);
assert.match(fileViewer, /if \(src && !isMarkdownDocument\(\)\) window\.setTimeout\(\(\) => prepareShareBlob/);

assert.ok(adapterJs.includes("const aMarkdown = /\\.md$/i.test(a) ? 0 : 1;"));
assert.match(cronBridge, /MEDIA_DOCUMENT_EXTENSIONS = \{"\.md"\} \| EXPORT_DOCUMENT_EXTENSIONS/);
assert.match(cronBridge, /def deliverable_items_from_run\(path: Path\)/);
assert.match(cronBridge, /def source_markdown_for_delivery\(run_path: Path, delivery_path: Path\)/);
assert.match(cronBridge, /"source-markdown"/);
assert.match(cronBridge, /document_source_rank\(item\)/);

console.log("markdown delivery UI tests passed");
