"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { readAppShellSource } = require("./app-shell-test-helper");

const repoRoot = path.resolve(__dirname, "..");
const serverJs = fs.readFileSync(path.join(repoRoot, "mobile-server-runtime.js"), "utf8");
const runtimeEnvironmentJs = fs.readFileSync(path.join(repoRoot, "adapters", "mobile-runtime-environment-service.js"), "utf8");
const runtimeStatePathEnvironmentJs = fs.readFileSync(path.join(repoRoot, "adapters", "mobile-runtime-state-path-environment-service.js"), "utf8");
const mobileApiComposition = fs.readFileSync(path.join(repoRoot, "server-routes", "mobile-api-composition.js"), "utf8");
const systemApiRoutes = fs.readFileSync(path.join(repoRoot, "server-routes", "system-api-routes.js"), "utf8");
const threadReadUploadApiRoutes = fs.readFileSync(path.join(repoRoot, "server-routes", "thread-read-upload-api-routes.js"), "utf8");
const mobileApiDispatcher = fs.readFileSync(path.join(repoRoot, "server-routes", "mobile-api-dispatcher.js"), "utf8");
const fileArtifactAccessService = fs.readFileSync(path.join(repoRoot, "adapters", "file-artifact-access-service.js"), "utf8");
const fileArtifactResolverService = fs.readFileSync(path.join(repoRoot, "adapters", "file-artifact-resolver-service.js"), "utf8");
const artifactTextRegistrationServiceJs = fs.readFileSync(path.join(repoRoot, "adapters", "artifact-text-registration-service.js"), "utf8");
const runtimeStateThreadServiceJs = fs.readFileSync(path.join(repoRoot, "adapters", "runtime-state-thread-service.js"), "utf8");
const gatewayRunInstructionServiceJs = fs.readFileSync(path.join(repoRoot, "adapters", "gateway-run-instruction-service.js"), "utf8");
const systemRuntimeStatusServiceJs = fs.readFileSync(path.join(repoRoot, "adapters", "system-runtime-status-service.js"), "utf8");
const webPushDeliveryServiceJs = fs.readFileSync(path.join(repoRoot, "adapters", "web-push-delivery-service.js"), "utf8");
const appJs = readAppShellSource(repoRoot);
const taskArtifactHelpersJs = fs.readFileSync(path.join(repoRoot, "public", "app-task-artifact-helpers.js"), "utf8");
const stylesCss = fs.readFileSync(path.join(repoRoot, "public", "styles.css"), "utf8");
const fileViewer = fs.readFileSync(path.join(repoRoot, "public", "file-viewer.html"), "utf8");
const markdownViewer = fs.readFileSync(path.join(repoRoot, "public", "markdown-viewer.html"), "utf8");
const markdownRendererClient = fs.readFileSync(path.join(repoRoot, "public", "markdown-renderer-client.js"), "utf8");
const adapterJs = fs.readFileSync(path.join(repoRoot, "adapters", "automation-provider.js"), "utf8");
const cronBridge = fs.readFileSync(path.join(repoRoot, "cron_bridge.py"), "utf8");

assert.match(runtimeEnvironmentJs, /AUTOMATION_PUSH_DELIVERABLE_EXTENSIONS = new Set\(\["\.md", "\.pdf"/);
assert.match(gatewayRunInstructionServiceJs, /Write final document deliverables as Markdown by default/);
assert.match(webPushDeliveryServiceJs, /Markdown\/PDF\/Office file/);
assert.match(fileArtifactResolverService, /const localPath = artifact\.localPath \|\| artifact\.path/);
assert.match(fileArtifactResolverService, /stat = deps\.fs\.statSync\(localPath\)/);
assert.match(serverJs, /function compactArtifactsForMessage\(message, thread = null\)/);
assert.match(serverJs, /function attachUploadedArtifactsToMessage\(thread, message\)/);
assert.match(fileArtifactAccessService, /artifact\.messageId = message\.id/);
assert.match(runtimeStateThreadServiceJs, /function findArtifactReferenceById\(artifactId\)/);
assert.match(serverJs, /findArtifactReferenceById: \(\.\.\.args\) => getRuntimeStateThreadService\(\)\.findArtifactReferenceById\(\.\.\.args\)/);
assert.match(fileArtifactResolverService, /reference = deps\.findArtifactReferenceById\(artifactId\)/);
assert.match(runtimeStatePathEnvironmentJs, /const WORKSPACE_UPLOAD_DIR_NAME = "\.hermes-mobile"/);
assert.match(serverJs, /function workspaceUploadDirectoryForRequest\(auth, thread, body = \{\}\)/);
assert.match(fileArtifactAccessService, /function workspaceUploadDirectoryForRequest\(auth, thread, body = \{\}\)/);
assert.match(mobileApiComposition, /createThreadReadUploadApiRoutes/);
assert.match(mobileApiDispatcher, /key: "threadReadUploadApiRoutes"/);
assert.match(threadReadUploadApiRoutes, /const uploadDir = uploadTarget\.uploadDir/);
assert.match(threadReadUploadApiRoutes, /registerUploadArtifact\(thread, null, filePath, filename, \{ workspaceId: uploadTarget\.workspaceId \}\)/);
assert.match(runtimeEnvironmentJs, /HERMES_MOBILE_SOURCE_MARKDOWN_SEARCH_LIMIT/);
assert.match(serverJs, /function findSourceMarkdownForArtifact\(thread, value\)/);
assert.match(serverJs, /createArtifactTextRegistrationService/);
assert.match(serverJs, /getArtifactTextRegistrationService\(\)\.compactArtifactsForMessage/);
assert.match(artifactTextRegistrationServiceJs, /source_md_\$\{deps\.crypto\.createHash\("sha1"\)/);
assert.match(artifactTextRegistrationServiceJs, /\/api\/files\?\$\{params\.toString\(\)\}/);
assert.match(systemApiRoutes, /\/api\/app-update\/status/);
assert.match(systemApiRoutes, /\/api\/app-update\/apply/);
assert.match(systemRuntimeStatusServiceJs, /async function gitRepositoryStatus\(\)/);
assert.match(systemRuntimeStatusServiceJs, /merge", "--ff-only"/);

assert.match(appJs, /function isMarkdownArtifact\(artifact\)/);
assert.match(appJs, /function displayArtifacts\(artifacts\)/);
assert.match(appJs, /TaskArtifactHelpers\.isMarkdownArtifact\(artifact\)/);
assert.match(appJs, /TaskArtifactHelpers\.displayArtifacts\(artifacts\)/);
assert.match(appJs, /<a class="artifact-card doc-\$\{escapeHtml\(artifactKind\(artifact\)\)\}" href="\$\{escapeHtml\(artifactHref\(artifact\)\)\}" target="_self" data-task-doc data-artifact-mime/);
assert.match(appJs, /<a class="task-doc-icon doc-\$\{escapeHtml\(artifactKind\(latestArtifact\)\)\}" href="\$\{escapeHtml\(artifactHref\(latestArtifact\)\)\}" target="_self" data-task-doc data-artifact-mime/);
assert.match(appJs, /data-task-doc/);
assert.match(appJs, /function openImagePreviewOverlay\(link\)/);
assert.match(appJs, /function openMarkdownPreviewOverlay\(link\)/);
assert.match(appJs, /fontScale: "large"/);
assert.match(appJs, /const PREVIEW_HISTORY_KEY = "__hermesTaskPreview"/);
assert.match(appJs, /global\.addEventListener\("popstate"/);
assert.match(appJs, /global\.history\.pushState\(nextState/);
assert.match(appJs, /function closeActivePreviewFromUser\(\)/);
assert.match(appJs, /current\.target === "artifact-preview"/);
assert.match(appJs, /query\.set\("workspaceId", state\.selectedWorkspaceId\)/);
assert.match(appJs, /workspaceId: state\.selectedWorkspaceId \|\| "owner"/);
assert.match(appJs, /query\.set\("threadId", state\.currentThreadId\)/);
assert.match(taskArtifactHelpersJs, /const markdownDocuments = artifacts\.filter\(isMarkdownArtifact\)/);
assert.match(taskArtifactHelpersJs, /markdownStems\.has\(artifactStem\(artifact\)\)/);
assert.match(appJs, /displayArtifacts\(artifacts\)\.map/);
assert.match(taskArtifactHelpersJs, /return "markdown"/);
assert.match(taskArtifactHelpersJs, /return "html"/);
assert.match(appJs, /if \(kind === "markdown"\) return "MD"/);
assert.match(appJs, /if \(kind === "html"\) return "HTML"/);
assert.match(appJs, /kind === "html" \|\| mime\.startsWith\("image\/"\)/);
assert.match(appJs, /if \(kind === "markdown"\) return `\/markdown-viewer\.html\?\$\{query\.toString\(\)\}`/);
assert.match(stylesCss, /\.task-markdown-preview-overlay/);
assert.match(stylesCss, /\.task-markdown-preview-doc h1 \{[\s\S]*?font-size: 24px;/);
assert.match(stylesCss, /\.task-markdown-preview-doc h2 \{[\s\S]*?font-size: 22px;/);
assert.match(appJs, /function checkAppUpdate\(reason = "login"\)/);
assert.match(appJs, /function applyAppUpdateFromBadge\(\)/);
assert.match(appJs, /function isSelfUpdateUnsupported\(result\)/);
assert.match(appJs, /function appUpdateToastKind\(result\)/);
assert.match(appJs, /当前安装方式不支持应用内更新。/);
assert.match(appJs, /owner-admin-sheet/);
assert.match(appJs, /owner-workspace-card/);
assert.match(appJs, /data-workspace-config-section/);
assert.match(appJs, /localWorkspaceSection[\s\S]+workspaceCreateForm[\s\S]+deploymentWorkspaceSection/);
assert.match(appJs, /data-update-available/);

assert.match(stylesCss, /\.group-mention-menu[\s\S]+max-height: min\(320px/);
assert.match(stylesCss, /@media \(max-width: 1099px\)[\s\S]+\.group-mention-menu[\s\S]+max-height: min\(300px/);
assert.match(stylesCss, /\.automation-card-title \{[\s\S]*?font-weight: 600;/);
assert.match(stylesCss, /\.automation-doc-name \{[\s\S]*?font-weight: 500;/);
assert.match(stylesCss, /\.automation-doc-label \{[\s\S]*?font-weight: 500;/);
assert.match(stylesCss, /\.automation-state-time \{[\s\S]*?font-weight: 500;/);
assert.match(stylesCss, /\.directory-entry-name \{[\s\S]*?font-size: 15px;/);
assert.match(stylesCss, /\.todo-card-title \{[\s\S]*?font-size: 15px;/);
assert.match(stylesCss, /\.automation-card-title \{[\s\S]*?font-size: 15px;/);
assert.match(
  stylesCss,
  /:root\[data-font-size\] \.message-prose h3,[\s\S]*?:root\[data-font-size\] \.task-title-line,[\s\S]*?:root\[data-font-size\] \.directory-entry-name,[\s\S]*?:root\[data-font-size\] \.todo-card-title,[\s\S]*?:root\[data-font-size\] \.automation-card-title,[\s\S]*?:root\[data-font-size\] \.automation-doc-name,[\s\S]*?font-size: calc\(15px \* var\(--app-font-scale\)\);/
);
assert.doesNotMatch(
  stylesCss,
  /:root\[data-font-size\] \.message-body,[\s\S]*?:root\[data-font-size\] \.(?:directory-entry-name|todo-card-title|automation-card-title|automation-doc-name),[\s\S]*?font-size: calc\(16\.8px \* var\(--app-font-scale\)\);/
);
assert.match(
  stylesCss,
  /:root\[data-font-size\] \.automation-doc-preview\.compact \.automation-doc-name \{[\s\S]*?font-size: calc\(13px \* var\(--app-font-scale\)\);/
);

assert.match(fileViewer, /\/markdown-renderer-client\.js\?v=20260515-md-font-stepdown/);
assert.match(fileViewer, /const markdownRenderer = window\.HermesMarkdownRenderer/);
assert.match(fileViewer, /markdownRenderer\.renderMarkdownDocument\(text, \{/);
assert.match(fileViewer, /fontScale: currentViewerPreferences\(\)\.markdownSize\.id/);
assert.doesNotMatch(fileViewer, /linkTarget: "_blank"/);
assert.match(fileViewer, /taskListCompatibility: true/);
assert.match(fileViewer, /const escapeHtml = markdownRenderer\.escapeHtml/);
assert.doesNotMatch(fileViewer, /function sanitizeMarkdownLinkHref\(href\)/);
assert.doesNotMatch(fileViewer, /function renderInlineMarkdown\(value\)/);
assert.match(markdownRendererClient, /hermes-markdown-doc/);
assert.match(markdownRendererClient, /hermes-markdown-mobile/);
assert.match(markdownRendererClient, /markdown-table-wrap hermes-markdown-table-wrapper table-wrapper/);
assert.match(markdownRendererClient, /hermes-markdown-list task-list hermes-markdown-task-list/);
assert.match(markdownRendererClient, /task-list-item hermes-markdown-task-item/);
assert.match(fileViewer, /td::before[\s\S]+content: attr\(data-label\)/);
assert.match(fileViewer, /@media \(max-width: 640px\)/);
assert.match(fileViewer, /--hermes-markdown-font-family: var\(--viewer-font-family\)/);
assert.match(fileViewer, /--viewer-markdown-font-scale: 1;/);
assert.match(fileViewer, /function viewerMarkdownSizeOption\(value\) \{[\s\S]*?Math\.max\(0, index\)\)\] \|\| option;/);
assert.match(fileViewer, /font-size: calc\(18px \* var\(--viewer-markdown-font-scale\)\)/);
assert.match(fileViewer, /url\.pathname === "\/api\/files\/preview"/);
assert.match(fileViewer, /url\.pathname = "\/api\/files"/);
assert.match(fileViewer, /function markdownExportHtml\(options = \{\}\)/);
assert.match(fileViewer, /function shareGeneratedMarkdownFile\(format\)/);
assert.match(fileViewer, /function printMarkdownAsPdf\(\)/);
assert.doesNotMatch(fileViewer, /function openMarkdownPrintWindow\(\)/);
assert.doesNotMatch(fileViewer, /window\.open\(/);
assert.match(fileViewer, /markdownExportHtml\(\{ autoPrint: true \}\)/);
assert.match(fileViewer, /URL\.createObjectURL\(blob\)/);
assert.match(fileViewer, /const iframe = document\.createElement\("iframe"\)/);
assert.match(fileViewer, /iframe\.contentWindow\?\.print\?\.\(\)/);
assert.match(fileViewer, /downloadGeneratedBlob\(blob, markdownBaseName\("html"\)\)/);
assert.match(fileViewer, /Share raw \.md explicitly/);
assert.match(fileViewer, /data-markdown-share="group"/);
assert.match(fileViewer, /data-markdown-share="weixin"/);
assert.match(fileViewer, /id="markdownShareStatus"/);
assert.match(fileViewer, /function setMarkdownShareStatus\(message, kind = ""\)/);
assert.match(fileViewer, /function setMarkdownShareBusy\(button, busy\)/);
assert.match(fileViewer, /inlineFile: \{/);
assert.match(fileViewer, /contentBase64: bytesToBase64\(new TextEncoder\(\)\.encode\(text\)\)/);
assert.match(fileViewer, /\.viewer-toast \{[\s\S]*?z-index: 30;/);
assert.match(fileViewer, /\.viewer-sheet \{[\s\S]*?z-index: 20;/);
assert.match(fileViewer, /\.viewer-sheet-status\.error/);
assert.match(fileViewer, /function forwardMarkdownToGroup\(\)/);
assert.doesNotMatch(fileViewer, /resolveWeixinForwardTarget/);
assert.match(fileViewer, /\/api\/single-window/);
assert.match(fileViewer, /taskGroupId: "group-chat"/);
assert.match(fileViewer, /messageKind: "plain"/);
assert.match(fileViewer, /new TextEncoder\(\)\.encode\(text\)/);
assert.match(fileViewer, /if \(isMarkdownDocument\(\)\) \{/);
assert.match(fileViewer, /loadTextPreview\("Markdown preview", \{ markdown: true \}\)/);
assert.match(fileViewer, /return "HTML"/);
assert.match(fileViewer, /if \(src && kind === "HTML"\) \{/);
assert.match(fileViewer, /location\.replace\(originalUrlFor\(src\)\)/);
assert.doesNotMatch(fileViewer, /renderIframePreview\("HTML preview"\)/);
assert.match(fileViewer, /if \(src && !isMarkdownDocument\(\)\) window\.setTimeout\(\(\) => prepareShareBlob/);
assert.match(markdownViewer, /markdown-renderer-client\.js\?v=20260515-md-font-stepdown/);
assert.match(markdownViewer, /markdownRenderer\.renderMarkdownDocument/);
assert.match(markdownViewer, /"Noto Serif CJK SC", "Source Han Serif SC", "Songti SC", "SimSun"/);
assert.match(markdownViewer, /--viewer-markdown-font-scale: 1\.18/);
assert.match(markdownViewer, /fontScale: "large"/);
assert.match(markdownViewer, /function collapseBrowserChrome\(\)/);
assert.match(markdownViewer, /window\.scrollTo\(0, 1\)/);
assert.match(markdownViewer, /taskListCompatibility: true/);
assert.match(markdownViewer, /\/api\/files\/preview\?\$\{url\.searchParams\.toString\(\)\}/);
assert.doesNotMatch(markdownViewer, /viewer-more-button|viewer-done-button|topbar/);

assert.ok(adapterJs.includes("const aMarkdown = /\\.md$/i.test(a) ? 0 : 1;"));
assert.match(cronBridge, /MEDIA_DOCUMENT_EXTENSIONS = \{"\.md"\} \| EXPORT_DOCUMENT_EXTENSIONS/);
assert.match(cronBridge, /def deliverable_items_from_run\(path: Path\)/);
assert.match(cronBridge, /def source_markdown_for_delivery\(run_path: Path, delivery_path: Path\)/);
assert.match(cronBridge, /"source-markdown"/);
assert.match(cronBridge, /document_source_rank\(item\)/);

console.log("markdown delivery UI tests passed");
