"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const repoRoot = path.resolve(__dirname, "..");
const script = fs.readFileSync(path.join(repoRoot, "scripts", "playwright-visual-smoke.js"), "utf8");
const testMatrix = fs.readFileSync(path.join(repoRoot, "docs", "TEST_MATRIX.md"), "utf8");
const staticClientDoc = fs.readFileSync(path.join(repoRoot, "docs", "MODULES", "static-client.md"), "utf8");
const mapDoc = fs.readFileSync(path.join(repoRoot, "docs", "ARCHITECTURE_CODE_TEST_HARNESS_MAP.md"), "utf8");

assert.match(script, /getBoundingClientRect\(\)/);
assert.match(script, /argValue\("--access-key-path"/);
assert.match(script, /HERMES_VISUAL_SMOKE_ACCESS_KEY_PATH/);
assert.match(script, /HERMES_WEB_AUTH_KEY_PATH/);
assert.match(script, /localStorage\.setItem\("hermesWebKey", key\)/);
assert.match(script, /name: "hermes_web_key"/);
assert.match(script, /waitForFunction/);
assert.match(script, /authenticated_shell_not_visible/);
assert.match(script, /authenticatedInput: Boolean\(accessKey\)/);
assert.doesNotMatch(script, /console\.log\(accessKey/);
assert.doesNotMatch(script, /accessKeyPath:\s*accessKeyPath/);
assert.match(script, /HERMES_VISUAL_SMOKE_STRICT/);
assert.match(script, /HERMES_VISUAL_SMOKE_VIEW/);
assert.match(script, /argValue\("--open-capability-menu"/);
assert.match(script, /"--open-plugin-drawer-menu"/);
assert.match(script, /HERMES_VISUAL_SMOKE_OPEN_PLUGIN_DRAWER_MENU/);
assert.match(script, /openPluginDrawerQuickMenu/);
assert.match(script, /setGlobalPluginDockExpanded\(true, \{ persist: false \}\)/);
assert.match(script, /#topicPluginDock \.plugin-drawer-quick-card/);
assert.match(script, /#topicPluginDock \.plugin-app-card\[data-plugin-topic-open-app="\$\{openPluginDrawerMenu\}"\]/);
assert.match(script, /pluginDrawerMenuGesture = "contextmenu"/);
assert.match(script, /pluginDrawerMenuGesture = "click"/);
assert.match(script, /dispatchEvent\("contextmenu"/);
assert.match(script, /plugin_drawer_menu_not_opened/);
assert.match(script, /visibleDockMenuOpened/);
assert.match(script, /capability-action-menu:not\(\[hidden\]\)/);
assert.match(script, /HERMES_VISUAL_SMOKE_OPEN_CAPABILITY_MENU/);
assert.match(script, /HERMES_VISUAL_SMOKE_WORKSPACE_ID/);
assert.match(script, /HERMES_VISUAL_SMOKE_LONG_TASK_WARN_MS/);
assert.match(script, /HERMES_VISUAL_SMOKE_FAIL_ON_LONG_TASK/);
assert.match(script, /argValue\("--viewport"/);
assert.match(script, /HERMES_VISUAL_SMOKE_VIEWPORT/);
assert.match(script, /HERMES_VISUAL_SMOKE_VIEWPORT_WIDTH/);
assert.match(script, /HERMES_VISUAL_SMOKE_VIEWPORT_HEIGHT/);
assert.match(script, /normalizePositiveNumberEnv/);
assert.match(script, /--desktop/);
assert.match(script, /--mobile/);
assert.match(script, /browserContext/);
assert.match(script, /performance\.getEntriesByType\("longtask"\)/);
assert.match(script, /long_task_detected/);
assert.match(script, /value === undefined \|\| value === ""/);
assert.match(script, /hermesStartupPerfLast/);
assert.match(script, /startupPerfLast/);
assert.match(script, /horizontal_overflow/);
assert.match(script, /bottom_nav_out_of_view/);
assert.match(script, /--mobile-bottom-nav-visual-drop/);
assert.match(script, /mobileBottomNavVisualDrop/);
assert.match(script, /bottom_nav_visible_area_too_small/);
assert.match(script, /visibleHeight: round\(visibleHeight\)/);
assert.match(script, /bottom_nav_button_visible_area_too_small/);
assert.match(script, /bottom_nav_too_tall/);
assert.match(script, /composer_bottom_nav_overlap/);
assert.match(script, /top_bar_bottom_nav_overlap/);
assert.match(script, /topic_plugin_dock_bottom_nav_overlap/);
assert.match(script, /verticalOverlapPx/);
assert.match(script, /topicPluginDockNavOverlap/);
assert.match(script, /topicDockBottomNavOverlapTolerance/);
assert.match(script, /overlapPx: round\(topicDockBottomNavOverlapY\)/);
assert.match(script, /mobileBottomStackHeight/);
assert.match(script, /topicPluginDockReservedHeight/);
assert.match(script, /conversationPaddingBottom/);
assert.match(script, /topic_plugin_dock_scroll_reserve_too_small/);
assert.doesNotMatch(script, /topic_plugin_dock_conversation_overlap/);
assert.match(script, /no_tracked_shell_surface_visible/);
assert.match(script, /dockPluginIconCount/);
assert.match(script, /pluginDrawerQuickCardCount/);
assert.match(script, /pluginDrawerQuickActionCount/);
assert.match(script, /plugin_drawer_quick_card_missing/);
assert.match(script, /plugin_drawer_quick_actions_missing/);
assert.match(script, /openPluginDrawerQuickMenu && pluginDrawerMenuOpened/);
assert.match(script, /plugin_drawer_menu_bottom_nav_overlap/);
assert.match(script, /\.plugin-drawer-quick-card/);
assert.match(script, /\[data-plugin-drawer-action-menu\]:not\(\[hidden\]\) \[data-plugin-topic-action-plugin\]\[data-plugin-topic-action-id\]/);
assert.match(script, /#topicPluginDock \.plugin-app-card/);
assert.match(script, /\.capability-action-menu:not\(\[hidden\]\)/);
assert.match(script, /capabilityMenuOpened/);
assert.match(script, /capabilityMenuGesture/);
assert.match(script, /pluginDrawerMenuOpened/);
assert.match(script, /pluginDrawerMenuGesture/);
assert.match(script, /\.topbar/);
assert.match(script, /strictLayout/);
assert.match(script, /layout\.failures/);
assert.match(script, /fs\.mkdirSync\(path\.dirname\(screenshotPath\), \{ recursive: true \}\)/);
assert.match(testMatrix, /playwright-visual-smoke-harness\.test\.js/);
assert.match(testMatrix, /scripts\\playwright-visual-smoke\.js/);
assert.match(staticClientDoc, /bounding rectangles/);
assert.match(staticClientDoc, /horizontal overflow/);
assert.match(mapDoc, /playwright-visual-smoke-harness\.test\.js/);

console.log("playwright visual smoke harness tests passed");
