"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const repoRoot = path.resolve(__dirname, "..");

function read(relativePath) {
  return fs.readFileSync(path.join(repoRoot, relativePath), "utf8");
}

const startHermesWeb = read("start-hermes-web.ps1");
const server = read("server.js");
const startWorkerHost = read(path.join("scripts", "start-worker-host.ps1"));
const startGatewayPool = read(path.join("scripts", "start-gateway-pool.ps1"));
const provisionWorkerExternalConnectors = read(path.join("scripts", "provision-worker-external-connectors.ps1"));
const repairWorkspaceAcl = read(path.join("scripts", "repair-workspace-acl.ps1"));
const runKanbanGatewayWorker = read(path.join("scripts", "run-kanban-gateway-worker.ps1"));
const runKanbanGatewayWorkerChild = read(path.join("scripts", "run-kanban-gateway-worker-child.ps1"));
const runKanbanGatewayWorkerShell = read(path.join("scripts", "run-kanban-gateway-worker.sh"));
const startCronTickSidecar = read(path.join("scripts", "start-cron-tick-sidecar.ps1"));
const runCronTickSidecar = read(path.join("scripts", "run-cron-tick-sidecar.ps1"));
const startWeixinFrontGateway = read(path.join("scripts", "start-weixin-front-gateway.ps1"));
const startWeixinMobileIngressBridge = read(path.join("scripts", "start-weixin-mobile-ingress-bridge.ps1"));
const weixinMobileIngressBridge = read(path.join("scripts", "weixin-mobile-ingress-bridge.py"));
const configureLowGateways = read(path.join("scripts", "configure-low-gateways.sh"));
const checkWorkerCodexAuth = read(path.join("scripts", "check-worker-codex-auth.ps1"));
const weatherPluginManifest = read(path.join("gateway-plugins", "hermes-mobile-weather", "plugin.yaml"));
const weatherPlugin = read(path.join("gateway-plugins", "hermes-mobile-weather", "__init__.py"));
const httpPluginManifest = read(path.join("gateway-plugins", "hermes-mobile-http", "plugin.yaml"));
const httpPlugin = read(path.join("gateway-plugins", "hermes-mobile-http", "__init__.py"));

assert.match(startHermesWeb, /function Test-HermesWebHttpHealth/);
assert.match(startHermesWeb, /did not open a responsive Hermes Mobile HTTP endpoint/);
assert.match(startHermesWeb, /HTTP health failed/);
assert.match(startHermesWeb, /function Start-CronTickSidecarIfNeeded/);
assert.match(startHermesWeb, /HERMES_WEB_AUTOMATION_BACKEND/);
assert.match(startHermesWeb, /hermes_cron/);
assert.match(startHermesWeb, /start-cron-tick-sidecar\.ps1/);
assert.match(startHermesWeb, /HERMES_MOBILE_CRON_TICK_SIDECAR/);
assert.match(startHermesWeb, /Start-CronTickSidecarIfNeeded\s*\r?\n\s*\$existing = Get-HermesWebListener/s);

assert.match(startWorkerHost, /function Test-HermesMobileHttpHealth/);
assert.match(startWorkerHost, /function Test-HermesMobileAuthenticatedHealth/);
assert.match(startWorkerHost, /function Test-GatewayPoolPortHealth/);
assert.match(startWorkerHost, /X-Hermes-Web-Key/);
assert.match(startWorkerHost, /api\/client-version\?clientVersion=startup-health/);
assert.match(startWorkerHost, /Worker listener already running and authenticated API plus Gateway Pool ports are healthy/);
assert.match(startWorkerHost, /Restarting unhealthy worker listener/);
assert.match(startWorkerHost, /healthy authenticated API endpoint with ready Gateway Pool ports/);
assert.match(startWorkerHost, /MinGatewayPoolWorkers/);
assert.match(startWorkerHost, /GatewayPoolPorts/);
assert.match(startWorkerHost, /WeixinFrontGateway/);
assert.match(startWorkerHost, /start-weixin-mobile-ingress-bridge\.ps1/);
assert.match(startWorkerHost, /function Start-WeixinFrontGatewayIfNeeded/);
assert.match(startWorkerHost, /Start-WeixinFrontGatewayIfNeeded\s*\r?\nif \(-not \$CheckOnly\)/);

assert.match(server, /HERMES_MOBILE_WEB_PUSH_START_DELAY_MS/);
assert.match(server, /HERMES_WEB_TODO_PUSH_START_DELAY_MS/);
assert.match(server, /HERMES_WEB_AUTOMATION_PUSH_START_DELAY_MS/);
assert.match(server, /120000/);
assert.match(server, /function scheduleBackgroundWebPushDispatcher/);
assert.doesNotMatch(server, /setTimeout\(tick, 8000\)/);
assert.doesNotMatch(server, /setTimeout\(tick, 12000\)/);

assert.match(startGatewayPool, /function Start-LowGateways/);
assert.match(startGatewayPool, /function Check-LowGatewayCodexAuth/);
assert.match(startGatewayPool, /function Provision-OwnerExternalConnectors/);
assert.match(startGatewayPool, /function Start-OwnerMaintenanceGateways/);
assert.match(startGatewayPool, /function Resolve-ConnectorPath/);
assert.match(startGatewayPool, /function Ensure-LowGatewayProfileEnv/);
assert.match(startGatewayPool, /function Stop-LowGateways/);
assert.match(startGatewayPool, /stop-low-gateways\.sh/);
assert.match(startGatewayPool, /pkill -u hermes -f 'hermes_cli\\\.main -p lowgw\[0-9\]\+ gateway run'/);
assert.match(startGatewayPool, /Stop-LowGateways\s*\r?\n\s*Write-GatewayPoolLog "Starting low gateway pool\."/);
assert.match(startGatewayPool, /provision-worker-external-connectors\.ps1/);
assert.match(startGatewayPool, /HERMES_WEB_GOOGLE_TOKEN_PATH/);
assert.match(startGatewayPool, /HERMES_GOOGLE_PROFILE_HOME/);
assert.match(startGatewayPool, /runtime_bin="\$\{HERMES_GATEWAY_RUNTIME_BIN:-\$runtime_root\/bin\}"/);
assert.match(startGatewayPool, /cat > "\$runtime_bin\/hermes"/);
assert.match(startGatewayPool, /PATH="\$low_gateway_path"/);
assert.match(startGatewayPool, /google_token\.json/);
assert.match(startGatewayPool, /google_client_secret\.json/);
assert.match(startGatewayPool, /microsoft-graph-outlook-mail\\token\.json/);
assert.match(startGatewayPool, /configure-low-gateways\.sh/);
assert.match(startGatewayPool, /Provision-OwnerExternalConnectors\s*\r?\nStart-LowGateways/);
assert.match(startGatewayPool, /HERMES_LOW_GATEWAY_REQUIRE_UNIQUE_CODEX_AUTH/);
assert.match(startGatewayPool, /check-worker-codex-auth\.ps1/);
assert.match(startGatewayPool, /codex-auth:/);
assert.match(startGatewayPool, /Start-LowGateways\s*\r?\nCheck-LowGatewayCodexAuth/);
assert.match(startGatewayPool, /\$env:API_SERVER_KEY = \$apiKey/);
assert.match(startGatewayPool, /\$env:WSLENV = "API_SERVER_KEY\/u"/);
assert.match(startGatewayPool, /PYTHONPATH=\$officialCleanRoot/);
assert.match(startGatewayPool, /\$officialPython -m hermes_cli\.main/);
assert.match(startGatewayPool, /ln -sfn \$sharedAuthPath/);
assert.doesNotMatch(startGatewayPool, /\/home\/\$OfficialUser\/\.local\/bin\/hermes/);
assert.match(startGatewayPool, /Gateway pool startup OK; healthy ports/);
assert.doesNotMatch(startGatewayPool, /Write-GatewayPoolLog .*apiKey/i);

assert.match(provisionWorkerExternalConnectors, /external-connectors\/owner/);
assert.match(provisionWorkerExternalConnectors, /google_token\.json/);
assert.match(provisionWorkerExternalConnectors, /microsoft-graph-outlook-mail\/token\.json/);
assert.match(provisionWorkerExternalConnectors, /patch_google_workspace_skill\(\)/);
assert.match(provisionWorkerExternalConnectors, /HERMES_GOOGLE_RUNTIME_REEXEC/);
assert.match(provisionWorkerExternalConnectors, /profiles.*<profile>.*skills/s);
assert.match(provisionWorkerExternalConnectors, /HERMES_GOOGLE_PROFILE_HOME="\`\$profile_dir" python3 "\`\$google_setup" --check/);
assert.match(provisionWorkerExternalConnectors, /google_workspace_setup_check=ok/);
assert.match(provisionWorkerExternalConnectors, /\[owner-secret-root\]/);
assert.doesNotMatch(provisionWorkerExternalConnectors, /Get-Content\s+-Raw\s+\$GoogleTokenPath/i);
assert.doesNotMatch(provisionWorkerExternalConnectors, /Write-Host .*token/i);

assert.match(repairWorkspaceAcl, /\[string\]\$WorkspaceRoot/);
assert.match(repairWorkspaceAcl, /HermesMobileWorker/);
assert.match(repairWorkspaceAcl, /\[switch\]\$CheckOnly/);
assert.match(repairWorkspaceAcl, /icacls \$root \/grant \$grant/);
assert.match(repairWorkspaceAcl, /missingWorkerRead/);

assert.match(runKanbanGatewayWorker, /ValueFromRemainingArguments/);
assert.match(runKanbanGatewayWorker, /PositionalBinding\s*=\s*\$false/);
assert.match(runKanbanGatewayWorker, /HermesGatewayWorker/);
assert.match(runKanbanGatewayWorker, /run-as-worker\.ps1/);
assert.match(runKanbanGatewayWorker, /PayloadBase64/);
assert.match(runKanbanGatewayWorker, /kanbanArgs = \$KanbanArgs/);
assert.match(runKanbanGatewayWorker, /kanban-runner/);
assert.match(runKanbanGatewayWorker, /\[string\]\$WorkerUserName = "HermesMobileWorker"/);
assert.match(runKanbanGatewayWorker, /function Current-UserName/);
assert.match(runKanbanGatewayWorker, /Current-UserName\) -ieq \$WorkerUserName/);
assert.match(runKanbanGatewayWorker, /Copy-Item -LiteralPath \$sourceShellScript/);
assert.match(runKanbanGatewayWorker, /run-kanban-gateway-worker-child-\$stamp\.ps1/);
assert.match(runKanbanGatewayWorker, /run-kanban-gateway-worker-\$stamp\.sh/);
assert.match(runKanbanGatewayWorker, /run-kanban-command-\$stamp\.ps1/);
assert.match(runKanbanGatewayWorker, /Remove-Item -LiteralPath \$childScript/);
assert.match(runKanbanGatewayWorker, /Remove-Item -LiteralPath \$shellScript/);
assert.doesNotMatch(runKanbanGatewayWorker, /-ChildArgs/);

assert.match(runKanbanGatewayWorkerChild, /Convert-ToWslPath/);
assert.match(runKanbanGatewayWorkerChild, /wsl\.exe -d \$distroName -u root/);
assert.match(runKanbanGatewayWorkerChild, /PayloadBase64/);

assert.match(runKanbanGatewayWorkerShell, /runuser/);
assert.match(runKanbanGatewayWorkerShell, /-u",\s*"hermes"/);
assert.match(runKanbanGatewayWorkerShell, /runtime_bin="\$\{HERMES_GATEWAY_RUNTIME_BIN:-\$runtime_root\/bin\}"/);
assert.match(runKanbanGatewayWorkerShell, /hermes_shim="\$runtime_bin\/hermes"/);
assert.match(runKanbanGatewayWorkerShell, /exec "\$runtime_python" -m hermes_cli\.main "\\\$@"/);
assert.match(runKanbanGatewayWorkerShell, /PYTHONPATH=\{runtime_source\}/);
assert.match(runKanbanGatewayWorkerShell, /PATH=\{runtime_bin\}:\{runtime_root\}\/venv\/bin:\/usr\/local\/bin:\/usr\/bin:\/bin/);
assert.match(runKanbanGatewayWorkerShell, /hermes_cli\.main/);
assert.match(runKanbanGatewayWorkerShell, /kanban_args/);
assert.match(runKanbanGatewayWorkerShell, /capture_output=True/);
assert.match(runKanbanGatewayWorkerShell, /ensure_ascii=True/);

assert.match(startCronTickSidecar, /function Get-CronTickSidecarProcess/);
assert.match(startCronTickSidecar, /function Invoke-CronStatusCheck/);
assert.match(startCronTickSidecar, /cron", "status"/);
assert.match(startCronTickSidecar, /Start-Process/);
assert.match(startCronTickSidecar, /run-cron-tick-sidecar\.ps1/);
assert.match(startCronTickSidecar, /HERMES_WEB_HERMES_HOME/);
assert.match(startCronTickSidecar, /HERMES_MOBILE_CRON_TICK_LOG_PATH/);

assert.match(runCronTickSidecar, /cron", "tick"/);
assert.match(runCronTickSidecar, /--accept-hooks/);
assert.match(runCronTickSidecar, /HERMES_ACCEPT_HOOKS=1/);
assert.match(runCronTickSidecar, /HERMES_HOME=\$HermesHome/);
assert.match(runCronTickSidecar, /PYTHONPATH=\$pythonPath/);
assert.match(runCronTickSidecar, /Select-Object -Last \$maxLines/);
assert.doesNotMatch(runCronTickSidecar, /gateway", "run"/);

assert.match(startWeixinFrontGateway, /HERMES_MOBILE_WEIXIN_FRONT_GATEWAY/);
assert.match(startWeixinFrontGateway, /gateway_state\.json/);
assert.match(startWeixinFrontGateway, /hermes_cli\.main gateway run --replace/);
assert.match(startWeixinFrontGateway, /weixin/);
assert.match(startWeixinFrontGateway, /api_server/);
assert.match(startWeixinFrontGateway, /ensure-weixin-reminder-dispatcher\.sh/);
assert.match(startWeixinFrontGateway, /ensure-weixin-todo-dispatcher\.sh/);
assert.match(startWeixinFrontGateway, /ensure-weixin-delivery-queue-dispatcher\.sh/);
assert.match(startWeixinFrontGateway, /WEIXIN_FRONT_GATEWAY_OK/);
assert.doesNotMatch(startWeixinFrontGateway, /Hermes Gateway WSL/);

assert.match(startWeixinMobileIngressBridge, /weixin-mobile-ingress-bridge\.py/);
assert.match(startWeixinMobileIngressBridge, /HERMES_MOBILE_WEIXIN_INGRESS_KEY_FILE/);
assert.match(startWeixinMobileIngressBridge, /legacy_gateway_pid/);
assert.match(startWeixinMobileIngressBridge, /stop_legacy_gateway/);
assert.match(startWeixinMobileIngressBridge, /WEIXIN_MOBILE_INGRESS_BRIDGE_OK/);
assert.match(startWeixinMobileIngressBridge, /ensure-weixin-reminder-dispatcher\.sh/);
assert.match(startWeixinMobileIngressBridge, /ensure-weixin-todo-dispatcher\.sh/);
assert.match(startWeixinMobileIngressBridge, /ensure-weixin-delivery-queue-dispatcher\.sh/);
assert.doesNotMatch(startWeixinMobileIngressBridge, /hermes_cli\.main gateway run --replace/);
assert.match(weixinMobileIngressBridge, /class MobileIngressBridge/);
assert.match(weixinMobileIngressBridge, /class MobileIngressWeixinAdapter/);
assert.match(weixinMobileIngressBridge, /post_inbound_event/);
assert.match(weixinMobileIngressBridge, /\/api\/ingress\/weixin\/events/);
assert.match(weixinMobileIngressBridge, /\/api\/ingress\/weixin\/outbound/);
assert.match(weixinMobileIngressBridge, /workspace_id="owner" if principal_id == "owner" else principal_id/);
assert.doesNotMatch(weixinMobileIngressBridge, /gateway run --replace/);

assert.match(configureLowGateways, /profile_auth_seed_root/);
assert.match(configureLowGateways, /profile_seed="\$profile_auth_seed_root\/\$\{profile\}\/auth\.json"/);
assert.match(configureLowGateways, /shared_auth_mode/);
assert.match(configureLowGateways, /shared_auth_path/);
assert.match(configureLowGateways, /HERMES_LOW_GATEWAY_SHARED_AUTH_SOURCE_PROFILE/);
assert.match(configureLowGateways, /HERMES_MOBILE_WEATHER_PLUGIN_SOURCE/);
assert.match(configureLowGateways, /HERMES_MOBILE_HTTP_PLUGIN_SOURCE/);
assert.match(configureLowGateways, /gateway-plugins\/hermes-mobile-weather/);
assert.match(configureLowGateways, /gateway-plugins\/hermes-mobile-http/);
assert.match(configureLowGateways, /weather_plugin_enabled=1/);
assert.match(configureLowGateways, /http_plugin_enabled=1/);
assert.match(configureLowGateways, /- weather/);
assert.match(configureLowGateways, /- http/);
assert.match(configureLowGateways, /hermes-mobile-weather/);
assert.match(configureLowGateways, /hermes-mobile-http/);
assert.match(configureLowGateways, /profile_dir\/plugins\/hermes-mobile-weather/);
assert.match(configureLowGateways, /profile_dir\/plugins\/hermes-mobile-http/);
assert.match(configureLowGateways, /cat > "\$worker_home_dir\/config\.yaml"/);
assert.match(configureLowGateways, /chmod 600 "\$worker_home_dir\/config\.yaml"/);
assert.match(configureLowGateways, /chown "\$worker_user:\$worker_user" "\$worker_home_dir\/config\.yaml"/);
assert.match(configureLowGateways, /platform_toolsets:/);
assert.doesNotMatch(configureLowGateways, /api_server:\s*\r?\n\s+- hermes-api-server/);
assert.match(configureLowGateways, /\s+- web/);
assert.match(configureLowGateways, /\s+- http/);
assert.match(configureLowGateways, /\s+- file/);
assert.match(configureLowGateways, /\s+- vision/);
assert.match(configureLowGateways, /\s+- image_gen/);
assert.match(configureLowGateways, /\s+- messaging/);
assert.match(configureLowGateways, /\s+- tts/);
assert.match(configureLowGateways, /\s+- skills/);
assert.match(configureLowGateways, /\s+- todo/);
assert.match(configureLowGateways, /\s+- kanban/);
assert.match(configureLowGateways, /\s+- cronjob/);
assert.match(configureLowGateways, /\s+- memory/);
assert.match(configureLowGateways, /\s+- session_search/);
assert.match(configureLowGateways, /\s+- clarify/);
assert.doesNotMatch(configureLowGateways, /\s+- terminal/);
assert.doesNotMatch(configureLowGateways, /\s+- code_execution/);
assert.doesNotMatch(configureLowGateways, /\s+- delegation/);
assert.match(configureLowGateways, /newest_profile_auth_real/);
assert.match(configureLowGateways, /shared_auth_real/);
assert.match(configureLowGateways, /Missing shared low Gateway Codex auth/);
assert.match(configureLowGateways, /HERMES_LOW_GATEWAY_ALLOW_SHARED_AUTH_SEED/);
assert.match(configureLowGateways, /ln -s "\$shared_auth_path" "\$profile_link\/auth\.json"/);
assert.match(configureLowGateways, /ln -s "\$shared_auth_lock_path" "\$profile_link\/auth\.lock"/);
assert.doesNotMatch(configureLowGateways, /install -m 600 -o "\$worker_user" -g "\$worker_user" "\$gateway_worker_root\/secrets\/auth\.json" "\$worker_home_dir\/auth\.json"/);

assert.match(checkWorkerCodexAuth, /RequireUniqueRefreshTokens/);
assert.match(checkWorkerCodexAuth, /WSLENV = "HERMES_CHECK_PROFILES\/u:HERMES_REQUIRE_UNIQUE_REFRESH_TOKENS\/u"/);
assert.match(checkWorkerCodexAuth, /exit `\$LASTEXITCODE/);
assert.match(checkWorkerCodexAuth, /shared-refresh/);
assert.match(checkWorkerCodexAuth, /copied-refresh/);
assert.match(checkWorkerCodexAuth, /auth_path=/);
assert.match(checkWorkerCodexAuth, /hashlib\.sha256\(refresh\.encode\(\)\)\.hexdigest\(\)\[:12\]/);
assert.match(checkWorkerCodexAuth, /Worker child failed with exit code/);
assert.doesNotMatch(checkWorkerCodexAuth, /print\(.*refresh_token/);

assert.match(weatherPluginManifest, /name: hermes-mobile-weather/);
assert.match(weatherPluginManifest, /provides_tools:\s*\r?\n\s+- weather/);
assert.match(weatherPlugin, /WEATHER_SCHEMA/);
assert.match(weatherPlugin, /"name": "weather"/);
assert.match(weatherPlugin, /toolset="weather"/);
assert.match(weatherPlugin, /open-meteo/);
assert.match(httpPluginManifest, /name: hermes-mobile-http/);
assert.match(httpPluginManifest, /provides_tools:\s*\r?\n\s+- http/);
assert.match(httpPlugin, /HTTP_REQUEST_SCHEMA/);
assert.match(httpPlugin, /"name": "http_request"/);
assert.match(httpPlugin, /toolset="http"/);
assert.match(httpPlugin, /HERMES_MOBILE_HTTP_ALLOWED_ORIGINS/);
assert.match(httpPlugin, /Authorization/);
assert.match(httpPlugin, /wd_live_/);

console.log("startup scripts tests passed");
