"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const repoRoot = path.resolve(__dirname, "..");

function read(relativePath) {
  return fs.readFileSync(path.join(repoRoot, relativePath), "utf8");
}

const startHermesWeb = read("start-hermes-web.ps1");
const server = read("mobile-server-runtime.js");
const mobileRuntimeEnvironmentService = read(path.join("adapters", "mobile-runtime-environment-service.js"));
const mobileRuntimeGatewayEnvironmentService = read(path.join("adapters", "mobile-runtime-gateway-environment-service.js"));
const startWorkerHost = read(path.join("scripts", "start-worker-host.ps1"));
const startGatewayPool = read(path.join("scripts", "start-gateway-pool.ps1"));
const runAsWorker = read(path.join("scripts", "run-as-worker.ps1"));
const startLowGatewaysChild = read(path.join("scripts", "start-low-gateways-child.ps1"));
const startLowGatewaysShell = read(path.join("scripts", "start-low-gateways.sh"));
const configureLowGatewaysShell = read(path.join("scripts", "configure-low-gateways.sh"));
const provisionWorkerExternalConnectors = read(path.join("scripts", "provision-worker-external-connectors.ps1"));
const repairWorkspaceAcl = read(path.join("scripts", "repair-workspace-acl.ps1"));
const runKanbanGatewayWorker = read(path.join("scripts", "run-kanban-gateway-worker.ps1"));
const runKanbanGatewayWorkerChild = read(path.join("scripts", "run-kanban-gateway-worker-child.ps1"));
const runKanbanGatewayWorkerShell = read(path.join("scripts", "run-kanban-gateway-worker.sh"));
const runKanbanNativeWindows = read(path.join("scripts", "run-kanban-native-windows.ps1"));
const startCronTickSidecar = read(path.join("scripts", "start-cron-tick-sidecar.ps1"));
const runCronTickSidecar = read(path.join("scripts", "run-cron-tick-sidecar.ps1"));
const startNasCronTick = read(path.join("scripts", "start-nas-cron-tick.sh"));
const stopNasCronTick = read(path.join("scripts", "stop-nas-cron-tick.sh"));
const startNasGatewayPool = read(path.join("scripts", "start-nas-gateway-pool.sh"));
const hermesMobileCronDispatcher = read(path.join("scripts", "hermes-mobile-cron-dispatcher.py"));
const bridgeHost = read(path.join("scripts", "bridge-host.js"));
const startWeixinFrontGateway = read(path.join("scripts", "start-weixin-front-gateway.ps1"));
const startWeixinMobileIngressBridge = read(path.join("scripts", "start-weixin-mobile-ingress-bridge.ps1"));
const startWeixinMobileIngressBridgeWindows = read(path.join("scripts", "start-weixin-mobile-ingress-bridge-windows.ps1"));
const startWhisperLargeV3TurboWindows = read(path.join("scripts", "start-whisper-large-v3-turbo-windows.ps1"));
const weixinMobileIngressBridge = read(path.join("scripts", "weixin-mobile-ingress-bridge.py"));
const outlookGraphMcp = read(path.join("scripts", "python", "outlook_graph_mcp.py"));
const configureLowGateways = read(path.join("scripts", "configure-low-gateways.sh"));
const checkWorkerCodexAuth = read(path.join("scripts", "check-worker-codex-auth.ps1"));
const gatewayToolSchemaSmoke = read(path.join("scripts", "gateway-tool-schema-smoke.js"));
const gatewayRuntimeSiteCustomize = read(path.join("gateway-runtime-overrides", "sitecustomize.py"));
const transcribeReadingAudio = read(path.join("scripts", "transcribe-reading-audio.ps1"));
const weatherPluginManifest = read(path.join("gateway-plugins", "hermes-mobile-weather", "plugin.yaml"));
const weatherPlugin = read(path.join("gateway-plugins", "hermes-mobile-weather", "__init__.py"));
const webPluginManifest = read(path.join("gateway-plugins", "hermes-mobile-web", "plugin.yaml"));
const webPlugin = read(path.join("gateway-plugins", "hermes-mobile-web", "__init__.py"));
const httpPluginManifest = read(path.join("gateway-plugins", "hermes-mobile-http", "plugin.yaml"));
const httpPlugin = read(path.join("gateway-plugins", "hermes-mobile-http", "__init__.py"));
const docxPluginManifest = read(path.join("gateway-plugins", "hermes-mobile-docx", "plugin.yaml"));
const docxPlugin = read(path.join("gateway-plugins", "hermes-mobile-docx", "__init__.py"));
const audioPluginManifest = read(path.join("gateway-plugins", "hermes-mobile-audio", "plugin.yaml"));
const audioPlugin = read(path.join("gateway-plugins", "hermes-mobile-audio", "__init__.py"));
const imagePluginManifest = read(path.join("gateway-plugins", "hermes-mobile-image", "plugin.yaml"));
const imagePlugin = read(path.join("gateway-plugins", "hermes-mobile-image", "__init__.py"));
const videoPluginManifest = read(path.join("gateway-plugins", "hermes-mobile-video", "plugin.yaml"));
const videoPlugin = read(path.join("gateway-plugins", "hermes-mobile-video", "__init__.py"));
const cronjobPluginManifest = read(path.join("gateway-plugins", "hermes-mobile-cronjob", "plugin.yaml"));
const cronjobPlugin = read(path.join("gateway-plugins", "hermes-mobile-cronjob", "__init__.py"));

assert.match(startHermesWeb, /function Test-HermesWebHttpHealth/);
assert.match(startHermesWeb, /did not open a responsive Hermes Mobile HTTP endpoint/);
assert.match(startHermesWeb, /HTTP health failed/);
assert.match(startHermesWeb, /function Start-CronTickSidecarIfNeeded/);
assert.match(startHermesWeb, /HERMES_WEB_AUTOMATION_BACKEND/);
assert.match(startHermesWeb, /hermes_cron/);
assert.match(startHermesWeb, /start-cron-tick-sidecar\.ps1/);
assert.match(startHermesWeb, /HERMES_MOBILE_CRON_TICK_SIDECAR/);
assert.match(startHermesWeb, /if \(\$env:HERMES_MOBILE_CRON_TICK_HERMES_HOME\) \{[\s\S]*?-HermesHome", \$env:HERMES_MOBILE_CRON_TICK_HERMES_HOME[\s\S]*?\} elseif \(\$env:HERMES_WEB_HERMES_HOME\) \{/);
assert.match(startHermesWeb, /Start-CronTickSidecarIfNeeded\s*\r?\n\s*\$existing = Get-HermesWebListener/s);

assert.match(startNasCronTick, /HERMES_AGENT_ROOT/);
assert.match(startNasCronTick, /\/volume1\/docker\/hermes-agent\/current/);
assert.match(startNasCronTick, /PYTHONPATH="\$HERMES_AGENT_ROOT/);
assert.match(startNasCronTick, /hermes-mobile-cron-dispatcher\.py --dispatch/);
assert.match(startNasCronTick, /hermes-cron-tick\.pid/);
assert.match(startNasCronTick, /bg_pid=\$!/);
assert.match(startNasCronTick, /CRON_MODEL_PROXY_URL/);
assert.match(startNasCronTick, /HERMES_MOBILE_CRON_TICK_SIDE="nas"/);
assert.match(startNasCronTick, /HERMES_MOBILE_CRON_MODEL_PROXY_URL/);
assert.match(startNasCronTick, /HTTPS_PROXY="\$\{HTTPS_PROXY:-\$CRON_MODEL_PROXY_URL\}"/);
assert.match(startNasCronTick, /HTTP_PROXY="\$\{HTTP_PROXY:-\$CRON_MODEL_PROXY_URL\}"/);
assert.match(startNasCronTick, /ALL_PROXY="\$\{ALL_PROXY:-\$CRON_MODEL_PROXY_URL\}"/);
assert.match(stopNasCronTick, /hermes-cron-tick\.pid/);
assert.match(stopNasCronTick, /kill -9 "\$pid"/);
assert.match(startNasGatewayPool, /GATEWAY_RUNTIME_OVERRIDES="\$\{HERMES_MOBILE_NAS_GATEWAY_RUNTIME_OVERRIDES:-\$ROOT\/app\/gateway-runtime-overrides\}"/);
assert.match(startNasGatewayPool, /OFFICIAL_CLEAN_PATH="\$\{HERMES_MOBILE_NAS_OFFICIAL_CLEAN_PATH:-\$HERMES_AGENT_CURRENT\}"/);
assert.match(startNasGatewayPool, /NOTE_MCP_PYTHON="\$\{HERMES_MOBILE_NAS_NOTE_MCP_PYTHON:-\/usr\/bin\/python3\}"/);
assert.match(startNasGatewayPool, /NOTE_MCP_PATH="\$\{HERMES_MOBILE_NAS_NOTE_MCP_PATH:-\/volume1\/docker\/note\/source\/scripts\/note_mcp_stdio\.py\}"/);
assert.match(startNasGatewayPool, /NOTE_MCP_API_BASE_URL="\$\{HERMES_MOBILE_NAS_NOTE_MCP_API_BASE_URL:-http:\/\/127\.0\.0\.1:4181\}"/);
assert.match(startNasGatewayPool, /strip_plugin_toolset\(config, "note"\)/);
assert.match(startNasGatewayPool, /first_plugin_workspace\(workspace_root, "\.hermes-note", \["access-key\.txt"\]\)/);
assert.match(startNasGatewayPool, /append_toolset\(config, "note"\)/);
assert.match(startNasGatewayPool, /mcp_servers:[\s\S]*note:[\s\S]*--no-workspace-override[\s\S]*--api-base-url[\s\S]*\{note_mcp_api_base_url\}/);
assert.match(startNasGatewayPool, /HERMES_MOBILE_OFFICIAL_CLEAN_PATH="\$OFFICIAL_CLEAN_PATH"/);
assert.match(startNasGatewayPool, /PYTHONPATH="\$GATEWAY_RUNTIME_OVERRIDES:\$HERMES_AGENT_CURRENT\$\{PYTHONPATH:\+:\$PYTHONPATH\}"/);

assert.match(startWorkerHost, /function Test-HermesMobileHttpHealth/);
assert.match(startWorkerHost, /function Test-HermesMobileAuthenticatedHealth/);
assert.match(startWorkerHost, /function Test-GatewayPoolPortHealth/);
assert.match(startWorkerHost, /X-Hermes-Web-Key/);
assert.match(startWorkerHost, /api\/client-version\?clientVersion=startup-health/);
assert.match(startWorkerHost, /Worker listener already running and authenticated API plus Gateway Pool ports are healthy/);
assert.match(startWorkerHost, /Restarting unhealthy worker listener/);
assert.match(startWorkerHost, /healthy authenticated API endpoint with ready Gateway Pool ports/);
assert.match(startWorkerHost, /MinGatewayPoolWorkers/);
assert.match(startWorkerHost, /\[int\]\$MinGatewayPoolWorkers = 0/);
assert.match(startWorkerHost, /GatewayPoolPorts/);
assert.match(startWorkerHost, /\[switch\]\$RunInCallerContext/);
assert.match(startWorkerHost, /function Test-ListenerCallerContextMarker/);
assert.match(startWorkerHost, /HERMES_MOBILE_LISTENER_RUN_IN_CALLER_CONTEXT/);
assert.match(startWorkerHost, /listener-run-in-caller-context\.flag/);
assert.match(startWorkerHost, /Listener caller-context mode enabled by environment or marker file/);
assert.match(startWorkerHost, /WindowsIdentity\]::GetCurrent\(\)\.Name/);
assert.match(startWorkerHost, /if \(-not \$RunInCallerContext -and -not \(Test-Path -LiteralPath \$CredentialPath\)\)/);
assert.match(startWorkerHost, /if \(-not \$RunInCallerContext\) \{\s*\r?\n\s*\$psi\.UserName = \$UserName/s);
assert.match(startWorkerHost, /18762/);
assert.match(startWorkerHost, /18764,18765,18766,18767,18768,18769,18770,18771,18772,18773,18774,18651,18652,18653/);
assert.match(startWorkerHost, /WeixinFrontGateway/);
assert.match(startWorkerHost, /function Resolve-WeixinFrontGatewayMode/);
assert.match(startWorkerHost, /HERMES_MOBILE_WEIXIN_FRONT_GATEWAY/);
assert.match(startWorkerHost, /return "auto"/);
assert.match(startWorkerHost, /HERMES_MOBILE_WEIXIN_FRONT_GATEWAY_HERMES_HOME/);
assert.match(startWorkerHost, /C:\\ProgramData\\HermesMobile\\hermes-native-profile\\\.hermes/);
assert.match(startWorkerHost, /start-weixin-mobile-ingress-bridge-windows\.ps1/);
assert.match(startWorkerHost, /function Start-WeixinFrontGatewayIfNeeded/);
const startWeixinFrontGatewayIfNeededBlock = startWorkerHost.match(/function Start-WeixinFrontGatewayIfNeeded \{[\s\S]*?\n\}/)?.[0] || "";
assert.ok(startWeixinFrontGatewayIfNeededBlock, "missing Start-WeixinFrontGatewayIfNeeded block");
assert.doesNotMatch(startWeixinFrontGatewayIfNeededBlock, /-DistroName|-WslUser/);
assert.match(startWorkerHost, /CronTickSidecar/);
assert.match(startWorkerHost, /function Start-CronTickSidecarInCallerContextIfNeeded/);
assert.match(startWorkerHost, /start-cron-tick-sidecar\.ps1/);
const startCronTickSidecarInCallerContextBlock = startWorkerHost.match(/function Start-CronTickSidecarInCallerContextIfNeeded \{[\s\S]*?\n\}/)?.[0] || "";
assert.ok(startCronTickSidecarInCallerContextBlock, "missing Start-CronTickSidecarInCallerContextIfNeeded block");
assert.doesNotMatch(startCronTickSidecarInCallerContextBlock, /-DistroName|-WslUser/);
assert.match(startWorkerHost, /if \(\$ReplaceExisting\) \{ \$args \+= "-ReplaceExisting" \}/);
assert.match(startWorkerHost, /Start-WeixinFrontGatewayIfNeeded\s*\r?\nif \(-not \$CheckOnly\) \{\s*\r?\n\s*Start-CronTickSidecarInCallerContextIfNeeded/s);
assert.match(startWorkerHost, /Start-CronTickSidecarInCallerContextIfNeeded\s*\r?\n\}\s*\r?\nif \(-not \$CheckOnly\)/);

assert.match(mobileRuntimeEnvironmentService, /HERMES_MOBILE_WEB_PUSH_START_DELAY_MS/);
assert.match(mobileRuntimeEnvironmentService, /HERMES_WEB_TODO_PUSH_START_DELAY_MS/);
assert.match(mobileRuntimeEnvironmentService, /HERMES_WEB_AUTOMATION_PUSH_START_DELAY_MS/);
assert.match(mobileRuntimeGatewayEnvironmentService, /HERMES_MOBILE_GATEWAY_WORKER_ROOT/);
assert.match(mobileRuntimeGatewayEnvironmentService, /HERMES_WEB_GATEWAY_WORKER_ROOT/);
assert.match(mobileRuntimeGatewayEnvironmentService, /HERMES_MOBILE_GATEWAY_LAUNCH_REQUEST_ROOT/);
assert.match(mobileRuntimeGatewayEnvironmentService, /HERMES_WEB_GATEWAY_LAUNCH_REQUEST_ROOT/);
assert.match(mobileRuntimeGatewayEnvironmentService, /HERMES_MOBILE_GATEWAY_START_SCHEDULED_TASK_NAME/);
assert.match(mobileRuntimeGatewayEnvironmentService, /HERMES_WEB_GATEWAY_START_SCHEDULED_TASK_NAME/);
assert.match(mobileRuntimeGatewayEnvironmentService, /HERMES_MOBILE_GATEWAY_START_HEALTH_WAIT_MS/);
assert.match(mobileRuntimeGatewayEnvironmentService, /HERMES_WEB_GATEWAY_START_HEALTH_WAIT_MS/);
assert.match(mobileRuntimeGatewayEnvironmentService, /HERMES_MOBILE_GATEWAY_START_HEALTH_POLL_MS/);
assert.match(mobileRuntimeGatewayEnvironmentService, /HERMES_WEB_GATEWAY_START_HEALTH_POLL_MS/);
assert.match(mobileRuntimeEnvironmentService, /120000/);
assert.match(fs.readFileSync("adapters/web-push-delivery-service.js", "utf8"), /function scheduleBackgroundWebPushDispatcher/);
assert.doesNotMatch(server, /setTimeout\(tick, 8000\)/);
assert.doesNotMatch(server, /setTimeout\(tick, 12000\)/);

assert.match(startGatewayPool, /function Start-LowGateways/);
assert.match(startGatewayPool, /function Acquire-GatewayPoolRunMutex/);
assert.match(startGatewayPool, /Local\\HermesMobileGatewayPoolStart/);
assert.match(startGatewayPool, /Gateway Pool startup skipped; another start-gateway-pool\.ps1 instance is already running\./);
assert.match(startGatewayPool, /function Release-GatewayPoolRunMutex/);
assert.match(startGatewayPool, /function Check-LowGatewayCodexAuth/);
assert.match(startGatewayPool, /function Provision-OwnerExternalConnectors/);
assert.match(startGatewayPool, /function Start-OwnerMaintenanceGateways/);
assert.match(startGatewayPool, /\[switch\]\$OwnerMaintenanceOnly/);
assert.match(startGatewayPool, /\[switch\]\$OnlyWhenOwnerMaintenanceUnhealthy/);
assert.match(startGatewayPool, /\[ValidateSet\("eager", "hybrid"\)\]/);
assert.match(startGatewayPool, /\[string\]\$StartMode/);
assert.match(startGatewayPool, /\[string\[\]\]\$StartProfiles = @\(\)/);
assert.match(startGatewayPool, /\[string\[\]\]\$StopProfiles = @\(\)/);
assert.match(startGatewayPool, /\[string\[\]\]\$StartReplicas = @\(\)/);
assert.match(startGatewayPool, /\[string\[\]\]\$StopReplicas = @\(\)/);
assert.match(startGatewayPool, /\[switch\]\$NoStopExisting/);
assert.match(startGatewayPool, /\[switch\]\$ForceConfigure/);
assert.match(startGatewayPool, /\[string\]\$PoolKey = ""/);
assert.match(startGatewayPool, /\[string\]\$ProfileTemplateKey = ""/);
assert.match(startGatewayPool, /\[string\]\$TemplateKey = ""/);
assert.match(startGatewayPool, /\[string\]\$ReplicaId = ""/);
assert.match(startGatewayPool, /\[string\]\$WorkspaceId = ""/);
assert.match(startGatewayPool, /function Normalize-GatewayTemplateMetadataValue/);
assert.match(startGatewayPool, /function Normalize-GatewayReplicaList/);
assert.match(startGatewayPool, /function Resolve-GatewayReplicasToProfiles/);
assert.match(startGatewayPool, /\[int\]\$OwnerMaintenanceBusyGraceMinutes = 45/);
assert.match(startGatewayPool, /\[string\]\$ElasticRequestRoot/);
assert.match(startGatewayPool, /function Test-TcpPortOpen/);
assert.match(startGatewayPool, /function Invoke-GatewayPoolElasticRequests/);
assert.match(startGatewayPool, /function Write-GatewayPoolElasticResult/);
assert.match(startGatewayPool, /elastic-requests/);
assert.match(startGatewayPool, /if \(Invoke-GatewayPoolElasticRequests\) \{\s*\r?\n\s*exit 0/s);
assert.match(startGatewayPool, /elastic-request-start id=\{0\} action=\{1\} profiles=\{2\} replicas=\{3\}/);
assert.match(startGatewayPool, /elastic-request-start id=\{0\} action=\{1\} profiles=\{2\} replicas=\{3\} pool=\{4\} template=\{5\} replica=\{6\} workspace=\{7\}/);
assert.match(startGatewayPool, /Start-LowGateways -Profiles \$profiles -Replicas \$replicas -NoStopExisting:\(\[bool\]\$request\.noStopExisting\) -ForceConfigure:\(\[bool\]\$request\.forceConfigure\) -PoolKey \$requestPoolKey -ProfileTemplateKey \$requestProfileTemplateKey -TemplateKey \$requestTemplateKey -ReplicaId \$requestReplicaId -ProfileAlias \$requestProfileAlias -WorkspaceId \$requestWorkspaceId/);
assert.match(startGatewayPool, /Stop-LowGatewayProfiles -Profiles \$profiles -Replicas \$replicas/);
assert.match(startGatewayPool, /function Select-OwnerMaintenanceWorkersNeedingRepair/);
assert.match(startGatewayPool, /function Get-OwnerMaintenanceMinWarm/);
assert.match(startGatewayPool, /HERMES_MOBILE_GATEWAY_OWNER_MAINTENANCE_MIN_WARM/);
assert.match(startGatewayPool, /function Get-OwnerMaintenanceWatchdogTargetWorkers/);
assert.match(startGatewayPool, /Owner-maintenance watchdog skipped in hybrid on-demand mode; min warm is zero/);
assert.match(startGatewayPool, /owner-maintenance-watchdog-state\.json/);
assert.match(startGatewayPool, /HTTP health failed but TCP port \$port is open, likely busy with a long tool call/);
assert.match(startGatewayPool, /Select-OwnerMaintenanceWorkersNeedingRepair -Workers \$watchdogWorkers/);
assert.match(startGatewayPool, /function Repair-OwnerMaintenanceGateways/);
assert.match(startGatewayPool, /function Start-OwnerMaintenanceProfiles/);
assert.match(startGatewayPool, /function Stop-OwnerMaintenanceProfiles/);
assert.match(startGatewayPool, /function Stop-OwnerMaintenanceGateways/);
assert.match(startGatewayPool, /Owner-maintenance repair skipped; all owner-maintenance ports are healthy/);
assert.match(startGatewayPool, /if \(\$OwnerMaintenanceOnly\)/);
assert.match(startGatewayPool, /Repair-OwnerMaintenanceGateways/);
assert.match(startGatewayPool, /Acquire-GatewayPoolRunMutex\s*\r?\ntry \{/);
assert.match(startGatewayPool, /if \(\$resolvedStopProfiles\.Count -gt 0\) \{\s*\r?\n\s*Stop-LowGatewayProfiles -Profiles \$resolvedStopProfiles -Replicas \$resolvedStopReplicas\s*\r?\n\s*exit 0/s);
assert.match(startGatewayPool, /if \(\$resolvedStartProfiles\.Count -gt 0\) \{\s*\r?\n\s*Start-LowGateways -Profiles \$resolvedStartProfiles -Replicas \$resolvedStartReplicas -NoStopExisting:\$NoStopExisting -ForceConfigure:\$ForceConfigure -PoolKey \$PoolKey -ProfileTemplateKey \$ProfileTemplateKey -TemplateKey \$TemplateKey -ReplicaId \$ReplicaId -ProfileAlias \$ProfileAlias -WorkspaceId \$WorkspaceId/s);
assert.match(startGatewayPool, /if \(\$OwnerMaintenanceOnly\) \{\s*\r?\n\s*if \(\$resolvedStopProfiles\.Count -gt 0\) \{\s*\r?\n\s*Stop-OwnerMaintenanceProfiles -Profiles \$resolvedStopProfiles/s);
assert.match(startGatewayPool, /if \(\$resolvedStartProfiles\.Count -gt 0\) \{\s*\r?\n\s*Start-OwnerMaintenanceProfiles -Profiles \$resolvedStartProfiles\s*\r?\n\s*exit 0/s);
assert.match(startGatewayPool, /Write-GatewayPoolLog "Owner-maintenance gateway repair begin\."\s*\r?\n\s*Repair-OwnerMaintenanceGateways/s);
assert.match(startGatewayPool, /finally \{\s*\r?\n\s*Release-GatewayPoolRunMutex\s*\r?\n\}/);
assert.match(startGatewayPool, /wait-owner-maintenance-health/);
assert.match(startGatewayPool, /function Resolve-ConnectorPath/);
assert.match(startGatewayPool, /function Ensure-LowGatewayProfileEnv/);
assert.match(startGatewayPool, /function Stop-LowGateways/);
assert.match(startGatewayPool, /function Start-LowGateways \{\s*\r?\n\s*param\(/);
assert.match(startGatewayPool, /function Stop-LowGatewayProfiles/);
assert.match(startGatewayPool, /function Get-HybridOwnerWarmProfiles/);
assert.match(startGatewayPool, /function Add-OwnerMaintenanceSharedMemoryCommands/);
assert.match(startGatewayPool, /stop-low-gateways\.sh/);
assert.match(startGatewayPool, /pkill -u hermes -f 'hermes_cli\\\.main \.\*gateway run'/);
assert.match(startGatewayPool, /Stopping legacy official-distro low gateway processes before pool start/);
assert.match(startGatewayPool, /stop-legacy-official-low-gateways\.sh/);
assert.match(startGatewayPool, /Invoke-GatewayPoolWslBashFile -Distro \$OfficialDistro -User "root" -ScriptPath \$legacyStopShell/);
assert.match(startGatewayPool, /legacy-lowgw-stop:/);
assert.match(startGatewayPool, /if \(-not \$NoStopExisting\) \{ Stop-LowGateways \}/);
assert.match(startGatewayPool, /-StartProfiles", \(\$profiles -join ","\)/);
assert.match(startGatewayPool, /if \(\$NoStopExisting\) \{ \$profileArgs \+= "-SkipConfigureIfReady" \}/);
assert.match(startGatewayPool, /if \(\$ForceConfigure\) \{ \$profileArgs \+= "-ForceConfigure" \}/);
assert.match(startGatewayPool, /if \(\$safePoolKey\) \{ \$profileArgs \+= @\("-PoolKey", \$safePoolKey\) \}/);
assert.match(startGatewayPool, /if \(\$safeWorkspaceId\) \{ \$profileArgs \+= @\("-WorkspaceId", \$safeWorkspaceId\) \}/);
assert.match(startGatewayPool, /-StartProfiles \(\$profiles -join ","\) -StopOnly/);
assert.match(startGatewayPool, /Invoke-GatewayPoolPhase -Name "start-low-gateways-hybrid-owner-warm" -ScriptBlock \{ Start-LowGateways -Profiles \$ownerWarmProfiles -ForceConfigure:\$ForceConfigure \}/);
assert.match(startGatewayPool, /if \(\$StartMode -ne "hybrid"\) \{\s*\r?\n\s*Invoke-GatewayPoolPhase -Name "install-owner-maintenance-chatgpt-pro-plugin"/);
assert.match(startGatewayPool, /powershell\.exe -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File \$stopChild/);
assert.match(startGatewayPool, /powershell\.exe -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File \$child -DistroName \$LowGatewayDistroName/);
assert.match(startLowGatewaysChild, /\[string\]\$PoolKey = ""/);
assert.match(startLowGatewaysChild, /\[string\]\$WorkspaceId = ""/);
assert.match(startLowGatewaysChild, /HERMES_GATEWAY_REQUEST_POOL_KEY=\$PoolKey/);
assert.match(startLowGatewaysChild, /HERMES_GATEWAY_REQUEST_PROFILE_TEMPLATE_KEY=\$ProfileTemplateKey/);
assert.match(startLowGatewaysChild, /HERMES_GATEWAY_REQUEST_TEMPLATE_KEY=\$TemplateKey/);
assert.match(startLowGatewaysChild, /HERMES_GATEWAY_REQUEST_REPLICA_ID=\$ReplicaId/);
assert.match(startLowGatewaysChild, /HERMES_GATEWAY_REQUEST_WORKSPACE_ID=\$WorkspaceId/);
assert.match(startGatewayPool, /"-WindowStyle", "Hidden",\s*\r?\n\s*"-ExecutionPolicy", "Bypass",\s*\r?\n\s*"-File", \$checkScript/s);
assert.match(startGatewayPool, /"-WindowStyle", "Hidden",\s*\r?\n\s*"-ExecutionPolicy", "Bypass",\s*\r?\n\s*"-File", \$provisionScript/s);
assert.doesNotMatch(startGatewayPool, /\$runAsWorker -ChildScript \$child -ChildArgs @\("-DistroName", \$LowGatewayDistroName\)/);
assert.match(startGatewayPool, /provision-worker-external-connectors\.ps1/);
assert.match(startGatewayPool, /HERMES_WEB_GOOGLE_TOKEN_PATH/);
assert.match(startGatewayPool, /HERMES_GOOGLE_PROFILE_HOME/);
assert.match(startGatewayPool, /runtime_bin="\$\{HERMES_GATEWAY_RUNTIME_BIN:-\$runtime_root\/bin\}"/);
assert.match(startGatewayPool, /cat > "\$runtime_bin\/hermes"/);
assert.match(startGatewayPool, /runtime_hermes="\$runtime_bin\/hermes"/);
assert.match(startLowGatewaysShell, /is_gateway_stop_only\(\)/);
assert.match(startLowGatewaysShell, /safe_template_metadata_value\(\)/);
assert.match(startLowGatewaysShell, /HERMES_GATEWAY_REQUEST_POOL_KEY/);
assert.match(startLowGatewaysShell, /lowgw-template-request profiles=\$\{gateway_start_profiles:-all\} pool=\$\{gateway_request_pool_key\} template=\$\{gateway_request_template_key\} replica=\$\{gateway_request_replica_id\} workspace=\$\{gateway_request_workspace_id\}/);
assert.match(configureLowGatewaysShell, /write_materialized_identity\(\)/);
assert.match(configureLowGatewaysShell, /materialized-identity\.json/);
assert.match(configureLowGatewaysShell, /"memoryWorkspaceId": workspace_id/);
assert.match(configureLowGatewaysShell, /memory_store_for_gateway_profile\(\)/);
assert.match(configureLowGatewaysShell, /ensure_low_gateway_memory_link\(\)/);
assert.match(configureLowGatewaysShell, /profile_materialized_workspace_id="\$profile_workspace_id"/);
assert.match(configureLowGatewaysShell, /ensure_low_gateway_memory_link "\$profile" "\$profile_dir\/memories"/);
assert.match(configureLowGatewaysShell, /write_materialized_identity "\$profile_dir" "\$profile" "\$profile_materialized_workspace_id" "user" "\$profile_model_provider"/);
assert.match(configureLowGatewaysShell, /write_materialized_identity "\$profile_dir" "\$profile" "\$grok_materialized_workspace_id" "user" "xai-oauth"/);
assert.match(startLowGatewaysShell, /is_skip_configure_if_ready\(\)/);
assert.match(startLowGatewaysShell, /is_force_configure\(\)/);
assert.match(startLowGatewaysShell, /configure_signature_file="\$configure_state_root\/low-gateway-config\.sha256"/);
assert.match(startLowGatewaysShell, /compute_configure_signature\(\)/);
assert.match(startLowGatewaysShell, /finance_mcp_python="\$\{HERMES_MOBILE_FINANCE_MCP_PYTHON:-\/opt\/hermes-gateway-runtime\/venv\/bin\/python\}"/);
assert.match(startLowGatewaysShell, /note_mcp_python="\$\{HERMES_MOBILE_NOTE_MCP_PYTHON:-\/opt\/hermes-gateway-runtime\/venv\/bin\/python\}"/);
assert.match(startLowGatewaysShell, /email_mcp_python="\$\{HERMES_MOBILE_EMAIL_MCP_PYTHON:-\/opt\/hermes-gateway-runtime\/venv\/bin\/python\}"/);
assert.match(startLowGatewaysShell, /growth_mcp_command="\$\{HERMES_MOBILE_GROWTH_MCP_COMMAND:-node\}"/);
assert.match(startLowGatewaysShell, /--value "finance_mcp_api_base_url=\$finance_mcp_api_base_url"/);
assert.match(startLowGatewaysShell, /--value "note_mcp_api_base_url=\$note_mcp_api_base_url"/);
assert.match(startLowGatewaysShell, /--value "growth_mcp_api_base_url=\$growth_mcp_api_base_url"/);
assert.match(startLowGatewaysShell, /--value "email_mcp_api_base_url=\$email_mcp_api_base_url"/);
assert.match(startLowGatewaysShell, /--path "\$finance_mcp_path"/);
assert.match(startLowGatewaysShell, /--path "\$note_mcp_path"/);
assert.match(startLowGatewaysShell, /--path "\$growth_mcp_path"/);
assert.match(startLowGatewaysShell, /--path "\$email_mcp_path"/);
assert.match(startLowGatewaysShell, /default_finance_mcp_api_base_url="http:\/\/127\.0\.0\.1:8791"/);
assert.match(startLowGatewaysShell, /default_note_mcp_api_base_url="http:\/\/127\.0\.0\.1:4181"/);
assert.match(startLowGatewaysShell, /default_growth_mcp_api_base_url="http:\/\/127\.0\.0\.1:4881"/);
assert.match(startLowGatewaysShell, /default_email_mcp_api_base_url="http:\/\/127\.0\.0\.1:5175"/);
assert.match(startLowGatewaysShell, /\[\[ "\$gateway_worker_root" == \/mnt\/\* \]\] && \[ -n "\$\{windows_host_gateway:-\}" \]/);
assert.match(startLowGatewaysShell, /default_finance_mcp_api_base_url="http:\/\/\$\{windows_host_gateway\}:8791"/);
assert.match(startLowGatewaysShell, /default_note_mcp_api_base_url="http:\/\/\$\{windows_host_gateway\}:4181"/);
assert.match(startLowGatewaysShell, /default_growth_mcp_api_base_url="http:\/\/\$\{windows_host_gateway\}:4881"/);
assert.match(startLowGatewaysShell, /default_email_mcp_api_base_url="http:\/\/\$\{windows_host_gateway\}:5175"/);
assert.match(startLowGatewaysShell, /configure_cache_current\(\)/);
assert.match(startLowGatewaysShell, /write_configure_signature\(\)/);
assert.match(startLowGatewaysShell, /profile_environment_ready\(\)/);
assert.match(startLowGatewaysShell, /selected_gateway_profiles_ready\(\)/);
assert.match(startLowGatewaysShell, /profile_template_sync_current\(\)/);
assert.match(startLowGatewaysShell, /profile_template_drift:\{template_key\}:/);
assert.match(startLowGatewaysShell, /gateway_profile_template_builder_script="\$\{HERMES_GATEWAY_PROFILE_TEMPLATE_BUILDER_SCRIPT:-\$mobile_app_root\/scripts\/build-gateway-profile-template\.js\}"/);
assert.match(startLowGatewaysShell, /find_gateway_template_node\(\)/);
assert.match(startLowGatewaysShell, /\/mnt\/c\/Program Files\/nodejs\/node\.exe/);
assert.match(startLowGatewaysShell, /gateway_template_builder_script_arg\(\)/);
assert.match(startLowGatewaysShell, /gateway_template_manifest_arg\(\)/);
assert.match(startLowGatewaysShell, /template_peer_profiles_for_selection\(\)/);
assert.match(startLowGatewaysShell, /--print-configure-profiles/);
assert.match(startLowGatewaysShell, /gateway_configure_profiles="\$expanded_configure_profiles"/);
assert.match(startLowGatewaysShell, /run_configure_low_gateways\(\)/);
assert.match(startLowGatewaysShell, /manifest_memory_store_for_profile\(\)/);
assert.match(startLowGatewaysShell, /expected_memory_store="\$\(manifest_memory_store_for_profile "\$profile"\)"/);
assert.match(startLowGatewaysShell, /memory-store-backups/);
assert.match(startLowGatewaysShell, /lowgw-configure-template-peers requested=\$\{gateway_start_profiles\} configure=\$\{gateway_configure_profiles\}/);
assert.match(startLowGatewaysShell, /HERMES_GATEWAY_REQUEST_WORKSPACE_ID="\$gateway_request_workspace_id" HERMES_GATEWAY_START_PROFILES="\$gateway_configure_profiles" bash "\$configure_low_gateway_script"/);
assert.match(startLowGatewaysShell, /lowgw-configure-skipped reason=stop-only/);
assert.match(startLowGatewaysShell, /lowgw-configure-skipped reason=config-current/);
assert.match(startLowGatewaysShell, /lowgw-configure-cache-miss profiles=\$\{gateway_start_profiles\}/);
assert.match(startLowGatewaysShell, /lowgw-configure-signature-write-failed/);
assert.match(startLowGatewaysShell, /elif ! is_force_configure && selected_gateway_profiles_ready && configure_cache_current && profile_template_sync_current/);
assert.match(startLowGatewaysShell, /if ! is_gateway_stop_only && \[ ! -s "\$api_key_file" \]/);
assert.match(startLowGatewaysShell, /if is_gateway_stop_only;\s*then\s*\r?\n\s*log_step "lowgw-stop-profile-start profile=\$\{profile\} port=\$\{port\}"/);
assert.match(startLowGatewaysChild, /\[switch\]\$SkipConfigureIfReady/);
assert.match(startLowGatewaysChild, /\[switch\]\$ForceConfigure/);
assert.match(startLowGatewaysChild, /HERMES_GATEWAY_SKIP_CONFIGURE_IF_READY=1/);
assert.match(startLowGatewaysChild, /HERMES_GATEWAY_FORCE_CONFIGURE=1/);
assert.match(startLowGatewaysChild, /function Resolve-DefaultFinanceMcpApiBaseUrl/);
assert.match(startLowGatewaysChild, /function Resolve-DefaultNoteMcpApiBaseUrl/);
assert.match(startLowGatewaysChild, /function Resolve-DefaultEmailMcpApiBaseUrl/);
assert.match(startLowGatewaysChild, /Get-NetIPAddress -AddressFamily IPv4/);
assert.match(startLowGatewaysChild, /\^192\\\.168\\\.10\\\./);
assert.match(startLowGatewaysChild, /\[Environment\]::SetEnvironmentVariable\("HERMES_MOBILE_FINANCE_MCP_API_BASE_URL", \$financeApiBase, "Process"\)/);
assert.match(startLowGatewaysChild, /\[Environment\]::SetEnvironmentVariable\("HERMES_MOBILE_NOTE_MCP_API_BASE_URL", \$noteApiBase, "Process"\)/);
assert.match(startLowGatewaysChild, /\[Environment\]::SetEnvironmentVariable\("HERMES_MOBILE_EMAIL_MCP_API_BASE_URL", \$emailApiBase, "Process"\)/);
assert.match(startLowGatewaysChild, /\$passthroughEnvNames = @\(/);
assert.match(startLowGatewaysChild, /HERMES_MOBILE_FINANCE_MCP_API_BASE_URL/);
assert.match(startLowGatewaysChild, /HERMES_MOBILE_FINANCE_MCP_PATH/);
assert.match(startLowGatewaysChild, /HERMES_MOBILE_FINANCE_MCP_PYTHON/);
assert.match(startLowGatewaysChild, /HERMES_MOBILE_FINANCE_USER_DRIVE_ROOT/);
assert.match(startLowGatewaysChild, /HERMES_MOBILE_OWNER_FINANCE_WORKSPACE/);
assert.match(startLowGatewaysChild, /HERMES_MOBILE_WUPING_FINANCE_WORKSPACE/);
assert.match(startLowGatewaysChild, /HERMES_MOBILE_NOTE_MCP_API_BASE_URL/);
assert.match(startLowGatewaysChild, /HERMES_MOBILE_NOTE_MCP_PATH/);
assert.match(startLowGatewaysChild, /HERMES_MOBILE_NOTE_MCP_PYTHON/);
assert.match(startLowGatewaysChild, /HERMES_MOBILE_NOTE_USER_DRIVE_ROOT/);
assert.match(startLowGatewaysChild, /HERMES_MOBILE_OWNER_NOTE_WORKSPACE/);
assert.match(startLowGatewaysChild, /HERMES_MOBILE_WUPING_NOTE_WORKSPACE/);
assert.match(startLowGatewaysChild, /HERMES_MOBILE_EMAIL_MCP_API_BASE_URL/);
assert.match(startLowGatewaysChild, /HERMES_MOBILE_EMAIL_MCP_PATH/);
assert.match(startLowGatewaysChild, /HERMES_MOBILE_EMAIL_MCP_PYTHON/);
assert.match(startLowGatewaysChild, /HERMES_MOBILE_EMAIL_USER_DRIVE_ROOT/);
assert.match(startLowGatewaysChild, /HERMES_MOBILE_OWNER_EMAIL_WORKSPACE/);
assert.match(startLowGatewaysChild, /HERMES_MOBILE_WUPING_EMAIL_WORKSPACE/);
assert.match(startLowGatewaysChild, /\[Environment\]::GetEnvironmentVariable\(\$name, "Process"\)/);
assert.match(startLowGatewaysChild, /\$envArgs \+= "\$name=\$value"/);
assert.match(startGatewayPool, /HERMES_HOME="\$worker_home_dir\/profiles\/\$profile"/);
assert.match(startGatewayPool, /"\$runtime_hermes" gateway run/);
assert.match(startGatewayPool, /\$1 < \/dev\/null/);
assert.match(startGatewayPool, /PATH="\$low_gateway_path"/);
assert.match(startGatewayPool, /google_token\.json/);
assert.match(startGatewayPool, /google_client_secret\.json/);
assert.match(startGatewayPool, /microsoft-graph-outlook-mail\\token\.json/);
assert.match(startGatewayPool, /HERMES_WEB_OUTLOOK_GRAPH_ENV_PATH/);
assert.match(startGatewayPool, /outlook_graph_mcp\.py/);
assert.match(startGatewayPool, /-OutlookGraphEnvPath/);
assert.match(startGatewayPool, /-OutlookGraphMcpPath/);
assert.match(startGatewayPool, /configure-low-gateways\.sh/);
assert.match(startGatewayPool, /Invoke-GatewayPoolPhase -Name "provision-owner-external-connectors"/);
assert.match(startGatewayPool, /Invoke-GatewayPoolPhase -Name "start-low-gateways"/);
assert.match(startGatewayPool, /HERMES_LOW_GATEWAY_REQUIRE_UNIQUE_CODEX_AUTH/);
assert.match(startGatewayPool, /check-worker-codex-auth\.ps1/);
assert.match(startGatewayPool, /codex-auth:/);
assert.match(startGatewayPool, /Invoke-GatewayPoolPhase -Name "check-low-gateway-codex-auth"/);
assert.match(startGatewayPool, /function Install-OwnerMaintenanceChatGptProPlugin/);
assert.match(startGatewayPool, /function Ensure-ProfileToolsetEnabled/);
assert.match(startGatewayPool, /hermes-mobile-chatgpt-pro/);
assert.match(startGatewayPool, /hermes-mobile-weather/);
assert.match(startGatewayPool, /hermes-mobile-cronjob/);
assert.match(startGatewayPool, /Ensure-ProfilePluginEnabled -ConfigPath \$configPath -PluginName \$pluginName/);
assert.match(startGatewayPool, /Ensure-ProfileToolsetEnabled -ConfigPath \$configPath -ToolsetName "chatgpt_pro"/);
assert.match(startGatewayPool, /profiles\\\$profile\\plugins/);
assert.match(startGatewayPool, /Copy-Item -LiteralPath \$source -Destination \$profilePluginTarget -Recurse -Force/);
assert.match(startGatewayPool, /Invoke-GatewayPoolPhase -Name "install-owner-maintenance-chatgpt-pro-plugin"/);
assert.match(startGatewayPool, /Invoke-GatewayPoolPhase -Name "start-owner-maintenance-gateways"/);
assert.match(startGatewayPool, /Owner-maintenance on-demand start profiles/);
assert.match(startGatewayPool, /Owner-maintenance on-demand start OK/);
assert.match(startGatewayPool, /ownerMaintenanceStop/);
assert.match(startGatewayPool, /Stop-OwnerMaintenanceProfiles -Profiles \$profiles/);
assert.match(startGatewayPool, /start-owner-maintenance-gateways\.sh/);
assert.match(startGatewayPool, /stop-owner-maintenance-gateways\.sh/);
assert.match(startGatewayPool, /echo "Stopping owner-maintenance \$\{profile\} on port \$\{port\}: \$\{pids\}"/);
assert.doesNotMatch(startGatewayPool, /echo "Stopping owner-maintenance \$\{profile\} on port \$\{port\}: \$\{pids\}" >&2/);
assert.match(startGatewayPool, /manifest_api_key\(\)/);
assert.match(startGatewayPool, /gateway_pool_manifest_path=\$manifestPathArg/);
assert.match(startGatewayPool, /owner-maintenance gateway API key missing for \$profile/);
assert.match(startGatewayPool, /API_SERVER_KEY=`"`\$api_server_key`"/);
assert.doesNotMatch(startGatewayPool, /\$env:API_SERVER_KEY = \$apiKey/);
assert.doesNotMatch(startGatewayPool, /\$env:WSLENV = "API_SERVER_KEY\/u"/);
assert.match(startGatewayPool, /Invoke-GatewayPoolWslBashFile -Distro \$OfficialDistro -User \$OfficialUser -ScriptPath \$ownerMaintenanceStartShell/);
assert.match(startGatewayPool, /runtime_overrides="\$\{HERMES_GATEWAY_RUNTIME_OVERRIDES:-\$runtime_root\/runtime-overrides\}"/);
assert.match(startGatewayPool, /PYTHONPATH="\$runtime_overrides:\$runtime_source/);
assert.match(startGatewayPool, /runtimeOverridesRoot = "\$runtimeRoot\/runtime-overrides"/);
assert.match(startGatewayPool, /PYTHONPATH=\$\{runtimeOverridesRoot\}:\$\{officialCleanRoot\}/);
assert.doesNotMatch(startGatewayPool, /PYTHONPATH=\$runtimeOverridesRoot:\$officialCleanRoot/);
assert.match(startGatewayPool, /HERMES_HOME=\$profileRoot/);
assert.match(startGatewayPool, /HERMES_PROFILE=\$profile/);
assert.match(startGatewayPool, /\$officialPython -m hermes_cli\.main gateway run --replace/);
assert.match(startGatewayPool, /ln -sfn \$sharedAuthPath/);
assert.match(startGatewayPool, /function Assert-SafeGatewayProfileName/);
assert.match(startGatewayPool, /\^\[A-Za-z0-9\]\[A-Za-z0-9_-\]\*\$/);
assert.match(startGatewayPool, /function Assert-SafeLinuxUserName/);
assert.match(startGatewayPool, /function Is-OwnerMaintenanceWorker/);
assert.match(startGatewayPool, /securityLevel -ne "owner-maintenance"/);
assert.match(startGatewayPool, /\^\(officialclean\|deepseekmaint\)\[0-9\]\+\$/);
assert.match(startGatewayPool, /function Ensure-OwnerMaintenanceProfileConfig/);
assert.match(startGatewayPool, /default: deepseek-chat/);
assert.match(startGatewayPool, /provider: deepseek/);
assert.match(startGatewayPool, /- skills/);
assert.match(startGatewayPool, /- hermes-cli/);
assert.match(startGatewayPool, /platform_toolsets:\s*\r?\n\s*api_server:/);
assert.match(startGatewayPool, /mcp_servers:\s*\r?\n\s*wardrobe:/);
assert.match(startGatewayPool, /finance_mcp_stdio\.py/);
assert.match(startGatewayPool, /note_mcp_stdio\.py/);
assert.match(startGatewayPool, /health-mcp\/scripts\/mcp-health-wrapper\.js/);
assert.match(startGatewayPool, /email-mcp\/scripts\/email-mcp-wrapper\.py/);
assert.match(startGatewayPool, /Resolve-GatewayPoolWslHostApiBaseUrl -Port 5175/);
assert.match(startGatewayPool, /telemetry\\profiles/);
assert.match(startGatewayPool, /missing DeepSeek API key for \$profile/);
assert.match(startGatewayPool, /owner-full\/skills/);
assert.match(startGatewayPool, /function Add-OwnerMaintenanceSkillStoreCommands/);
assert.match(startGatewayPool, /skills-before-owner-link/);
assert.doesNotMatch(startGatewayPool, /owner_maintenance_skills_directory_exists_keeping_profile_local/);
assert.doesNotMatch(startGatewayPool, /profile -match '\^officialclean[12]\$'/);
assert.match(startGatewayPool, /HERMES_MOBILE_OWNER_MAINTENANCE_SHARED_MEMORY_MODE/);
assert.match(startGatewayPool, /HERMES_WEB_OWNER_MAINTENANCE_SHARED_MEMORY_MODE/);
assert.match(startGatewayPool, /if \(-not \$value\) \{ return \$true \}/);
assert.match(startGatewayPool, /\$value = \$value\.Trim\(\)/);
assert.match(startGatewayPool, /\^\(0\|false\|no\|off\|profile-local\)\$/);
assert.match(startGatewayPool, /\$sharedMemoryPath = "\/home\/\$OfficialUser\/\.hermes\/memories"/);
assert.match(startGatewayPool, /hermes-mobile-owner-maintenance-memory\.lock/);
assert.match(startGatewayPool, /flock -w 60 9/);
assert.match(startGatewayPool, /owner_maintenance_memory_lock_timeout/);
assert.doesNotMatch(startGatewayPool, /while ! mkdir \$ownerMaintenanceLockDir/);
assert.match(startGatewayPool, /Add-OwnerMaintenanceSharedMemoryCommands -Commands \$commands -ProfileRoot \$profileRoot -ProfileMemoryPath \$profileMemoryPath -SharedMemoryPath \$sharedMemoryPath/);
assert.match(startGatewayPool, /ln -sfn \$SharedMemoryPath \$ProfileMemoryPath/);
assert.match(startGatewayPool, /\$backupDir = "\{0\}\/memories\.profile-local-markdown-backup-\{1\}"/);
assert.match(startGatewayPool, /Get-Date\)\.ToString\("yyyyMMddHHmmss"\)/);
assert.match(startGatewayPool, /find \$ProfileMemoryPath -maxdepth 1 -type f -name \\\*\.md/);
assert.match(startGatewayPool, /find \$ProfileMemoryPath -maxdepth 1 -type f -name \\\*\.md\.lock -size 0 -delete/);
assert.match(startGatewayPool, /-exec cp -n \{\} \$SharedMemoryPath\/ \\\;/);
assert.match(startGatewayPool, /-exec cp -n \{\} \$backupDir\/ \\\;/);
assert.match(startGatewayPool, /-delete/);
assert.match(startGatewayPool, /if \[ ! -e \$ProfileMemoryPath \]; then ln -sfn \$SharedMemoryPath \$ProfileMemoryPath; fi/);
assert.match(startGatewayPool, /profile_memories_contains_non_markdown_files_keeping_profile_local_directory/);
assert.doesNotMatch(startGatewayPool, /profile-local-backup/);
assert.doesNotMatch(startGatewayPool, /mv \$profileMemoryPath/);
assert.doesNotMatch(startGatewayPool, /find .*state\.db/);
assert.doesNotMatch(startGatewayPool, /find .*response_store/);
assert.doesNotMatch(startGatewayPool, /find .*config\.yaml/);
assert.doesNotMatch(startGatewayPool, /ln -sfn .*state\.db/);
assert.doesNotMatch(startGatewayPool, /ln -sfn .*response_store\.db/);
assert.doesNotMatch(startGatewayPool, /ln -sfn .*config\.yaml/);
assert.doesNotMatch(startGatewayPool, /ln -sfn .*\/home\/\$OfficialUser\/\.hermes\/profiles\/\$profile(?!\/)/);
assert.doesNotMatch(startGatewayPool, /\/home\/\$OfficialUser\/\.local\/bin\/hermes/);
assert.match(startGatewayPool, /Gateway pool startup OK; healthy ports/);
assert.doesNotMatch(startGatewayPool, /Write-GatewayPoolLog .*apiKey/i);
assert.doesNotMatch(startGatewayPool, /bash\s+-lc/);

assert.match(runAsWorker, /\[Parameter\(Mandatory = \$true\)\]/);
assert.match(runAsWorker, /worker-credential\.xml/);
assert.match(runAsWorker, /Import-Clixml/);
assert.match(runAsWorker, /ProcessStartInfo/);
assert.match(runAsWorker, /\$psi\.LoadUserProfile = \$true/);
assert.match(runAsWorker, /worker_exit=/);
assert.doesNotMatch(runAsWorker, /Write-Host .*Password/i);

assert.match(startLowGatewaysChild, /HERMES_LOW_GATEWAY_DISTRO_NAME/);
assert.match(startLowGatewaysChild, /Ubuntu-24\.04/);
assert.match(startLowGatewaysChild, /\[string\]\$StartProfiles = ""/);
assert.match(startLowGatewaysChild, /\[switch\]\$StopOnly/);
assert.match(startLowGatewaysChild, /HERMES_GATEWAY_START_PROFILES=\$StartProfiles/);
assert.match(startLowGatewaysChild, /HERMES_GATEWAY_STOP_ONLY=1/);
assert.match(startLowGatewaysChild, /-- env @envArgs bash/);
assert.match(startLowGatewaysShell, /runtime_overrides="\$\{HERMES_GATEWAY_RUNTIME_OVERRIDES:-\$runtime_root\/runtime-overrides\}"/);
assert.match(startLowGatewaysShell, /gateway_start_profiles="\$\{HERMES_GATEWAY_START_PROFILES:-\}"/);
assert.match(startLowGatewaysShell, /profile_selected\(\)/);
assert.match(startLowGatewaysShell, /filtered_gateway_specs/);
assert.match(startLowGatewaysShell, /gateway_stop_only/);
assert.match(startLowGatewaysShell, /LOW_GATEWAYS_STOPPED/);
assert.match(startLowGatewaysShell, /runtime_overrides_source="\$\{HERMES_GATEWAY_RUNTIME_OVERRIDES_SOURCE:-\$gateway_worker_root\/runtime-overrides\}"/);
assert.match(startLowGatewaysShell, /sync_runtime_overrides\(\)/);
assert.match(startLowGatewaysShell, /runtime-overrides-sync-start source=\$\{runtime_overrides_source\} target=\$\{runtime_overrides\}/);
assert.match(startLowGatewaysShell, /cp -a "\$runtime_overrides_source\/\." "\$runtime_overrides\/"/);
assert.match(startLowGatewaysShell, /-name '__pycache__' -prune -exec rm -rf \{\} \+/);
assert.match(startLowGatewaysShell, /-name '\*\.pyc' -o -name '\*\.pyo'/);
assert.match(startLowGatewaysShell, /missing Gateway runtime overrides source: \$runtime_overrides_source/);
assert.match(startLowGatewaysShell, /PYTHONPATH="\$runtime_overrides:\$runtime_source/);
assert.match(gatewayRuntimeSiteCustomize, /def _missing_configured_mcp_tools/);
assert.match(gatewayRuntimeSiteCustomize, /def _has_patch_marker/);
assert.match(gatewayRuntimeSiteCustomize, /def _mark_patched/);
assert.match(gatewayRuntimeSiteCustomize, /discover_mcp_tools\(\)/);
assert.match(gatewayRuntimeSiteCustomize, /def _mcp_tool_inventory_prompt/);
assert.match(gatewayRuntimeSiteCustomize, /Mounted MCP callable tools/);
assert.match(gatewayRuntimeSiteCustomize, /Treat this list as authoritative for MCP/);
assert.match(gatewayRuntimeSiteCustomize, /class _SystemPromptPatchFinder/);
assert.match(gatewayRuntimeSiteCustomize, /fullname != "agent\.system_prompt"/);
assert.match(gatewayRuntimeSiteCustomize, /build_system_prompt_parts/);
assert.match(gatewayRuntimeSiteCustomize, /def _append_mcp_inventory_to_agent_ephemeral_prompt/);
assert.match(gatewayRuntimeSiteCustomize, /sitecustomize_loaded=True/);
assert.match(gatewayRuntimeSiteCustomize, /def _write_runtime_event_marker/);
assert.match(gatewayRuntimeSiteCustomize, /class _ApiServerPatchFinder/);
assert.match(gatewayRuntimeSiteCustomize, /fullname != "gateway\.platforms\.api_server"/);
assert.match(gatewayRuntimeSiteCustomize, /_create_agent/);
assert.match(gatewayRuntimeSiteCustomize, /api_server_handle_responses/);
assert.match(gatewayRuntimeSiteCustomize, /api_server_run_agent/);
assert.match(gatewayRuntimeSiteCustomize, /api_server_create_agent/);
assert.match(gatewayRuntimeSiteCustomize, /_has_patch_marker\(original_handle_responses, "api_server_handle_responses"\)/);
assert.match(gatewayRuntimeSiteCustomize, /class _RunAgentPatchFinder/);
assert.match(gatewayRuntimeSiteCustomize, /fullname != "run_agent"/);
assert.match(gatewayRuntimeSiteCustomize, /def patched_agent_init/);
assert.match(gatewayRuntimeSiteCustomize, /setattr\(agent_class, "__init__", _mark_patched\(patched_agent_init, "agent_init"\)\)/);
assert.match(gatewayRuntimeSiteCustomize, /_has_patch_marker\(original_init, "agent_init"\)/);
assert.match(gatewayRuntimeSiteCustomize, /run_conversation/);
assert.match(gatewayRuntimeSiteCustomize, /class _ConversationLoopPatchFinder/);
assert.match(gatewayRuntimeSiteCustomize, /fullname != "agent\.conversation_loop"/);
assert.match(gatewayRuntimeSiteCustomize, /patched_conversation_loop/);
assert.match(gatewayRuntimeSiteCustomize, /class _ChatCompletionPatchFinder/);
assert.match(gatewayRuntimeSiteCustomize, /fullname != "agent\.chat_completion_helpers"/);
assert.match(gatewayRuntimeSiteCustomize, /patched_build_api_kwargs/);
assert.match(gatewayRuntimeSiteCustomize, /class _CodexTransportPatchFinder/);
assert.match(gatewayRuntimeSiteCustomize, /fullname != "agent\.transports\.codex"/);
assert.match(gatewayRuntimeSiteCustomize, /patched_transport_build_kwargs/);
assert.match(gatewayRuntimeSiteCustomize, /def _instructions_with_mcp_inventory/);
assert.match(gatewayRuntimeSiteCustomize, /params\["instructions"\] = _instructions_with_mcp_inventory/);
assert.match(gatewayRuntimeSiteCustomize, /transport_mcp_count/);
assert.match(gatewayRuntimeSiteCustomize, /codex_transport=\{codex_transport\}/);
assert.match(gatewayRuntimeSiteCustomize, /def _deferred_patch_attempt/);
assert.match(gatewayRuntimeSiteCustomize, /patch_status prompt=/);
assert.match(gatewayRuntimeSiteCustomize, /threading\.Timer\(0\.05, _deferred_patch_attempt\)/);
assert.match(gatewayRuntimeSiteCustomize, /threading\.Timer\(max\(0\.1, interval_seconds\), _deferred_patch_attempt\)/);
assert.match(gatewayRuntimeSiteCustomize, /def _eager_import_and_patch_runtime_modules/);
assert.match(gatewayRuntimeSiteCustomize, /importlib\.import_module\(module_name\)/);
assert.match(gatewayRuntimeSiteCustomize, /_eager_import_and_patch_runtime_modules\(\)/);
assert.match(gatewayRuntimeSiteCustomize, /_install_deferred_patch_retry\(\)/);
assert.match(gatewayRuntimeSiteCustomize, /def _patch_utils_atomic_replace_module/);
assert.match(gatewayRuntimeSiteCustomize, /errno\.EXDEV/);
assert.match(gatewayRuntimeSiteCustomize, /shutil\.copyfileobj/);
assert.match(gatewayRuntimeSiteCustomize, /"utils", _patch_utils_atomic_replace_module/);
assert.match(gatewayRuntimeSiteCustomize, /_install_utils_atomic_replace_patch\(\)/);
assert.match(gatewayRuntimeSiteCustomize, /def _patch_auth_atomic_replace_module/);
assert.match(gatewayRuntimeSiteCustomize, /fullname != "hermes_cli\.auth"/);
assert.match(gatewayRuntimeSiteCustomize, /"hermes_cli\.auth", _patch_auth_atomic_replace_module/);
assert.match(gatewayRuntimeSiteCustomize, /_install_auth_atomic_replace_patch\(\)/);
assert.match(startLowGatewaysChild, /start-low-gateways\.sh/);
assert.match(startLowGatewaysChild, /wsl\.exe -d \$distroName -u root/);

assert.match(startLowGatewaysShell, /configure-low-gateways\.sh/);
assert.match(startLowGatewaysShell, /HERMES_GATEWAY_RUNTIME_ROOT/);
assert.match(startLowGatewaysShell, /HERMES_GROK_GATEWAY_COUNT/);
assert.match(startLowGatewaysShell, /log_step\(\)/);
assert.match(startLowGatewaysShell, /lowgw-configure-start/);
assert.match(startLowGatewaysShell, /lowgw-start-profile-start profile=\$\{profile\} port=\$\{port\}/);
assert.match(startLowGatewaysShell, /lowgw-wait-health-done port=\$\{port\}/);
assert.match(startLowGatewaysShell, /HERMES_MOBILE_BRIDGE_HOST_URL/);
assert.match(startLowGatewaysShell, /HERMES_MOBILE_BRIDGE_HOST_KEY_PATH/);
assert.match(startLowGatewaysShell, /HERMES_WEB_BRIDGE_HOST_URL/);
assert.match(startLowGatewaysShell, /HERMES_WEB_BRIDGE_HOST_KEY_PATH/);
assert.match(startLowGatewaysShell, /detect_windows_host_gateway\(\)/);
assert.match(startLowGatewaysShell, /default_mobile_bridge_host_url="http:\/\/\$\{windows_host_gateway\}:8798"/);
assert.match(startLowGatewaysShell, /manifest_gateway_specs\(\)/);
assert.match(startLowGatewaysShell, /gateway_specs="\$\(manifest_gateway_specs\)"/);
assert.match(startLowGatewaysShell, /hm-\[a-z0-9-\]\+-\(openai\|deepseek\)-\\d\+/);
assert.match(startLowGatewaysShell, /grok_gateway_port="\$\(printf '%s\\n' "\$gateway_specs"/);
assert.match(startLowGatewaysShell, /HERMES_GATEWAY_RUNTIME_BIN/);
assert.match(startLowGatewaysShell, /runtime_hermes="\$runtime_bin\/hermes"/);
assert.match(startLowGatewaysShell, /HERMES_HOME="\$worker_home_dir\/profiles\/\$profile"/);
assert.match(startLowGatewaysShell, /"\$runtime_hermes" gateway run --replace --accept-hooks/);
assert.doesNotMatch(startLowGatewaysShell, /"\$runtime_hermes" -p "\$profile" gateway run/);
assert.match(startLowGatewaysShell, /pgrep -u "\$worker_user" -f "hermes_cli\.main \.\*gateway run --replace --accept-hooks" \| tail -1/);
assert.match(startLowGatewaysShell, /> "\$log" 2>&1 < \/dev\/null/);
assert.doesNotMatch(startLowGatewaysShell, /"\$runtime_python" -m hermes_cli\.main -p "\$profile" gateway run/);
assert.match(startLowGatewaysShell, /HERMES_PROFILE="\$profile"/);
assert.match(startLowGatewaysShell, /HERMES_MOBILE_MCP_INVENTORY_LOG="\$worker_home_dir\/logs\/\$\{profile\}-mcp-inventory\.log"/);
assert.match(startLowGatewaysShell, /HERMES_GOOGLE_PROFILE_HOME/);
assert.match(startLowGatewaysShell, /PATH="\$low_gateway_path"/);
assert.match(startLowGatewaysShell, /manifest_worker_api_key\(\)/);
assert.match(startLowGatewaysShell, /api_key="\$\(manifest_worker_api_key "\$profile"\)"/);
assert.match(startLowGatewaysShell, /API_SERVER_KEY="\$api_key"/);
assert.match(startLowGatewaysShell, /LOW_GATEWAYS_STARTED/);
assert.match(startLowGatewaysShell, /start_gateway_profile "\$profile" "\$port"/);
assert.doesNotMatch(startLowGatewaysShell, /start_gateway_profile "grokgw\$\{idx\}"/);
assert.match(startLowGatewaysShell, /verify_gateway_profile\(\)/);
assert.match(startLowGatewaysShell, /repair_gateway_profile_link\(\)/);
assert.match(startLowGatewaysShell, /stop_gateway_port\(\)/);
assert.match(startLowGatewaysShell, /ss -ltnp "sport = :\$\{port\}"/);
assert.match(startLowGatewaysShell, /echo "Stopping existing low Gateway listener on port \$\{port\}: \$\{pids\}"/);
assert.doesNotMatch(startLowGatewaysShell, /echo "Stopping existing low Gateway listener on port \$\{port\}: \$\{pids\}" >&2/);
assert.match(startLowGatewaysShell, /kill -9 \$pids/);
assert.match(startGatewayPool, /Invoke-GatewayPoolPhase/);
assert.match(startGatewayPool, /phase-start \{0\}/);
assert.match(startGatewayPool, /phase-done \{0\} elapsedMs=\{1\}/);
assert.match(startGatewayPool, /Assert-SafeWslDistroName/);
assert.match(startGatewayPool, /\$distroName = "\$LowGatewayDistroName"/);
assert.doesNotMatch(startGatewayPool, /wsl\.exe -d HermesGatewayWorker -u root -- bash \/mnt\/c\/ProgramData\/HermesMobile\/gateway-worker\/stop-low-gateways\.sh/);

assert.match(startWorkerHost, /\$env:HERMES_MOBILE_BRIDGE_HOST = "0\.0\.0\.0"/);
assert.match(startWorkerHost, /HERMES_MOBILE_BRIDGE_PYTHON_MODE = "windows-native"/);
assert.match(startWorkerHost, /HERMES_MOBILE_BRIDGE_PYTHON_EXE = \$nativePython/);
assert.match(startWorkerHost, /HERMES_WEB_HERMES_HOME = \$resolvedHermesHome/);
assert.doesNotMatch(startWorkerHost, /BridgeWslUser|WeixinFrontGatewayWslUser|CronTickSidecarDistroName|CronTickSidecarWslUser/);
assert.doesNotMatch(startWorkerHost, /HERMES_WEB_WSL_DISTRO = "Ubuntu-24\.04"/);
assert.doesNotMatch(startWorkerHost, /HERMES_WEB_WSL_USER = \$resolvedWslUser/);
assert.match(startLowGatewaysShell, /profile_link="\$worker_home_dir\/profiles\/\$profile"/);
assert.match(startLowGatewaysShell, /expected_target="\$gateway_worker_root\/telemetry\/profiles\/\$profile"/);
assert.match(startLowGatewaysShell, /profile-directory-backups/);
assert.match(startLowGatewaysShell, /start-repair/);
assert.doesNotMatch(startLowGatewaysShell, /moving real low Gateway profile directory[^\n]+>&2/);
assert.match(startLowGatewaysShell, /low gateway profile is not a symlink/);
assert.match(startLowGatewaysShell, /missing shared auth link for low gateway profile/);
assert.match(startLowGatewaysShell, /missing shared auth lock link for low gateway profile/);
assert.doesNotMatch(startLowGatewaysShell, /xuxin/);

assert.match(configureLowGateways, /HERMES_MOBILE_OWNER_CONNECTOR_PROFILES/);
assert.match(configureLowGateways, /lowgw1 lowgw2 lowgw3 lowgw4 lowgw10 deepseekgw1 deepseekgw2 deepseekgw99/);
assert.match(configureLowGateways, /gateway_profile_template_builder_script="\$\{HERMES_GATEWAY_PROFILE_TEMPLATE_BUILDER_SCRIPT:-\$mobile_app_root\/scripts\/build-gateway-profile-template\.js\}"/);
assert.match(configureLowGateways, /find_gateway_template_node\(\)/);
assert.match(configureLowGateways, /\/mnt\/c\/Program Files\/nodejs\/node\.exe/);
assert.match(configureLowGateways, /gateway_template_builder_script_arg\(\)/);
assert.match(configureLowGateways, /render_gateway_template_yaml\(\)/);
assert.match(configureLowGateways, /--render-config-yaml "\$@" > "\$temp_path" < \/dev\/null/);
assert.match(configureLowGateways, /gateway-template-rendered output=\$\{output_path\}/);
assert.match(configureLowGateways, /--render-config-yaml/);
assert.match(configureLowGateways, /--config-kind base/);
assert.match(configureLowGateways, /--config-kind profile/);
assert.match(configureLowGateways, /--config-kind grok/);
assert.match(configureLowGateways, /link_low_gateway_profile_subdir\(\)/);
assert.match(configureLowGateways, /deepseek_companion_low_profile\(\)/);
assert.match(configureLowGateways, /ensure_low_gateway_memory_link "\$profile" "\$profile_dir\/memories"/);
assert.doesNotMatch(configureLowGateways, /link_low_gateway_profile_subdir "\$profile_dir\/memories" "\$companion_profile_dir\/memories" "memories"/);
assert.match(configureLowGateways, /link_low_gateway_profile_subdir "\$profile_dir\/skills" "\$\(skill_store_for_gateway_profile "\$profile"\)" "skills"/);
assert.match(configureLowGateways, /link_low_gateway_profile_subdir "\$profile_dir\/skills" "\$owner_skill_store" "skills"/);
assert.match(configureLowGateways, /HERMES_GROK_GATEWAY_COUNT/);
assert.match(configureLowGateways, /manifest_gateway_specs\(\)/);
assert.match(configureLowGateways, /gateway_specs="\$\(manifest_gateway_specs\)"/);
assert.match(configureLowGateways, /done <<< "\$gateway_specs"/);
assert.match(configureLowGateways, /hm-\[a-z0-9-\]\+-\(openai\|deepseek\)-\\d\+/);
assert.match(configureLowGateways, /HERMES_MOBILE_OUTLOOK_GRAPH_MCP_PATH/);
assert.match(configureLowGateways, /HERMES_MOBILE_OWNER_SKILL_STORE/);
assert.match(configureLowGateways, /HERMES_MOBILE_SKILL_PROFILES_ROOT/);
assert.match(configureLowGateways, /HERMES_MOBILE_WARDROBE_MCP_PATH/);
assert.match(configureLowGateways, /HERMES_MOBILE_WARDROBE_USER_DRIVE_ROOT/);
assert.match(configureLowGateways, /HERMES_MOBILE_OWNER_WARDROBE_WORKSPACE/);
assert.match(configureLowGateways, /HERMES_MOBILE_WUPING_WARDROBE_WORKSPACE/);
assert.match(configureLowGateways, /HERMES_MOBILE_FINANCE_MCP_PYTHON/);
assert.match(configureLowGateways, /HERMES_MOBILE_FINANCE_MCP_PATH/);
assert.match(configureLowGateways, /HERMES_MOBILE_FINANCE_MCP_API_BASE_URL/);
assert.match(configureLowGateways, /HERMES_MOBILE_FINANCE_MCP_SCHEMA_PROBE_TIMEOUT_SECONDS/);
assert.match(configureLowGateways, /HERMES_MOBILE_NOTE_MCP_PYTHON/);
assert.match(configureLowGateways, /HERMES_MOBILE_NOTE_MCP_PATH/);
assert.match(configureLowGateways, /HERMES_MOBILE_NOTE_MCP_API_BASE_URL/);
assert.match(configureLowGateways, /HERMES_MOBILE_GROWTH_MCP_COMMAND/);
assert.match(configureLowGateways, /HERMES_MOBILE_GROWTH_MCP_PATH/);
assert.match(configureLowGateways, /HERMES_MOBILE_GROWTH_MCP_API_BASE_URL/);
assert.match(configureLowGateways, /detect_windows_host_gateway\(\)/);
assert.match(configureLowGateways, /\[\[ "\$gateway_worker_root" == \/mnt\/\* \]\] && \[ -n "\$windows_host_gateway" \]/);
assert.match(configureLowGateways, /default_finance_mcp_api_base_url="http:\/\/\$\{windows_host_gateway\}:8791"/);
assert.match(configureLowGateways, /default_note_mcp_api_base_url="http:\/\/\$\{windows_host_gateway\}:4181"/);
assert.match(configureLowGateways, /default_growth_mcp_api_base_url="http:\/\/\$\{windows_host_gateway\}:4881"/);
assert.match(configureLowGateways, /default_email_mcp_api_base_url="http:\/\/\$\{windows_host_gateway\}:5175"/);
assert.match(configureLowGateways, /HERMES_MOBILE_FINANCE_USER_DRIVE_ROOT/);
assert.match(configureLowGateways, /HERMES_MOBILE_OWNER_FINANCE_WORKSPACE/);
assert.match(configureLowGateways, /HERMES_MOBILE_WUPING_FINANCE_WORKSPACE/);
assert.match(configureLowGateways, /HERMES_MOBILE_NOTE_USER_DRIVE_ROOT/);
assert.match(configureLowGateways, /HERMES_MOBILE_OWNER_NOTE_WORKSPACE/);
assert.match(configureLowGateways, /HERMES_MOBILE_WUPING_NOTE_WORKSPACE/);
assert.match(configureLowGateways, /gateway_start_profiles="\$\{HERMES_GATEWAY_START_PROFILES:-\}"/);
assert.match(configureLowGateways, /safe_request_workspace_id\(\)/);
assert.match(configureLowGateways, /gateway_request_workspace_id="\$\(safe_request_workspace_id "\$\{HERMES_GATEWAY_REQUEST_WORKSPACE_ID:-\}"\)"/);
assert.match(configureLowGateways, /profile_selected_for_configure\(\)/);
assert.match(configureLowGateways, /if ! profile_selected_for_configure "\$profile"; then/);
assert.match(configureLowGateways, /is_owner_connector_profile/);
assert.match(configureLowGateways, /find_first_wardrobe_workspace_root\(\)/);
assert.match(configureLowGateways, /rglob\("\.hermes-wardrobe\/config\.json"\)/);
assert.match(configureLowGateways, /find_first_finance_workspace_root\(\)/);
assert.match(configureLowGateways, /user_root \/ "\.hermes-finance" \/ "config\.json"/);
assert.match(configureLowGateways, /finance_mcp_schema_ready\(\)/);
assert.match(configureLowGateways, /\/api\/finance\/mcp\/schemas/);
assert.match(configureLowGateways, /X-Finance-MCP-Workspace-Id/);
assert.match(configureLowGateways, /Skipping finance MCP for \$profile: schema probe failed/);
assert.match(configureLowGateways, /find_first_note_workspace_root\(\)/);
assert.match(configureLowGateways, /user_root \/ "\.hermes-note" \/ "config\.json"/);
assert.match(configureLowGateways, /find_first_email_workspace_root\(\)/);
assert.match(configureLowGateways, /user_root \/ "\.hermes-email" \/ "config\.json"/);
assert.match(configureLowGateways, /access-key\.txt/);
assert.match(configureLowGateways, /workspace_id_for_gateway_profile\(\)/);
assert.match(configureLowGateways, /ensure_low_gateway_skill_link\(\)/);
assert.match(configureLowGateways, /skill_store_for_gateway_profile\(\)/);
assert.match(configureLowGateways, /request_workspace and request_workspace not in \("owner", "\*"\)/);
assert.match(configureLowGateways, /skillWorkspaceIds/);
assert.match(configureLowGateways, /ln -s "\$target_skill_store" "\$skill_dir"/);
assert.match(configureLowGateways, /ensure_low_gateway_skill_link "\$profile" "\$profile_dir\/skills"/);
assert.match(startLowGatewaysShell, /manifest_skill_store_for_profile\(\)/);
assert.match(startLowGatewaysShell, /skill_profile\.lower\(\)\.startswith\("workspace:"\)/);
assert.match(startLowGatewaysShell, /manifest_path, profile, owner_skill_store, skill_profiles_root, request_workspace = sys\.argv\[1:6\]/);
assert.match(startLowGatewaysShell, /request_workspace and request_workspace not in \("owner", "\*"\)/);
assert.doesNotMatch(startLowGatewaysShell, /if skill_profile:\s*\r?\n\s*value = clean_profile/);
assert.match(startLowGatewaysShell, /skills-before-workspace-link/);
assert.match(startLowGatewaysShell, /missing Skill Store mapping for low gateway profile/);
assert.match(startLowGatewaysShell, /ln -sfn "\$expected_skill_store" "\$skill_dir"/);
assert.match(configureLowGateways, /outlook_graph:/);
assert.match(configureLowGateways, /wardrobe:/);
assert.match(configureLowGateways, /finance:/);
assert.match(configureLowGateways, /note:/);
assert.match(configureLowGateways, /email:/);
assert.match(configureLowGateways, /\/opt\/hermes-gateway-runtime\/venv\/bin\/python/);
assert.match(configureLowGateways, /--no-workspace-override/);
assert.match(configureLowGateways, /--api-base-url/);
assert.match(configureLowGateways, /profile_workspace_id="\$\(workspace_id_for_gateway_profile "\$profile"\)"/);
assert.match(configureLowGateways, /wuping_wardrobe_workspace/);
assert.match(configureLowGateways, /wuping_finance_workspace/);
assert.match(configureLowGateways, /wuping_note_workspace/);
assert.match(configureLowGateways, /wuping_email_workspace/);
assert.match(configureLowGateways, /HERMES_HOME: \$profile_link/);
assert.match(configureLowGateways, /platform_toolsets:[\s\S]*api_server:[\s\S]*\$\{finance_api_toolset_block\}[\s\S]*\$\{note_api_toolset_block\}[\s\S]*\$\{email_api_toolset_block\}[\s\S]*\$\{outlook_api_toolset_block\}/);
assert.match(configureLowGateways, /prepare_low_gateway_profile_link\(\)/);
assert.match(configureLowGateways, /profile-directory-backups/);
assert.match(configureLowGateways, /moving real low Gateway profile directory/);
assert.doesNotMatch(configureLowGateways, /moving real low Gateway profile directory[^\n]+>&2/);
assert.match(configureLowGateways, /prepare_low_gateway_profile_link "\$profile" "\$profile_link"/);
assert.doesNotMatch(configureLowGateways, /rm -rf "\$profile_link"/);

assert.match(provisionWorkerExternalConnectors, /external-connectors\/owner/);
assert.match(provisionWorkerExternalConnectors, /google_token\.json/);
assert.match(provisionWorkerExternalConnectors, /microsoft-graph-outlook-mail\/token\.json/);
assert.match(provisionWorkerExternalConnectors, /Copy-FilteredOutlookEnvFile/);
assert.match(provisionWorkerExternalConnectors, /outlook_graph\.env/);
assert.match(provisionWorkerExternalConnectors, /outlook_graph_mcp\.py/);
assert.match(provisionWorkerExternalConnectors, /MS_GRAPH_CLIENT_ID/);
assert.match(provisionWorkerExternalConnectors, /patch_google_workspace_skill\(\)/);
assert.match(provisionWorkerExternalConnectors, /HERMES_GOOGLE_RUNTIME_REEXEC/);
assert.match(provisionWorkerExternalConnectors, /profiles.*<profile>.*skills/s);
assert.match(provisionWorkerExternalConnectors, /HERMES_GOOGLE_PROFILE_HOME="\`\$profile_dir" python3 "\`\$google_setup" --check/);
assert.match(provisionWorkerExternalConnectors, /google_workspace_setup_check=ok/);
assert.match(provisionWorkerExternalConnectors, /\[owner-secret-root\]/);
assert.doesNotMatch(provisionWorkerExternalConnectors, /Get-Content\s+-Raw\s+\$GoogleTokenPath/i);
assert.doesNotMatch(provisionWorkerExternalConnectors, /Write-Host .*token/i);

assert.match(outlookGraphMcp, /FastMCP\("OutlookGraph"/);
assert.match(outlookGraphMcp, /microsoft-graph-outlook-mail/);
assert.match(outlookGraphMcp, /MS_GRAPH_CLIENT_ID/);
assert.doesNotMatch(outlookGraphMcp, /client_secret\s*=\s*["'][^"']+["']/i);

assert.match(repairWorkspaceAcl, /\[string\]\$WorkspaceRoot/);
assert.match(repairWorkspaceAcl, /HermesMobileWorker/);
assert.match(repairWorkspaceAcl, /\[switch\]\$CheckOnly/);
assert.match(repairWorkspaceAcl, /icacls \$root \/grant \$grant/);
assert.match(repairWorkspaceAcl, /missingWorkerRead/);

assert.match(runKanbanGatewayWorker, /ValueFromRemainingArguments/);
assert.match(runKanbanGatewayWorker, /PositionalBinding\s*=\s*\$false/);
assert.match(runKanbanGatewayWorker, /\[string\]\$DistroName = ""/);
assert.match(runKanbanGatewayWorker, /HERMES_MOBILE_KANBAN_WSL_DISTRO/);
assert.match(runKanbanGatewayWorker, /HERMES_WEB_WSL_DISTRO/);
assert.match(runKanbanGatewayWorker, /Ubuntu-24\.04/);
assert.doesNotMatch(runKanbanGatewayWorker, /\[string\]\$DistroName = "HermesGatewayWorker"/);
assert.match(runKanbanGatewayWorker, /run-as-worker\.ps1/);
assert.match(runKanbanGatewayWorker, /PayloadBase64/);
assert.match(runKanbanGatewayWorker, /kanbanArgs = \$KanbanArgs/);
assert.match(runKanbanGatewayWorker, /kanban-runner/);
assert.match(runKanbanGatewayWorker, /\[string\]\$WorkerUserName = "HermesMobileWorker"/);
assert.match(runKanbanGatewayWorker, /\[switch\]\$RunInCallerContext/);
assert.match(runKanbanGatewayWorker, /HERMES_MOBILE_KANBAN_RUN_IN_CALLER_CONTEXT/);
assert.match(runKanbanGatewayWorker, /HERMES_MOBILE_LISTENER_RUN_IN_CALLER_CONTEXT/);
assert.match(runKanbanGatewayWorker, /listener-run-in-caller-context\.flag/);
assert.match(runKanbanGatewayWorker, /function Current-UserName/);
assert.match(runKanbanGatewayWorker, /Test-KanbanRunInCallerContext/);
assert.match(runKanbanGatewayWorker, /Current-UserName\) -ieq \$WorkerUserName/);
assert.match(runKanbanGatewayWorker, /Copy-Item -LiteralPath \$sourceShellScript/);
assert.match(runKanbanGatewayWorker, /run-kanban-gateway-worker-child-\$stamp\.ps1/);
assert.match(runKanbanGatewayWorker, /run-kanban-gateway-worker-\$stamp\.sh/);
assert.match(runKanbanGatewayWorker, /run-kanban-command-\$stamp\.ps1/);
assert.match(runKanbanGatewayWorker, /Remove-Item -LiteralPath \$childScript/);
assert.match(runKanbanGatewayWorker, /Remove-Item -LiteralPath \$shellScript/);
assert.doesNotMatch(runKanbanGatewayWorker, /-ChildArgs/);

assert.match(runKanbanGatewayWorkerChild, /Convert-ToWslPath/);
assert.match(runKanbanGatewayWorkerChild, /wsl\.exe -d \$distroName -u root/);
assert.match(runKanbanGatewayWorkerChild, /PayloadBase64/);

assert.match(runKanbanGatewayWorkerShell, /runuser/);
assert.match(runKanbanGatewayWorkerShell, /-u",\s*"hermes"/);
assert.match(runKanbanGatewayWorkerShell, /runtime_bin="\$\{HERMES_GATEWAY_RUNTIME_BIN:-\$runtime_root\/bin\}"/);
assert.match(runKanbanGatewayWorkerShell, /hermes_shim="\$runtime_bin\/hermes"/);
assert.match(runKanbanGatewayWorkerShell, /exec "\$runtime_python" -m hermes_cli\.main "\\\$@"/);
assert.match(runKanbanGatewayWorkerShell, /PYTHONPATH=\{runtime_source\}/);
assert.match(runKanbanGatewayWorkerShell, /PATH=\{runtime_bin\}:\{runtime_root\}\/venv\/bin:\/usr\/local\/bin:\/usr\/bin:\/bin/);
assert.match(runKanbanGatewayWorkerShell, /hermes_cli\.main/);
assert.match(runKanbanGatewayWorkerShell, /kanban_args/);
assert.match(runKanbanGatewayWorkerShell, /capture_output=True/);
assert.match(runKanbanGatewayWorkerShell, /ensure_ascii=True/);

assert.match(runKanbanNativeWindows, /venv\\Scripts\\python\.exe/);
assert.match(runKanbanNativeWindows, /official-clean/);
assert.match(runKanbanNativeWindows, /HERMES_HOME = \$HermesHome/);
assert.match(runKanbanNativeWindows, /PYTHONPATH = \$runtimeSource/);
assert.match(runKanbanNativeWindows, /HERMES_ACCEPT_HOOKS = "1"/);
assert.match(runKanbanNativeWindows, /-m hermes_cli\.main @KanbanArgs/);
assert.doesNotMatch(runKanbanNativeWindows, /wsl\.exe|bash|DistroName|WslUser|runuser/i);

assert.match(startCronTickSidecar, /function Get-CronTickSidecarProcess/);
assert.match(startCronTickSidecar, /function Invoke-CronStatusCheck/);
assert.match(startCronTickSidecar, /-m hermes_cli\.main cron status/);
assert.match(startCronTickSidecar, /Start-Process/);
assert.match(startCronTickSidecar, /run-cron-tick-sidecar\.ps1/);
assert.match(startCronTickSidecar, /HERMES_WEB_HERMES_HOME/);
assert.match(startCronTickSidecar, /HERMES_MOBILE_CRON_TICK_LOG_PATH/);
assert.match(startCronTickSidecar, /HERMES_MOBILE_CRON_DISPATCH_TIMEOUT_SECONDS/);
assert.match(runCronTickSidecar, /HERMES_MOBILE_CRON_TICK_SIDE = "windows-native"/);
assert.doesNotMatch(startCronTickSidecar, /wsl\.exe/i);
assert.doesNotMatch(runCronTickSidecar, /wsl\.exe/i);
assert.doesNotMatch(runCronTickSidecar, /DistroName|WslUser|windows-wsl/);
assert.match(startCronTickSidecar, /DispatchTimeoutSeconds/);
assert.match(startCronTickSidecar, /hermes-mobile-cron-dispatcher\.py/);
assert.match(startCronTickSidecar, /DispatcherScript/);

assert.match(runCronTickSidecar, /hermes-mobile-cron-dispatcher\.py/);
assert.match(runCronTickSidecar, /--dispatch/);
assert.match(runCronTickSidecar, /HERMES_ACCEPT_HOOKS = "1"/);
assert.match(runCronTickSidecar, /HERMES_HOME = \$HermesHome/);
assert.match(runCronTickSidecar, /PYTHONPATH = \$runtimeSource/);
assert.match(runCronTickSidecar, /WaitForExit\(\$DispatchTimeoutSeconds \* 1000\)/);
assert.match(runCronTickSidecar, /Stop-Process -Id \$process\.Id -Force/);
assert.match(runCronTickSidecar, /exitCode = 124/);
assert.match(runCronTickSidecar, /\$process\.Refresh\(\)/);
assert.match(runCronTickSidecar, /timed_out=\$timedOut/);
assert.doesNotMatch(runCronTickSidecar, /TickTimeoutSeconds/);
assert.doesNotMatch(startCronTickSidecar, /TickTimeoutSeconds/);
assert.match(runCronTickSidecar, /Select-Object -Last \$maxLines/);
assert.doesNotMatch(runCronTickSidecar, /cron", "tick"/);
assert.doesNotMatch(runCronTickSidecar, /gateway", "run"/);

assert.match(hermesMobileCronDispatcher, /def dispatch_due_jobs/);
assert.match(hermesMobileCronDispatcher, /def _cron_child_env/);
assert.match(hermesMobileCronDispatcher, /def _default_windows_host_gateway/);
assert.match(hermesMobileCronDispatcher, /def _runner_tool_failure_summary/);
assert.match(hermesMobileCronDispatcher, /HERMES_MOBILE_X_SEARCH_PROXY_URL/);
assert.match(hermesMobileCronDispatcher, /existing_proxy/);
assert.match(hermesMobileCronDispatcher, /HERMES_MOBILE_CRON_MODEL_PROXY_URL/);
assert.match(hermesMobileCronDispatcher, /cron_model_proxy_required/);
assert.match(hermesMobileCronDispatcher, /cron_model_proxy_unreachable/);
assert.match(hermesMobileCronDispatcher, /side in \{"nas", "windows-native"\}/);
assert.match(hermesMobileCronDispatcher, /HTTPS_PROXY/);
assert.match(hermesMobileCronDispatcher, /HTTP_PROXY/);
assert.match(hermesMobileCronDispatcher, /ALL_PROXY/);
assert.match(hermesMobileCronDispatcher, /_ensure_model_proxy_for_job/);
assert.match(hermesMobileCronDispatcher, /HERMES_MOBILE_CRON_RUNNER_LOG_PATH/);
assert.match(hermesMobileCronDispatcher, /\/bridge\/grok-gateway-proxy/);
assert.match(hermesMobileCronDispatcher, /Tool x_search returned error/);
assert.match(hermesMobileCronDispatcher, /subprocess\.Popen/);
assert.match(hermesMobileCronDispatcher, /start_new_session=True/);
assert.match(hermesMobileCronDispatcher, /advance_next_run\(job_id\)/);
assert.match(hermesMobileCronDispatcher, /def run_one_job/);
assert.match(hermesMobileCronDispatcher, /prepared_job = _job_with_prepared_data_context\(job\)/);
assert.match(hermesMobileCronDispatcher, /run_job\(prepared_job\)/);
assert.match(hermesMobileCronDispatcher, /_run_plugin_workspace_audit_job\(job\)/);
assert.match(hermesMobileCronDispatcher, /mark_job_run\(job_id/);
assert.match(hermesMobileCronDispatcher, /save_job_output\(job_id/);
assert.doesNotMatch(hermesMobileCronDispatcher, /cron tick/);

assert.match(bridgeHost, /\/bridge\/grok-gateway-proxy\/v1\/responses/);
assert.match(bridgeHost, /HERMES_MOBILE_GROK_GATEWAY_URL/);
assert.match(bridgeHost, /function grokGatewayTargetFromManifest/);
assert.match(bridgeHost, /createGatewayWorkerProfileLaunchService/);
assert.match(bridgeHost, /function ensureGrokGatewayReady/);
assert.match(bridgeHost, /grokGatewayStartPromise/);
assert.match(bridgeHost, /startWorkerProfile\(\{ profile/);
assert.match(bridgeHost, /HERMES_MOBILE_GROK_GATEWAY_PROXY_AUTOSTART/);
assert.match(bridgeHost, /gateway-pool-manifest\.json/);
assert.match(bridgeHost, /xai-oauth/);
assert.match(bridgeHost, /new URL\("\/v1\/responses"/);
assert.match(bridgeHost, /gateway_api_key_required/);
assert.match(bridgeHost, /grok_gateway_unavailable/);
assert.match(bridgeHost, /grok_gateway_proxy_failed/);

assert.match(startWeixinFrontGateway, /HERMES_MOBILE_WEIXIN_FRONT_GATEWAY/);
assert.match(startWeixinFrontGateway, /gateway_state\.json/);
assert.match(startWeixinFrontGateway, /hermes_cli\.main gateway run --replace/);
assert.match(startWeixinFrontGateway, /HERMES_PROFILE/);
assert.match(startWeixinFrontGateway, /\/\.hermes\/profiles\//);
assert.match(startWeixinFrontGateway, /weixin/);
assert.match(startWeixinFrontGateway, /api_server/);
assert.match(startWeixinFrontGateway, /ensure-weixin-reminder-dispatcher\.sh/);
assert.match(startWeixinFrontGateway, /ensure-weixin-todo-dispatcher\.sh/);
assert.match(startWeixinFrontGateway, /ensure-weixin-delivery-queue-dispatcher\.sh/);
assert.match(startWeixinFrontGateway, /WEIXIN_FRONT_GATEWAY_OK/);
assert.doesNotMatch(startWeixinFrontGateway, /Hermes Gateway WSL/);
assert.match(startWeixinFrontGateway, /wslpath -a \$portableTmpScript/);
assert.doesNotMatch(startWeixinFrontGateway, /bash\s+-lc/);

assert.match(startWeixinMobileIngressBridge, /weixin-mobile-ingress-bridge\.py/);
assert.match(startWeixinMobileIngressBridge, /HERMES_MOBILE_WEIXIN_INGRESS_KEY_FILE/);
assert.match(startWeixinMobileIngressBridge, /legacy_gateway_pid/);
assert.match(startWeixinMobileIngressBridge, /stop_legacy_gateway/);
assert.match(startWeixinMobileIngressBridge, /HERMES_PROFILE/);
assert.match(startWeixinMobileIngressBridge, /\/\.hermes\/profiles\//);
assert.match(startWeixinMobileIngressBridge, /WEIXIN_MOBILE_INGRESS_BRIDGE_OK/);
assert.match(startWeixinMobileIngressBridge, /ensure-weixin-reminder-dispatcher\.sh/);
assert.match(startWeixinMobileIngressBridge, /ensure-weixin-todo-dispatcher\.sh/);
assert.match(startWeixinMobileIngressBridge, /ensure-weixin-delivery-queue-dispatcher\.sh/);
assert.doesNotMatch(startWeixinMobileIngressBridge, /hermes_cli\.main gateway run --replace/);
assert.match(startWeixinMobileIngressBridge, /wslpath -a \$portableTmpScript/);
assert.doesNotMatch(startWeixinMobileIngressBridge, /bash\s+-lc/);
assert.match(startWeixinMobileIngressBridgeWindows, /NativeProfileRoot = "C:\\ProgramData\\HermesMobile\\hermes-native-profile"/);
assert.match(startWeixinMobileIngressBridgeWindows, /RuntimeRoot = "C:\\ProgramData\\HermesMobile\\gateway-worker\\native-runtime"/);
assert.match(startWeixinMobileIngressBridgeWindows, /HERMES_MOBILE_WEIXIN_RUNTIME_SOURCE/);
assert.match(startWeixinMobileIngressBridgeWindows, /weixin-mobile-ingress-bridge\.py/);
assert.match(startWeixinMobileIngressBridgeWindows, /weixin-reminder-dispatcher\.py/);
assert.match(startWeixinMobileIngressBridgeWindows, /weixin-todo-dispatcher\.py/);
assert.match(startWeixinMobileIngressBridgeWindows, /weixin-delivery-queue-dispatcher\.py/);
assert.match(startWeixinMobileIngressBridgeWindows, /function DispatcherSpec[\s\S]*?\[string\]\$SpecName/);
assert.match(startWeixinMobileIngressBridgeWindows, /\(DispatcherSpec -SpecName "weixin-reminder"/);
assert.match(startWeixinMobileIngressBridgeWindows, /\(DispatcherSpec -SpecName "weixin-todo"/);
assert.doesNotMatch(startWeixinMobileIngressBridgeWindows, /DispatcherSpec -Name/);
assert.doesNotMatch(startWeixinMobileIngressBridgeWindows, /wsl\.exe/i);
assert.doesNotMatch(startWeixinMobileIngressBridgeWindows, /DistroName|WslUser|wslpath/i);
assert.match(weixinMobileIngressBridge, /class MobileIngressBridge/);
assert.match(weixinMobileIngressBridge, /class MobileIngressWeixinAdapter/);
assert.match(weixinMobileIngressBridge, /post_inbound_event/);
assert.match(weixinMobileIngressBridge, /\/api\/ingress\/weixin\/events/);
assert.match(weixinMobileIngressBridge, /\/api\/ingress\/weixin\/outbound/);
assert.match(weixinMobileIngressBridge, /inbound post ignored unmatched route/);
assert.match(weixinMobileIngressBridge, /def process_exists\(pid: int\) -> bool:/);
assert.match(weixinMobileIngressBridge, /os\.name == "nt"/);
assert.match(weixinMobileIngressBridge, /OpenProcess\(process_query_limited_information, False, pid\)/);
assert.match(weixinMobileIngressBridge, /GetExitCodeProcess\(handle, ctypes\.byref\(exit_code\)\)/);
assert.doesNotMatch(weixinMobileIngressBridge, /入口暂不可用|Gateway 处理/);
assert.match(weixinMobileIngressBridge, /workspace_id="owner" if principal_id == "owner" else principal_id/);
assert.doesNotMatch(weixinMobileIngressBridge, /gateway run --replace/);

assert.match(configureLowGateways, /profile_auth_seed_root/);
assert.match(configureLowGateways, /profile_seed="\$profile_auth_seed_root\/\$\{profile\}\/auth\.json"/);
assert.match(configureLowGateways, /shared_auth_mode/);
assert.match(configureLowGateways, /shared_auth_path/);
assert.match(configureLowGateways, /shared_auth_default_root/);
assert.match(configureLowGateways, /telemetry_profiles_root\/shared-auth/);
assert.match(configureLowGateways, /legacy_shared_auth_path/);
assert.match(configureLowGateways, /HERMES_LOW_GATEWAY_SHARED_AUTH_SOURCE_PROFILE/);
assert.match(configureLowGateways, /HERMES_MOBILE_WEATHER_PLUGIN_SOURCE/);
assert.match(configureLowGateways, /HERMES_MOBILE_WEB_PLUGIN_SOURCE/);
assert.match(configureLowGateways, /HERMES_MOBILE_HTTP_PLUGIN_SOURCE/);
assert.match(configureLowGateways, /HERMES_MOBILE_DOCX_PLUGIN_SOURCE/);
assert.match(configureLowGateways, /HERMES_MOBILE_AUDIO_PLUGIN_SOURCE/);
assert.match(configureLowGateways, /HERMES_MOBILE_IMAGE_PLUGIN_SOURCE/);
assert.match(configureLowGateways, /HERMES_MOBILE_VIDEO_PLUGIN_SOURCE/);
assert.match(configureLowGateways, /HERMES_MOBILE_CRONJOB_PLUGIN_SOURCE/);
assert.match(configureLowGateways, /gateway-plugins\/hermes-mobile-weather/);
assert.match(configureLowGateways, /gateway-plugins\/hermes-mobile-web/);
assert.match(configureLowGateways, /gateway-plugins\/hermes-mobile-http/);
assert.match(configureLowGateways, /gateway-plugins\/hermes-mobile-docx/);
assert.match(configureLowGateways, /gateway-plugins\/hermes-mobile-audio/);
assert.match(configureLowGateways, /gateway-plugins\/hermes-mobile-image/);
assert.match(configureLowGateways, /gateway-plugins\/hermes-mobile-video/);
assert.match(configureLowGateways, /gateway-plugins\/hermes-mobile-cronjob/);
assert.match(configureLowGateways, /weather_plugin_enabled=1/);
assert.match(configureLowGateways, /web_plugin_enabled=1/);
assert.match(configureLowGateways, /http_plugin_enabled=1/);
assert.match(configureLowGateways, /docx_plugin_enabled=1/);
assert.match(configureLowGateways, /audio_plugin_enabled=1/);
assert.match(configureLowGateways, /image_plugin_enabled=1/);
assert.match(configureLowGateways, /video_plugin_enabled=1/);
assert.match(configureLowGateways, /cronjob_plugin_enabled=1/);
assert.match(configureLowGateways, /- wardrobe/);
assert.match(configureLowGateways, /- finance/);
assert.match(configureLowGateways, /- note/);
assert.match(configureLowGateways, /- email/);
assert.match(configureLowGateways, /- weather/);
assert.match(configureLowGateways, /- http/);
assert.match(configureLowGateways, /- cronjob_mobile/);
assert.match(configureLowGateways, /wardrobe-mcp\/scripts\/wardrobe-mcp\.py/);
assert.match(configureLowGateways, /finance_mcp_stdio\.py/);
assert.match(configureLowGateways, /note_mcp_stdio\.py/);
assert.match(configureLowGateways, /email-mcp\/scripts\/email-mcp-wrapper\.py/);
assert.match(configureLowGateways, /hermes-mobile-weather/);
assert.match(configureLowGateways, /hermes-mobile-web/);
assert.match(configureLowGateways, /hermes-mobile-http/);
assert.match(configureLowGateways, /hermes-mobile-docx/);
assert.match(configureLowGateways, /hermes-mobile-audio/);
assert.match(configureLowGateways, /hermes-mobile-image/);
assert.match(configureLowGateways, /hermes-mobile-video/);
assert.match(configureLowGateways, /hermes-mobile-cronjob/);
assert.match(configureLowGateways, /profile_dir\/plugins\/hermes-mobile-weather/);
assert.match(configureLowGateways, /profile_dir\/plugins\/hermes-mobile-web/);
assert.match(configureLowGateways, /profile_dir\/plugins\/hermes-mobile-http/);
assert.match(configureLowGateways, /profile_dir\/plugins\/hermes-mobile-docx/);
assert.match(configureLowGateways, /profile_dir\/plugins\/hermes-mobile-audio/);
assert.match(configureLowGateways, /profile_dir\/plugins\/hermes-mobile-image/);
assert.match(configureLowGateways, /profile_dir\/plugins\/hermes-mobile-video/);
assert.match(configureLowGateways, /profile_dir\/plugins\/hermes-mobile-cronjob/);
assert.match(configureLowGateways, /\(\(lowgw\|deepseekgw\)\[0-9\]\+\|hm-\[a-z0-9-\]\+-\(openai\|deepseek\)-\[0-9\]\+\)/);
assert.match(configureLowGateways, /sqlite_integrity_ok/);
assert.match(configureLowGateways, /PRAGMA integrity_check/);
assert.match(configureLowGateways, /repair_low_gateway_sqlite/);
assert.match(configureLowGateways, /state\.db/);
assert.match(configureLowGateways, /response_store\.db/);
assert.match(configureLowGateways, /sqlite-quarantine/);
assert.match(configureLowGateways, /sqlite-quarantine-\$\{stamp\}/);
assert.doesNotMatch(configureLowGateways, /sqlite-quarantine-\$\{stamp\}\/\$\{db_name\}/);
assert.match(configureLowGateways, /sqlite-sidecar-quarantine/);
assert.match(configureLowGateways, /cat > "\$worker_home_dir\/config\.yaml"/);
assert.match(configureLowGateways, /chmod 600 "\$worker_home_dir\/config\.yaml"/);
assert.match(configureLowGateways, /chown "\$worker_user:\$worker_user" "\$worker_home_dir\/config\.yaml"/);
assert.match(configureLowGateways, /platform_toolsets:/);
assert.doesNotMatch(configureLowGateways, /api_server:\s*\r?\n\s+- hermes-api-server/);
assert.match(configureLowGateways, /\s+- web/);
assert.match(configureLowGateways, /\s+- search/);
assert.match(configureLowGateways, /\s+- x_search/);
assert.match(configureLowGateways, /\s+- http/);
assert.match(configureLowGateways, /\s+- browser/);
assert.match(configureLowGateways, /\s+- file/);
assert.match(configureLowGateways, /\s+- vision/);
assert.match(configureLowGateways, /\s+- video/);
assert.match(configureLowGateways, /\s+- image_gen/);
assert.match(configureLowGateways, /\s+- messaging/);
assert.match(configureLowGateways, /\s+- tts/);
assert.match(configureLowGateways, /\s+- skills/);
assert.match(configureLowGateways, /\s+- todo/);
assert.match(configureLowGateways, /\s+- kanban/);
assert.match(configureLowGateways, /\s+- cronjob/);
assert.match(configureLowGateways, /\s+- memory/);
assert.match(configureLowGateways, /\s+- session_search/);
assert.match(configureLowGateways, /\s+- clarify/);
assert.doesNotMatch(configureLowGateways, /\s+- terminal/);
assert.doesNotMatch(configureLowGateways, /\s+- code_execution/);
assert.doesNotMatch(configureLowGateways, /\s+- delegation/);
assert.match(configureLowGateways, /newest_profile_auth_real/);
assert.match(configureLowGateways, /shared_auth_real/);
assert.match(configureLowGateways, /legacy_auth_real/);
assert.match(configureLowGateways, /legacy_shared_auth_path\}\.profile-local-backup-\$\(date \+%Y%m%d-%H%M%S\)/);
assert.match(configureLowGateways, /ln -s "\$shared_auth_path" "\$legacy_shared_auth_path"/);
assert.match(configureLowGateways, /ln -s "\$shared_auth_lock_path" "\$legacy_shared_auth_lock_path"/);
assert.match(configureLowGateways, /grok_auth_default_root="\$\{HERMES_GROK_GATEWAY_AUTH_ROOT:-\$shared_auth_default_root\}"/);
assert.match(configureLowGateways, /grok_auth_path="\$\{HERMES_GROK_GATEWAY_AUTH_PATH:-\$grok_auth_default_root\/auth\.json\}"/);
assert.match(configureLowGateways, /grok_auth_lock_path="\$\{HERMES_GROK_GATEWAY_AUTH_LOCK_PATH:-\$grok_auth_default_root\/auth\.lock\}"/);
assert.match(configureLowGateways, /Missing shared low Gateway Codex auth/);
assert.match(configureLowGateways, /HERMES_LOW_GATEWAY_ALLOW_SHARED_AUTH_SEED/);
assert.match(configureLowGateways, /ln -s "\$shared_auth_path" "\$profile_link\/auth\.json"/);
assert.match(configureLowGateways, /ln -s "\$shared_auth_lock_path" "\$profile_link\/auth\.lock"/);
assert.doesNotMatch(configureLowGateways, /merge_grok_xai_oauth_to_shared_auth/);
assert.match(configureLowGateways, /\[\[ ! "\$profile" =~ \^grokgw\[0-9\]\+\$ \]\]/);
assert.doesNotMatch(configureLowGateways, /profile="grokgw\$\{idx\}"/);
assert.match(configureLowGateways, /provider: xai-oauth/);
assert.match(configureLowGateways, /default: grok-4\.3/);
assert.match(configureLowGateways, /HERMES_DEEPSEEK_GATEWAY_COUNT:-0/);
assert.match(configureLowGateways, /lowgw\|grokgw\|deepseekgw/);
assert.match(configureLowGateways, /\[\[ ! "\$profile" =~ \^\(\(lowgw\|deepseekgw\)\[0-9\]\+\|hm-\[a-z0-9-\]\+-\(openai\|deepseek\)-\[0-9\]\+\)\$ \]\]/);
assert.match(configureLowGateways, /printf 'deepseekgw%s\\t%s\\n'/);
assert.match(configureLowGateways, /profile_default_model="deepseek-chat"/);
assert.match(configureLowGateways, /profile_model_provider="deepseek"/);
assert.match(configureLowGateways, /video_gen:\s*\r?\n\s+provider: hermes-mobile-xai\s*\r?\n\s+model: grok-imagine-video/);
assert.match(configureLowGateways, /\s+- video_gen/);
assert.match(configureLowGateways, /grok_plugin_block="  enabled:\s*\r?\n\s+- hermes-mobile-video"/);
assert.doesNotMatch(configureLowGateways, /install -m 600 -o "\$worker_user" -g "\$worker_user" "\$gateway_worker_root\/secrets\/auth\.json" "\$worker_home_dir\/auth\.json"/);

assert.match(checkWorkerCodexAuth, /RequireUniqueRefreshTokens/);
assert.match(checkWorkerCodexAuth, /WSLENV = "HERMES_CHECK_PROFILES\/u:HERMES_REQUIRE_UNIQUE_REFRESH_TOKENS\/u"/);
assert.match(checkWorkerCodexAuth, /exit `\$LASTEXITCODE/);
assert.match(checkWorkerCodexAuth, /shared-refresh/);
assert.match(checkWorkerCodexAuth, /copied-refresh/);
assert.match(checkWorkerCodexAuth, /auth_path=/);
assert.match(checkWorkerCodexAuth, /hashlib\.sha256\(refresh\.encode\(\)\)\.hexdigest\(\)\[:12\]/);
assert.match(checkWorkerCodexAuth, /Worker child failed with exit code/);
assert.doesNotMatch(checkWorkerCodexAuth, /print\(.*refresh_token/);

assert.match(gatewayToolSchemaSmoke, /\/v1\/responses/);
assert.match(gatewayToolSchemaSmoke, /conversation: marker/);
assert.match(gatewayToolSchemaSmoke, /session_.*\\\.json/);
assert.match(gatewayToolSchemaSmoke, /newestMatchingSession/);
assert.match(gatewayToolSchemaSmoke, /toolsFromSession/);
assert.match(gatewayToolSchemaSmoke, /--require-tool-description/);
assert.match(gatewayToolSchemaSmoke, /--forbid/);
assert.match(gatewayToolSchemaSmoke, /--all-user-workers/);
assert.match(gatewayToolSchemaSmoke, /runAgentSchemaProbe/);
assert.match(gatewayToolSchemaSmoke, /--schema-only/);
assert.match(gatewayToolSchemaSmoke, /--require-agent-schema/);
assert.match(gatewayToolSchemaSmoke, /hasMcpToolRequirement/);
assert.match(gatewayToolSchemaSmoke, /requiresMcpEvidence/);
assert.match(gatewayToolSchemaSmoke, /--agent-schema-timeout-ms/);
assert.match(gatewayToolSchemaSmoke, /agentSchemaTimeoutMs/);
assert.match(gatewayToolSchemaSmoke, /--agent-schema-mode/);
assert.match(gatewayToolSchemaSmoke, /process\.platform === "win32"/);
assert.match(gatewayToolSchemaSmoke, /spawnSync\("bash", \[tempScript\]/);
assert.match(gatewayToolSchemaSmoke, /--allow-mcp-log-evidence/);
assert.match(gatewayToolSchemaSmoke, /only has runtime-log MCP evidence/);
assert.match(gatewayToolSchemaSmoke, /Registration logs are not enough/);
assert.match(gatewayToolSchemaSmoke, /HERMES_AGENT_SCHEMA_PROBE_JSON_START/);
assert.match(gatewayToolSchemaSmoke, /AIAgent/);
assert.match(gatewayToolSchemaSmoke, /HERMES_HOME/);
assert.match(gatewayToolSchemaSmoke, /runtime-overrides/);
assert.match(gatewayToolSchemaSmoke, /http_request,weather,mobile_web_search,mobile_web_extract,image_generate,chatgpt_image_edit,chatgpt_image_erase,docx_extract_text,audio_transcribe/);
assert.match(gatewayToolSchemaSmoke, /missing tools in/);
assert.match(gatewayToolSchemaSmoke, /C:\/ProgramData\/HermesMobile\/gateway-worker\/telemetry\/profiles/);
assert.match(gatewayToolSchemaSmoke, /newestRegisteredToolsFromLogs/);
assert.match(gatewayToolSchemaSmoke, /did not write a matching session.*no registered tools were observed/);
assert.match(startLowGatewaysShell, /HERMES_MOBILE_X_SEARCH_PROXY_URL/);
assert.match(startLowGatewaysShell, /deepseek-api-key\.secret/);
assert.match(startLowGatewaysShell, /DEEPSEEK_API_KEY="\$deepseek_api_key"/);
assert.match(startLowGatewaysShell, /HERMES_DEEPSEEK_GATEWAY_COUNT:-0/);
assert.match(startLowGatewaysShell, /lowgw\|grokgw\|deepseekgw/);
assert.match(startLowGatewaysShell, /printf 'deepseekgw%s\\t%s\\n'/);
assert.match(startLowGatewaysShell, /missing DeepSeek API key for \$\{profile\}/);
assert.match(startGatewayPool, /\[string\]\$LowGatewayDistroName = "Ubuntu-24\.04"/);
assert.doesNotMatch(startGatewayPool, /\[string\]\$LowGatewayDistroName = "HermesGatewayWorker"/);
assert.match(startGatewayPool, /deepseek-api-key\.secret/);
assert.match(startGatewayPool, /deepseek_api_key/);
assert.match(startGatewayPool, /DEEPSEEK_API_KEY=/);
assert.match(configureLowGatewaysShell, /chown -R "\$worker_user:\$worker_user" "\$profile_dir" 2>\/dev\/null \|\| true/);
assert.match(configureLowGatewaysShell, /chown -R "\$worker_user:\$worker_user" "\$worker_home_dir" 2>\/dev\/null \|\| true/);
assert.doesNotMatch(gatewayToolSchemaSmoke, /console\.log\(.*api[_-]?key/i);

assert.match(transcribeReadingAudio, /HermesGatewayWorker/);
assert.match(transcribeReadingAudio, /large-v3-turbo/);
assert.match(transcribeReadingAudio, /whisper-large-v3-turbo-service/);
assert.match(transcribeReadingAudio, /127\.0\.0\.1:8001\/v1\/audio\/transcriptions/);
assert.doesNotMatch(transcribeReadingAudio, /falling back to worker STT/);
assert.doesNotMatch(transcribeReadingAudio, /from faster_whisper import WhisperModel/);
assert.match(transcribeReadingAudio, /\[string\]\$Language = "auto"/);
assert.doesNotMatch(transcribeReadingAudio, /Write-Host .*token/i);
assert.match(startWhisperLargeV3TurboWindows, /whisper-large-v3-turbo/);
assert.match(startWhisperLargeV3TurboWindows, /\.venv-windows/);
assert.match(startWhisperLargeV3TurboWindows, /uvicorn/);
assert.match(startWhisperLargeV3TurboWindows, /WHISPER_MODEL/);
assert.match(startWhisperLargeV3TurboWindows, /WHISPER_DEVICE/);
assert.match(startWhisperLargeV3TurboWindows, /WHISPER_LANGUAGE/);
assert.match(startWhisperLargeV3TurboWindows, /WHISPER_INITIAL_PROMPT/);
assert.match(startWhisperLargeV3TurboWindows, /WHISPER_CONDITION_ON_PREVIOUS_TEXT/);
assert.match(startWhisperLargeV3TurboWindows, /WHISPER_VAD_FILTER/);
assert.doesNotMatch(startWhisperLargeV3TurboWindows, /wsl\.exe|bash/i);

assert.match(weatherPluginManifest, /name: hermes-mobile-weather/);
assert.match(weatherPluginManifest, /provides_tools:\s*\r?\n\s+- weather/);
assert.match(weatherPlugin, /WEATHER_SCHEMA/);
assert.match(weatherPlugin, /"name": "weather"/);
assert.match(weatherPlugin, /toolset="weather"/);
assert.match(weatherPlugin, /open-meteo/);
assert.match(webPluginManifest, /name: hermes-mobile-web/);
assert.match(webPluginManifest, /provides_tools:\s*\r?\n\s+- web\r?\n\s+- search/);
assert.match(webPlugin, /WEB_SEARCH_SCHEMA/);
assert.match(webPlugin, /WEB_EXTRACT_SCHEMA/);
assert.match(webPlugin, /MOBILE_WEB_SEARCH_SCHEMA/);
assert.match(webPlugin, /MOBILE_WEB_EXTRACT_SCHEMA/);
assert.match(webPlugin, /"name": "web_search"/);
assert.match(webPlugin, /"name": "web_extract"/);
assert.match(webPlugin, /MOBILE_WEB_SEARCH_SCHEMA = _schema_alias\(WEB_SEARCH_SCHEMA, "mobile_web_search"\)/);
assert.match(webPlugin, /MOBILE_WEB_EXTRACT_SCHEMA = _schema_alias\(WEB_EXTRACT_SCHEMA, "mobile_web_extract"\)/);
assert.match(webPlugin, /toolset="web"/);
assert.match(webPlugin, /duckduckgo-html-fallback/);
assert.match(webPlugin, /private_or_local_url_not_allowed/);
assert.match(httpPluginManifest, /name: hermes-mobile-http/);
assert.match(httpPluginManifest, /provides_tools:\s*\r?\n\s+- http/);
assert.match(httpPlugin, /HTTP_REQUEST_SCHEMA/);
assert.match(httpPlugin, /CRONJOB_MOBILE_SCHEMA/);
assert.match(httpPlugin, /"name": "http_request"/);
assert.match(httpPlugin, /"name": "cronjob_mobile"/);
assert.match(httpPlugin, /toolset="http"/);
assert.match(httpPlugin, /hermes-mobile:\/\/cron/);
assert.match(httpPlugin, /Use hermes-mobile:\/\/cron for live Hermes Mobile automation jobs/);
assert.match(httpPlugin, /owner_principal_id is required/);
assert.match(httpPlugin, /\/bridge\/cron/);
assert.match(httpPlugin, /_tool_defs_cache\.clear\(\)/);
assert.match(httpPlugin, /HERMES_MOBILE_HTTP_ALLOWED_ORIGINS/);

assert.match(webPlugin, /"name": "x_search"/);
assert.match(webPlugin, /grok-gateway-proxy/);
assert.match(webPlugin, /HERMES_MOBILE_X_SEARCH_PROXY_URL/);
assert.match(webPlugin, /def _bridge_host_x_search_proxy_url/);
assert.match(webPlugin, /HERMES_MOBILE_BRIDGE_HOST_URL/);
assert.match(webPlugin, /"127\.0\.0\.1" in raw/);
assert.match(webPlugin, /_is_grok_gateway_profile/);
assert.match(httpPlugin, /HERMES_MOBILE_HTTP_FILE_ROOTS/);
assert.match(httpPlugin, /file_body/);
assert.match(httpPlugin, /multipart_files/);
assert.match(httpPlugin, /save_base64/);
assert.match(httpPlugin, /saved_file/);
assert.match(httpPlugin, /"run"/);
assert.match(httpPlugin, /file_path_outside_allowed_roots/);
assert.match(httpPlugin, /Authorization/);
assert.match(httpPlugin, /wd_live_/);
assert.match(docxPluginManifest, /name: hermes-mobile-docx/);
assert.match(docxPluginManifest, /provides_tools:\s*\r?\n\s+- file/);
assert.match(docxPlugin, /DOCX_EXTRACT_TEXT_SCHEMA/);
assert.match(docxPlugin, /"name": "docx_extract_text"/);
assert.match(docxPlugin, /toolset="file"/);
assert.match(docxPlugin, /HERMES_MOBILE_DOCX_ALLOWED_ROOTS/);
assert.match(docxPlugin, /zipfile\.ZipFile/);
assert.match(docxPlugin, /word\/document\.xml/);
assert.match(docxPlugin, /file_path_outside_allowed_roots/);
assert.match(docxPlugin, /preview = full_text\[:max_chars\]/);
assert.match(docxPlugin, /"text": preview/);
assert.match(docxPlugin, /"textPreview": preview/);
assert.match(docxPlugin, /"totalChars": len\(full_text\)/);
assert.match(docxPlugin, /"truncated": truncated/);
assert.match(docxPlugin, /"fileName": path\.name/);
assert.doesNotMatch(docxPlugin, /"file_path": str\(path\)/);
assert.doesNotMatch(docxPlugin, /"allowed_roots":/);
assert.match(audioPluginManifest, /name: hermes-mobile-audio/);
assert.match(audioPluginManifest, /provides_tools:\s*\r?\n\s+- file/);
assert.match(audioPlugin, /AUDIO_TRANSCRIBE_SCHEMA/);
assert.match(audioPlugin, /"name": "audio_transcribe"/);
assert.match(audioPlugin, /toolset="file"/);
assert.match(audioPlugin, /HERMES_MOBILE_AUDIO_ALLOWED_ROOTS/);
assert.match(audioPlugin, /large-v3-turbo/);
assert.match(audioPlugin, /whisper-large-v3-turbo-service/);
assert.doesNotMatch(audioPlugin, /from faster_whisper import WhisperModel/);
assert.match(audioPlugin, /SUPPORTED_SUFFIXES/);
assert.match(audioPlugin, /unsupported_audio_file_suffix/);
assert.match(imagePluginManifest, /name: hermes-mobile-image/);
assert.match(imagePluginManifest, /provides_tools:\s*\r?\n\s+- image_gen/);
assert.match(imagePlugin, /IMAGE_EDIT_SCHEMA/);
assert.match(imagePlugin, /IMAGE_ERASE_SCHEMA/);
assert.match(imagePlugin, /CHATGPT_IMAGE_EDIT_SCHEMA/);
assert.match(imagePlugin, /CHATGPT_IMAGE_ERASE_SCHEMA/);
assert.match(imagePlugin, /"name": "image_edit"/);
assert.match(imagePlugin, /"name": "image_erase"/);
assert.match(imagePlugin, /CHATGPT_IMAGE_EDIT_SCHEMA = _schema_alias\(IMAGE_EDIT_SCHEMA, "chatgpt_image_edit"\)/);
assert.match(imagePlugin, /CHATGPT_IMAGE_ERASE_SCHEMA = _schema_alias\(IMAGE_ERASE_SCHEMA, "chatgpt_image_erase"\)/);
assert.match(imagePlugin, /toolset="image_gen"/);
assert.match(imagePlugin, /gpt-image-2/);
assert.doesNotMatch(imagePlugin, /"input_fidelity"/);
assert.match(imagePlugin, /HERMES_MOBILE_IMAGE_ALLOWED_ROOTS/);
assert.match(imagePlugin, /output_path_crosses_workspace_scope/);
assert.match(videoPluginManifest, /name: hermes-mobile-video/);
assert.match(videoPluginManifest, /kind: backend/);
assert.match(videoPlugin, /PROVIDER_NAME = "hermes-mobile-xai"/);
assert.match(videoPlugin, /register_video_gen_provider/);
assert.match(videoPlugin, /VideoGenProvider/);
assert.doesNotMatch(videoPlugin, /ctx\.register_tool/);
assert.doesNotMatch(videoPlugin, /override=True/);
assert.match(videoPlugin, /HERMES_MOBILE_VIDEO_ALLOWED_ROOTS/);
assert.match(videoPlugin, /resolve_xai_http_credentials/);
assert.match(videoPlugin, /data:\{mime\};base64/);
assert.match(videoPlugin, /media_line/);
assert.match(cronjobPluginManifest, /name: hermes-mobile-cronjob/);
assert.match(cronjobPluginManifest, /provides_tools:\s*\r?\n\s+- http/);
assert.match(cronjobPlugin, /MOBILE_CRONJOB_SCHEMA/);
assert.match(cronjobPlugin, /"name": "cronjob_mobile"/);
assert.match(cronjobPlugin, /toolset="http"/);
assert.match(cronjobPlugin, /owner_principal_id is required/);
assert.match(cronjobPlugin, /\/bridge\/cron/);
assert.match(cronjobPlugin, /"run"/);
assert.match(cronjobPlugin, /HERMES_MOBILE_BRIDGE_HOST_KEY_PATH/);
assert.match(cronjobPlugin, /_tool_defs_cache\.clear\(\)/);
assert.doesNotMatch(cronjobPlugin, /print\(.*key/i);

console.log("startup scripts tests passed");
