"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const repoRoot = path.resolve(__dirname, "..");

function read(relativePath) {
  return fs.readFileSync(path.join(repoRoot, relativePath), "utf8");
}

const startHermesWeb = read("start-hermes-web.ps1");
const server = read("mobile-server-runtime.js");
const mobileRuntimeEnvironmentService = read(path.join("adapters", "mobile-runtime-environment-service.js"));
const startWorkerHost = read(path.join("scripts", "start-worker-host.ps1"));
const startGatewayPool = read(path.join("scripts", "start-gateway-pool.ps1"));
const runAsWorker = read(path.join("scripts", "run-as-worker.ps1"));
const startLowGatewaysChild = read(path.join("scripts", "start-low-gateways-child.ps1"));
const startLowGatewaysShell = read(path.join("scripts", "start-low-gateways.sh"));
const provisionWorkerExternalConnectors = read(path.join("scripts", "provision-worker-external-connectors.ps1"));
const repairWorkspaceAcl = read(path.join("scripts", "repair-workspace-acl.ps1"));
const runKanbanGatewayWorker = read(path.join("scripts", "run-kanban-gateway-worker.ps1"));
const runKanbanGatewayWorkerChild = read(path.join("scripts", "run-kanban-gateway-worker-child.ps1"));
const runKanbanGatewayWorkerShell = read(path.join("scripts", "run-kanban-gateway-worker.sh"));
const startCronTickSidecar = read(path.join("scripts", "start-cron-tick-sidecar.ps1"));
const runCronTickSidecar = read(path.join("scripts", "run-cron-tick-sidecar.ps1"));
const hermesMobileCronDispatcher = read(path.join("scripts", "hermes-mobile-cron-dispatcher.py"));
const bridgeHost = read(path.join("scripts", "bridge-host.js"));
const startWeixinFrontGateway = read(path.join("scripts", "start-weixin-front-gateway.ps1"));
const startWeixinMobileIngressBridge = read(path.join("scripts", "start-weixin-mobile-ingress-bridge.ps1"));
const weixinMobileIngressBridge = read(path.join("scripts", "weixin-mobile-ingress-bridge.py"));
const outlookGraphMcp = read(path.join("scripts", "python", "outlook_graph_mcp.py"));
const configureLowGateways = read(path.join("scripts", "configure-low-gateways.sh"));
const checkWorkerCodexAuth = read(path.join("scripts", "check-worker-codex-auth.ps1"));
const gatewayToolSchemaSmoke = read(path.join("scripts", "gateway-tool-schema-smoke.js"));
const transcribeReadingAudio = read(path.join("scripts", "transcribe-reading-audio.ps1"));
const weatherPluginManifest = read(path.join("gateway-plugins", "hermes-mobile-weather", "plugin.yaml"));
const weatherPlugin = read(path.join("gateway-plugins", "hermes-mobile-weather", "__init__.py"));
const webPluginManifest = read(path.join("gateway-plugins", "hermes-mobile-web", "plugin.yaml"));
const webPlugin = read(path.join("gateway-plugins", "hermes-mobile-web", "__init__.py"));
const httpPluginManifest = read(path.join("gateway-plugins", "hermes-mobile-http", "plugin.yaml"));
const httpPlugin = read(path.join("gateway-plugins", "hermes-mobile-http", "__init__.py"));
const docxPluginManifest = read(path.join("gateway-plugins", "hermes-mobile-docx", "plugin.yaml"));
const docxPlugin = read(path.join("gateway-plugins", "hermes-mobile-docx", "__init__.py"));
const audioPluginManifest = read(path.join("gateway-plugins", "hermes-mobile-audio", "plugin.yaml"));
const audioPlugin = read(path.join("gateway-plugins", "hermes-mobile-audio", "__init__.py"));
const imagePluginManifest = read(path.join("gateway-plugins", "hermes-mobile-image", "plugin.yaml"));
const imagePlugin = read(path.join("gateway-plugins", "hermes-mobile-image", "__init__.py"));
const videoPluginManifest = read(path.join("gateway-plugins", "hermes-mobile-video", "plugin.yaml"));
const videoPlugin = read(path.join("gateway-plugins", "hermes-mobile-video", "__init__.py"));
const cronjobPluginManifest = read(path.join("gateway-plugins", "hermes-mobile-cronjob", "plugin.yaml"));
const cronjobPlugin = read(path.join("gateway-plugins", "hermes-mobile-cronjob", "__init__.py"));

assert.match(startHermesWeb, /function Test-HermesWebHttpHealth/);
assert.match(startHermesWeb, /did not open a responsive Hermes Mobile HTTP endpoint/);
assert.match(startHermesWeb, /HTTP health failed/);
assert.match(startHermesWeb, /function Start-CronTickSidecarIfNeeded/);
assert.match(startHermesWeb, /HERMES_WEB_AUTOMATION_BACKEND/);
assert.match(startHermesWeb, /hermes_cron/);
assert.match(startHermesWeb, /start-cron-tick-sidecar\.ps1/);
assert.match(startHermesWeb, /HERMES_MOBILE_CRON_TICK_SIDECAR/);
assert.match(startHermesWeb, /Start-CronTickSidecarIfNeeded\s*\r?\n\s*\$existing = Get-HermesWebListener/s);

assert.match(startWorkerHost, /function Test-HermesMobileHttpHealth/);
assert.match(startWorkerHost, /function Test-HermesMobileAuthenticatedHealth/);
assert.match(startWorkerHost, /function Test-GatewayPoolPortHealth/);
assert.match(startWorkerHost, /X-Hermes-Web-Key/);
assert.match(startWorkerHost, /api\/client-version\?clientVersion=startup-health/);
assert.match(startWorkerHost, /Worker listener already running and authenticated API plus Gateway Pool ports are healthy/);
assert.match(startWorkerHost, /Restarting unhealthy worker listener/);
assert.match(startWorkerHost, /healthy authenticated API endpoint with ready Gateway Pool ports/);
assert.match(startWorkerHost, /MinGatewayPoolWorkers/);
assert.match(startWorkerHost, /GatewayPoolPorts/);
assert.match(startWorkerHost, /18762/);
assert.match(startWorkerHost, /WeixinFrontGateway/);
assert.match(startWorkerHost, /function Resolve-WeixinFrontGatewayMode/);
assert.match(startWorkerHost, /HERMES_MOBILE_WEIXIN_FRONT_GATEWAY/);
assert.match(startWorkerHost, /return "auto"/);
assert.match(startWorkerHost, /HERMES_MOBILE_WEIXIN_FRONT_GATEWAY_WSL_USER/);
assert.match(startWorkerHost, /HERMES_MOBILE_WEIXIN_FRONT_GATEWAY_HERMES_HOME/);
assert.match(startWorkerHost, /if \(-not \$resolvedWslUser\) \{ \$resolvedWslUser = "xuxin" \}/);
assert.match(startWorkerHost, /if \(-not \$resolvedHermesHome\) \{ \$resolvedHermesHome = "\/home\/\$resolvedWslUser\/\.hermes" \}/);
assert.match(startWorkerHost, /start-weixin-mobile-ingress-bridge\.ps1/);
assert.match(startWorkerHost, /function Start-WeixinFrontGatewayIfNeeded/);
assert.match(startWorkerHost, /CronTickSidecar/);
assert.match(startWorkerHost, /function Start-CronTickSidecarInCallerContextIfNeeded/);
assert.match(startWorkerHost, /start-cron-tick-sidecar\.ps1/);
assert.match(startWorkerHost, /HERMES_MOBILE_CRON_TICK_WSL_USER/);
assert.match(startWorkerHost, /if \(-not \$resolvedWslUser\) \{ \$resolvedWslUser = "xuxin" \}/);
assert.match(startWorkerHost, /if \(\$ReplaceExisting\) \{ \$args \+= "-ReplaceExisting" \}/);
assert.match(startWorkerHost, /Start-WeixinFrontGatewayIfNeeded\s*\r?\nif \(-not \$CheckOnly\) \{\s*\r?\n\s*Start-CronTickSidecarInCallerContextIfNeeded/s);
assert.match(startWorkerHost, /Start-CronTickSidecarInCallerContextIfNeeded\s*\r?\n\}\s*\r?\nif \(-not \$CheckOnly\)/);

assert.match(mobileRuntimeEnvironmentService, /HERMES_MOBILE_WEB_PUSH_START_DELAY_MS/);
assert.match(mobileRuntimeEnvironmentService, /HERMES_WEB_TODO_PUSH_START_DELAY_MS/);
assert.match(mobileRuntimeEnvironmentService, /HERMES_WEB_AUTOMATION_PUSH_START_DELAY_MS/);
assert.match(mobileRuntimeEnvironmentService, /120000/);
assert.match(fs.readFileSync("adapters/web-push-delivery-service.js", "utf8"), /function scheduleBackgroundWebPushDispatcher/);
assert.doesNotMatch(server, /setTimeout\(tick, 8000\)/);
assert.doesNotMatch(server, /setTimeout\(tick, 12000\)/);

assert.match(startGatewayPool, /function Start-LowGateways/);
assert.match(startGatewayPool, /function Check-LowGatewayCodexAuth/);
assert.match(startGatewayPool, /function Provision-OwnerExternalConnectors/);
assert.match(startGatewayPool, /function Start-OwnerMaintenanceGateways/);
assert.match(startGatewayPool, /\[switch\]\$OwnerMaintenanceOnly/);
assert.match(startGatewayPool, /\[switch\]\$OnlyWhenOwnerMaintenanceUnhealthy/);
assert.match(startGatewayPool, /\[int\]\$OwnerMaintenanceBusyGraceMinutes = 45/);
assert.match(startGatewayPool, /function Test-TcpPortOpen/);
assert.match(startGatewayPool, /function Select-OwnerMaintenanceWorkersNeedingRepair/);
assert.match(startGatewayPool, /owner-maintenance-watchdog-state\.json/);
assert.match(startGatewayPool, /HTTP health failed but TCP port \$port is open, likely busy with a long tool call/);
assert.match(startGatewayPool, /Select-OwnerMaintenanceWorkersNeedingRepair -Workers \$workers/);
assert.match(startGatewayPool, /function Repair-OwnerMaintenanceGateways/);
assert.match(startGatewayPool, /Owner-maintenance repair skipped; all owner-maintenance ports are healthy/);
assert.match(startGatewayPool, /if \(\$OwnerMaintenanceOnly\)/);
assert.match(startGatewayPool, /Repair-OwnerMaintenanceGateways/);
assert.match(startGatewayPool, /wait-owner-maintenance-health/);
assert.match(startGatewayPool, /function Resolve-ConnectorPath/);
assert.match(startGatewayPool, /function Ensure-LowGatewayProfileEnv/);
assert.match(startGatewayPool, /function Stop-LowGateways/);
assert.match(startGatewayPool, /function Add-OwnerMaintenanceSharedMemoryCommands/);
assert.match(startGatewayPool, /stop-low-gateways\.sh/);
assert.match(startGatewayPool, /pkill -u hermes -f 'hermes_cli\\\.main \.\*gateway run'/);
assert.match(startGatewayPool, /Stopping legacy official-distro low gateway processes before pool start/);
assert.match(startGatewayPool, /stop-legacy-official-low-gateways\.sh/);
assert.match(startGatewayPool, /Invoke-GatewayPoolWslBashFile -Distro \$OfficialDistro -User "root" -ScriptPath \$legacyStopShell/);
assert.match(startGatewayPool, /legacy-lowgw-stop:/);
assert.match(startGatewayPool, /Stop-LowGateways\s*\r?\n\s*Write-GatewayPoolLog "Starting low gateway pool\."/);
assert.match(startGatewayPool, /provision-worker-external-connectors\.ps1/);
assert.match(startGatewayPool, /HERMES_WEB_GOOGLE_TOKEN_PATH/);
assert.match(startGatewayPool, /HERMES_GOOGLE_PROFILE_HOME/);
assert.match(startGatewayPool, /runtime_bin="\$\{HERMES_GATEWAY_RUNTIME_BIN:-\$runtime_root\/bin\}"/);
assert.match(startGatewayPool, /cat > "\$runtime_bin\/hermes"/);
assert.match(startGatewayPool, /runtime_hermes="\$runtime_bin\/hermes"/);
assert.match(startGatewayPool, /HERMES_HOME="\$worker_home_dir\/profiles\/\$profile"/);
assert.match(startGatewayPool, /"\$runtime_hermes" gateway run/);
assert.match(startGatewayPool, /\$1 < \/dev\/null/);
assert.match(startGatewayPool, /PATH="\$low_gateway_path"/);
assert.match(startGatewayPool, /google_token\.json/);
assert.match(startGatewayPool, /google_client_secret\.json/);
assert.match(startGatewayPool, /microsoft-graph-outlook-mail\\token\.json/);
assert.match(startGatewayPool, /HERMES_WEB_OUTLOOK_GRAPH_ENV_PATH/);
assert.match(startGatewayPool, /outlook_graph_mcp\.py/);
assert.match(startGatewayPool, /-OutlookGraphEnvPath/);
assert.match(startGatewayPool, /-OutlookGraphMcpPath/);
assert.match(startGatewayPool, /configure-low-gateways\.sh/);
assert.match(startGatewayPool, /Invoke-GatewayPoolPhase -Name "provision-owner-external-connectors"/);
assert.match(startGatewayPool, /Invoke-GatewayPoolPhase -Name "start-low-gateways"/);
assert.match(startGatewayPool, /HERMES_LOW_GATEWAY_REQUIRE_UNIQUE_CODEX_AUTH/);
assert.match(startGatewayPool, /check-worker-codex-auth\.ps1/);
assert.match(startGatewayPool, /codex-auth:/);
assert.match(startGatewayPool, /Invoke-GatewayPoolPhase -Name "check-low-gateway-codex-auth"/);
assert.match(startGatewayPool, /function Install-OwnerMaintenanceChatGptProPlugin/);
assert.match(startGatewayPool, /function Ensure-ProfileToolsetEnabled/);
assert.match(startGatewayPool, /hermes-mobile-chatgpt-pro/);
assert.match(startGatewayPool, /Ensure-ProfilePluginEnabled -ConfigPath \$configPath -PluginName \$pluginName/);
assert.match(startGatewayPool, /Ensure-ProfileToolsetEnabled -ConfigPath \$configPath -ToolsetName "chatgpt_pro"/);
assert.match(startGatewayPool, /profiles\\\$profile\\plugins/);
assert.match(startGatewayPool, /Copy-Item -LiteralPath \$source -Destination \$profilePluginTarget -Recurse -Force/);
assert.match(startGatewayPool, /Invoke-GatewayPoolPhase -Name "install-owner-maintenance-chatgpt-pro-plugin"/);
assert.match(startGatewayPool, /Invoke-GatewayPoolPhase -Name "start-owner-maintenance-gateways"/);
assert.match(startGatewayPool, /\$env:API_SERVER_KEY = \$apiKey/);
assert.match(startGatewayPool, /\$env:WSLENV = "API_SERVER_KEY\/u"/);
assert.match(startGatewayPool, /start-owner-maintenance-gateways\.sh/);
assert.match(startGatewayPool, /Invoke-GatewayPoolWslBashFile -Distro \$OfficialDistro -User \$OfficialUser -ScriptPath \$ownerMaintenanceStartShell/);
assert.match(startGatewayPool, /PYTHONPATH=\$officialCleanRoot/);
assert.match(startGatewayPool, /HERMES_HOME=\$profileRoot/);
assert.match(startGatewayPool, /HERMES_PROFILE=\$profile/);
assert.match(startGatewayPool, /\$officialPython -m hermes_cli\.main gateway run --replace/);
assert.match(startGatewayPool, /ln -sfn \$sharedAuthPath/);
assert.match(startGatewayPool, /function Assert-SafeGatewayProfileName/);
assert.match(startGatewayPool, /\^\[A-Za-z0-9\]\[A-Za-z0-9_-\]\*\$/);
assert.match(startGatewayPool, /function Assert-SafeLinuxUserName/);
assert.match(startGatewayPool, /function Is-OwnerMaintenanceWorker/);
assert.match(startGatewayPool, /securityLevel -ne "owner-maintenance"/);
assert.match(startGatewayPool, /\^officialclean\[0-9\]\+\$/);
assert.doesNotMatch(startGatewayPool, /profile -match '\^officialclean[12]\$'/);
assert.match(startGatewayPool, /HERMES_MOBILE_OWNER_MAINTENANCE_SHARED_MEMORY_MODE/);
assert.match(startGatewayPool, /HERMES_WEB_OWNER_MAINTENANCE_SHARED_MEMORY_MODE/);
assert.match(startGatewayPool, /if \(-not \$value\) \{ return \$true \}/);
assert.match(startGatewayPool, /\$value = \$value\.Trim\(\)/);
assert.match(startGatewayPool, /\^\(0\|false\|no\|off\|profile-local\)\$/);
assert.match(startGatewayPool, /\$sharedMemoryPath = "\/home\/\$OfficialUser\/\.hermes\/memories"/);
assert.match(startGatewayPool, /hermes-mobile-owner-maintenance-memory\.lock/);
assert.match(startGatewayPool, /flock -w 60 9/);
assert.match(startGatewayPool, /owner_maintenance_memory_lock_timeout/);
assert.doesNotMatch(startGatewayPool, /while ! mkdir \$ownerMaintenanceLockDir/);
assert.match(startGatewayPool, /Add-OwnerMaintenanceSharedMemoryCommands -Commands \$commands -ProfileRoot \$profileRoot -ProfileMemoryPath \$profileMemoryPath -SharedMemoryPath \$sharedMemoryPath/);
assert.match(startGatewayPool, /ln -sfn \$SharedMemoryPath \$ProfileMemoryPath/);
assert.match(startGatewayPool, /\$backupDir = "\{0\}\/memories\.profile-local-markdown-backup-\{1\}"/);
assert.match(startGatewayPool, /Get-Date\)\.ToString\("yyyyMMddHHmmss"\)/);
assert.match(startGatewayPool, /find \$ProfileMemoryPath -maxdepth 1 -type f -name \\\*\.md/);
assert.match(startGatewayPool, /find \$ProfileMemoryPath -maxdepth 1 -type f -name \\\*\.md\.lock -size 0 -delete/);
assert.match(startGatewayPool, /-exec cp -n \{\} \$SharedMemoryPath\/ \\\;/);
assert.match(startGatewayPool, /-exec cp -n \{\} \$backupDir\/ \\\;/);
assert.match(startGatewayPool, /-delete/);
assert.match(startGatewayPool, /if \[ ! -e \$ProfileMemoryPath \]; then ln -sfn \$SharedMemoryPath \$ProfileMemoryPath; fi/);
assert.match(startGatewayPool, /profile_memories_contains_non_markdown_files_keeping_profile_local_directory/);
assert.doesNotMatch(startGatewayPool, /profile-local-backup/);
assert.doesNotMatch(startGatewayPool, /mv \$profileMemoryPath/);
assert.doesNotMatch(startGatewayPool, /find .*state\.db/);
assert.doesNotMatch(startGatewayPool, /find .*response_store/);
assert.doesNotMatch(startGatewayPool, /find .*config\.yaml/);
assert.doesNotMatch(startGatewayPool, /ln -sfn .*state\.db/);
assert.doesNotMatch(startGatewayPool, /ln -sfn .*response_store\.db/);
assert.doesNotMatch(startGatewayPool, /ln -sfn .*config\.yaml/);
assert.doesNotMatch(startGatewayPool, /ln -sfn .*\/home\/\$OfficialUser\/\.hermes\/profiles\/\$profile(?!\/)/);
assert.doesNotMatch(startGatewayPool, /\/home\/\$OfficialUser\/\.local\/bin\/hermes/);
assert.match(startGatewayPool, /Gateway pool startup OK; healthy ports/);
assert.doesNotMatch(startGatewayPool, /Write-GatewayPoolLog .*apiKey/i);
assert.doesNotMatch(startGatewayPool, /bash\s+-lc/);

assert.match(runAsWorker, /\[Parameter\(Mandatory = \$true\)\]/);
assert.match(runAsWorker, /worker-credential\.xml/);
assert.match(runAsWorker, /Import-Clixml/);
assert.match(runAsWorker, /ProcessStartInfo/);
assert.match(runAsWorker, /\$psi\.LoadUserProfile = \$true/);
assert.match(runAsWorker, /worker_exit=/);
assert.doesNotMatch(runAsWorker, /Write-Host .*Password/i);

assert.match(startLowGatewaysChild, /HERMES_LOW_GATEWAY_DISTRO_NAME/);
assert.match(startLowGatewaysChild, /Ubuntu-24\.04/);
assert.match(startLowGatewaysChild, /start-low-gateways\.sh/);
assert.match(startLowGatewaysChild, /wsl\.exe -d \$distroName -u root/);

assert.match(startLowGatewaysShell, /configure-low-gateways\.sh/);
assert.match(startLowGatewaysShell, /HERMES_GATEWAY_RUNTIME_ROOT/);
assert.match(startLowGatewaysShell, /HERMES_GROK_GATEWAY_COUNT/);
assert.match(startLowGatewaysShell, /log_step\(\)/);
assert.match(startLowGatewaysShell, /lowgw-configure-start/);
assert.match(startLowGatewaysShell, /lowgw-start-profile-start profile=\$\{profile\} port=\$\{port\}/);
assert.match(startLowGatewaysShell, /lowgw-wait-health-done port=\$\{port\}/);
assert.match(startLowGatewaysShell, /HERMES_MOBILE_BRIDGE_HOST_URL/);
assert.match(startLowGatewaysShell, /HERMES_MOBILE_BRIDGE_HOST_KEY_PATH/);
assert.match(startLowGatewaysShell, /HERMES_WEB_BRIDGE_HOST_URL/);
assert.match(startLowGatewaysShell, /HERMES_WEB_BRIDGE_HOST_KEY_PATH/);
assert.match(startLowGatewaysShell, /detect_windows_host_gateway\(\)/);
assert.match(startLowGatewaysShell, /default_mobile_bridge_host_url="http:\/\/\$\{windows_host_gateway\}:8798"/);
assert.match(startLowGatewaysShell, /manifest_gateway_specs\(\)/);
assert.match(startLowGatewaysShell, /gateway_specs="\$\(manifest_gateway_specs\)"/);
assert.match(startLowGatewaysShell, /grok_gateway_port="\$\(printf '%s\\n' "\$gateway_specs"/);
assert.match(startLowGatewaysShell, /HERMES_GATEWAY_RUNTIME_BIN/);
assert.match(startLowGatewaysShell, /runtime_hermes="\$runtime_bin\/hermes"/);
assert.match(startLowGatewaysShell, /HERMES_HOME="\$worker_home_dir\/profiles\/\$profile"/);
assert.match(startLowGatewaysShell, /"\$runtime_hermes" gateway run --replace --accept-hooks/);
assert.doesNotMatch(startLowGatewaysShell, /"\$runtime_hermes" -p "\$profile" gateway run/);
assert.match(startLowGatewaysShell, /pgrep -u "\$worker_user" -f "hermes_cli\.main \.\*gateway run --replace --accept-hooks" \| tail -1/);
assert.match(startLowGatewaysShell, /> "\$log" 2>&1 < \/dev\/null/);
assert.doesNotMatch(startLowGatewaysShell, /"\$runtime_python" -m hermes_cli\.main -p "\$profile" gateway run/);
assert.match(startLowGatewaysShell, /HERMES_PROFILE="\$profile"/);
assert.match(startLowGatewaysShell, /HERMES_GOOGLE_PROFILE_HOME/);
assert.match(startLowGatewaysShell, /PATH="\$low_gateway_path"/);
assert.match(startLowGatewaysShell, /API_SERVER_KEY="\$api_key"/);
assert.match(startLowGatewaysShell, /LOW_GATEWAYS_STARTED/);
assert.match(startLowGatewaysShell, /start_gateway_profile "\$profile" "\$port"/);
assert.doesNotMatch(startLowGatewaysShell, /start_gateway_profile "grokgw\$\{idx\}"/);
assert.match(startLowGatewaysShell, /verify_gateway_profile\(\)/);
assert.match(startLowGatewaysShell, /repair_gateway_profile_link\(\)/);
assert.match(startLowGatewaysShell, /stop_gateway_port\(\)/);
assert.match(startLowGatewaysShell, /ss -ltnp "sport = :\$\{port\}"/);
assert.match(startLowGatewaysShell, /kill -9 \$pids/);
assert.match(startGatewayPool, /Invoke-GatewayPoolPhase/);
assert.match(startGatewayPool, /phase-start \{0\}/);
assert.match(startGatewayPool, /phase-done \{0\} elapsedMs=\{1\}/);
assert.match(startGatewayPool, /Assert-SafeWslDistroName/);
assert.match(startGatewayPool, /\$distroName = "\$LowGatewayDistroName"/);
assert.doesNotMatch(startGatewayPool, /wsl\.exe -d HermesGatewayWorker -u root -- bash \/mnt\/c\/ProgramData\/HermesMobile\/gateway-worker\/stop-low-gateways\.sh/);

assert.match(startWorkerHost, /\$env:HERMES_MOBILE_BRIDGE_HOST = "0\.0\.0\.0"/);
assert.match(startLowGatewaysShell, /profile_link="\$worker_home_dir\/profiles\/\$profile"/);
assert.match(startLowGatewaysShell, /expected_target="\$gateway_worker_root\/telemetry\/profiles\/\$profile"/);
assert.match(startLowGatewaysShell, /profile-directory-backups/);
assert.match(startLowGatewaysShell, /start-repair/);
assert.match(startLowGatewaysShell, /low gateway profile is not a symlink/);
assert.match(startLowGatewaysShell, /missing shared auth link for low gateway profile/);
assert.match(startLowGatewaysShell, /missing shared auth lock link for low gateway profile/);
assert.doesNotMatch(startLowGatewaysShell, /xuxin/);

assert.match(configureLowGateways, /HERMES_MOBILE_OWNER_CONNECTOR_PROFILES/);
assert.match(configureLowGateways, /HERMES_GROK_GATEWAY_COUNT/);
assert.match(configureLowGateways, /manifest_gateway_specs\(\)/);
assert.match(configureLowGateways, /gateway_specs="\$\(manifest_gateway_specs\)"/);
assert.match(configureLowGateways, /done <<< "\$gateway_specs"/);
assert.match(configureLowGateways, /HERMES_MOBILE_OUTLOOK_GRAPH_MCP_PATH/);
assert.match(configureLowGateways, /HERMES_MOBILE_OWNER_SKILL_STORE/);
assert.match(configureLowGateways, /is_owner_connector_profile/);
assert.match(configureLowGateways, /ensure_low_gateway_skill_link\(\)/);
assert.match(configureLowGateways, /ln -s "\$owner_skill_store" "\$skill_dir"/);
assert.match(configureLowGateways, /ensure_low_gateway_skill_link "\$profile_dir\/skills"/);
assert.match(configureLowGateways, /outlook_graph:/);
assert.match(configureLowGateways, /HERMES_HOME: \$profile_link/);
assert.match(configureLowGateways, /platform_toolsets:[\s\S]*api_server:[\s\S]*\$\{outlook_api_toolset_block\}/);
assert.match(configureLowGateways, /prepare_low_gateway_profile_link\(\)/);
assert.match(configureLowGateways, /profile-directory-backups/);
assert.match(configureLowGateways, /moving real low Gateway profile directory/);
assert.match(configureLowGateways, /prepare_low_gateway_profile_link "\$profile" "\$profile_link"/);
assert.doesNotMatch(configureLowGateways, /rm -rf "\$profile_link"/);

assert.match(provisionWorkerExternalConnectors, /external-connectors\/owner/);
assert.match(provisionWorkerExternalConnectors, /google_token\.json/);
assert.match(provisionWorkerExternalConnectors, /microsoft-graph-outlook-mail\/token\.json/);
assert.match(provisionWorkerExternalConnectors, /Copy-FilteredOutlookEnvFile/);
assert.match(provisionWorkerExternalConnectors, /outlook_graph\.env/);
assert.match(provisionWorkerExternalConnectors, /outlook_graph_mcp\.py/);
assert.match(provisionWorkerExternalConnectors, /MS_GRAPH_CLIENT_ID/);
assert.match(provisionWorkerExternalConnectors, /patch_google_workspace_skill\(\)/);
assert.match(provisionWorkerExternalConnectors, /HERMES_GOOGLE_RUNTIME_REEXEC/);
assert.match(provisionWorkerExternalConnectors, /profiles.*<profile>.*skills/s);
assert.match(provisionWorkerExternalConnectors, /HERMES_GOOGLE_PROFILE_HOME="\`\$profile_dir" python3 "\`\$google_setup" --check/);
assert.match(provisionWorkerExternalConnectors, /google_workspace_setup_check=ok/);
assert.match(provisionWorkerExternalConnectors, /\[owner-secret-root\]/);
assert.doesNotMatch(provisionWorkerExternalConnectors, /Get-Content\s+-Raw\s+\$GoogleTokenPath/i);
assert.doesNotMatch(provisionWorkerExternalConnectors, /Write-Host .*token/i);

assert.match(outlookGraphMcp, /FastMCP\("OutlookGraph"/);
assert.match(outlookGraphMcp, /microsoft-graph-outlook-mail/);
assert.match(outlookGraphMcp, /MS_GRAPH_CLIENT_ID/);
assert.doesNotMatch(outlookGraphMcp, /client_secret\s*=\s*["'][^"']+["']/i);

assert.match(repairWorkspaceAcl, /\[string\]\$WorkspaceRoot/);
assert.match(repairWorkspaceAcl, /HermesMobileWorker/);
assert.match(repairWorkspaceAcl, /\[switch\]\$CheckOnly/);
assert.match(repairWorkspaceAcl, /icacls \$root \/grant \$grant/);
assert.match(repairWorkspaceAcl, /missingWorkerRead/);

assert.match(runKanbanGatewayWorker, /ValueFromRemainingArguments/);
assert.match(runKanbanGatewayWorker, /PositionalBinding\s*=\s*\$false/);
assert.match(runKanbanGatewayWorker, /HermesGatewayWorker/);
assert.match(runKanbanGatewayWorker, /run-as-worker\.ps1/);
assert.match(runKanbanGatewayWorker, /PayloadBase64/);
assert.match(runKanbanGatewayWorker, /kanbanArgs = \$KanbanArgs/);
assert.match(runKanbanGatewayWorker, /kanban-runner/);
assert.match(runKanbanGatewayWorker, /\[string\]\$WorkerUserName = "HermesMobileWorker"/);
assert.match(runKanbanGatewayWorker, /function Current-UserName/);
assert.match(runKanbanGatewayWorker, /Current-UserName\) -ieq \$WorkerUserName/);
assert.match(runKanbanGatewayWorker, /Copy-Item -LiteralPath \$sourceShellScript/);
assert.match(runKanbanGatewayWorker, /run-kanban-gateway-worker-child-\$stamp\.ps1/);
assert.match(runKanbanGatewayWorker, /run-kanban-gateway-worker-\$stamp\.sh/);
assert.match(runKanbanGatewayWorker, /run-kanban-command-\$stamp\.ps1/);
assert.match(runKanbanGatewayWorker, /Remove-Item -LiteralPath \$childScript/);
assert.match(runKanbanGatewayWorker, /Remove-Item -LiteralPath \$shellScript/);
assert.doesNotMatch(runKanbanGatewayWorker, /-ChildArgs/);

assert.match(runKanbanGatewayWorkerChild, /Convert-ToWslPath/);
assert.match(runKanbanGatewayWorkerChild, /wsl\.exe -d \$distroName -u root/);
assert.match(runKanbanGatewayWorkerChild, /PayloadBase64/);

assert.match(runKanbanGatewayWorkerShell, /runuser/);
assert.match(runKanbanGatewayWorkerShell, /-u",\s*"hermes"/);
assert.match(runKanbanGatewayWorkerShell, /runtime_bin="\$\{HERMES_GATEWAY_RUNTIME_BIN:-\$runtime_root\/bin\}"/);
assert.match(runKanbanGatewayWorkerShell, /hermes_shim="\$runtime_bin\/hermes"/);
assert.match(runKanbanGatewayWorkerShell, /exec "\$runtime_python" -m hermes_cli\.main "\\\$@"/);
assert.match(runKanbanGatewayWorkerShell, /PYTHONPATH=\{runtime_source\}/);
assert.match(runKanbanGatewayWorkerShell, /PATH=\{runtime_bin\}:\{runtime_root\}\/venv\/bin:\/usr\/local\/bin:\/usr\/bin:\/bin/);
assert.match(runKanbanGatewayWorkerShell, /hermes_cli\.main/);
assert.match(runKanbanGatewayWorkerShell, /kanban_args/);
assert.match(runKanbanGatewayWorkerShell, /capture_output=True/);
assert.match(runKanbanGatewayWorkerShell, /ensure_ascii=True/);

assert.match(startCronTickSidecar, /function Get-CronTickSidecarProcess/);
assert.match(startCronTickSidecar, /function Invoke-CronStatusCheck/);
assert.match(startCronTickSidecar, /cron", "status"/);
assert.match(startCronTickSidecar, /Start-Process/);
assert.match(startCronTickSidecar, /run-cron-tick-sidecar\.ps1/);
assert.match(startCronTickSidecar, /HERMES_WEB_HERMES_HOME/);
assert.match(startCronTickSidecar, /HERMES_MOBILE_CRON_TICK_LOG_PATH/);
assert.match(startCronTickSidecar, /HERMES_MOBILE_CRON_DISPATCH_TIMEOUT_SECONDS/);
assert.match(startCronTickSidecar, /DispatchTimeoutSeconds/);
assert.match(startCronTickSidecar, /hermes-mobile-cron-dispatcher\.py/);
assert.match(startCronTickSidecar, /DispatcherScript/);

assert.match(runCronTickSidecar, /hermes-mobile-cron-dispatcher\.py/);
assert.match(runCronTickSidecar, /--dispatch/);
assert.match(runCronTickSidecar, /\/mnt\/\$drive\/\$tail/);
assert.match(runCronTickSidecar, /HERMES_ACCEPT_HOOKS=1/);
assert.match(runCronTickSidecar, /HERMES_HOME=\$HermesHome/);
assert.match(runCronTickSidecar, /PYTHONPATH=\$pythonPath/);
assert.match(runCronTickSidecar, /WaitForExit\(\$DispatchTimeoutSeconds \* 1000\)/);
assert.match(runCronTickSidecar, /Stop-Process -Id \$process\.Id -Force/);
assert.match(runCronTickSidecar, /exitCode = 124/);
assert.match(runCronTickSidecar, /\$process\.Refresh\(\)/);
assert.match(runCronTickSidecar, /timed_out=\$timedOut/);
assert.doesNotMatch(runCronTickSidecar, /TickTimeoutSeconds/);
assert.doesNotMatch(startCronTickSidecar, /TickTimeoutSeconds/);
assert.match(runCronTickSidecar, /Select-Object -Last \$maxLines/);
assert.doesNotMatch(runCronTickSidecar, /cron", "tick"/);
assert.doesNotMatch(runCronTickSidecar, /gateway", "run"/);

assert.match(hermesMobileCronDispatcher, /def dispatch_due_jobs/);
assert.match(hermesMobileCronDispatcher, /def _cron_child_env/);
assert.match(hermesMobileCronDispatcher, /def _default_windows_host_gateway/);
assert.match(hermesMobileCronDispatcher, /def _runner_tool_failure_summary/);
assert.match(hermesMobileCronDispatcher, /HERMES_MOBILE_X_SEARCH_PROXY_URL/);
assert.match(hermesMobileCronDispatcher, /existing_proxy/);
assert.match(hermesMobileCronDispatcher, /HERMES_MOBILE_CRON_RUNNER_LOG_PATH/);
assert.match(hermesMobileCronDispatcher, /\/bridge\/grok-gateway-proxy/);
assert.match(hermesMobileCronDispatcher, /Tool x_search returned error/);
assert.match(hermesMobileCronDispatcher, /subprocess\.Popen/);
assert.match(hermesMobileCronDispatcher, /start_new_session=True/);
assert.match(hermesMobileCronDispatcher, /advance_next_run\(job_id\)/);
assert.match(hermesMobileCronDispatcher, /def run_one_job/);
assert.match(hermesMobileCronDispatcher, /run_job\(job\)/);
assert.match(hermesMobileCronDispatcher, /mark_job_run\(job_id/);
assert.match(hermesMobileCronDispatcher, /save_job_output\(job_id/);
assert.doesNotMatch(hermesMobileCronDispatcher, /cron tick/);

assert.match(bridgeHost, /\/bridge\/grok-gateway-proxy\/v1\/responses/);
assert.match(bridgeHost, /HERMES_MOBILE_GROK_GATEWAY_URL/);
assert.match(bridgeHost, /function grokGatewayUrlFromManifest/);
assert.match(bridgeHost, /gateway-pool-manifest\.json/);
assert.match(bridgeHost, /xai-oauth/);
assert.match(bridgeHost, /new URL\("\/v1\/responses"/);
assert.match(bridgeHost, /gateway_api_key_required/);
assert.match(bridgeHost, /grok_gateway_proxy_failed/);

assert.match(startWeixinFrontGateway, /HERMES_MOBILE_WEIXIN_FRONT_GATEWAY/);
assert.match(startWeixinFrontGateway, /gateway_state\.json/);
assert.match(startWeixinFrontGateway, /hermes_cli\.main gateway run --replace/);
assert.match(startWeixinFrontGateway, /HERMES_PROFILE/);
assert.match(startWeixinFrontGateway, /\/\.hermes\/profiles\//);
assert.match(startWeixinFrontGateway, /weixin/);
assert.match(startWeixinFrontGateway, /api_server/);
assert.match(startWeixinFrontGateway, /ensure-weixin-reminder-dispatcher\.sh/);
assert.match(startWeixinFrontGateway, /ensure-weixin-todo-dispatcher\.sh/);
assert.match(startWeixinFrontGateway, /ensure-weixin-delivery-queue-dispatcher\.sh/);
assert.match(startWeixinFrontGateway, /WEIXIN_FRONT_GATEWAY_OK/);
assert.doesNotMatch(startWeixinFrontGateway, /Hermes Gateway WSL/);
assert.match(startWeixinFrontGateway, /wslpath -a \$portableTmpScript/);
assert.doesNotMatch(startWeixinFrontGateway, /bash\s+-lc/);

assert.match(startWeixinMobileIngressBridge, /weixin-mobile-ingress-bridge\.py/);
assert.match(startWeixinMobileIngressBridge, /HERMES_MOBILE_WEIXIN_INGRESS_KEY_FILE/);
assert.match(startWeixinMobileIngressBridge, /legacy_gateway_pid/);
assert.match(startWeixinMobileIngressBridge, /stop_legacy_gateway/);
assert.match(startWeixinMobileIngressBridge, /HERMES_PROFILE/);
assert.match(startWeixinMobileIngressBridge, /\/\.hermes\/profiles\//);
assert.match(startWeixinMobileIngressBridge, /WEIXIN_MOBILE_INGRESS_BRIDGE_OK/);
assert.match(startWeixinMobileIngressBridge, /ensure-weixin-reminder-dispatcher\.sh/);
assert.match(startWeixinMobileIngressBridge, /ensure-weixin-todo-dispatcher\.sh/);
assert.match(startWeixinMobileIngressBridge, /ensure-weixin-delivery-queue-dispatcher\.sh/);
assert.doesNotMatch(startWeixinMobileIngressBridge, /hermes_cli\.main gateway run --replace/);
assert.match(startWeixinMobileIngressBridge, /wslpath -a \$portableTmpScript/);
assert.doesNotMatch(startWeixinMobileIngressBridge, /bash\s+-lc/);
assert.match(weixinMobileIngressBridge, /class MobileIngressBridge/);
assert.match(weixinMobileIngressBridge, /class MobileIngressWeixinAdapter/);
assert.match(weixinMobileIngressBridge, /post_inbound_event/);
assert.match(weixinMobileIngressBridge, /\/api\/ingress\/weixin\/events/);
assert.match(weixinMobileIngressBridge, /\/api\/ingress\/weixin\/outbound/);
assert.match(weixinMobileIngressBridge, /inbound post ignored unmatched route/);
assert.doesNotMatch(weixinMobileIngressBridge, /入口暂不可用|Gateway 处理/);
assert.match(weixinMobileIngressBridge, /workspace_id="owner" if principal_id == "owner" else principal_id/);
assert.doesNotMatch(weixinMobileIngressBridge, /gateway run --replace/);

assert.match(configureLowGateways, /profile_auth_seed_root/);
assert.match(configureLowGateways, /profile_seed="\$profile_auth_seed_root\/\$\{profile\}\/auth\.json"/);
assert.match(configureLowGateways, /shared_auth_mode/);
assert.match(configureLowGateways, /shared_auth_path/);
assert.match(configureLowGateways, /shared_auth_default_root/);
assert.match(configureLowGateways, /telemetry_profiles_root\/shared-auth/);
assert.match(configureLowGateways, /legacy_shared_auth_path/);
assert.match(configureLowGateways, /HERMES_LOW_GATEWAY_SHARED_AUTH_SOURCE_PROFILE/);
assert.match(configureLowGateways, /HERMES_MOBILE_WEATHER_PLUGIN_SOURCE/);
assert.match(configureLowGateways, /HERMES_MOBILE_WEB_PLUGIN_SOURCE/);
assert.match(configureLowGateways, /HERMES_MOBILE_HTTP_PLUGIN_SOURCE/);
assert.match(configureLowGateways, /HERMES_MOBILE_DOCX_PLUGIN_SOURCE/);
assert.match(configureLowGateways, /HERMES_MOBILE_AUDIO_PLUGIN_SOURCE/);
assert.match(configureLowGateways, /HERMES_MOBILE_IMAGE_PLUGIN_SOURCE/);
assert.match(configureLowGateways, /HERMES_MOBILE_VIDEO_PLUGIN_SOURCE/);
assert.match(configureLowGateways, /HERMES_MOBILE_CRONJOB_PLUGIN_SOURCE/);
assert.match(configureLowGateways, /gateway-plugins\/hermes-mobile-weather/);
assert.match(configureLowGateways, /gateway-plugins\/hermes-mobile-web/);
assert.match(configureLowGateways, /gateway-plugins\/hermes-mobile-http/);
assert.match(configureLowGateways, /gateway-plugins\/hermes-mobile-docx/);
assert.match(configureLowGateways, /gateway-plugins\/hermes-mobile-audio/);
assert.match(configureLowGateways, /gateway-plugins\/hermes-mobile-image/);
assert.match(configureLowGateways, /gateway-plugins\/hermes-mobile-video/);
assert.match(configureLowGateways, /gateway-plugins\/hermes-mobile-cronjob/);
assert.match(configureLowGateways, /weather_plugin_enabled=1/);
assert.match(configureLowGateways, /web_plugin_enabled=1/);
assert.match(configureLowGateways, /http_plugin_enabled=1/);
assert.match(configureLowGateways, /docx_plugin_enabled=1/);
assert.match(configureLowGateways, /audio_plugin_enabled=1/);
assert.match(configureLowGateways, /image_plugin_enabled=1/);
assert.match(configureLowGateways, /video_plugin_enabled=1/);
assert.match(configureLowGateways, /cronjob_plugin_enabled=1/);
assert.match(configureLowGateways, /- weather/);
assert.match(configureLowGateways, /- http/);
assert.match(configureLowGateways, /- cronjob_mobile/);
assert.match(configureLowGateways, /hermes-mobile-weather/);
assert.match(configureLowGateways, /hermes-mobile-web/);
assert.match(configureLowGateways, /hermes-mobile-http/);
assert.match(configureLowGateways, /hermes-mobile-docx/);
assert.match(configureLowGateways, /hermes-mobile-audio/);
assert.match(configureLowGateways, /hermes-mobile-image/);
assert.match(configureLowGateways, /hermes-mobile-video/);
assert.match(configureLowGateways, /hermes-mobile-cronjob/);
assert.match(configureLowGateways, /profile_dir\/plugins\/hermes-mobile-weather/);
assert.match(configureLowGateways, /profile_dir\/plugins\/hermes-mobile-web/);
assert.match(configureLowGateways, /profile_dir\/plugins\/hermes-mobile-http/);
assert.match(configureLowGateways, /profile_dir\/plugins\/hermes-mobile-docx/);
assert.match(configureLowGateways, /profile_dir\/plugins\/hermes-mobile-audio/);
assert.match(configureLowGateways, /profile_dir\/plugins\/hermes-mobile-image/);
assert.match(configureLowGateways, /profile_dir\/plugins\/hermes-mobile-video/);
assert.match(configureLowGateways, /profile_dir\/plugins\/hermes-mobile-cronjob/);
assert.match(configureLowGateways, /sqlite_integrity_ok/);
assert.match(configureLowGateways, /PRAGMA integrity_check/);
assert.match(configureLowGateways, /repair_low_gateway_sqlite/);
assert.match(configureLowGateways, /state\.db/);
assert.match(configureLowGateways, /response_store\.db/);
assert.match(configureLowGateways, /sqlite-quarantine/);
assert.match(configureLowGateways, /sqlite-quarantine-\$\{stamp\}/);
assert.doesNotMatch(configureLowGateways, /sqlite-quarantine-\$\{stamp\}\/\$\{db_name\}/);
assert.match(configureLowGateways, /sqlite-sidecar-quarantine/);
assert.match(configureLowGateways, /cat > "\$worker_home_dir\/config\.yaml"/);
assert.match(configureLowGateways, /chmod 600 "\$worker_home_dir\/config\.yaml"/);
assert.match(configureLowGateways, /chown "\$worker_user:\$worker_user" "\$worker_home_dir\/config\.yaml"/);
assert.match(configureLowGateways, /platform_toolsets:/);
assert.doesNotMatch(configureLowGateways, /api_server:\s*\r?\n\s+- hermes-api-server/);
assert.match(configureLowGateways, /\s+- web/);
assert.match(configureLowGateways, /\s+- search/);
assert.match(configureLowGateways, /\s+- x_search/);
assert.match(configureLowGateways, /\s+- http/);
assert.match(configureLowGateways, /\s+- browser/);
assert.match(configureLowGateways, /\s+- file/);
assert.match(configureLowGateways, /\s+- vision/);
assert.match(configureLowGateways, /\s+- video/);
assert.match(configureLowGateways, /\s+- image_gen/);
assert.match(configureLowGateways, /\s+- messaging/);
assert.match(configureLowGateways, /\s+- tts/);
assert.match(configureLowGateways, /\s+- skills/);
assert.match(configureLowGateways, /\s+- todo/);
assert.match(configureLowGateways, /\s+- kanban/);
assert.match(configureLowGateways, /\s+- cronjob/);
assert.match(configureLowGateways, /\s+- memory/);
assert.match(configureLowGateways, /\s+- session_search/);
assert.match(configureLowGateways, /\s+- clarify/);
assert.doesNotMatch(configureLowGateways, /\s+- terminal/);
assert.doesNotMatch(configureLowGateways, /\s+- code_execution/);
assert.doesNotMatch(configureLowGateways, /\s+- delegation/);
assert.match(configureLowGateways, /newest_profile_auth_real/);
assert.match(configureLowGateways, /shared_auth_real/);
assert.match(configureLowGateways, /legacy_auth_real/);
assert.match(configureLowGateways, /legacy_shared_auth_path\}\.profile-local-backup-\$\(date \+%Y%m%d-%H%M%S\)/);
assert.match(configureLowGateways, /ln -s "\$shared_auth_path" "\$legacy_shared_auth_path"/);
assert.match(configureLowGateways, /ln -s "\$shared_auth_lock_path" "\$legacy_shared_auth_lock_path"/);
assert.match(configureLowGateways, /grok_auth_default_root="\$\{HERMES_GROK_GATEWAY_AUTH_ROOT:-\$telemetry_profiles_root\/shared-auth-grok\}"/);
assert.match(configureLowGateways, /grok_auth_path="\$\{HERMES_GROK_GATEWAY_AUTH_PATH:-\$grok_auth_default_root\/auth\.json\}"/);
assert.match(configureLowGateways, /grok_auth_lock_path="\$\{HERMES_GROK_GATEWAY_AUTH_LOCK_PATH:-\$grok_auth_default_root\/auth\.lock\}"/);
assert.match(configureLowGateways, /Missing shared low Gateway Codex auth/);
assert.match(configureLowGateways, /HERMES_LOW_GATEWAY_ALLOW_SHARED_AUTH_SEED/);
assert.match(configureLowGateways, /ln -s "\$shared_auth_path" "\$profile_link\/auth\.json"/);
assert.match(configureLowGateways, /ln -s "\$shared_auth_lock_path" "\$profile_link\/auth\.lock"/);
assert.doesNotMatch(configureLowGateways, /merge_grok_xai_oauth_to_shared_auth/);
assert.match(configureLowGateways, /\[\[ ! "\$profile" =~ \^grokgw\[0-9\]\+\$ \]\]/);
assert.doesNotMatch(configureLowGateways, /profile="grokgw\$\{idx\}"/);
assert.match(configureLowGateways, /provider: xai-oauth/);
assert.match(configureLowGateways, /default: grok-4\.3/);
assert.match(configureLowGateways, /video_gen:\s*\r?\n\s+provider: hermes-mobile-xai\s*\r?\n\s+model: grok-imagine-video/);
assert.match(configureLowGateways, /\s+- video_gen/);
assert.match(configureLowGateways, /grok_plugin_block="  enabled:\s*\r?\n\s+- hermes-mobile-video"/);
assert.doesNotMatch(configureLowGateways, /install -m 600 -o "\$worker_user" -g "\$worker_user" "\$gateway_worker_root\/secrets\/auth\.json" "\$worker_home_dir\/auth\.json"/);

assert.match(checkWorkerCodexAuth, /RequireUniqueRefreshTokens/);
assert.match(checkWorkerCodexAuth, /WSLENV = "HERMES_CHECK_PROFILES\/u:HERMES_REQUIRE_UNIQUE_REFRESH_TOKENS\/u"/);
assert.match(checkWorkerCodexAuth, /exit `\$LASTEXITCODE/);
assert.match(checkWorkerCodexAuth, /shared-refresh/);
assert.match(checkWorkerCodexAuth, /copied-refresh/);
assert.match(checkWorkerCodexAuth, /auth_path=/);
assert.match(checkWorkerCodexAuth, /hashlib\.sha256\(refresh\.encode\(\)\)\.hexdigest\(\)\[:12\]/);
assert.match(checkWorkerCodexAuth, /Worker child failed with exit code/);
assert.doesNotMatch(checkWorkerCodexAuth, /print\(.*refresh_token/);

assert.match(gatewayToolSchemaSmoke, /\/v1\/responses/);
assert.match(gatewayToolSchemaSmoke, /conversation: marker/);
assert.match(gatewayToolSchemaSmoke, /session_.*\\\.json/);
assert.match(gatewayToolSchemaSmoke, /newestMatchingSession/);
assert.match(gatewayToolSchemaSmoke, /toolsFromSession/);
assert.match(gatewayToolSchemaSmoke, /--require-tool-description/);
assert.match(gatewayToolSchemaSmoke, /--forbid/);
assert.match(gatewayToolSchemaSmoke, /--all-user-workers/);
assert.match(gatewayToolSchemaSmoke, /http_request,weather,mobile_web_search,mobile_web_extract,image_generate,chatgpt_image_edit,chatgpt_image_erase,docx_extract_text,audio_transcribe/);
assert.match(gatewayToolSchemaSmoke, /missing tools in live session schema/);
assert.match(gatewayToolSchemaSmoke, /C:\/ProgramData\/HermesMobile\/gateway-worker\/telemetry\/profiles/);
assert.match(startLowGatewaysShell, /HERMES_MOBILE_X_SEARCH_PROXY_URL/);
assert.doesNotMatch(gatewayToolSchemaSmoke, /console\.log\(.*api[_-]?key/i);

assert.match(transcribeReadingAudio, /HermesGatewayWorker/);
assert.match(transcribeReadingAudio, /large-v3-turbo/);
assert.match(transcribeReadingAudio, /whisper-large-v3-turbo-service/);
assert.match(transcribeReadingAudio, /127\.0\.0\.1:8001\/v1\/audio\/transcriptions/);
assert.doesNotMatch(transcribeReadingAudio, /falling back to worker STT/);
assert.doesNotMatch(transcribeReadingAudio, /from faster_whisper import WhisperModel/);
assert.match(transcribeReadingAudio, /\[string\]\$Language = "auto"/);
assert.doesNotMatch(transcribeReadingAudio, /Write-Host .*token/i);

assert.match(weatherPluginManifest, /name: hermes-mobile-weather/);
assert.match(weatherPluginManifest, /provides_tools:\s*\r?\n\s+- weather/);
assert.match(weatherPlugin, /WEATHER_SCHEMA/);
assert.match(weatherPlugin, /"name": "weather"/);
assert.match(weatherPlugin, /toolset="weather"/);
assert.match(weatherPlugin, /open-meteo/);
assert.match(webPluginManifest, /name: hermes-mobile-web/);
assert.match(webPluginManifest, /provides_tools:\s*\r?\n\s+- web\r?\n\s+- search/);
assert.match(webPlugin, /WEB_SEARCH_SCHEMA/);
assert.match(webPlugin, /WEB_EXTRACT_SCHEMA/);
assert.match(webPlugin, /MOBILE_WEB_SEARCH_SCHEMA/);
assert.match(webPlugin, /MOBILE_WEB_EXTRACT_SCHEMA/);
assert.match(webPlugin, /"name": "web_search"/);
assert.match(webPlugin, /"name": "web_extract"/);
assert.match(webPlugin, /MOBILE_WEB_SEARCH_SCHEMA = _schema_alias\(WEB_SEARCH_SCHEMA, "mobile_web_search"\)/);
assert.match(webPlugin, /MOBILE_WEB_EXTRACT_SCHEMA = _schema_alias\(WEB_EXTRACT_SCHEMA, "mobile_web_extract"\)/);
assert.match(webPlugin, /toolset="web"/);
assert.match(webPlugin, /duckduckgo-html-fallback/);
assert.match(webPlugin, /private_or_local_url_not_allowed/);
assert.match(httpPluginManifest, /name: hermes-mobile-http/);
assert.match(httpPluginManifest, /provides_tools:\s*\r?\n\s+- http/);
assert.match(httpPlugin, /HTTP_REQUEST_SCHEMA/);
assert.match(httpPlugin, /CRONJOB_MOBILE_SCHEMA/);
assert.match(httpPlugin, /"name": "http_request"/);
assert.match(httpPlugin, /"name": "cronjob_mobile"/);
assert.match(httpPlugin, /toolset="http"/);
assert.match(httpPlugin, /hermes-mobile:\/\/cron/);
assert.match(httpPlugin, /Use hermes-mobile:\/\/cron for live Hermes Mobile automation jobs/);
assert.match(httpPlugin, /owner_principal_id is required/);
assert.match(httpPlugin, /\/bridge\/cron/);
assert.match(httpPlugin, /_tool_defs_cache\.clear\(\)/);
assert.match(httpPlugin, /HERMES_MOBILE_HTTP_ALLOWED_ORIGINS/);

assert.match(webPlugin, /"name": "x_search"/);
assert.match(webPlugin, /grok-gateway-proxy/);
assert.match(webPlugin, /HERMES_MOBILE_X_SEARCH_PROXY_URL/);
assert.match(webPlugin, /def _bridge_host_x_search_proxy_url/);
assert.match(webPlugin, /HERMES_MOBILE_BRIDGE_HOST_URL/);
assert.match(webPlugin, /"127\.0\.0\.1" in raw/);
assert.match(webPlugin, /_is_grok_gateway_profile/);
assert.match(httpPlugin, /HERMES_MOBILE_HTTP_FILE_ROOTS/);
assert.match(httpPlugin, /file_body/);
assert.match(httpPlugin, /multipart_files/);
assert.match(httpPlugin, /save_base64/);
assert.match(httpPlugin, /saved_file/);
assert.match(httpPlugin, /"run"/);
assert.match(httpPlugin, /file_path_outside_allowed_roots/);
assert.match(httpPlugin, /Authorization/);
assert.match(httpPlugin, /wd_live_/);
assert.match(docxPluginManifest, /name: hermes-mobile-docx/);
assert.match(docxPluginManifest, /provides_tools:\s*\r?\n\s+- file/);
assert.match(docxPlugin, /DOCX_EXTRACT_TEXT_SCHEMA/);
assert.match(docxPlugin, /"name": "docx_extract_text"/);
assert.match(docxPlugin, /toolset="file"/);
assert.match(docxPlugin, /HERMES_MOBILE_DOCX_ALLOWED_ROOTS/);
assert.match(docxPlugin, /zipfile\.ZipFile/);
assert.match(docxPlugin, /word\/document\.xml/);
assert.match(docxPlugin, /file_path_outside_allowed_roots/);
assert.match(docxPlugin, /preview = full_text\[:max_chars\]/);
assert.match(docxPlugin, /"text": preview/);
assert.match(docxPlugin, /"textPreview": preview/);
assert.match(docxPlugin, /"totalChars": len\(full_text\)/);
assert.match(docxPlugin, /"truncated": truncated/);
assert.match(docxPlugin, /"fileName": path\.name/);
assert.doesNotMatch(docxPlugin, /"file_path": str\(path\)/);
assert.doesNotMatch(docxPlugin, /"allowed_roots":/);
assert.match(audioPluginManifest, /name: hermes-mobile-audio/);
assert.match(audioPluginManifest, /provides_tools:\s*\r?\n\s+- file/);
assert.match(audioPlugin, /AUDIO_TRANSCRIBE_SCHEMA/);
assert.match(audioPlugin, /"name": "audio_transcribe"/);
assert.match(audioPlugin, /toolset="file"/);
assert.match(audioPlugin, /HERMES_MOBILE_AUDIO_ALLOWED_ROOTS/);
assert.match(audioPlugin, /large-v3-turbo/);
assert.match(audioPlugin, /whisper-large-v3-turbo-service/);
assert.doesNotMatch(audioPlugin, /from faster_whisper import WhisperModel/);
assert.match(audioPlugin, /SUPPORTED_SUFFIXES/);
assert.match(audioPlugin, /unsupported_audio_file_suffix/);
assert.match(imagePluginManifest, /name: hermes-mobile-image/);
assert.match(imagePluginManifest, /provides_tools:\s*\r?\n\s+- image_gen/);
assert.match(imagePlugin, /IMAGE_EDIT_SCHEMA/);
assert.match(imagePlugin, /IMAGE_ERASE_SCHEMA/);
assert.match(imagePlugin, /CHATGPT_IMAGE_EDIT_SCHEMA/);
assert.match(imagePlugin, /CHATGPT_IMAGE_ERASE_SCHEMA/);
assert.match(imagePlugin, /"name": "image_edit"/);
assert.match(imagePlugin, /"name": "image_erase"/);
assert.match(imagePlugin, /CHATGPT_IMAGE_EDIT_SCHEMA = _schema_alias\(IMAGE_EDIT_SCHEMA, "chatgpt_image_edit"\)/);
assert.match(imagePlugin, /CHATGPT_IMAGE_ERASE_SCHEMA = _schema_alias\(IMAGE_ERASE_SCHEMA, "chatgpt_image_erase"\)/);
assert.match(imagePlugin, /toolset="image_gen"/);
assert.match(imagePlugin, /gpt-image-2/);
assert.doesNotMatch(imagePlugin, /"input_fidelity"/);
assert.match(imagePlugin, /HERMES_MOBILE_IMAGE_ALLOWED_ROOTS/);
assert.match(imagePlugin, /output_path_crosses_workspace_scope/);
assert.match(videoPluginManifest, /name: hermes-mobile-video/);
assert.match(videoPluginManifest, /kind: backend/);
assert.match(videoPlugin, /PROVIDER_NAME = "hermes-mobile-xai"/);
assert.match(videoPlugin, /register_video_gen_provider/);
assert.match(videoPlugin, /VideoGenProvider/);
assert.doesNotMatch(videoPlugin, /ctx\.register_tool/);
assert.doesNotMatch(videoPlugin, /override=True/);
assert.match(videoPlugin, /HERMES_MOBILE_VIDEO_ALLOWED_ROOTS/);
assert.match(videoPlugin, /resolve_xai_http_credentials/);
assert.match(videoPlugin, /data:\{mime\};base64/);
assert.match(videoPlugin, /media_line/);
assert.match(cronjobPluginManifest, /name: hermes-mobile-cronjob/);
assert.match(cronjobPluginManifest, /provides_tools:\s*\r?\n\s+- http/);
assert.match(cronjobPlugin, /MOBILE_CRONJOB_SCHEMA/);
assert.match(cronjobPlugin, /"name": "cronjob_mobile"/);
assert.match(cronjobPlugin, /toolset="http"/);
assert.match(cronjobPlugin, /owner_principal_id is required/);
assert.match(cronjobPlugin, /\/bridge\/cron/);
assert.match(cronjobPlugin, /"run"/);
assert.match(cronjobPlugin, /HERMES_MOBILE_BRIDGE_HOST_KEY_PATH/);
assert.match(cronjobPlugin, /_tool_defs_cache\.clear\(\)/);
assert.doesNotMatch(cronjobPlugin, /print\(.*key/i);

console.log("startup scripts tests passed");
