"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const repoRoot = path.resolve(__dirname, "..");
const appJs = fs.readFileSync(path.join(repoRoot, "public", "app.js"), "utf8");
const indexHtml = fs.readFileSync(path.join(repoRoot, "public", "index.html"), "utf8");
const serviceWorkerJs = fs.readFileSync(path.join(repoRoot, "public", "service-worker.js"), "utf8");
const fileViewerHtml = fs.readFileSync(path.join(repoRoot, "public", "file-viewer.html"), "utf8");
const pdfViewerHtml = fs.readFileSync(path.join(repoRoot, "public", "pdf-viewer.html"), "utf8");
const stylesCss = fs.readFileSync(path.join(repoRoot, "public", "styles.css"), "utf8");
const serverJs = fs.readFileSync(path.join(repoRoot, "server.js"), "utf8");
const ownerElevationApiRoutes = fs.readFileSync(path.join(repoRoot, "server-routes", "owner-elevation-api-routes.js"), "utf8");
const weixinApiRoutes = fs.readFileSync(path.join(repoRoot, "server-routes", "weixin-api-routes.js"), "utf8");
const kanbanCardApiRoutes = fs.readFileSync(path.join(repoRoot, "server-routes", "kanban-card-api-routes.js"), "utf8");
const kanbanStudyApiRoutes = fs.readFileSync(path.join(repoRoot, "server-routes", "kanban-study-api-routes.js"), "utf8");
const threadReadUploadApiRoutes = fs.readFileSync(path.join(repoRoot, "server-routes", "thread-read-upload-api-routes.js"), "utf8");
const directoryMutationApiRoutes = fs.readFileSync(path.join(repoRoot, "server-routes", "directory-mutation-api-routes.js"), "utf8");
const kanbanProviderJs = fs.readFileSync(path.join(repoRoot, "adapters", "kanban-provider.js"), "utf8");
const kanbanCardProviderJs = fs.readFileSync(path.join(repoRoot, "adapters", "kanban-card-provider.js"), "utf8");
const weixinIngressProviderJs = fs.readFileSync(path.join(repoRoot, "adapters", "weixin-ingress-provider.js"), "utf8");

assert.match(appJs, /function taskGroupsForThread\(thread\)/);
assert.match(appJs, /return \[\.\.\.groups\.values\(\)\]\.sort\(\(a, b\) => String\(b\.updatedAt\)\.localeCompare\(String\(a\.updatedAt\)\)\);/);
assert.match(appJs, /const allGroups = taskListGroupsForThread\(thread\)\s+\.concat\(sharedCaseTopicGroupsForTaskList\(thread\)\)\s+\.sort/);
assert.match(appJs, /const displayGroups = allGroups\.slice\(\);/);
assert.equal(appJs.includes("allGroups.slice().reverse()"), false);
assert.ok(appJs.includes("(?:\\/[A-Za-z0-9_.-]+)+"));
assert.equal(appJs.includes("namedSkillPattern"), false);
assert.match(indexHtml, /id="taskRenameOverlay"/);
assert.match(appJs, /function openTaskRenameDialog\(currentTitle\)/);
assert.match(appJs, /function selectTaskRenameInput\(input\)/);
assert.match(appJs, /input\.setSelectionRange\(0, input\.value\.length\)/);
assert.match(appJs, /input\.select\(\)/);
assert.match(appJs, /const nextTitle = await openTaskRenameDialog\(currentTitle\)/);
assert.doesNotMatch(appJs, /taskStatus\(group\)} \|/);
assert.equal(appJs.includes("task-doc-empty\">No doc"), false);
assert.match(appJs, /const latestArtifact = latestTaskListDocument\(group\);/);
assert.match(appJs, /const artifactChips = latestArtifact \?/);
assert.match(appJs, /\$\{artifactChips\}/);
assert.match(appJs, /function messageExtractedDirectoryAliases\(message\)/);
assert.match(appJs, /for \(const message of group\?\.messages \|\| \[\]\) \{\s+const candidates = usableTaskBindingAliases/);
assert.match(appJs, /const exactProject = candidates\.find\(\(candidate\) =>\s+candidate\.projectId === requestedProjectId && String\(candidate\.subprojectId \|\| ""\) === requestedSubprojectId\)/);
assert.match(appJs, /const rootProject = candidates\.find\(\(candidate\) =>\s+candidate\.projectId === requestedProjectId && !candidate\.subprojectId\)/);
assert.match(stylesCss, /\.task-rename-sheet/);
assert.match(appJs, /function renderOwnerElevationPanel\(\)/);
assert.match(appJs, /function openOwnerElevationApprovalDialog\(options = \{\}\)/);
assert.match(appJs, /\/api\/owner-elevation/);
assert.match(appJs, /body\.maintenanceMode = true/);
assert.match(appJs, /owner_high_privilege/);
assert.match(stylesCss, /\.workspace-permission-panel/);
assert.match(stylesCss, /\.owner-elevation-approval-actions/);
assert.match(indexHtml, /id="ownerElevationApprovalOverlay"/);
assert.match(serverJs, /function publicOwnerElevationStatus\(auth\)/);
assert.match(ownerElevationApiRoutes, /path: "\/api\/owner-elevation"/);
assert.match(ownerElevationApiRoutes, /path: "\/api\/owner-elevation\/once"/);
assert.match(serverJs, /function grantOwnerElevationOnce\(auth\)/);
assert.match(serverJs, /function consumeOwnerElevationOnce\(auth, token\)/);
assert.match(serverJs, /consumeOwnerElevationOnce\(auth, onceToken\) \|\| isOwnerElevationActive\(auth\)/);
assert.match(serverJs, /isOwnerElevationActive\(auth\)/);
assert.match(serverJs, /HERMES_PERMISSION_APPROVAL_REQUIRED/);
assert.match(serverJs, /function modelPermissionApprovalRequest\(text, message = \{\}\)/);
assert.match(serverJs, /elevationRequired: Boolean\(message\.elevationRequired\)/);
assert.match(serverJs, /messages\\\/\(\[\^\/\]\+\)\\\/owner-elevation/);
assert.match(serverJs, /gatewaySecurityLevel: gatewayRouting\.securityLevel/);
assert.match(serverJs, /gatewayMaintenance: Boolean\(gatewayRouting\.maintenance/);
assert.match(serverJs, /gatewayMaintenanceCategory: gatewayRouting\.maintenanceCategory/);
assert.match(appJs, /function offerOwnerElevationForMessage\(message\)/);
assert.match(appJs, /ownerElevationPromptedMessageIds/);
assert.match(appJs, /await openOwnerElevationApprovalDialog/);
assert.doesNotMatch(appJs, /window\.confirm\(ownerElevationConfirmMessage/);
assert.match(appJs, /\/messages\/\$\{encodeURIComponent\(messageId\)\}\/owner-elevation/);
assert.match(appJs, /function canDeleteDirectoryRootProject\(project\)/);
assert.match(appJs, /data-delete-directory-path="\$\{escapeHtml\(project\.root \|\| ""\)\}"/);
assert.match(appJs, /function deletedDirectoryWasRootListProject\(pathText\)/);
assert.match(appJs, /const wasRootListProject = deletedDirectoryWasRootListProject\(path\)/);
assert.match(appJs, /if \(!directoryActivePath\(\) \|\| wasRootListProject\) await loadProjects\(\);/);
assert.match(serverJs, /function isDeletableWorkspaceRootChild\(thread, localPath, displayPath = ""\)/);
assert.match(serverJs, /function pathDirectChildOfRoot\(candidate, root\)/);
assert.equal(serverJs.includes("Workspace users can delete empty folders only"), false);
assert.match(directoryMutationApiRoutes, /id: "directories-delete"/);
assert.match(directoryMutationApiRoutes, /clearDirectoryCatalogCaches\(deps, thread\)/);
assert.match(directoryMutationApiRoutes, /deps\.clearDynamicProjectCache\(String\(thread\?\.workspaceId \|\| ""\)\)/);
assert.match(serverJs, /function taskDirectoryAttachmentCandidatesForMessage\(thread, message\)/);
assert.match(serverJs, /the attached task directory is the frozen working directory/);
assert.match(serverJs, /singleWindowMode === "chat" \|\| taskDirectory\?\.path \? "" : semanticProjectRoutingInstructions/);
assert.match(serverJs, /function callableFunctionHintsForToolsets\(toolsets = \[\]\)/);
assert.match(serverJs, /web: \["mobile_web_search", "mobile_web_extract", "web_search", "web_extract"\]/);
assert.match(serverJs, /search: \["mobile_web_search", "mobile_web_extract", "web_search", "web_extract"\]/);
assert.match(serverJs, /http: \["http_request"\]/);
assert.match(serverJs, /file: \["read_file", "write_file", "patch", "search_files", "docx_extract_text", "audio_transcribe"\]/);
assert.match(serverJs, /image_gen: \["image_generate", "chatgpt_image_edit", "chatgpt_image_erase", "image_edit", "image_erase"\]/);
assert.match(serverJs, /For HTTP\/API Program calls, use `http_request`; do not look for or mention a `web_request` function\./);
assert.match(serverJs, /For Word DOCX text extraction, use `docx_extract_text`/);
assert.match(serverJs, /For MP3\/M4A\/WAV\/AAC\/OGG\/OPUS\/AMR\/FLAC voice notes or reading-retelling audio, use `audio_transcribe`/);
assert.match(serverJs, /Callable function names for enabled toolsets/);
assert.match(serverJs, /function currentToolSchemaOverrideInstructions\(policy = \{\}\)/);
assert.match(serverJs, /Current tool schema override: the `http` toolset is enabled for this run/);
assert.match(serverJs, /Word DOCX text extraction is available as `docx_extract_text`, and audio transcription/);
assert.match(serverJs, /For audio-only files such as \.mp3\/\.m4a\/\.wav/);
assert.match(serverJs, /Do not ask the user to convert an ordinary current-workspace audio file into a blank video/);
assert.match(serverJs, /Current tool schema override: the `web`\/`search` toolsets are enabled for this run/);
assert.match(serverJs, /Prefer callable function names `mobile_web_search` and `mobile_web_extract`/);
assert.match(serverJs, /Current tool schema override: the `image_gen` toolset is enabled for this run/);
assert.match(serverJs, /`chatgpt_image_edit`, and `chatgpt_image_erase`/);
assert.match(serverJs, /For existing-image retouching, object removal, background cleanup, P image requests, or erase\/inpainting requests/);
assert.match(serverJs, /prefer `chatgpt_image_edit` or `chatgpt_image_erase`/);
assert.match(serverJs, /GATEWAY_TOOL_SCHEMA_EPOCH/);
assert.match(serverJs, /20260513-audio-file-v1/);
assert.match(serverJs, /function gatewayConversationId\(thread, userMessage, runPolicy = \{\}\)/);
assert.match(serverJs, /schemaSensitive \? `\$\{base\}_\$\{GATEWAY_TOOL_SCHEMA_EPOCH\}` : base/);
assert.match(serverJs, /\["web", "search", "http", "weather", "file", "image_gen"\]/);
assert.match(serverJs, /toolSchemaEpoch: GATEWAY_TOOL_SCHEMA_EPOCH/);
assert.match(serverJs, /Do not request Owner elevation merely because an ordinary current-workspace image editing tool is missing/);
assert.match(serverJs, /Image editing, object removal, background cleanup, P image requests, and erase\/inpainting requests inside the current workspace are ordinary user work/);
assert.match(serverJs, /do not use local PIL\/OpenCV\/rembg\/SAM\/ffmpeg\/terminal\/code image repair/);
assert.match(serverJs, /function isStaleHttpToolAvailabilityClaim\(text\)/);
assert.match(serverJs, /function isStaleImageToolAvailabilityClaim\(text\)/);
assert.match(serverJs, /function isStaleDocxToolAvailabilityClaim\(text\)/);
assert.match(serverJs, /function isStaleAudioToolAvailabilityClaim\(text\)/);
assert.match(serverJs, /audio_transcribe/);
assert.match(serverJs, /video_analyze.*mp3|mp3.*video_analyze/);
assert.match(serverJs, /function isOrdinaryToolSchemaElevationRequest\(approvalRequest, output, message = \{\}\)/);
assert.match(serverJs, /Stale assistant tool-availability claim omitted by Hermes Mobile/);
assert.match(serverJs, /internal_owner_elevation_request_not_external_delivered/);
assert.match(serverJs, /internal_tool_schema_failure_not_external_delivered/);
assert.match(serverJs, /conversation_history: buildConversationHistory\(thread, userMessage\.id, runPolicy\)/);
assert.match(serverJs, /function ensureGroupChatSharedArtifactCopies\(thread, latestUserMessage, deliveryRoot\)/);
assert.match(serverJs, /Group-chat shared attachments authorized for this run/);
assert.match(serverJs, /groupChatAttachmentCopies/);
assert.match(serverJs, /shared-attachments/);
assert.match(serverJs, /reason: "unmatched_workspace_route"/);
assert.match(serverJs, /terminalStatus === "failed"/);
assert.match(serverJs, /status: "skipped"/);
assert.match(serverJs, /function userFacingWeixinRunError\(err\)/);
assert.match(serverJs, /function publicWeixinOutboundDelivery\(thread, message\)/);
assert.match(serverJs, /function weixinForwardTargetsForWorkspace\(workspaceId, auth\)/);
assert.match(serverJs, /async function resolveFileFromSourceUrlForRequest\(sourceUrl, auth\)/);
assert.match(serverJs, /async function createWeixinFileForwardDelivery\(auth, body = \{\}\)/);
assert.match(serverJs, /const caption = String\(body\.caption \?\? body\.text \?\? ""\)\.trim\(\)/);
assert.doesNotMatch(serverJs, /Weixin file forwarding:/);
assert.match(serverJs, /function materializeWeixinForwardFile\(file, workspaceId\)/);
assert.match(serverJs, /function renderMarkdownForwardPdf\(markdownPath, workspaceId, title\)/);
assert.match(serverJs, /function renderMarkdownForwardDocument\(markdown\)/);
assert.match(serverJs, /function renderMarkdownForwardTable\(lines, startIndex\)/);
assert.match(serverJs, /document-kicker/);
assert.match(serverJs, /markdown-table-wrap/);
assert.match(serverJs, /Weixin readable PDF/);
assert.doesNotMatch(serverJs, /<pre>\$\{escapeHtmlForDocument\(markdown \|\| ""\)\}<\/pre>/);
assert.match(serverJs, /const sourceFile = resolved\.file \|\| fileResultFromBridgeFileForForward\(resolved\.bridgeFile, workspaceId\)\.file/);
assert.match(serverJs, /const forwardFile = materializeWeixinForwardFile\(sourceFile, workspaceId\)/);
assert.match(serverJs, /pathToFileURL\(htmlPath\)\.href/);
assert.match(serverJs, /WEIXIN_FORWARD_MARKDOWN_MAX_BYTES/);
assert.match(serverJs, /fileResultFromBridgeFileForForward\(file, workspaceId\)/);
assert.match(serverJs, /parsed\.pathname === "\/api\/automations\/output" \|\| parsed\.pathname === "\/api\/automations\/output\/preview"/);
assert.match(serverJs, /parsed\.pathname === "\/api\/kanban\/cards\/output" \|\| parsed\.pathname === "\/api\/kanban\/cards\/output\/preview"/);
assert.match(serverJs, /deliveryId: weixinIngressProvider\.deliveryId\(thread\.id, message\.id\)/);
assert.match(serverJs, /WEIXIN_DELIVERY_RETRY_LIMIT/);
assert.match(serverJs, /WEIXIN_INGRESS_ATTACHMENT_CONTEXT_WINDOW_MS/);
assert.match(serverJs, /function isWeixinInboundWakeRequiredFailure\(ack = \{\}\)/);
assert.match(serverJs, /function isWeixinDeliveryRetryable\(delivery, nowMs = Date\.now\(\)\)/);
assert.match(serverJs, /function wakeWeixinOutboundDeliveriesForInboundEvent\(event, workspaceId\)/);
assert.match(serverJs, /function weixinIngressIsAttachmentOnlyEvent\(event\)/);
assert.match(serverJs, /function consumeWeixinPendingAttachmentMessages\(thread, event, consumedAt = nowIso\(\)\)/);
assert.match(serverJs, /function weixinIngressInstructions\(event, pendingAttachmentMessages = \[\]\)/);
assert.match(serverJs, /status: "waiting_instruction"/);
assert.match(serverJs, /awaitingInstruction: true/);
assert.match(serverJs, /Treat these media files as attached to the latest user instruction/);
assert.ok(serverJs.indexOf("if (attachmentOnly)") < serverJs.indexOf("startRunForThread(thread, userMessage, assistantMessage, runOptions)"));
assert.match(serverJs, /delivery\.status === "pending" \|\| isWeixinDeliveryRetryable\(delivery, nowMs\)/);
assert.match(serverJs, /status: waitForInbound \? "waiting_inbound" : ack\.status/);
assert.match(serverJs, /retryAfterInbound: waitForInbound/);
assert.match(serverJs, /awakenedOutbound/);
assert.match(weixinApiRoutes, /path: "\/api\/weixin\/forward-targets"/);
assert.match(weixinApiRoutes, /path: "\/api\/weixin\/forward-file"/);
assert.match(weixinApiRoutes, /const result = await deps\.createWeixinFileForwardDelivery\(auth, body\)/);
assert.match(serverJs, /externalDelivery: message\.externalDelivery\?\.source === "weixin" && thread \? publicWeixinOutboundDelivery\(thread, message\) : null/);
assert.match(appJs, /function renderArtifactWeixinButton\(artifact\)/);
assert.match(appJs, /function renderArtifactWeixinButton\(artifact\) \{\s+if \(isWeixinChatView\(\)\) return ""/);
assert.match(appJs, /data-forward-artifact-weixin/);
assert.match(appJs, /async function forwardArtifactToWeixin\(button\)/);
assert.match(appJs, /\/api\/weixin\/forward-file/);
assert.match(appJs, /function renderExternalDeliveryStatus\(message\)/);
assert.match(appJs, /function renderExternalDeliveryStatus\(message\) \{\s+if \(isWeixinChatView\(\)\) return ""/);
assert.match(appJs, /message\?\.externalDelivery/);
assert.match(appJs, /delivery\.terminalStatus !== "manual_forward"/);
assert.match(appJs, /if \(status !== "sent"\) return ""/);
assert.match(appJs, /\\u5fae\\u4fe1\\u5df2\\u8f6c\\u53d1/);
assert.match(stylesCss, /\.artifact-weixin-button/);
assert.match(stylesCss, /\.external-delivery-status/);
assert.match(fileViewerHtml, /id="forwardWeixin"/);
assert.match(fileViewerHtml, /data-markdown-share="weixin"/);
assert.match(fileViewerHtml, /\.markdown-preview article/);
assert.match(fileViewerHtml, /hermesWebFontSize/);
assert.match(fileViewerHtml, /hermesWebFontFamily/);
assert.match(fileViewerHtml, /--viewer-markdown-font-scale/);
assert.match(fileViewerHtml, /function viewerMarkdownSizeOption\(value\)/);
assert.match(fileViewerHtml, /font:\$\{markdownFontSize\}\/1\.72 \$\{fontFamily\}/);
assert.match(fileViewerHtml, /#0969da/);
assert.match(fileViewerHtml, /task-list-item/);
assert.match(fileViewerHtml, /renderListItem\(item\)/);
assert.match(fileViewerHtml, /markdownExportHtml\(options = \{\}\)/);
assert.match(fileViewerHtml, /async function forwardFileToWeixin\(\)/);
assert.match(fileViewerHtml, /\/api\/weixin\/forward-file/);
assert.match(pdfViewerHtml, /id="weixinButton"/);
assert.match(pdfViewerHtml, /async function forwardPdfToWeixin\(\)/);
assert.match(pdfViewerHtml, /\/api\/weixin\/forward-file/);
assert.match(serverJs, /运行被终止，未生成回复。/);
assert.match(serverJs, /function gatewayPoolStatusHealthy\(poolStatus\)/);
assert.match(serverJs, /status\.fallbackError = status\.error \|\| ""/);
assert.match(indexHtml, /id="topSearchChat"/);
assert.match(appJs, /\$\("topSearchChat"\)\?\.addEventListener\("click"/);
assert.match(indexHtml, /id="topToggleWeixinChat"/);
assert.match(appJs, /function toggleWeixinChat\(\)/);
assert.match(appJs, /function isThreadWeixinChat\(thread = state\.currentThread\)/);
assert.match(appJs, /function isWeixinChatView\(\)/);
assert.match(appJs, /weixinChatOpen: localStorage\.getItem\("hermesWebWeixinChatOpen"\) === "1"/);
assert.match(appJs, /state\.weixinChatThread = mergeChatScopeThread\(state\.weixinChatThread, result\.weixinChatThread\)/);
assert.match(serverJs, /function ensureWeixinSingleWindowThread\(workspaceId, seed = \{\}\)/);
assert.match(serverJs, /function migrateWeixinMessagesToDedicatedThread\(workspaceId, targetThread = null\)/);
assert.match(serverJs, /function findWeixinSingleWindowThreadForWorkspace\(workspaceId\)/);
assert.equal(indexHtml.includes("searchButton"), false);
assert.equal(appJs.includes("$('searchButton')"), false);
assert.equal(appJs.includes('$("#searchButton")'), false);
assert.match(appJs, /const KANBAN_STATUS_ORDER = Object\.freeze\(\["triage", "todo", "ready", "running", "blocked", "done", "archived"\]\)/);
assert.match(appJs, /const KANBAN_STORY_STATUS = "story"/);
assert.match(appJs, /const KANBAN_TAB_ORDER = Object\.freeze\(\[KANBAN_STORY_STATUS, \.\.\.KANBAN_STATUS_ORDER\]\)/);
assert.match(appJs, /const TODO_AUTO_REFRESH_INTERVAL_MS = 8000/);
assert.match(appJs, /const TODO_LIST_CACHE_MAX_AGE_MS = 30 \* 60 \* 1000/);
assert.match(appJs, /if \(options\.freshServer\) params\.set\("fresh", "1"\)/);
assert.match(appJs, /result\?\.cache\?\.hit && !options\.freshServer/);
assert.match(serverJs, /const KANBAN_CARD_LIST_CACHE_TTL_MS = Math\.max/);
assert.match(serverJs, /const KANBAN_CARD_LIST_CACHE_PATH = path\.resolve/);
assert.match(serverJs, /const kanbanCardListCache = new Map\(\)/);
assert.match(serverJs, /let kanbanCardListCacheStoreLoaded = false/);
assert.match(serverJs, /function readKanbanCardListCache\(args = \{\}\)/);
assert.match(serverJs, /readJsonStore\(KANBAN_CARD_LIST_CACHE_PATH/);
assert.match(serverJs, /writeJsonStore\(KANBAN_CARD_LIST_CACHE_PATH/);
assert.match(kanbanCardApiRoutes, /url\.searchParams\.get\("fresh"\)/);
assert.match(serverJs, /function scheduleKanbanDependencyReconcile\(workspaceId\)/);
assert.match(appJs, /function renderTodoKanbanBoard\(todos\)/);
assert.match(appJs, /function renderTodoKanbanCard\(todo\)/);
assert.match(appJs, /function sortArchivedKanbanCards\(items\)/);
assert.match(appJs, /function kanbanArchiveCases\(items\)/);
assert.match(appJs, /function kanbanStoryCases\(items\)/);
assert.match(appJs, /function kanbanActiveStoryCases\(items\)/);
assert.match(appJs, /return kanbanArchiveCases\(items\);/);
assert.match(appJs, /function kanbanStoryCaseArchiveItems\(group\)/);
assert.match(appJs, /function renderKanbanStoryTree\(items\)/);
assert.match(appJs, /function renderKanbanArchiveStories\(items\)/);
assert.match(appJs, /function renderKanbanArchiveCase\(group, options = \{\}\)/);
assert.match(appJs, /function scheduleKanbanStoryDetailLoads\(items\)/);
assert.match(appJs, /function kanbanStoryCaseRenderState\(group, options = \{\}\)/);
assert.match(appJs, /data-kanban-story-case/);
assert.match(appJs, /data-archive-kanban-story-case/);
assert.doesNotMatch(appJs, /data-delete-kanban-story-case/);
assert.match(appJs, /function kanbanStorySwipeRenderState\(group, options = \{\}\)/);
assert.match(appJs, /data-swipe-kind="kanban-story"/);
assert.match(appJs, /deleteKanbanStoryCase\(itemId\)/);
assert.match(appJs, /kanban-story-swipe-delete/);
assert.match(appJs, /FONT_FAMILY_OPTIONS/);
assert.match(appJs, /hermesWebFontFamily/);
assert.match(appJs, /function applyFontFamilyPreference\(value = state\.fontFamily\)/);
assert.match(appJs, /data-font-family-option/);
assert.match(stylesCss, /\.kanban-story-swipe-content/);
assert.match(stylesCss, /\.kanban-story-swipe-delete/);
assert.match(stylesCss, /--app-font-family/);
assert.match(stylesCss, /\.font-family-options/);
assert.match(stylesCss, /\.kanban-archive-case-head h3 \{[\s\S]*?font-size: calc\(17px \* var\(--app-font-scale\)\)/);
assert.match(stylesCss, /\.kanban-archive-story-grid p \{[\s\S]*?font-size: calc\(15px \* var\(--app-font-scale\)\)/);
assert.match(appJs, /kanbanActiveStoryCases\(items\)\.filter\(kanbanStoryCaseExpanded\)/);
assert.match(appJs, /renderKanbanArchiveCase\(group, \{ collapsible: true, archiveAction: true, deleteAction: true \}\)/);
assert.match(appJs, /renderKanbanArchiveCase\(group, \{ collapsible: true, deleteAction: true \}\)/);
assert.match(appJs, /async function archiveKanbanStoryCase\(caseKey\)/);
assert.match(appJs, /async function deleteKanbanStoryCase\(caseKey\)/);
assert.match(appJs, /return false/);
assert.match(appJs, /function kanbanStoryCaseDeleteItems\(group\)/);
assert.match(appJs, /kanbanCardHasExplicitStoryCase\(selectedTodo\)/);
assert.match(appJs, /function kanbanCardStoryFeedbackLine\(todo\)/);
assert.match(appJs, /function renderKanbanReadingFields\(disabled = false\)/);
assert.match(appJs, /id="kanbanStudyTemplate"/);
assert.match(appJs, /id="kanbanStudyScheduleFrequency"/);
assert.match(appJs, /data-kanban-study-weekday/);
assert.match(appJs, /id="kanbanStudyScheduleMonthDay"/);
assert.match(appJs, /function normalizeKanbanStudyScheduleFrequency\(value = ""\)/);
assert.match(appJs, /function selectedKanbanStudyWeekdays\(root = document\)/);
assert.match(appJs, /defaultKanbanAssessmentDraft/);
assert.match(appJs, /id="kanbanAssessmentSubject"/);
assert.match(appJs, /\/api\/kanban\/cards\/assessment-plan/);
assert.match(appJs, /function renderKanbanAssessmentExamPanel\(todo\)/);
assert.match(appJs, /function loadAssessmentExam\(todoId\)/);
assert.match(appJs, /function submitAssessmentExam\(todoId\)/);
assert.match(appJs, /\/api\/kanban\/cards\/\$\{encodeURIComponent\(todoId\)\}\/assessment-exam/);
assert.match(appJs, /data-assessment-exam-choice/);
assert.match(appJs, /function isKanbanAssessmentCard\(todo\)/);
assert.match(appJs, /status === "done"\s+&& !assessmentExamCompleted\(todo\)/);
assert.match(appJs, /compatible === "completed"\s+&& !assessmentExamCompleted\(todo\)/);
assert.match(appJs, /function kanbanAssessmentCaseCurrentItem\(group\)/);
assert.match(appJs, /function kanbanAssessmentVisibleCardItems\(group\)/);
assert.match(appJs, /const visibleCards = kanbanAssessmentVisibleCardItems\(group\)/);
assert.match(appJs, /function stripAssessmentConfigText\(text = ""\)/);
assert.match(appJs, /ASSESSMENT_CONFIG:\[A-Za-z0-9_-\]\+/);
assert.match(appJs, /function assessmentTemplateDisplayText\(group, currentTodo, firstTodo\)/);
assert.match(appJs, /function assessmentPriorComplete\(todo\)/);
assert.match(appJs, /return assessmentPriorComplete\(todo\)/);
assert.match(appJs, /function assessmentHasVisibleResult\(todo\)/);
assert.match(appJs, /isKanbanAssessmentCard\(todo\) && !assessmentHasVisibleResult\(todo\)/);
assert.match(appJs, /const next = cards\.find\(\(item\) => isKanbanAssessmentCard\(item\.todo\) && !assessmentExamCompleted\(item\.todo\) && normalizedKanbanStatus\(item\.todo\) !== "archived"\)/);
assert.match(appJs, /if \(!summary\.lastAttempt && !assessmentExamCompleted\(todo\)\) return \[\]/);
assert.match(appJs, /function renderKanbanAssessmentArchiveCase\(group, options = \{\}\)/);
assert.match(appJs, /阅读复述/);
assert.match(appJs, /通用学习/);
assert.match(appJs, /id="kanbanStudyPerformerWorkspace"/);
assert.match(appJs, /id="kanbanStudyViewerWorkspaces"/);
assert.match(appJs, /function renderKanbanPlanBindingPreview\(draft = \{\}, kind = "study"\)/);
assert.match(appJs, /data-kanban-binding-preview/);
assert.match(appJs, /updateKanbanPlanBindingPreview\(root, "study"\)/);
assert.match(appJs, /updateKanbanPlanBindingPreview\(root, "assessment"\)/);
assert.match(appJs, /id="kanbanReadingCover"/);
assert.match(appJs, /setKanbanReadingCoverFile\(file\)/);
assert.match(appJs, /coverImage/);
assert.match(appJs, /function renderKanbanCaseCover\(cover, options = \{\}\)/);
assert.match(appJs, /function loadKanbanCoverImages\(root = document\)/);
assert.match(appJs, /data-kanban-composer-mode="\$\{mode\}"/);
assert.match(appJs, /\/api\/kanban\/cards\/study-plan/);
assert.match(appJs, /function renderKanbanReadingSubmissionPanel\(todo\)/);
assert.match(appJs, /\/api\/kanban\/cards\/\$\{encodeURIComponent\(todoId\)\}\/reading-submission/);
assert.match(appJs, /function renderKanbanReadingQuizPanel\(todo\)/);
assert.match(appJs, /function loadReadingQuiz\(todoId\)/);
assert.match(appJs, /function submitReadingQuiz\(todoId\)/);
assert.match(appJs, /\/api\/kanban\/cards\/\$\{encodeURIComponent\(todoId\)\}\/reading-quiz/);
assert.match(appJs, /data-reading-quiz-choice/);
assert.match(appJs, /data-reading-quiz-next/);
assert.match(appJs, /reading-quiz-feedback/);
assert.match(appJs, /currentResult = resultItems\[step\]/);
assert.match(appJs, /result: null/);
assert.match(appJs, /function renderKanbanReadingWorkflowPanel\(todo\)/);
assert.match(appJs, /function isKanbanStudyCase\(todo\)/);
assert.match(appJs, /function kanbanActorPermissions\(todo\)/);
assert.match(appJs, /function kanbanCan\(todo, key\)/);
assert.match(appJs, /function kanbanCardWorkspaceId\(todoOrId\)/);
assert.match(appJs, /data-reading-workflow/);
assert.match(appJs, /分析已完成，下一步完成 10 题单选考卷/);
assert.match(appJs, /10 题全对后，本卡片才会完成/);
assert.match(appJs, /todoReadingSubmissionDrafts/);
assert.match(appJs, /todoReadingSubmitting/);
assert.match(appJs, /todoReadingSubmissionProgress/);
assert.match(appJs, /todoReadingQuizzes/);
assert.match(appJs, /todoReadingQuizAnswers/);
assert.match(appJs, /todoReadingQuizStep/);
assert.match(appJs, /data-reading-audio-status/);
assert.match(appJs, /todoReadingRecorders/);
assert.match(appJs, /function supportsKanbanReadingRecorder\(\)/);
assert.match(appJs, /MediaRecorder/);
assert.match(appJs, /navigator\.mediaDevices\.getUserMedia/);
assert.match(appJs, /data-reading-record-toggle/);
assert.match(appJs, /data-reading-record-submit/);
assert.match(appJs, /function submitRecordedReadingSubmission\(todoId, notes = ""\)/);
assert.match(appJs, /\u6d4f\u89c8\u5668\u4e0d\u652f\u6301\u76f4\u63a5\u5f55\u97f3/);
assert.match(stylesCss, /\.todo-reading-recorder-actions/);
assert.match(stylesCss, /\.todo-reading-record-button/);
assert.match(stylesCss, /\.todo-reading-playback/);
assert.match(stylesCss, /\.kanban-study-schedule-weekdays/);
assert.match(appJs, /先录音，停止生成音频后才能提交/);
assert.equal(appJs.includes('#readingSubmissionAudio")?.addEventListener("change"'), false);
assert.match(appJs, /<audio class="todo-reading-playback" controls/);
assert.match(appJs, /revokeKanbanReadingRecordingUrl/);
assert.match(appJs, /function parseWorkspaceIdList\(value\)/);
assert.match(appJs, /data-kanban-study-viewer-workspace/);
assert.match(appJs, /kanban-study-share-list/);
assert.match(appJs, /\$\{labels\.recording\}已开始上传，正在\$\{labels\.analysis\}/);
assert.match(appJs, /function cleanKanbanReadingResultText\(text\)/);
assert.match(appJs, /function isReadingPlanWaitingCard\(todo\)/);
assert.match(appJs, /function kanbanReadingCaseKey\(todo\)/);
assert.match(appJs, /function kanbanVisibleReadingTodoIds\(todos\)/);
assert.match(appJs, /function kanbanVisibleBoardTodos\(todos\)/);
assert.match(appJs, /function readingCardAcceptsSubmission\(todo\)/);
assert.match(appJs, /function readingCasePriorComplete\(todo\)/);
assert.match(appJs, /status === "blocked" && !readingCasePriorComplete\(todo\)/);
assert.match(appJs, /function kanbanReadingRevisionOriginal\(group, item\)/);
assert.match(appJs, /function kanbanReadingDisplayCardIndex\(group, item\)/);
assert.match(appJs, /function kanbanReadingBaseCardItems\(group\)/);
assert.match(appJs, /function kanbanReadingCaseCurrentItem\(group\)/);
assert.match(appJs, /const pendingQuiz = cards\.find\(\(item\) => readingSubmissionHasAnalysis\(item\.todo\) && !readingSubmissionCompleted\(item\.todo\)\)/);
assert.match(appJs, /function renderKanbanReadingArchiveCase\(group, options = \{\}\)/);
assert.match(appJs, /buttonText = readingSubmissionCompleted\(todo\) \? "查看答卷" : "开始答卷"/);
const readingCompletionFn = appJs.slice(
  appJs.indexOf("function readingSubmissionCompleted(todo)"),
  appJs.indexOf("function renderKanbanReadingWorkflowPanel(todo)"),
);
assert.equal(readingCompletionFn.includes("normalizedKanbanStatus"), false);
assert.match(readingCompletionFn, /summary\?\.completionError/);
const assessmentCompletionFn = appJs.slice(
  appJs.indexOf("function assessmentExamCompleted(todo)"),
  appJs.indexOf("function assessmentHasVisibleResult(todo)"),
);
assert.match(assessmentCompletionFn, /summary\?\.completionError/);
assert.match(serverJs, /completionError: ""/);
assert.match(serverJs, /operation: "manual_forward"[\s\S]{0,500}explicitUserApproved: true/);
assert.match(serverJs, /const sourceFile = resolved\.file \|\| fileResultFromBridgeFileForForward/);
assert.match(serverJs, /if \(resolved\?\.bridgeFile\) return \{ bridgeFile: resolved\.bridgeFile/);
assert.match(serverJs, /const publicTodoListContextCache = new WeakMap\(\)/);
assert.match(serverJs, /publicTodoWorkflowCompleted\(payload\)/);
assert.match(serverJs, /function kanbanWorkflowStateCompleted\(state = \{\}, officialDone = false\)/);
assert.match(serverJs, /officialDone && kanbanHasPassedAttempt\(state\)/);
assert.match(serverJs, /const invalidAnswers = questions/);
assert.match(serverJs, /Assessment answers are incomplete/);
assert.match(serverJs, /workflowInput\.priorComplete = priorContext\.priorComplete/);
assert.match(fs.readFileSync(path.join(repoRoot, "adapters", "kanban-card-provider.js"), "utf8"), /\.map\(\(row, index\) => publicCard\(row, index, rows\)\)/);
assert.match(fs.readFileSync(path.join(repoRoot, "adapters", "todo-provider.js"), "utf8"), /\.map\(\(row, index\) => publicTodo\(row, index, rows\)\)/);
const studyWorkflowProviderJs = fs.readFileSync(path.join(repoRoot, "adapters", "study-workflow-provider.js"), "utf8");
assert.match(studyWorkflowProviderJs, /function readingCompletionEvidence\(state = \{\}, officialDone = false\)/);
assert.match(studyWorkflowProviderJs, /officialDone && hasPassedAttempt\(state\)/);
assert.match(appJs, /group\.mode === "study-plan"/);
assert.match(appJs, /kanbanDisplayResultText\(todo, todo\.kanbanResult \|\| detail\?\.summary \|\| ""\)/);
assert.match(appJs, /detail && !readingCard \? renderKanbanProcessRows\(detail\) : ""/);
assert.match(appJs, /data-reading-submission-waiting/);
assert.match(appJs, /readingCardAcceptsSubmission\(item\.todo\)/);
assert.match(serverJs, /createKanbanStudyApiRoutes/);
assert.match(serverJs, /kanbanStudyApiRoutes\.handle\(req, res, url/);
assert.match(kanbanStudyApiRoutes, /path: "\/api\/kanban\/cards\/study-plan"/);
assert.match(kanbanStudyApiRoutes, /path: "\/api\/kanban\/cards\/assessment-plan"/);
assert.match(kanbanStudyApiRoutes, /assessment-exam/);
assert.equal(serverJs.includes('/api/kanban/cards/reading-plan'), false);
assert.match(serverJs, /function normalizeKanbanStudyTemplate\(raw = \{\}\)/);
assert.match(serverJs, /function chatGroupMemberWorkspaceIds\(thread, options = \{\}\)/);
assert.match(serverJs, /normalizeChatGroup\(thread\.chatGroup \|\| \{\}, thread\.workspaceId, options\)/);
assert.match(serverJs, /chatGroupMemberWorkspaceIds\(thread, options\)\.length/);
assert.match(serverJs, /function normalizeStudyPlanSchedule\(raw = \{\}, startDate = "", timeOfDay = ""\)/);
assert.match(serverJs, /function readingPlanScheduleDueTime\(schedule = \{\}, occurrenceIndex = 0\)/);
assert.match(serverJs, /scheduleFrequency: schedule\.frequency/);
assert.match(serverJs, /scheduleWeekdays: schedule\.weekdaysOneBased/);
assert.match(serverJs, /dueTime: readingPlanScheduleDueTime\(schedule, index\)/);
assert.match(serverJs, /caseTemplate: cardCaseTemplate/);
const studyPlanCreateFn = serverJs.slice(
  serverJs.indexOf("async function createKanbanStudyPlanCards(workspaceId, input = {})"),
  serverJs.indexOf("async function createKanbanAssessmentPlanCards(workspaceId, input = {}, options = {})"),
);
assert.match(studyPlanCreateFn, /const cardCaseTemplate = card\.caseTemplate \|\| plan\.template/);
assert.match(studyPlanCreateFn, /const cardSourceText = compactText/);
assert.match(serverJs, /function normalizeKanbanAssessmentPlan\(raw = \{\}, workspaceId = "owner", options = \{\}\)/);
assert.match(serverJs, /async function createKanbanAssessmentPlanCards\(workspaceId, input = \{\}, options = \{\}\)/);
assert.match(serverJs, /function generateVerifiedMathAssessmentQuestions\(config = \{\}, seedText = ""\)/);
assert.match(serverJs, /async function submitKanbanAssessmentExam\(workspaceId, cardId, body = \{\}\)/);
assert.match(serverJs, /Manual formal assessment is open in Hermes Mobile; parked from official worker execution\./);
assert.match(serverJs, /function kanbanAssessmentPriorComplete\(workspaceId, priorCards = \[\]\)/);
assert.match(serverJs, /function visibleKanbanCaseCards\(cards = \[\]\)/);
assert.match(serverJs, /kanbanCardEffectiveCaseIndex\(current, byId\)/);
assert.match(serverJs, /const canonicalCardId = String\(currentCard\.id \|\| cardId\)/);
assert.match(serverJs, /function generateVerifiedAmc8AssessmentQuestions\(config = \{\}, seedText = ""\)/);
assert.match(serverJs, /assessmentLooksLikeAmc8\(config, seedText\)/);
assert.match(serverJs, /function kanbanAssessmentArchived\(card = \{\}\)/);
assert.match(serverJs, /kanbanAssessmentCanStart\(currentCard, existing, context\.prior \|\| \[\], workspaceId\)/);
assert.match(serverJs, /caseTemplate: "final-assessment"/);
assert.match(serverJs, /const KANBAN_CASE_SHARE_PATH = path\.resolve/);
assert.match(serverJs, /function upsertKanbanCaseShare\(ownerWorkspaceId, caseId, input = \{\}\)/);
assert.match(serverJs, /KANBAN_STUDY_SHARED_FOLDER_NAME/);
assert.match(serverJs, /function kanbanStableTextKey\(value, fallback = "item"\)/);
assert.match(serverJs, /function kanbanLearnerRootDirectory\(ownerWorkspaceId, ownerRoot, plan = \{\}\)/);
assert.match(serverJs, /String\(record\?\.source \|\| ""\) !== "hermes-mobile-study-plan"/);
assert.match(serverJs, /function kanbanCaseDirectoryName\(plan = \{\}\)/);
assert.match(serverJs, /safeDirectoryName\(compactText\(kanbanCaseTopicTitle\(plan\), 96\)\)/);
assert.match(serverJs, /function kanbanCaseDirectoryPath\(ownerWorkspaceId, sharedRoot, plan = \{\}\)/);
assert.match(serverJs, /readKanbanCaseShare\(owner, plan\.id \|\| ""\)/);
assert.match(serverJs, /function ensureKanbanCaseSharedDirectory\(ownerWorkspaceId, plan = \{\}\)/);
assert.match(serverJs, /permission: "read_only"/);
assert.match(serverJs, /source: "hermes-mobile-study-plan"/);
assert.match(serverJs, /function ensureKanbanCaseTopicThread\(ownerWorkspaceId, plan = \{\}, directoryInfo = null\)/);
assert.match(serverJs, /kind: KANBAN_CASE_TOPIC_KIND/);
assert.match(serverJs, /if \(rawMeta\.sharedTopic\) out\[key\]\.sharedTopic = true/);
assert.match(serverJs, /kanbanCaseOwnerWorkspaceId/);
assert.match(serverJs, /topicThreadId/);
assert.match(serverJs, /caseTopicThreads/);
assert.match(serverJs, /function isReadOnlyCaseTopicDirectoryForAuth\(thread, auth, localPath, displayPath = ""\)/);
assert.match(serverJs, /This shared learning topic is read-only for the current workspace/);
assert.match(appJs, /caseTopicThreads: \[\]/);
assert.match(appJs, /function sharedCaseTopicGroupsForTaskList\(currentThread\)/);
assert.match(appJs, /data-open-task-thread/);
assert.match(appJs, /function openSharedTaskGroupFromList\(threadId, taskGroupId\)/);
assert.match(appJs, /function sharedTopicChatDisabledForSelectedWorkspace\(group\)/);
assert.match(appJs, /function selectedSharedTopicGroup\(\)/);
assert.match(appJs, /body\.singleWindowMode = "chat";\s*body\.messageKind = aiMention\.mentionsAi \? "ai" : "plain";/);
assert.match(appJs, /@ChatGPT \\u624d\\u4f1a\\u8c03\\u7528 AI/);
assert.match(appJs, /if \(group\?\.directoryRoute\) aliases\.push\(Object\.assign\(\{ source: "bound" \}, group\.directoryRoute\)\)/);
assert.match(appJs, /pathIsNested && displayAlias\.label/);
assert.match(appJs, /function messageUsesSenderLabel\(message\)/);
assert.match(appJs, /messageTaskGroup\(message\)\?\.sharedTopic/);
assert.match(appJs, /function userMessageSenderLabel\(message\)/);
assert.match(stylesCss, /\.shared-topic-card \.task-card-main/);
assert.match(stylesCss, /\.kanban-plan-binding-preview/);
assert.match(serverJs, /function kanbanCaseRoleForAuth\(auth, ownerWorkspaceId, caseId\)/);
assert.match(serverJs, /function sharedKanbanCardsForAuth\(auth, selectedWorkspaceId, listArgs = \{\}\)/);
assert.match(serverJs, /function kanbanCaseSharesForActor\(auth, selectedWorkspaceId = ""\)/);
assert.match(serverJs, /function kanbanShareActorWorkspaceId\(auth, selectedWorkspaceId = ""\)/);
assert.match(serverJs, /function kanbanCaseRoleForWorkspaceActor\(actorWorkspaceId, ownerWorkspaceId, caseId, auth = null\)/);
assert.match(serverJs, /const requestedCaseTopicChat = Boolean\(/);
assert.match(serverJs, /const isCaseTopicChatMessage = requestedCaseTopicChat && groupMemberIds\.length > 0/);
assert.match(serverJs, /\(isGroupChatMessage \|\| isCaseTopicChatMessage\) && String\(body\.messageKind/);
assert.match(serverJs, /annotateKanbanCardForAuth\(card, auth, \{ actorWorkspaceId \}\)/);
assert.match(serverJs, /isOwnerAuth\(auth\) && selected && selected !== "owner"/);
assert.match(kanbanCardApiRoutes, /kanbanCaseSharesForActor\(auth, workspaceId\)/);
assert.match(serverJs, /function resolveKanbanCardAccess\(req, res, workspaceId, cardId, capability = "view"\)/);
assert.match(serverJs, /reading-submission/);
assert.match(serverJs, /async function createKanbanStudyPlanCards\(workspaceId, input = \{\}\)/);
assert.match(serverJs, /function submitKanbanReadingSubmission\(workspaceId, cardId, body = \{\}\)/);
assert.match(serverJs, /function generateKanbanReadingQuiz\(workspaceId, cardId, currentCard, transcription, analysis, notes = ""\)/);
assert.match(serverJs, /function submitKanbanReadingQuiz\(workspaceId, cardId, body = \{\}\)/);
assert.match(serverJs, /function publicKanbanReadingQuiz\(quiz = \{\}\)/);
assert.match(serverJs, /function publicKanbanReadingSubmissionSummary\(workspaceId, card = \{\}\)/);
assert.match(serverJs, /KANBAN_READING_QUIZ_TARGETING_VERSION = "20260513-score-weakness-v1"/);
assert.match(serverJs, /dedicated quiz-target section with 3-5 concrete targets/);
assert.match(serverJs, /At least 7 of 10 questions must directly train weaknesses/);
assert.match(serverJs, /Calibrate difficulty from the analysis score/);
assert.match(serverJs, /function ensureKanbanReadingQuizTargeted\(workspaceId, cardId, currentCard, state = \{\}\)/);
assert.match(serverJs, /quizTargetingVersion: KANBAN_READING_QUIZ_TARGETING_VERSION/);
assert.match(serverJs, /payload\.readingSubmission = publicKanbanReadingSubmissionSummary\(workspaceId, payload\)/);
assert.match(serverJs, /function findKanbanReadingSubmissionState\(workspaceId, cardId, context = \{\}\)/);
assert.match(serverJs, /kanbanRevisionOf/);
assert.match(serverJs, /canonicalCardId: lookup\.cardId/);
assert.match(serverJs, /Study submission quiz passed/);
assert.match(serverJs, /Reading retelling quiz passed/);
assert.match(serverJs, /correctCount === 10/);
assert.match(serverJs, /reading-quiz/);
assert.match(serverJs, /caseDependsOn: index > 0 \? \[plan\.cards\[index - 1\]\.clientId\] : \[\]/);
assert.match(serverJs, /Waiting for previous study session completion; Hermes Mobile shows only the current study session\./);
assert.match(serverJs, /maybeReconcileKanbanDependencyBlocks\(workspaceId, \{ force: true, limit: 500 \}\)/);
assert.match(serverJs, /function saveKanbanReadingCoverUpload\(workspaceId, planId, rawCover = null\)/);
assert.match(serverJs, /kanbanCaseCover: publicKanbanCoverFile/);
assert.match(kanbanCardProviderJs, /case_cover: args\.caseCover/);
assert.match(kanbanProviderJs, /caseCover: payload\.case_cover/);
assert.match(kanbanProviderJs, /kanban_block_reason: String\(meta\.blockReason/);
assert.match(kanbanProviderJs, /caseTemplate: meta\.caseTemplate/);
assert.match(kanbanProviderJs, /kanban_case_template/);
assert.match(kanbanProviderJs, /"study-plan"/);
assert.match(kanbanProviderJs, /"assessment-plan"/);
assert.match(kanbanProviderJs, /caseMode === "study-plan" \|\| caseMode === "assessment-plan"/);
assert.match(serverJs, /transcribe-reading-audio\.ps1/);
assert.match(kanbanProviderJs, /const completionResult = String\(payload\.result/);
assert.match(appJs, /KANBAN_STORY_DETAIL_LOAD_LIMIT = 6/);
assert.match(appJs, /selectedStatus === KANBAN_STORY_STATUS\s+\? renderKanbanStoryTree\(todos\)/);
assert.match(appJs, /KANBAN_TAB_ORDER\.map\(\(status\) =>/);
assert.match(appJs, /state\.todoKanbanStatus = KANBAN_STORY_STATUS/);
assert.match(appJs, /function shouldLoadCompletedTodos\(options = \{\}\)/);
assert.match(appJs, /function kanbanComposerOpen\(\)/);
assert.match(appJs, /function kanbanComposerFocused\(\)/);
assert.match(appJs, /function syncKanbanComposerDraftFromDom\(\)/);
assert.match(appJs, /function todoRefreshShouldYieldToKanbanComposer\(options = \{\}\)/);
assert.match(appJs, /if \(kanbanComposerOpen\(\)\) \{\s+scheduleTodoAutoRefresh\(\);\s+return;/);
assert.match(appJs, /if \(todoRefreshShouldYieldToKanbanComposer\(options\)\) \{/);
assert.match(appJs, /const yieldToComposer = todoRefreshShouldYieldToKanbanComposer\(options\)/);
assert.match(appJs, /if \(includeCompleted\) params\.set\("includeCompleted", "1"\)/);
assert.match(appJs, /function scheduleTodoAutoRefresh\(\)/);
assert.match(appJs, /function readTodoListCache\(workspaceId, includeCompleted\)/);
assert.match(appJs, /function writeTodoListCache\(workspaceId, includeCompleted\)/);
assert.match(appJs, /function clearTodoListCache\(workspaceId = state\.selectedWorkspaceId \|\| "owner"\)/);
assert.match(appJs, /const cached = useCache \? readTodoListCache\(workspaceId, includeCompleted\) : null/);
assert.match(appJs, /todoWorkspaceId: ""/);
assert.match(appJs, /await loadTodos\(\{ preferCache: true \}\)/);
assert.match(appJs, /if \(cached\) \{/);
assert.match(appJs, /state\.todos\.length && state\.todoWorkspaceId === workspaceId && state\.todoCompletedLoaded === includeCompleted/);
assert.match(appJs, /loadTodos\(\{ preserveScroll: true, autoRefresh: true \}\)/);
assert.match(appJs, /kanbanStatusNeedsCompleted\(status\) && !state\.todoCompletedLoaded/);
assert.match(appJs, /!state\.todoCompletedLoaded && kanbanStatusNeedsCompleted\(status\) \? "\\u2026"/);
assert.match(appJs, /grouped\.set\("done", sortArchivedKanbanCards/);
assert.match(appJs, /grouped\.set\("archived", sortArchivedKanbanCards/);
assert.equal(appJs.includes("Official Hermes Kanban"), false);
assert.equal(appJs.includes("todo-kanban-summary"), false);
assert.equal(stylesCss.includes(".todo-kanban-summary"), false);
assert.match(appJs, /function normalizedKanbanStatus\(todo\)/);
assert.match(appJs, /todoKanbanStatus: initialTodoKanbanStatus\(\)/);
assert.ok(indexHtml.includes("\u8bdd\u9898"));
assert.ok(indexHtml.includes("\u770b\u677f"));
assert.ok(indexHtml.includes("\u8bdd\u9898\u5217\u8868"));
assert.ok(indexHtml.includes("\u8bdd\u9898\u6d41"));
assert.ok(indexHtml.includes("\u65b0\u5efa\u8bdd\u9898"));
assert.ok(indexHtml.includes("\u65b0\u589e\u4efb\u52a1"));
assert.ok(appJs.includes("\u5f00\u542f\u8bdd\u9898"));
assert.equal(appJs.includes("\u5f00\u542f\u4efb\u52a1"), false);
assert.ok(appJs.includes("New topic"));
assert.ok(appJs.includes("\u770b\u677f\u8be6\u60c5"));
assert.ok(appJs.includes("\u65b0\u589e\u5361\u7247"));
assert.ok(appJs.includes("Topic ID"));
assert.ok(indexHtml.includes("20260514-story-swipe-font-preferences"));
assert.ok(serviceWorkerJs.includes("20260514-story-swipe-font-preferences"));
assert.match(indexHtml, /hermesWebFontFamily/);
assert.match(indexHtml, /--app-font-family/);
assert.match(indexHtml, /id="chatManagementMode"/);
assert.match(appJs, /\$\("chatManagementMode"\)\?\.addEventListener\("click"/);
assert.match(appJs, /\$\("chatManagementMode"\)\?\.classList\.toggle\("active", single && state\.singleWindowMode === "chat"\)/);
assert.match(stylesCss, /\.section-toggle \{[\s\S]*?grid-template-columns: repeat\(5, minmax\(0, 1fr\)\)/);
assert.match(stylesCss, /@media \(max-width: 1099px\)/);
assert.match(appJs, /window\.matchMedia\("\(max-width: 1099px\)"\)/);
assert.match(appJs, /const mainBack = taskDetail \|\| todoDetail \|\| todoCreate \|\| automationDetail \|\| skillDetail \|\| directoryBack/);
assert.match(stylesCss, /\.main-back-visible \.top-nav-button \{[\s\S]*?display: grid;/);
assert.match(serverJs, /groupChatAvailable/);
assert.match(serverJs, /groupChatThreadId/);
assert.match(serverJs, /groupChatThread/);
assert.match(serverJs, /weixinChatAvailable/);
assert.match(serverJs, /weixinChatThreadId/);
assert.match(serverJs, /weixinChatThread/);
assert.match(stylesCss, /--mobile-bottom-nav-height: calc\(80px \+ env\(safe-area-inset-bottom\)\)/);
assert.match(stylesCss, /--mobile-bottom-nav-reserved-height/);
assert.match(stylesCss, /calc\(var\(--mobile-bottom-nav-height\) \+ 12px\)/);
assert.match(appJs, /Math\.max\(96, rectHeight \+ 12, contentHeight \+ 12\)/);
assert.match(stylesCss, /@media \(max-width: 1099px\) and \(orientation: landscape\) and \(max-height: 620px\)/);
assert.match(stylesCss, /--mobile-bottom-nav-height: calc\(50px \+ env\(safe-area-inset-bottom\)\)/);
assert.match(stylesCss, /--mobile-bottom-nav-reserved-height-runtime, calc\(var\(--mobile-bottom-nav-height\) \+ 8px\)/);
assert.match(stylesCss, /\.bottom-tab-label \{[\s\S]*?display: none;/);
assert.match(stylesCss, /\.thread-meta \{[\s\S]*?display: none;/);
assert.match(appJs, /function isMobileLandscapeCompactLayout\(\)/);
assert.match(appJs, /window\.matchMedia\("\(max-width: 1099px\) and \(orientation: landscape\) and \(max-height: 620px\)"\)/);
assert.match(appJs, /Math\.max\(62, rectHeight \+ 8, contentHeight \+ 8\)/);
assert.match(indexHtml, /id="topToggleReadingFullscreen"/);
assert.match(indexHtml, /id="readingFullscreenEnter"/);
assert.match(indexHtml, /id="readingFullscreenExit"/);
assert.match(indexHtml, /id="readingFullscreenExit"[^>]*>\s*&times;<\/button>/);
assert.match(appJs, /readingFullscreen: false/);
assert.match(appJs, /function setReadingFullscreen\(enabled\)/);
assert.match(appJs, /setReadingFullscreen\(!state\.readingFullscreen\)/);
assert.match(appJs, /updateNavigationControls\(\);\s+applyViewMode\(\);/);
assert.match(appJs, /\$\("readingFullscreenEnter"\)\?\.addEventListener\("click"/);
assert.match(stylesCss, /\.reading-fullscreen-mode \.topbar,[\s\S]*?\.reading-fullscreen-mode \.composer,[\s\S]*?\.reading-fullscreen-mode \.bottom-nav \{[\s\S]*?display: none !important;/);
assert.match(stylesCss, /\.reading-fullscreen-mode \.main \{[\s\S]*?grid-template-rows: minmax\(0, 1fr\)/);
assert.match(stylesCss, /\.reading-fullscreen-mode \.reading-fullscreen-exit \{[\s\S]*?position: fixed;/);
assert.match(stylesCss, /@media \(max-width: 1099px\) and \(orientation: landscape\) \{[\s\S]*?\.reading-fullscreen-enter \{/);
assert.match(stylesCss, /\.reading-fullscreen-mode \.reading-fullscreen-exit \{[\s\S]*?font-size: 17px;/);
assert.match(stylesCss, /padding-bottom: var\(--mobile-bottom-nav-reserved-height\)/);
assert.match(stylesCss, /height: var\(--mobile-bottom-nav-height\)/);
assert.match(appJs, /function currentTodoKanbanStatus\(grouped\)/);
assert.match(appJs, /data-kanban-status="\$\{escapeHtml\(status\)\}"/);
assert.match(appJs, /localStorage\.setItem\("hermesTodoKanbanStatus", status\)/);
assert.match(appJs, /function renderTodoList\(\) \{\s+const list = \$\("threadList"\);\s+if \(!list\) return;\s+list\.innerHTML = "";\s+return;/);
assert.match(appJs, /function renderAutomationList\(\) \{\s+const list = \$\("threadList"\);\s+if \(!list\) return;\s+list\.innerHTML = "";\s+return;/);
assert.match(appJs, /function projectDisplayLabel\(project\) \{\s+return project\?\.label \|\| project\?\.id \|\| "Project";\s+\}/);
assert.match(appJs, /function renderDirectorySharedBadge\(project\)/);
assert.match(appJs, /directory-shared-badge/);
assert.doesNotMatch(appJs, /sharedDelta/);
assert.match(appJs, /localeCompare\(String\(directoryRootProjectLabel\(b\.project\)\), "zh-Hans-CN", \{ numeric: true, sensitivity: "base" \}\)/);
assert.match(stylesCss, /\.directory-shared-badge \{/);
assert.match(appJs, /data-block-todo/);
assert.match(appJs, /data-unblock-todo/);
assert.match(appJs, /data-todo-comment-form/);
assert.match(appJs, /data-comment-unblock-todo/);
assert.match(appJs, /data-todo-revision-form/);
assert.match(appJs, /data-revise-todo/);
assert.match(appJs, /function commentAndUnblockTodo\(todoId, comment\)/);
assert.match(appJs, /function requestTodoRevision\(todoId, comment\)/);
assert.match(appJs, /function syncTodoDetailDraftFromDom\(input = null\)/);
assert.match(appJs, /function restoreTodoDetailDraftFocus\(focus = null\)/);
assert.match(appJs, /todoRevisionDrafts/);
assert.match(appJs, /todoCommentDrafts/);
assert.match(appJs, /todoRevisionSubmitting/);
assert.match(appJs, /正在创建修改任务，请勿重复提交/);
assert.match(appJs, /正在创建\.\.\./);
assert.match(appJs, /boardActionApiPath\(todoId, "revise"\)/);
assert.match(appJs, /function boardCollectionApiPath\(\)/);
assert.match(appJs, /function boardActionApiPath\(todoId, action = ""\)/);
assert.match(appJs, /\/api\/kanban\/cards/);
assert.match(appJs, /const KANBAN_MULTI_AGENT_DEFAULT_PARALLEL = 3/);
assert.match(appJs, /const KANBAN_MULTI_AGENT_MAX_PARALLEL = 8/);
assert.match(appJs, /function renderKanbanComposerPanel\(\)/);
assert.match(appJs, /function renderKanbanMultiAgentControls\(disabled = false\)/);
assert.match(appJs, /id="kanbanComposerMaxParallel"/);
assert.match(appJs, /id="kanbanComposerReasoningEffort"/);
assert.match(appJs, /function renderKanbanComposerDocumentPanel\(disabled = false\)/);
assert.match(appJs, /id="kanbanComposerDocument"/);
assert.match(appJs, /\/api\/kanban\/cards\/document-preview/);
assert.match(appJs, /function kanbanComposerSubmissionText\(rawText = ""\)/);
assert.match(appJs, /function renderKanbanCreatePage\(\)/);
assert.match(appJs, /function renderKanbanComposerProgress\(\)/);
assert.match(appJs, /const KANBAN_PLAN_PROGRESS_STEPS = Object\.freeze/);
assert.match(appJs, /const KANBAN_CREATE_PROGRESS_STEPS = Object\.freeze/);
assert.match(appJs, /const KANBAN_ASSESSMENT_PROGRESS_STEPS = Object\.freeze/);
assert.match(appJs, /beginKanbanComposerProgress\(assessmentPlan \? "assessment" : \(studyPlan \? "reading" : \(multiAgent \? "plan" : "create"\)\)\)/);
assert.match(appJs, /modeButton\("study", "\\u5b66\\u4e60\\u8ba1\\u5212", studyActive\)/);
assert.match(appJs, /modeButton\("assessment", "\\u8003\\u8bd5\\u8ba1\\u5212", assessmentActive\)/);
assert.match(appJs, /beginKanbanComposerProgress\("create"\)/);
assert.match(appJs, /creating\s+\?\s+renderKanbanCreatePage\(\)/);
assert.match(appJs, /newTodo\.textContent = "\\u65b0\\u589e\\u4efb\\u52a1"/);
assert.match(appJs, /!state\.todoCreateOpen && !busy/);
assert.match(appJs, /id="kanbanComposerForm"/);
assert.match(appJs, /data-kanban-composer-mode="\$\{mode\}"/);
assert.match(appJs, /function saveKanbanComposerMode\(mode\)/);
assert.match(appJs, /state\.kanbanComposerMultiAgent = next === "multi"/);
assert.match(appJs, /restoreKanbanComposerFocus/);
assert.match(appJs, /input\.focus\(\{ preventScroll: true \}\)/);
assert.match(appJs, /data-close-todo-create/);
assert.match(appJs, /\\u521b\\u5efa\\u4efb\\u52a1/);
assert.match(appJs, /state\.todoCreateOpen = false;/);
assert.match(appJs, /\$\("topNewTodo"\)\?\.addEventListener\("click", \(\) => \{\s+closeTopMoreMenu\(\);\s+openTodoCreate\(\);/);
assert.match(appJs, /function renderKanbanPlanDraft\(plan\)/);
assert.match(appJs, /data-create-kanban-plan/);
assert.match(appJs, /\/api\/kanban\/cards\/plan/);
assert.match(appJs, /\/api\/kanban\/cards\/batch/);
assert.match(appJs, /reasoning_effort: reasoningEffort/);
assert.match(appJs, /reasoning_effort: state\.kanbanPlanDraft\?\.reasoningEffort \|\| state\.kanbanComposerReasoningEffort \|\| ""/);
assert.match(appJs, /maxParallel: normalizeKanbanComposerMaxParallel\(state\.kanbanPlanDraft\?\.maxParallel \|\| state\.kanbanComposerMaxParallel\)/);
assert.match(appJs, /kanbanCaseSourceText/);
assert.match(appJs, /kanbanCaseSummary/);
assert.match(appJs, /kanbanCaseCardIndex/);
assert.match(stylesCss, /\.kanban-composer-panel/);
assert.match(stylesCss, /\.kanban-create-page/);
assert.match(stylesCss, /\.kanban-create-mode-button\.active/);
assert.match(stylesCss, /\.kanban-multi-agent-controls/);
assert.match(stylesCss, /\.kanban-document-source/);
assert.match(stylesCss, /\.kanban-document-source-list/);
assert.match(stylesCss, /\.kanban-create-progress/);
assert.match(stylesCss, /\.kanban-plan-draft/);
assert.match(stylesCss, /\.kanban-archive-stories/);
assert.match(stylesCss, /\.kanban-archive-case::before/);
assert.match(stylesCss, /\.kanban-archive-case\.study-plan-case::before/);
assert.match(stylesCss, /\.kanban-archive-case\.assessment-plan-case::before/);
assert.match(stylesCss, /\.kanban-archive-case\.single-card-case::before/);
assert.match(stylesCss, /\.kanban-archive-case-head \{[\s\S]*?border-bottom: 1px solid rgba\(20, 32, 39, 0\.08\)/);
assert.match(stylesCss, /\.kanban-archive-case\.story-collapsed \.kanban-archive-case-head \{[\s\S]*?border-bottom: 0;/);
assert.match(stylesCss, /\.kanban-archive-case\.story-collapsed > :not\(\.kanban-archive-case-head\)/);
assert.match(stylesCss, /\.kanban-archive-case-toggle/);
assert.match(stylesCss, /\.kanban-archive-case-action/);
assert.match(stylesCss, /\.kanban-archive-case-action\.danger/);
assert.match(stylesCss, /\.kanban-archive-story-grid/);
assert.match(stylesCss, /\.kanban-archive-card-chain/);
assert.match(stylesCss, /\.kanban-archive-card-feedback/);
assert.match(stylesCss, /\.todo-revision-panel/);
assert.match(stylesCss, /\.todo-reading-quiz-panel/);
assert.match(stylesCss, /\.reading-quiz-choice/);
assert.match(stylesCss, /\.reading-quiz-feedback/);
assert.match(stylesCss, /overflow-wrap: anywhere/);
assert.match(kanbanCardApiRoutes, /complete\|cancel\|postpone\|delete\|block\|unblock\|comment\|revise/);
assert.match(serverJs, /const KANBAN_MULTI_AGENT_DEFAULT_PARALLEL = 3/);
assert.match(serverJs, /HERMES_MOBILE_KANBAN_MULTI_AGENT_MAX_PARALLEL/);
assert.match(serverJs, /const KANBAN_SOURCE_DOCUMENT_MAX_BYTES = Math\.max/);
assert.match(serverJs, /function normalizeKanbanMaxParallel\(value\)/);
assert.match(serverJs, /function normalizeKanbanPlanReasoningEffort\(value\)/);
assert.match(serverJs, /async function planKanbanMultiAgent\(text, workspace, ownerPrincipalId, options = \{\}\)/);
assert.match(serverJs, /function normalizeKanbanPlan\(raw, sourceText, workspaceId, options = \{\}\)/);
assert.match(serverJs, /async function createKanbanPlanCards\(workspaceId, planInput, options = \{\}\)/);
assert.match(serverJs, /function kanbanSingleCardCasePayload\(content, description = "", sourceText = ""\)/);
assert.match(serverJs, /caseId: plan\.id/);
assert.match(serverJs, /caseSourceText: compactText\(plan\.sourceText, 2000\)/);
assert.match(serverJs, /caseCardIndex: cardIndex \+ 1/);
assert.match(kanbanCardApiRoutes, /path: "\/api\/kanban\/cards\/plan"/);
assert.match(kanbanCardApiRoutes, /path: "\/api\/kanban\/cards\/batch"/);
assert.match(kanbanCardApiRoutes, /path: "\/api\/kanban\/cards\/document-preview"/);
assert.match(serverJs, /function saveKanbanSourceDocumentUpload\(workspaceId, body = \{\}\)/);
assert.match(serverJs, /function extractKanbanSourceDocumentText\(upload\)/);
assert.match(serverJs, /reasoning_effort: reasoningEffort/);
assert.match(serverJs, /reasoningEffort,/);
assert.match(serverJs, /Requested reasoning effort: \$\{reasoningEffort\}/);
assert.match(kanbanCardApiRoutes, /body\.maxParallel \?\? body\.max_parallel/);
assert.match(serverJs, /Waiting for a free multi-Agent execution slot/);
assert.match(serverJs, /async function maybeReconcileKanbanDependencyBlocks\(workspaceId, options = \{\}\)/);
assert.match(serverJs, /action: "dependency-unblocked"/);
assert.match(serverJs, /KANBAN_BLOCKED_PUSH_DELAY_MINUTES/);
assert.match(serverJs, /function kanbanExecutableProfileForWorkspace\(workspaceId, principalId, requestedAssignee = ""\)/);
assert.match(serverJs, /assigneeForWorkspace: kanbanExecutableProfileForWorkspace/);
assert.match(serverJs, /const kanbanExecutableProfileCursor = new Map\(\)/);
assert.match(serverJs, /function nextKanbanExecutableProfile\(workspace, workers\)/);
assert.match(kanbanProviderJs, /const left = a\.updated_at \|\| a\.created_at \|\| a\.due_at \|\| ""/);
assert.match(kanbanProviderJs, /const byRecent = String\(right\)\.localeCompare\(String\(left\)\)/);
assert.match(kanbanProviderJs, /const leftOpen = a\.status === "open" && OPEN_KANBAN_STATUSES\.has/);
assert.match(kanbanProviderJs, /if \(leftOpen !== rightOpen\) return leftOpen \? -1 : 1/);
assert.match(appJs, /评论并解除阻塞/);
assert.match(appJs, /function renderKanbanDetailReport\(todo\)/);
assert.match(appJs, /\/api\/kanban\/cards\/\$\{encodeURIComponent\(id\)\}\/detail/);
assert.match(appJs, /params\.set\("logTail", "4000"\)/);
assert.match(appJs, /function shouldAutoLoadKanbanDetail\(todo\)/);
assert.match(appJs, /!String\(todo\?\.kanbanResult \|\| ""\)\.trim\(\) && !kanbanCardOutputs\(todo\)\.length/);
assert.match(appJs, /window\.setTimeout\(\(\) => loadKanbanCardDetail\(selected\.id\)\.catch\(showError\), 0\)/);
assert.doesNotMatch(appJs, /renderTodos\(\);\s+loadKanbanCardDetail\(state\.selectedTodoId\)/);
assert.match(appJs, /const previousScrollTop = conversation \? conversation\.scrollTop : 0/);
assert.match(appJs, /const nextScrollTop = Number\.isFinite\(options\.restoreScrollTop\) \? options\.restoreScrollTop : previousScrollTop/);
assert.match(appJs, /const finalRestoreScrollTop = options\.preserveScroll && conversation \? conversation\.scrollTop : restoreScrollTop/);
assert.match(appJs, /data-load-kanban-detail="\$\{escapeHtml\(todo\.id\)\}"\$\{loading \? " disabled" : ""\}/);
assert.match(appJs, /class="todo-detail-meta"/);
assert.match(appJs, /function dedupeKanbanOutputs\(outputs\)/);
assert.match(appJs, /function kanbanCardOutputs\(todo\)/);
assert.match(appJs, /function renderKanbanDeliveryFiles\(todo\)/);
assert.match(appJs, /\$\{coverBlock\}\s+\$\{readingWorkflowBlock\}\s+\$\{deliveryBlock\}\s+\$\{resultBlock\}\s+\$\{readingPanel\}\s+\$\{readingQuizBlock\}\s+\$\{assessmentExamBlock\}\s+\$\{metaBlock\}/);
assert.match(appJs, /pendingReadingQuizTodoId/);
assert.match(appJs, /params\.get\("readingQuiz"\)/);
assert.match(appJs, /await loadReadingQuiz\(todoId\)/);
assert.match(appJs, /const canonicalId = String\(result\.canonicalCardId \|\| todoId \|\| ""\)/);
assert.match(appJs, /state\.selectedTodoId = canonicalId/);
assert.match(appJs, /quizState\?\.quiz \|\| readingSubmissionHasAnalysis\(todo\)/);
assert.match(appJs, /function kanbanOutputHref\(item\)/);
assert.match(fileViewerHtml, /\/api\/kanban\/cards\/output\/preview/);
assert.match(kanbanCardApiRoutes, /path: "\/api\/kanban\/cards\/output"/);
assert.match(kanbanCardApiRoutes, /path: "\/api\/kanban\/cards\/output\/preview"/);
assert.match(kanbanCardApiRoutes, /publicKanbanCardDetail\(workspaceId, result\)/);
assert.match(serverJs, /function publicKanbanOutputsFromText\(workspaceId, text\)/);
assert.match(serverJs, /kanbanOutputs: publicKanbanOutputsFromText\(workspaceId, kanbanResult\)/);
assert.match(serverJs, /payload\.kanbanResult = ""/);
assert.match(serverJs, /payload\.kanbanOutputs = \[\]/);
assert.match(kanbanProviderJs, /workspace_id: String\(meta\.workspaceId \|\| meta\.workspace_id \|\| payload\.workspace_id \|\| payload\.workspaceId \|\| ""\)/);
assert.match(kanbanProviderJs, /let runs = Array\.isArray\(show\?\.runs\) \? show\.runs : \[\]/);
assert.match(kanbanProviderJs, /const includeLog = bool\(payload\.include_log \|\| payload\.includeLog\)/);
assert.match(serverJs, /txt\|json\|csv\|html\?\|zip/);
assert.match(stylesCss, /\.todo-detail-outputs/);
assert.match(stylesCss, /\.todo-detail-deliverables/);
assert.match(stylesCss, /\.todo-detail-meta/);
assert.match(stylesCss, /--kanban-receipt-body-size: 16px/);
assert.match(stylesCss, /--kanban-receipt-body-size: 16\.5px/);
assert.match(stylesCss, /--kanban-receipt-body-size: 15\.5px/);
assert.match(appJs, /const kanban = isKanbanTodoSource\(\);/);
assert.match(appJs, /if \(!kanban && !dueValue\) throw new Error\("Todo due time is required"\)/);
assert.match(appJs, /state\.todoKanbanStatus = "todo"/);
assert.match(serverJs, /kanbanAssignee: String\(row\.kanban_assignee/);
assert.match(stylesCss, /\.todo-kanban-board/);
assert.match(stylesCss, /\.todo-kanban-switcher/);
assert.match(stylesCss, /\.todo-kanban-tab/);
assert.match(stylesCss, /\.todo-kanban-current/);
assert.match(stylesCss, /\.todo-kanban-lane/);
assert.match(stylesCss, /\.todo-kanban-card/);
assert.match(stylesCss, /\.todo-kanban-card-title \{[\s\S]*?font-weight: 600;/);
assert.match(stylesCss, /\.todo-kanban-tab-label \{[\s\S]*?font-weight: 560;/);
assert.match(stylesCss, /\.todo-detail-head h2 \{[\s\S]*?font-weight: 600;/);
assert.match(serverJs, /THREAD_MESSAGE_INITIAL_LIMIT/);
assert.match(serverJs, /function directTodoCreateEnabled\(\)/);
assert.match(serverJs, /return false;/);
assert.match(serverJs, /function detectDirectKanbanCreateRequest\(text\)/);
assert.match(serverJs, /async function interpretKanbanNaturalLanguage\(text, workspace, ownerPrincipalId\)/);
assert.match(kanbanCardApiRoutes, /path: "\/api\/kanban\/cards"/);
assert.ok(serverJs.includes("\u770b\u677f"));
assert.ok(serverJs.includes("\u5361\u7247"));
assert.ok(serverJs.includes("kanban|board"));
assert.match(serverJs, /新增\|新建\|创建\|增加\|添加/);
assert.match(serverJs, /已新增看板卡片/);
assert.match(serverJs, /Do not run raw `hermes kanban` CLI commands/);
assert.match(serverJs, /function threadMessagesPage\(thread, options = \{\}\)/);
assert.match(serverJs, /function searchThreadMessages\(thread, options = \{\}\)/);
assert.match(serverJs, /mode === "tasks" \|\| mode === "task"/);
assert.match(serverJs, /function singleWindowChatTaskGroupId\(requestedTaskGroupId = ""\)/);
assert.match(serverJs, /next\.singleWindowMode === "chat"[\s\S]*?next\.taskGroupId = singleWindowChatTaskGroupId\(next\.taskGroupId\)/);
assert.match(serverJs, /function isExternalIngressThread\(thread\)/);
assert.match(serverJs, /&& !isExternalIngressThread\(thread\)/);
assert.match(serverJs, /const externalIngressThreads = \(state\.threads \|\| \[\]\)\.filter/);
assert.match(serverJs, /state\.threads = \(state\.threads \|\| \[\]\)\.filter\(\(thread\) => thread\.id !== externalThread\.id\)/);
assert.match(serverJs, /function weixinIngressThreadForEvent\(event, workspaceId\) \{\s+return ensureWeixinSingleWindowThread\(workspaceId, event\);\s+\}/);
assert.match(serverJs, /weixinIngressProvider\.isInboundHeartbeatEvent\(event\)/);
assert.match(serverJs, /heartbeat: true/);
assert.match(serverJs, /reason: workspace \? "weixin_ingress_heartbeat" : "unmatched_workspace_route"/);
assert.match(serverJs, /wakeWeixinOutboundDeliveriesForInboundEvent\(event, workspaceId\)/);
assert.ok(serverJs.indexOf("weixinIngressProvider.isInboundHeartbeatEvent(event)") < serverJs.indexOf("startRunForThread(thread, userMessage, assistantMessage, runOptions)"));
assert.match(weixinIngressProviderJs, /function isInboundHeartbeatEvent\(event\)/);
assert.match(weixinIngressProviderJs, /text === "#" \|\| text === "＃"/);
assert.match(serverJs, /const taskGroupId = SINGLE_WINDOW_CHAT_TASK_GROUP_ID;/);
assert.match(serverJs, /singleWindowMode === "chat" \? singleWindowChatTaskGroupId\(requestedTaskGroupId\) : \(requestedTaskGroupId \|\| makeId\("task"\)\)/);
assert.match(serverJs, /singleWindowMode === "chat"\s+\? "The latest user message is a Hermes Mobile continuous-chat turn/);
assert.equal(serverJs.includes("\"weixin-chat\""), false);
assert.match(serverJs, /&& !isWeixinSingleWindowThread\(thread\)/);
assert.match(serverJs, /params\.weixinChat = "1"/);
assert.match(serverJs, /compactThreadWithMessagePage\(thread/);
assert.match(serverJs, /createThreadReadUploadApiRoutes/);
assert.match(serverJs, /threadReadUploadApiRoutes\.handle\(req, res, url/);
assert.match(threadReadUploadApiRoutes, /thread-messages-list/);
assert.match(threadReadUploadApiRoutes, /handleThreadMessagesList/);
assert.match(appJs, /const CHAT_MESSAGE_INITIAL_LIMIT = 60/);
assert.match(appJs, /const TASK_MESSAGE_INITIAL_LIMIT = 300/);
assert.match(appJs, /const messageMode = isSingleWindowChatView\(\)/);
assert.match(appJs, /messageMode === "tasks" \? TASK_MESSAGE_INITIAL_LIMIT : CHAT_MESSAGE_INITIAL_LIMIT/);
assert.match(appJs, /function loadOlderChatMessages\(\)/);
assert.match(appJs, /maybeLoadOlderChatMessages\(\)/);
assert.match(appJs, /\/messages\?\$\{params\}/);
assert.match(appJs, /function renderChatHistoryPager\(thread\)/);
assert.match(appJs, /body\.messageLimit = CHAT_MESSAGE_INITIAL_LIMIT/);
assert.match(stylesCss, /\.chat-history-pager/);
assert.match(serverJs, /function verifyDirectTodoCreateResult\(todo\)/);
assert.match(serverJs, /Todo created but no visible card id returned\./);
assert.match(serverJs, /function formatDirectTodoCreateSuccessMessage\(intent, todo\)/);
assert.match(serverJs, /ID: \$\{id\}/);
assert.match(serverJs, /verification: directTodoVerification/);

console.log("task list UI tests passed");
