"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const repoRoot = path.resolve(__dirname, "..");
const appJs = fs.readFileSync(path.join(repoRoot, "public", "app.js"), "utf8");
const indexHtml = fs.readFileSync(path.join(repoRoot, "public", "index.html"), "utf8");
const serviceWorkerJs = fs.readFileSync(path.join(repoRoot, "public", "service-worker.js"), "utf8");
const fileViewerHtml = fs.readFileSync(path.join(repoRoot, "public", "file-viewer.html"), "utf8");
const pdfViewerHtml = fs.readFileSync(path.join(repoRoot, "public", "pdf-viewer.html"), "utf8");
const stylesCss = fs.readFileSync(path.join(repoRoot, "public", "styles.css"), "utf8");
const serverJs = fs.readFileSync(path.join(repoRoot, "server.js"), "utf8");
const kanbanProviderJs = fs.readFileSync(path.join(repoRoot, "adapters", "kanban-provider.js"), "utf8");
const kanbanCardProviderJs = fs.readFileSync(path.join(repoRoot, "adapters", "kanban-card-provider.js"), "utf8");
const weixinIngressProviderJs = fs.readFileSync(path.join(repoRoot, "adapters", "weixin-ingress-provider.js"), "utf8");

assert.match(appJs, /function taskGroupsForThread\(thread\)/);
assert.match(appJs, /return \[\.\.\.groups\.values\(\)\]\.sort\(\(a, b\) => String\(b\.updatedAt\)\.localeCompare\(String\(a\.updatedAt\)\)\);/);
assert.match(appJs, /const allGroups = taskListGroupsForThread\(thread\);\s+const displayGroups = allGroups\.slice\(\);/);
assert.equal(appJs.includes("allGroups.slice().reverse()"), false);
assert.ok(appJs.includes("(?:\\/[A-Za-z0-9_.-]+)+"));
assert.equal(appJs.includes("namedSkillPattern"), false);
assert.match(indexHtml, /id="taskRenameOverlay"/);
assert.match(appJs, /function openTaskRenameDialog\(currentTitle\)/);
assert.match(appJs, /function selectTaskRenameInput\(input\)/);
assert.match(appJs, /input\.setSelectionRange\(0, input\.value\.length\)/);
assert.match(appJs, /input\.select\(\)/);
assert.match(appJs, /const nextTitle = await openTaskRenameDialog\(currentTitle\)/);
assert.doesNotMatch(appJs, /taskStatus\(group\)} \|/);
assert.equal(appJs.includes("task-doc-empty\">No doc"), false);
assert.match(appJs, /const latestArtifact = latestTaskListDocument\(group\);/);
assert.match(appJs, /const artifactChips = latestArtifact \?/);
assert.match(appJs, /\$\{artifactChips\}/);
assert.match(appJs, /function messageExtractedDirectoryAliases\(message\)/);
assert.match(appJs, /for \(const message of group\?\.messages \|\| \[\]\) \{\s+const candidates = usableTaskBindingAliases/);
assert.match(appJs, /const exactProject = candidates\.find\(\(candidate\) =>\s+candidate\.projectId === requestedProjectId && String\(candidate\.subprojectId \|\| ""\) === requestedSubprojectId\)/);
assert.match(appJs, /const rootProject = candidates\.find\(\(candidate\) =>\s+candidate\.projectId === requestedProjectId && !candidate\.subprojectId\)/);
assert.match(stylesCss, /\.task-rename-sheet/);
assert.match(appJs, /function renderOwnerElevationPanel\(\)/);
assert.match(appJs, /function openOwnerElevationApprovalDialog\(options = \{\}\)/);
assert.match(appJs, /\/api\/owner-elevation/);
assert.match(appJs, /body\.maintenanceMode = true/);
assert.match(appJs, /owner_high_privilege/);
assert.match(stylesCss, /\.workspace-permission-panel/);
assert.match(stylesCss, /\.owner-elevation-approval-actions/);
assert.match(indexHtml, /id="ownerElevationApprovalOverlay"/);
assert.match(serverJs, /function publicOwnerElevationStatus\(auth\)/);
assert.match(serverJs, /url\.pathname === "\/api\/owner-elevation"/);
assert.match(serverJs, /url\.pathname === "\/api\/owner-elevation\/once"/);
assert.match(serverJs, /function grantOwnerElevationOnce\(auth\)/);
assert.match(serverJs, /function consumeOwnerElevationOnce\(auth, token\)/);
assert.match(serverJs, /consumeOwnerElevationOnce\(auth, onceToken\) \|\| isOwnerElevationActive\(auth\)/);
assert.match(serverJs, /isOwnerElevationActive\(auth\)/);
assert.match(serverJs, /HERMES_PERMISSION_APPROVAL_REQUIRED/);
assert.match(serverJs, /function modelPermissionApprovalRequest\(text, message = \{\}\)/);
assert.match(serverJs, /elevationRequired: Boolean\(message\.elevationRequired\)/);
assert.match(serverJs, /messages\\\/\(\[\^\/\]\+\)\\\/owner-elevation/);
assert.match(serverJs, /gatewaySecurityLevel: gatewayRouting\.securityLevel/);
assert.match(serverJs, /gatewayMaintenance: Boolean\(gatewayRouting\.maintenance/);
assert.match(serverJs, /gatewayMaintenanceCategory: gatewayRouting\.maintenanceCategory/);
assert.match(appJs, /function offerOwnerElevationForMessage\(message\)/);
assert.match(appJs, /ownerElevationPromptedMessageIds/);
assert.match(appJs, /await openOwnerElevationApprovalDialog/);
assert.doesNotMatch(appJs, /window\.confirm\(ownerElevationConfirmMessage/);
assert.match(appJs, /\/messages\/\$\{encodeURIComponent\(messageId\)\}\/owner-elevation/);
assert.match(appJs, /function canDeleteDirectoryRootProject\(project\)/);
assert.match(appJs, /data-delete-directory-path="\$\{escapeHtml\(project\.root \|\| ""\)\}"/);
assert.match(appJs, /function deletedDirectoryWasRootListProject\(pathText\)/);
assert.match(appJs, /const wasRootListProject = deletedDirectoryWasRootListProject\(path\)/);
assert.match(appJs, /if \(!directoryActivePath\(\) \|\| wasRootListProject\) await loadProjects\(\);/);
assert.match(serverJs, /function isDeletableWorkspaceRootChild\(thread, localPath, displayPath = ""\)/);
assert.match(serverJs, /function pathDirectChildOfRoot\(candidate, root\)/);
assert.equal(serverJs.includes("Workspace users can delete empty folders only"), false);
const directoryDeleteBlock = serverJs.match(/if \(url\.pathname === "\/api\/directories\/delete"[\s\S]+?if \(url\.pathname === "\/api\/files\/preview"/)?.[0] || "";
assert.ok((directoryDeleteBlock.match(/dynamicProjectCache\.delete\(String\(thread\.workspaceId \|\| ""\)\)/g) || []).length >= 2);
assert.match(serverJs, /function taskDirectoryAttachmentCandidatesForMessage\(thread, message\)/);
assert.match(serverJs, /the attached task directory is the frozen working directory/);
assert.match(serverJs, /singleWindowMode === "chat" \|\| taskDirectory\?\.path \? "" : semanticProjectRoutingInstructions/);
assert.match(serverJs, /function callableFunctionHintsForToolsets\(toolsets = \[\]\)/);
assert.match(serverJs, /web: \["mobile_web_search", "mobile_web_extract", "web_search", "web_extract"\]/);
assert.match(serverJs, /search: \["mobile_web_search", "mobile_web_extract", "web_search", "web_extract"\]/);
assert.match(serverJs, /http: \["http_request"\]/);
assert.match(serverJs, /file: \["read_file", "write_file", "patch", "search_files", "docx_extract_text"\]/);
assert.match(serverJs, /image_gen: \["image_generate", "chatgpt_image_edit", "chatgpt_image_erase", "image_edit", "image_erase"\]/);
assert.match(serverJs, /For HTTP\/API Program calls, use `http_request`; do not look for or mention a `web_request` function\./);
assert.match(serverJs, /For Word DOCX text extraction, use `docx_extract_text`/);
assert.match(serverJs, /Callable function names for enabled toolsets/);
assert.match(serverJs, /function currentToolSchemaOverrideInstructions\(policy = \{\}\)/);
assert.match(serverJs, /Current tool schema override: the `http` toolset is enabled for this run/);
assert.match(serverJs, /Word DOCX text extraction is available as `docx_extract_text`/);
assert.match(serverJs, /Current tool schema override: the `web`\/`search` toolsets are enabled for this run/);
assert.match(serverJs, /Prefer callable function names `mobile_web_search` and `mobile_web_extract`/);
assert.match(serverJs, /Current tool schema override: the `image_gen` toolset is enabled for this run/);
assert.match(serverJs, /`chatgpt_image_edit`, and `chatgpt_image_erase`/);
assert.match(serverJs, /For existing-image retouching, object removal, background cleanup, P image requests, or erase\/inpainting requests/);
assert.match(serverJs, /prefer `chatgpt_image_edit` or `chatgpt_image_erase`/);
assert.match(serverJs, /GATEWAY_TOOL_SCHEMA_EPOCH/);
assert.match(serverJs, /20260513-docx-file-v1/);
assert.match(serverJs, /function gatewayConversationId\(thread, userMessage, runPolicy = \{\}\)/);
assert.match(serverJs, /schemaSensitive \? `\$\{base\}_\$\{GATEWAY_TOOL_SCHEMA_EPOCH\}` : base/);
assert.match(serverJs, /\["web", "search", "http", "weather", "file", "image_gen"\]/);
assert.match(serverJs, /toolSchemaEpoch: GATEWAY_TOOL_SCHEMA_EPOCH/);
assert.match(serverJs, /Do not request Owner elevation merely because an ordinary current-workspace image editing tool is missing/);
assert.match(serverJs, /Image editing, object removal, background cleanup, P image requests, and erase\/inpainting requests inside the current workspace are ordinary user work/);
assert.match(serverJs, /do not use local PIL\/OpenCV\/rembg\/SAM\/ffmpeg\/terminal\/code image repair/);
assert.match(serverJs, /function isStaleHttpToolAvailabilityClaim\(text\)/);
assert.match(serverJs, /function isStaleImageToolAvailabilityClaim\(text\)/);
assert.match(serverJs, /function isStaleDocxToolAvailabilityClaim\(text\)/);
assert.match(serverJs, /function isOrdinaryToolSchemaElevationRequest\(approvalRequest, output, message = \{\}\)/);
assert.match(serverJs, /Stale assistant tool-availability claim omitted by Hermes Mobile/);
assert.match(serverJs, /internal_owner_elevation_request_not_external_delivered/);
assert.match(serverJs, /internal_tool_schema_failure_not_external_delivered/);
assert.match(serverJs, /conversation_history: buildConversationHistory\(thread, userMessage\.id, runPolicy\)/);
assert.match(serverJs, /function ensureGroupChatSharedArtifactCopies\(thread, latestUserMessage, deliveryRoot\)/);
assert.match(serverJs, /Group-chat shared attachments authorized for this run/);
assert.match(serverJs, /groupChatAttachmentCopies/);
assert.match(serverJs, /shared-attachments/);
assert.match(serverJs, /reason: "unmatched_workspace_route"/);
assert.match(serverJs, /terminalStatus === "failed"/);
assert.match(serverJs, /status: "skipped"/);
assert.match(serverJs, /function userFacingWeixinRunError\(err\)/);
assert.match(serverJs, /function publicWeixinOutboundDelivery\(thread, message\)/);
assert.match(serverJs, /function weixinForwardTargetsForWorkspace\(workspaceId, auth\)/);
assert.match(serverJs, /async function resolveFileFromSourceUrlForRequest\(sourceUrl, auth\)/);
assert.match(serverJs, /async function createWeixinFileForwardDelivery\(auth, body = \{\}\)/);
assert.match(serverJs, /const caption = String\(body\.caption \?\? body\.text \?\? ""\)\.trim\(\)/);
assert.doesNotMatch(serverJs, /Weixin file forwarding:/);
assert.match(serverJs, /function materializeWeixinForwardFile\(file, workspaceId\)/);
assert.match(serverJs, /function renderMarkdownForwardPdf\(markdownPath, workspaceId, title\)/);
assert.match(serverJs, /function renderMarkdownForwardDocument\(markdown\)/);
assert.match(serverJs, /function renderMarkdownForwardTable\(lines, startIndex\)/);
assert.match(serverJs, /document-kicker/);
assert.match(serverJs, /markdown-table-wrap/);
assert.match(serverJs, /Weixin readable PDF/);
assert.doesNotMatch(serverJs, /<pre>\$\{escapeHtmlForDocument\(markdown \|\| ""\)\}<\/pre>/);
assert.match(serverJs, /const forwardFile = materializeWeixinForwardFile\(resolved\.file, workspaceId\)/);
assert.match(serverJs, /pathToFileURL\(htmlPath\)\.href/);
assert.match(serverJs, /WEIXIN_FORWARD_MARKDOWN_MAX_BYTES/);
assert.match(serverJs, /fileResultFromBridgeFileForForward\(file, workspaceId\)/);
assert.match(serverJs, /parsed\.pathname === "\/api\/automations\/output" \|\| parsed\.pathname === "\/api\/automations\/output\/preview"/);
assert.match(serverJs, /parsed\.pathname === "\/api\/kanban\/cards\/output" \|\| parsed\.pathname === "\/api\/kanban\/cards\/output\/preview"/);
assert.match(serverJs, /deliveryId: weixinIngressProvider\.deliveryId\(thread\.id, message\.id\)/);
assert.match(serverJs, /WEIXIN_DELIVERY_RETRY_LIMIT/);
assert.match(serverJs, /WEIXIN_INGRESS_ATTACHMENT_CONTEXT_WINDOW_MS/);
assert.match(serverJs, /function isWeixinInboundWakeRequiredFailure\(ack = \{\}\)/);
assert.match(serverJs, /function isWeixinDeliveryRetryable\(delivery, nowMs = Date\.now\(\)\)/);
assert.match(serverJs, /function wakeWeixinOutboundDeliveriesForInboundEvent\(event, workspaceId\)/);
assert.match(serverJs, /function weixinIngressIsAttachmentOnlyEvent\(event\)/);
assert.match(serverJs, /function consumeWeixinPendingAttachmentMessages\(thread, event, consumedAt = nowIso\(\)\)/);
assert.match(serverJs, /function weixinIngressInstructions\(event, pendingAttachmentMessages = \[\]\)/);
assert.match(serverJs, /status: "waiting_instruction"/);
assert.match(serverJs, /awaitingInstruction: true/);
assert.match(serverJs, /Treat these media files as attached to the latest user instruction/);
assert.ok(serverJs.indexOf("if (attachmentOnly)") < serverJs.indexOf("startRunForThread(thread, userMessage, assistantMessage, runOptions)"));
assert.match(serverJs, /delivery\.status === "pending" \|\| isWeixinDeliveryRetryable\(delivery, nowMs\)/);
assert.match(serverJs, /status: waitForInbound \? "waiting_inbound" : ack\.status/);
assert.match(serverJs, /retryAfterInbound: waitForInbound/);
assert.match(serverJs, /awakenedOutbound/);
assert.match(serverJs, /url\.pathname === "\/api\/weixin\/forward-targets"/);
assert.match(serverJs, /url\.pathname === "\/api\/weixin\/forward-file"/);
assert.match(serverJs, /const result = await createWeixinFileForwardDelivery\(auth, body\)/);
assert.match(serverJs, /externalDelivery: message\.externalDelivery\?\.source === "weixin" && thread \? publicWeixinOutboundDelivery\(thread, message\) : null/);
assert.match(appJs, /function renderArtifactWeixinButton\(artifact\)/);
assert.match(appJs, /function renderArtifactWeixinButton\(artifact\) \{\s+if \(isWeixinChatView\(\)\) return ""/);
assert.match(appJs, /data-forward-artifact-weixin/);
assert.match(appJs, /async function forwardArtifactToWeixin\(button\)/);
assert.match(appJs, /\/api\/weixin\/forward-file/);
assert.match(appJs, /function renderExternalDeliveryStatus\(message\)/);
assert.match(appJs, /function renderExternalDeliveryStatus\(message\) \{\s+if \(isWeixinChatView\(\)\) return ""/);
assert.match(appJs, /message\?\.externalDelivery/);
assert.match(appJs, /delivery\.terminalStatus !== "manual_forward"/);
assert.match(appJs, /if \(status !== "sent"\) return ""/);
assert.match(appJs, /\\u5fae\\u4fe1\\u5df2\\u8f6c\\u53d1/);
assert.match(stylesCss, /\.artifact-weixin-button/);
assert.match(stylesCss, /\.external-delivery-status/);
assert.match(fileViewerHtml, /id="forwardWeixin"/);
assert.match(fileViewerHtml, /data-markdown-share="weixin"/);
assert.match(fileViewerHtml, /async function forwardFileToWeixin\(\)/);
assert.match(fileViewerHtml, /\/api\/weixin\/forward-file/);
assert.match(pdfViewerHtml, /id="weixinButton"/);
assert.match(pdfViewerHtml, /async function forwardPdfToWeixin\(\)/);
assert.match(pdfViewerHtml, /\/api\/weixin\/forward-file/);
assert.match(serverJs, /运行被终止，未生成回复。/);
assert.match(serverJs, /function gatewayPoolStatusHealthy\(poolStatus\)/);
assert.match(serverJs, /status\.fallbackError = status\.error \|\| ""/);
assert.match(indexHtml, /id="topSearchChat"/);
assert.match(appJs, /\$\("topSearchChat"\)\?\.addEventListener\("click"/);
assert.match(indexHtml, /id="topToggleWeixinChat"/);
assert.match(appJs, /function toggleWeixinChat\(\)/);
assert.match(appJs, /function isThreadWeixinChat\(thread = state\.currentThread\)/);
assert.match(appJs, /function isWeixinChatView\(\)/);
assert.match(appJs, /weixinChatOpen: localStorage\.getItem\("hermesWebWeixinChatOpen"\) === "1"/);
assert.match(appJs, /state\.weixinChatThread = mergeChatScopeThread\(state\.weixinChatThread, result\.weixinChatThread\)/);
assert.match(serverJs, /function ensureWeixinSingleWindowThread\(workspaceId, seed = \{\}\)/);
assert.match(serverJs, /function migrateWeixinMessagesToDedicatedThread\(workspaceId, targetThread = null\)/);
assert.match(serverJs, /function findWeixinSingleWindowThreadForWorkspace\(workspaceId\)/);
assert.equal(indexHtml.includes("searchButton"), false);
assert.equal(appJs.includes("$('searchButton')"), false);
assert.equal(appJs.includes('$("#searchButton")'), false);
assert.match(appJs, /const KANBAN_STATUS_ORDER = Object\.freeze\(\["triage", "todo", "ready", "running", "blocked", "done", "archived"\]\)/);
assert.match(appJs, /const KANBAN_STORY_STATUS = "story"/);
assert.match(appJs, /const KANBAN_TAB_ORDER = Object\.freeze\(\[KANBAN_STORY_STATUS, \.\.\.KANBAN_STATUS_ORDER\]\)/);
assert.match(appJs, /const TODO_AUTO_REFRESH_INTERVAL_MS = 8000/);
assert.match(appJs, /const TODO_LIST_CACHE_MAX_AGE_MS = 30 \* 60 \* 1000/);
assert.match(appJs, /if \(options\.freshServer\) params\.set\("fresh", "1"\)/);
assert.match(appJs, /result\?\.cache\?\.hit && !options\.freshServer/);
assert.match(serverJs, /const KANBAN_CARD_LIST_CACHE_TTL_MS = Math\.max/);
assert.match(serverJs, /const KANBAN_CARD_LIST_CACHE_PATH = path\.resolve/);
assert.match(serverJs, /const kanbanCardListCache = new Map\(\)/);
assert.match(serverJs, /let kanbanCardListCacheStoreLoaded = false/);
assert.match(serverJs, /function readKanbanCardListCache\(args = \{\}\)/);
assert.match(serverJs, /readJsonStore\(KANBAN_CARD_LIST_CACHE_PATH/);
assert.match(serverJs, /writeJsonStore\(KANBAN_CARD_LIST_CACHE_PATH/);
assert.match(serverJs, /url\.searchParams\.get\("fresh"\)/);
assert.match(serverJs, /function scheduleKanbanDependencyReconcile\(workspaceId\)/);
assert.match(appJs, /function renderTodoKanbanBoard\(todos\)/);
assert.match(appJs, /function renderTodoKanbanCard\(todo\)/);
assert.match(appJs, /function sortArchivedKanbanCards\(items\)/);
assert.match(appJs, /function kanbanArchiveCases\(items\)/);
assert.match(appJs, /function kanbanStoryCases\(items\)/);
assert.match(appJs, /function renderKanbanStoryTree\(items\)/);
assert.match(appJs, /function renderKanbanArchiveStories\(items\)/);
assert.match(appJs, /function renderKanbanArchiveCase\(group\)/);
assert.match(appJs, /function scheduleKanbanStoryDetailLoads\(items\)/);
assert.match(appJs, /function kanbanCardStoryFeedbackLine\(todo\)/);
assert.match(appJs, /function renderKanbanReadingFields\(disabled = false\)/);
assert.match(appJs, /id="kanbanReadingCover"/);
assert.match(appJs, /setKanbanReadingCoverFile\(file\)/);
assert.match(appJs, /coverImage/);
assert.match(appJs, /function renderKanbanCaseCover\(cover, options = \{\}\)/);
assert.match(appJs, /function loadKanbanCoverImages\(root = document\)/);
assert.match(appJs, /data-kanban-composer-mode="\$\{mode\}"/);
assert.match(appJs, /\/api\/kanban\/cards\/reading-plan/);
assert.match(appJs, /function renderKanbanReadingSubmissionPanel\(todo\)/);
assert.match(appJs, /\/api\/kanban\/cards\/\$\{encodeURIComponent\(todoId\)\}\/reading-submission/);
assert.match(appJs, /todoReadingSubmissionDrafts/);
assert.match(appJs, /todoReadingSubmitting/);
assert.match(serverJs, /url\.pathname === "\/api\/kanban\/cards\/reading-plan"/);
assert.match(serverJs, /reading-submission/);
assert.match(serverJs, /function createKanbanReadingPlanCards\(workspaceId, input = \{\}\)/);
assert.match(serverJs, /function submitKanbanReadingSubmission\(workspaceId, cardId, body = \{\}\)/);
assert.match(serverJs, /function saveKanbanReadingCoverUpload\(workspaceId, planId, rawCover = null\)/);
assert.match(serverJs, /kanbanCaseCover: publicKanbanCoverFile/);
assert.match(kanbanCardProviderJs, /case_cover: args\.caseCover/);
assert.match(kanbanProviderJs, /caseCover: payload\.case_cover/);
assert.match(serverJs, /transcribe-reading-audio\.ps1/);
assert.match(kanbanProviderJs, /const completionResult = String\(payload\.result/);
assert.match(appJs, /KANBAN_STORY_DETAIL_LOAD_LIMIT = 6/);
assert.match(appJs, /selectedStatus === KANBAN_STORY_STATUS\s+\? renderKanbanStoryTree\(todos\)/);
assert.match(appJs, /KANBAN_TAB_ORDER\.map\(\(status\) =>/);
assert.match(appJs, /state\.todoKanbanStatus = KANBAN_STORY_STATUS/);
assert.match(appJs, /function shouldLoadCompletedTodos\(options = \{\}\)/);
assert.match(appJs, /function kanbanComposerOpen\(\)/);
assert.match(appJs, /function kanbanComposerFocused\(\)/);
assert.match(appJs, /function syncKanbanComposerDraftFromDom\(\)/);
assert.match(appJs, /function todoRefreshShouldYieldToKanbanComposer\(options = \{\}\)/);
assert.match(appJs, /if \(kanbanComposerOpen\(\)\) \{\s+scheduleTodoAutoRefresh\(\);\s+return;/);
assert.match(appJs, /if \(todoRefreshShouldYieldToKanbanComposer\(options\)\) \{/);
assert.match(appJs, /const yieldToComposer = todoRefreshShouldYieldToKanbanComposer\(options\)/);
assert.match(appJs, /if \(includeCompleted\) params\.set\("includeCompleted", "1"\)/);
assert.match(appJs, /function scheduleTodoAutoRefresh\(\)/);
assert.match(appJs, /function readTodoListCache\(workspaceId, includeCompleted\)/);
assert.match(appJs, /function writeTodoListCache\(workspaceId, includeCompleted\)/);
assert.match(appJs, /function clearTodoListCache\(workspaceId = state\.selectedWorkspaceId \|\| "owner"\)/);
assert.match(appJs, /const cached = useCache \? readTodoListCache\(workspaceId, includeCompleted\) : null/);
assert.match(appJs, /todoWorkspaceId: ""/);
assert.match(appJs, /await loadTodos\(\{ preferCache: true \}\)/);
assert.match(appJs, /if \(cached\) \{/);
assert.match(appJs, /state\.todos\.length && state\.todoWorkspaceId === workspaceId && state\.todoCompletedLoaded === includeCompleted/);
assert.match(appJs, /loadTodos\(\{ preserveScroll: true, autoRefresh: true \}\)/);
assert.match(appJs, /kanbanStatusNeedsCompleted\(status\) && !state\.todoCompletedLoaded/);
assert.match(appJs, /!state\.todoCompletedLoaded && kanbanStatusNeedsCompleted\(status\) \? "\\u2026"/);
assert.match(appJs, /grouped\.set\("archived", sortArchivedKanbanCards/);
assert.equal(appJs.includes("Official Hermes Kanban"), false);
assert.equal(appJs.includes("todo-kanban-summary"), false);
assert.equal(stylesCss.includes(".todo-kanban-summary"), false);
assert.match(appJs, /function normalizedKanbanStatus\(todo\)/);
assert.match(appJs, /todoKanbanStatus: initialTodoKanbanStatus\(\)/);
assert.ok(indexHtml.includes("\u8bdd\u9898"));
assert.ok(indexHtml.includes("\u770b\u677f"));
assert.ok(indexHtml.includes("\u8bdd\u9898\u5217\u8868"));
assert.ok(indexHtml.includes("\u8bdd\u9898\u6d41"));
assert.ok(indexHtml.includes("\u65b0\u5efa\u8bdd\u9898"));
assert.ok(indexHtml.includes("\u65b0\u589e\u4efb\u52a1"));
assert.ok(appJs.includes("\u5f00\u542f\u8bdd\u9898"));
assert.equal(appJs.includes("\u5f00\u542f\u4efb\u52a1"), false);
assert.ok(appJs.includes("New topic"));
assert.ok(appJs.includes("\u770b\u677f\u8be6\u60c5"));
assert.ok(appJs.includes("\u65b0\u589e\u5361\u7247"));
assert.ok(appJs.includes("Topic ID"));
assert.ok(indexHtml.includes("20260513-1615"));
assert.ok(serviceWorkerJs.includes("20260513-reading-cover"));
assert.match(indexHtml, /id="chatManagementMode"/);
assert.match(appJs, /\$\("chatManagementMode"\)\?\.addEventListener\("click"/);
assert.match(appJs, /\$\("chatManagementMode"\)\?\.classList\.toggle\("active", single && state\.singleWindowMode === "chat"\)/);
assert.match(stylesCss, /\.section-toggle \{[\s\S]*?grid-template-columns: repeat\(5, minmax\(0, 1fr\)\)/);
assert.match(stylesCss, /@media \(max-width: 1099px\)/);
assert.match(appJs, /window\.matchMedia\("\(max-width: 1099px\)"\)/);
assert.match(appJs, /const mainBack = taskDetail \|\| todoDetail \|\| todoCreate \|\| automationDetail \|\| skillDetail \|\| directoryBack/);
assert.match(stylesCss, /\.main-back-visible \.top-nav-button \{[\s\S]*?display: grid;/);
assert.match(serverJs, /groupChatAvailable/);
assert.match(serverJs, /groupChatThreadId/);
assert.match(serverJs, /groupChatThread/);
assert.match(serverJs, /weixinChatAvailable/);
assert.match(serverJs, /weixinChatThreadId/);
assert.match(serverJs, /weixinChatThread/);
assert.match(stylesCss, /--mobile-bottom-nav-height: calc\(80px \+ env\(safe-area-inset-bottom\)\)/);
assert.match(stylesCss, /--mobile-bottom-nav-reserved-height/);
assert.match(stylesCss, /calc\(var\(--mobile-bottom-nav-height\) \+ 12px\)/);
assert.match(appJs, /Math\.max\(96, rectHeight \+ 12, contentHeight \+ 12\)/);
assert.match(stylesCss, /padding-bottom: var\(--mobile-bottom-nav-reserved-height\)/);
assert.match(stylesCss, /height: var\(--mobile-bottom-nav-height\)/);
assert.match(appJs, /function currentTodoKanbanStatus\(grouped\)/);
assert.match(appJs, /data-kanban-status="\$\{escapeHtml\(status\)\}"/);
assert.match(appJs, /localStorage\.setItem\("hermesTodoKanbanStatus", status\)/);
assert.match(appJs, /function renderTodoList\(\) \{\s+const list = \$\("threadList"\);\s+if \(!list\) return;\s+list\.innerHTML = "";\s+return;/);
assert.match(appJs, /function renderAutomationList\(\) \{\s+const list = \$\("threadList"\);\s+if \(!list\) return;\s+list\.innerHTML = "";\s+return;/);
assert.match(appJs, /function projectDisplayLabel\(project\) \{\s+return project\?\.label \|\| project\?\.id \|\| "Project";\s+\}/);
assert.match(appJs, /function renderDirectorySharedBadge\(project\)/);
assert.match(appJs, /directory-shared-badge/);
assert.doesNotMatch(appJs, /sharedDelta/);
assert.match(appJs, /localeCompare\(String\(directoryRootProjectLabel\(b\.project\)\), "zh-Hans-CN", \{ numeric: true, sensitivity: "base" \}\)/);
assert.match(stylesCss, /\.directory-shared-badge \{/);
assert.match(appJs, /data-block-todo/);
assert.match(appJs, /data-unblock-todo/);
assert.match(appJs, /data-todo-comment-form/);
assert.match(appJs, /data-comment-unblock-todo/);
assert.match(appJs, /data-todo-revision-form/);
assert.match(appJs, /data-revise-todo/);
assert.match(appJs, /function commentAndUnblockTodo\(todoId, comment\)/);
assert.match(appJs, /function requestTodoRevision\(todoId, comment\)/);
assert.match(appJs, /function syncTodoDetailDraftFromDom\(input = null\)/);
assert.match(appJs, /function restoreTodoDetailDraftFocus\(focus = null\)/);
assert.match(appJs, /todoRevisionDrafts/);
assert.match(appJs, /todoCommentDrafts/);
assert.match(appJs, /todoRevisionSubmitting/);
assert.match(appJs, /正在创建修改任务，请勿重复提交/);
assert.match(appJs, /正在创建\.\.\./);
assert.match(appJs, /boardActionApiPath\(todoId, "revise"\)/);
assert.match(appJs, /function boardCollectionApiPath\(\)/);
assert.match(appJs, /function boardActionApiPath\(todoId, action = ""\)/);
assert.match(appJs, /\/api\/kanban\/cards/);
assert.match(appJs, /const KANBAN_MULTI_AGENT_MAX_PARALLEL = 3/);
assert.match(appJs, /function renderKanbanComposerPanel\(\)/);
assert.match(appJs, /function renderKanbanCreatePage\(\)/);
assert.match(appJs, /function renderKanbanComposerProgress\(\)/);
assert.match(appJs, /const KANBAN_PLAN_PROGRESS_STEPS = Object\.freeze/);
assert.match(appJs, /const KANBAN_CREATE_PROGRESS_STEPS = Object\.freeze/);
assert.match(appJs, /beginKanbanComposerProgress\(readingPlan \? "reading" : \(multiAgent \? "plan" : "create"\)\)/);
assert.match(appJs, /beginKanbanComposerProgress\("create"\)/);
assert.match(appJs, /creating\s+\?\s+renderKanbanCreatePage\(\)/);
assert.match(appJs, /newTodo\.textContent = "\\u65b0\\u589e\\u4efb\\u52a1"/);
assert.match(appJs, /!state\.todoCreateOpen && !busy/);
assert.match(appJs, /id="kanbanComposerForm"/);
assert.match(appJs, /data-kanban-composer-mode="\$\{mode\}"/);
assert.match(appJs, /function saveKanbanComposerMode\(mode\)/);
assert.match(appJs, /state\.kanbanComposerMultiAgent = next === "multi"/);
assert.match(appJs, /restoreKanbanComposerFocus/);
assert.match(appJs, /input\.focus\(\{ preventScroll: true \}\)/);
assert.match(appJs, /data-close-todo-create/);
assert.match(appJs, /\\u521b\\u5efa\\u4efb\\u52a1/);
assert.match(appJs, /state\.todoCreateOpen = false;/);
assert.match(appJs, /\$\("topNewTodo"\)\?\.addEventListener\("click", \(\) => \{\s+closeTopMoreMenu\(\);\s+openTodoCreate\(\);/);
assert.match(appJs, /function renderKanbanPlanDraft\(plan\)/);
assert.match(appJs, /data-create-kanban-plan/);
assert.match(appJs, /\/api\/kanban\/cards\/plan/);
assert.match(appJs, /\/api\/kanban\/cards\/batch/);
assert.match(appJs, /kanbanCaseSourceText/);
assert.match(appJs, /kanbanCaseSummary/);
assert.match(appJs, /kanbanCaseCardIndex/);
assert.match(stylesCss, /\.kanban-composer-panel/);
assert.match(stylesCss, /\.kanban-create-page/);
assert.match(stylesCss, /\.kanban-create-mode-button\.active/);
assert.match(stylesCss, /\.kanban-create-progress/);
assert.match(stylesCss, /\.kanban-plan-draft/);
assert.match(stylesCss, /\.kanban-archive-stories/);
assert.match(stylesCss, /\.kanban-archive-story-grid/);
assert.match(stylesCss, /\.kanban-archive-card-chain/);
assert.match(stylesCss, /\.kanban-archive-card-feedback/);
assert.match(stylesCss, /\.todo-revision-panel/);
assert.match(serverJs, /complete\|cancel\|postpone\|delete\|block\|unblock\|comment\|revise/);
assert.match(serverJs, /const KANBAN_MULTI_AGENT_MAX_PARALLEL = 3/);
assert.match(serverJs, /async function planKanbanMultiAgent\(text, workspace, ownerPrincipalId\)/);
assert.match(serverJs, /function normalizeKanbanPlan\(raw, sourceText, workspaceId\)/);
assert.match(serverJs, /async function createKanbanPlanCards\(workspaceId, planInput, options = \{\}\)/);
assert.match(serverJs, /function kanbanSingleCardCasePayload\(content, description = "", sourceText = ""\)/);
assert.match(serverJs, /caseId: plan\.id/);
assert.match(serverJs, /caseSourceText: compactText\(plan\.sourceText, 2000\)/);
assert.match(serverJs, /caseCardIndex: cardIndex \+ 1/);
assert.match(serverJs, /url\.pathname === "\/api\/kanban\/cards\/plan"/);
assert.match(serverJs, /url\.pathname === "\/api\/kanban\/cards\/batch"/);
assert.match(serverJs, /Waiting for a free multi-Agent execution slot/);
assert.match(serverJs, /async function maybeReconcileKanbanDependencyBlocks\(workspaceId, options = \{\}\)/);
assert.match(serverJs, /action: "dependency-unblocked"/);
assert.match(serverJs, /KANBAN_BLOCKED_PUSH_DELAY_MINUTES/);
assert.match(serverJs, /function kanbanExecutableProfileForWorkspace\(workspaceId, principalId, requestedAssignee = ""\)/);
assert.match(serverJs, /assigneeForWorkspace: kanbanExecutableProfileForWorkspace/);
assert.match(serverJs, /const kanbanExecutableProfileCursor = new Map\(\)/);
assert.match(serverJs, /function nextKanbanExecutableProfile\(workspace, workers\)/);
assert.match(appJs, /评论并解除阻塞/);
assert.match(appJs, /function renderKanbanDetailReport\(todo\)/);
assert.match(appJs, /\/api\/kanban\/cards\/\$\{encodeURIComponent\(id\)\}\/detail/);
assert.match(appJs, /params\.set\("logTail", "4000"\)/);
assert.match(appJs, /function shouldAutoLoadKanbanDetail\(todo\)/);
assert.match(appJs, /!String\(todo\?\.kanbanResult \|\| ""\)\.trim\(\) && !kanbanCardOutputs\(todo\)\.length/);
assert.match(appJs, /window\.setTimeout\(\(\) => loadKanbanCardDetail\(selected\.id\)\.catch\(showError\), 0\)/);
assert.doesNotMatch(appJs, /renderTodos\(\);\s+loadKanbanCardDetail\(state\.selectedTodoId\)/);
assert.match(appJs, /const previousScrollTop = conversation \? conversation\.scrollTop : 0/);
assert.match(appJs, /const nextScrollTop = Number\.isFinite\(options\.restoreScrollTop\) \? options\.restoreScrollTop : previousScrollTop/);
assert.match(appJs, /const finalRestoreScrollTop = options\.preserveScroll && conversation \? conversation\.scrollTop : restoreScrollTop/);
assert.match(appJs, /data-load-kanban-detail="\$\{escapeHtml\(todo\.id\)\}"\$\{loading \? " disabled" : ""\}/);
assert.match(appJs, /class="todo-detail-meta"/);
assert.match(appJs, /function dedupeKanbanOutputs\(outputs\)/);
assert.match(appJs, /function kanbanCardOutputs\(todo\)/);
assert.match(appJs, /function renderKanbanDeliveryFiles\(todo\)/);
assert.match(appJs, /\$\{coverBlock\}\s+\$\{deliveryBlock\}\s+\$\{resultBlock\}\s+\$\{readingPanel\}\s+\$\{metaBlock\}/);
assert.match(appJs, /function kanbanOutputHref\(item\)/);
assert.match(fileViewerHtml, /\/api\/kanban\/cards\/output\/preview/);
assert.match(serverJs, /url\.pathname === "\/api\/kanban\/cards\/output"/);
assert.match(serverJs, /url\.pathname === "\/api\/kanban\/cards\/output\/preview"/);
assert.match(serverJs, /publicKanbanCardDetail\(workspaceId, result\)/);
assert.match(serverJs, /function publicKanbanOutputsFromText\(workspaceId, text\)/);
assert.match(serverJs, /kanbanOutputs: publicKanbanOutputsFromText\(workspaceId, kanbanResult\)/);
assert.match(kanbanProviderJs, /workspace_id: String\(meta\.workspaceId \|\| meta\.workspace_id \|\| payload\.workspace_id \|\| payload\.workspaceId \|\| ""\)/);
assert.match(kanbanProviderJs, /let runs = Array\.isArray\(show\?\.runs\) \? show\.runs : \[\]/);
assert.match(kanbanProviderJs, /const includeLog = bool\(payload\.include_log \|\| payload\.includeLog\)/);
assert.match(serverJs, /txt\|json\|csv\|html\?\|zip/);
assert.match(stylesCss, /\.todo-detail-outputs/);
assert.match(stylesCss, /\.todo-detail-deliverables/);
assert.match(stylesCss, /\.todo-detail-meta/);
assert.match(stylesCss, /--kanban-receipt-body-size: 16px/);
assert.match(stylesCss, /--kanban-receipt-body-size: 16\.5px/);
assert.match(stylesCss, /--kanban-receipt-body-size: 15\.5px/);
assert.match(appJs, /const kanban = isKanbanTodoSource\(\);/);
assert.match(appJs, /if \(!kanban && !dueValue\) throw new Error\("Todo due time is required"\)/);
assert.match(appJs, /state\.todoKanbanStatus = "todo"/);
assert.match(serverJs, /kanbanAssignee: String\(row\.kanban_assignee/);
assert.match(stylesCss, /\.todo-kanban-board/);
assert.match(stylesCss, /\.todo-kanban-switcher/);
assert.match(stylesCss, /\.todo-kanban-tab/);
assert.match(stylesCss, /\.todo-kanban-current/);
assert.match(stylesCss, /\.todo-kanban-lane/);
assert.match(stylesCss, /\.todo-kanban-card/);
assert.match(stylesCss, /\.todo-kanban-card-title \{[\s\S]*?font-weight: 600;/);
assert.match(stylesCss, /\.todo-kanban-tab-label \{[\s\S]*?font-weight: 560;/);
assert.match(stylesCss, /\.todo-detail-head h2 \{[\s\S]*?font-weight: 600;/);
assert.match(serverJs, /THREAD_MESSAGE_INITIAL_LIMIT/);
assert.match(serverJs, /function directTodoCreateEnabled\(\)/);
assert.match(serverJs, /return false;/);
assert.match(serverJs, /function detectDirectKanbanCreateRequest\(text\)/);
assert.match(serverJs, /async function interpretKanbanNaturalLanguage\(text, workspace, ownerPrincipalId\)/);
assert.match(serverJs, /url\.pathname === "\/api\/kanban\/cards"/);
assert.ok(serverJs.includes("\u770b\u677f"));
assert.ok(serverJs.includes("\u5361\u7247"));
assert.ok(serverJs.includes("kanban|board"));
assert.match(serverJs, /新增\|新建\|创建\|增加\|添加/);
assert.match(serverJs, /已新增看板卡片/);
assert.match(serverJs, /Do not run raw `hermes kanban` CLI commands/);
assert.match(serverJs, /function threadMessagesPage\(thread, options = \{\}\)/);
assert.match(serverJs, /function searchThreadMessages\(thread, options = \{\}\)/);
assert.match(serverJs, /mode === "tasks" \|\| mode === "task"/);
assert.match(serverJs, /function singleWindowChatTaskGroupId\(requestedTaskGroupId = ""\)/);
assert.match(serverJs, /next\.singleWindowMode === "chat"[\s\S]*?next\.taskGroupId = singleWindowChatTaskGroupId\(next\.taskGroupId\)/);
assert.match(serverJs, /function isExternalIngressThread\(thread\)/);
assert.match(serverJs, /&& !isExternalIngressThread\(thread\)/);
assert.match(serverJs, /const externalIngressThreads = \(state\.threads \|\| \[\]\)\.filter/);
assert.match(serverJs, /state\.threads = \(state\.threads \|\| \[\]\)\.filter\(\(thread\) => thread\.id !== externalThread\.id\)/);
assert.match(serverJs, /function weixinIngressThreadForEvent\(event, workspaceId\) \{\s+return ensureWeixinSingleWindowThread\(workspaceId, event\);\s+\}/);
assert.match(serverJs, /weixinIngressProvider\.isInboundHeartbeatEvent\(event\)/);
assert.match(serverJs, /heartbeat: true/);
assert.match(serverJs, /reason: workspace \? "weixin_ingress_heartbeat" : "unmatched_workspace_route"/);
assert.match(serverJs, /wakeWeixinOutboundDeliveriesForInboundEvent\(event, workspaceId\)/);
assert.ok(serverJs.indexOf("weixinIngressProvider.isInboundHeartbeatEvent(event)") < serverJs.indexOf("startRunForThread(thread, userMessage, assistantMessage, runOptions)"));
assert.match(weixinIngressProviderJs, /function isInboundHeartbeatEvent\(event\)/);
assert.match(weixinIngressProviderJs, /text === "#" \|\| text === "＃"/);
assert.match(serverJs, /const taskGroupId = SINGLE_WINDOW_CHAT_TASK_GROUP_ID;/);
assert.match(serverJs, /singleWindowMode === "chat" \? singleWindowChatTaskGroupId\(requestedTaskGroupId\) : \(requestedTaskGroupId \|\| makeId\("task"\)\)/);
assert.match(serverJs, /singleWindowMode === "chat"\s+\? "The latest user message is a Hermes Mobile continuous-chat turn/);
assert.equal(serverJs.includes("\"weixin-chat\""), false);
assert.match(serverJs, /&& !isWeixinSingleWindowThread\(thread\)/);
assert.match(serverJs, /params\.weixinChat = "1"/);
assert.match(serverJs, /compactThreadWithMessagePage\(thread/);
assert.match(serverJs, /threadMessagesRead && req\.method === "GET"/);
assert.match(appJs, /const CHAT_MESSAGE_INITIAL_LIMIT = 60/);
assert.match(appJs, /const TASK_MESSAGE_INITIAL_LIMIT = 300/);
assert.match(appJs, /const messageMode = isSingleWindowChatView\(\)/);
assert.match(appJs, /messageMode === "tasks" \? TASK_MESSAGE_INITIAL_LIMIT : CHAT_MESSAGE_INITIAL_LIMIT/);
assert.match(appJs, /function loadOlderChatMessages\(\)/);
assert.match(appJs, /maybeLoadOlderChatMessages\(\)/);
assert.match(appJs, /\/messages\?\$\{params\}/);
assert.match(appJs, /function renderChatHistoryPager\(thread\)/);
assert.match(appJs, /body\.messageLimit = CHAT_MESSAGE_INITIAL_LIMIT/);
assert.match(stylesCss, /\.chat-history-pager/);
assert.match(serverJs, /function verifyDirectTodoCreateResult\(todo\)/);
assert.match(serverJs, /Todo created but no visible card id returned\./);
assert.match(serverJs, /function formatDirectTodoCreateSuccessMessage\(intent, todo\)/);
assert.match(serverJs, /ID: \$\{id\}/);
assert.match(serverJs, /verification: directTodoVerification/);

console.log("task list UI tests passed");
