"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const repoRoot = path.resolve(__dirname, "..");
const appJs = fs.readFileSync(path.join(repoRoot, "public", "app.js"), "utf8");
const indexHtml = fs.readFileSync(path.join(repoRoot, "public", "index.html"), "utf8");
const stylesCss = fs.readFileSync(path.join(repoRoot, "public", "styles.css"), "utf8");
const serverJs = fs.readFileSync(path.join(repoRoot, "server.js"), "utf8");

assert.match(appJs, /function taskGroupsForThread\(thread\)/);
assert.match(appJs, /return \[\.\.\.groups\.values\(\)\]\.sort\(\(a, b\) => String\(b\.updatedAt\)\.localeCompare\(String\(a\.updatedAt\)\)\);/);
assert.match(appJs, /const allGroups = taskListGroupsForThread\(thread\);\s+const displayGroups = allGroups\.slice\(\);/);
assert.equal(appJs.includes("allGroups.slice().reverse()"), false);
assert.ok(appJs.includes("(?:\\/[A-Za-z0-9_.-]+)+"));
assert.equal(appJs.includes("namedSkillPattern"), false);
assert.match(indexHtml, /id="taskRenameOverlay"/);
assert.match(appJs, /function openTaskRenameDialog\(currentTitle\)/);
assert.match(appJs, /function selectTaskRenameInput\(input\)/);
assert.match(appJs, /input\.setSelectionRange\(0, input\.value\.length\)/);
assert.match(appJs, /input\.select\(\)/);
assert.match(appJs, /const nextTitle = await openTaskRenameDialog\(currentTitle\)/);
assert.doesNotMatch(appJs, /taskStatus\(group\)} \|/);
assert.equal(appJs.includes("task-doc-empty\">No doc"), false);
assert.match(appJs, /const latestArtifact = latestTaskListDocument\(group\);/);
assert.match(appJs, /const artifactChips = latestArtifact \?/);
assert.match(appJs, /\$\{artifactChips\}/);
assert.match(appJs, /function messageExtractedDirectoryAliases\(message\)/);
assert.match(appJs, /for \(const message of group\?\.messages \|\| \[\]\) \{\s+const candidates = usableTaskBindingAliases/);
assert.match(appJs, /const exactProject = candidates\.find\(\(candidate\) =>\s+candidate\.projectId === requestedProjectId && String\(candidate\.subprojectId \|\| ""\) === requestedSubprojectId\)/);
assert.match(appJs, /const rootProject = candidates\.find\(\(candidate\) =>\s+candidate\.projectId === requestedProjectId && !candidate\.subprojectId\)/);
assert.match(stylesCss, /\.task-rename-sheet/);
assert.match(appJs, /function renderOwnerElevationPanel\(\)/);
assert.match(appJs, /function openOwnerElevationApprovalDialog\(options = \{\}\)/);
assert.match(appJs, /\/api\/owner-elevation/);
assert.match(appJs, /body\.maintenanceMode = true/);
assert.match(appJs, /owner_high_privilege/);
assert.match(stylesCss, /\.workspace-permission-panel/);
assert.match(stylesCss, /\.owner-elevation-approval-actions/);
assert.match(indexHtml, /id="ownerElevationApprovalOverlay"/);
assert.match(serverJs, /function publicOwnerElevationStatus\(auth\)/);
assert.match(serverJs, /url\.pathname === "\/api\/owner-elevation"/);
assert.match(serverJs, /url\.pathname === "\/api\/owner-elevation\/once"/);
assert.match(serverJs, /function grantOwnerElevationOnce\(auth\)/);
assert.match(serverJs, /function consumeOwnerElevationOnce\(auth, token\)/);
assert.match(serverJs, /consumeOwnerElevationOnce\(auth, onceToken\) \|\| isOwnerElevationActive\(auth\)/);
assert.match(serverJs, /isOwnerElevationActive\(auth\)/);
assert.match(serverJs, /HERMES_PERMISSION_APPROVAL_REQUIRED/);
assert.match(serverJs, /function modelPermissionApprovalRequest\(text, message = \{\}\)/);
assert.match(serverJs, /elevationRequired: Boolean\(message\.elevationRequired\)/);
assert.match(serverJs, /messages\\\/\(\[\^\/\]\+\)\\\/owner-elevation/);
assert.match(serverJs, /gatewaySecurityLevel: gatewayRouting\.securityLevel/);
assert.match(serverJs, /gatewayMaintenance: Boolean\(gatewayRouting\.maintenance/);
assert.match(serverJs, /gatewayMaintenanceCategory: gatewayRouting\.maintenanceCategory/);
assert.match(appJs, /function offerOwnerElevationForMessage\(message\)/);
assert.match(appJs, /ownerElevationPromptedMessageIds/);
assert.match(appJs, /await openOwnerElevationApprovalDialog/);
assert.doesNotMatch(appJs, /window\.confirm\(ownerElevationConfirmMessage/);
assert.match(appJs, /\/messages\/\$\{encodeURIComponent\(messageId\)\}\/owner-elevation/);
assert.match(appJs, /function canDeleteDirectoryRootProject\(project\)/);
assert.match(appJs, /data-delete-directory-path="\$\{escapeHtml\(project\.root \|\| ""\)\}"/);
assert.match(appJs, /function deletedDirectoryWasRootListProject\(pathText\)/);
assert.match(appJs, /const wasRootListProject = deletedDirectoryWasRootListProject\(path\)/);
assert.match(appJs, /if \(!directoryActivePath\(\) \|\| wasRootListProject\) await loadProjects\(\);/);
assert.match(serverJs, /function isDeletableWorkspaceRootChild\(thread, localPath, displayPath = ""\)/);
assert.match(serverJs, /function pathDirectChildOfRoot\(candidate, root\)/);
assert.equal(serverJs.includes("Workspace users can delete empty folders only"), false);
const directoryDeleteBlock = serverJs.match(/if \(url\.pathname === "\/api\/directories\/delete"[\s\S]+?if \(url\.pathname === "\/api\/files\/preview"/)?.[0] || "";
assert.ok((directoryDeleteBlock.match(/dynamicProjectCache\.delete\(String\(thread\.workspaceId \|\| ""\)\)/g) || []).length >= 2);
assert.match(serverJs, /function taskDirectoryAttachmentCandidatesForMessage\(thread, message\)/);
assert.match(serverJs, /the attached task directory is the frozen working directory/);
assert.match(serverJs, /singleWindowMode === "chat" \|\| taskDirectory\?\.path \? "" : semanticProjectRoutingInstructions/);
assert.match(indexHtml, /id="topSearchChat"/);
assert.match(appJs, /\$\("topSearchChat"\)\?\.addEventListener\("click"/);
assert.equal(indexHtml.includes("searchButton"), false);
assert.equal(appJs.includes("$('searchButton')"), false);
assert.equal(appJs.includes('$("#searchButton")'), false);
assert.match(appJs, /const KANBAN_STATUS_ORDER = Object\.freeze\(\["triage", "todo", "ready", "running", "blocked", "done", "archived"\]\)/);
assert.match(appJs, /function renderTodoKanbanBoard\(todos\)/);
assert.match(appJs, /function renderTodoKanbanCard\(todo\)/);
assert.match(appJs, /function normalizedKanbanStatus\(todo\)/);
assert.match(appJs, /todoKanbanStatus: localStorage\.getItem\("hermesTodoKanbanStatus"\) \|\| "todo"/);
assert.match(appJs, /function currentTodoKanbanStatus\(grouped\)/);
assert.match(appJs, /data-kanban-status="\$\{escapeHtml\(status\)\}"/);
assert.match(appJs, /localStorage\.setItem\("hermesTodoKanbanStatus", status\)/);
assert.match(appJs, /function renderTodoList\(\) \{\s+const list = \$\("threadList"\);\s+if \(!list\) return;\s+list\.innerHTML = "";\s+return;/);
assert.match(appJs, /function renderAutomationList\(\) \{\s+const list = \$\("threadList"\);\s+if \(!list\) return;\s+list\.innerHTML = "";\s+return;/);
assert.match(appJs, /data-block-todo/);
assert.match(appJs, /data-unblock-todo/);
assert.match(appJs, /\/api\/todos\/\$\{encodeURIComponent\(todoId\)\}\/block/);
assert.match(serverJs, /complete\|cancel\|postpone\|delete\|block\|unblock/);
assert.match(serverJs, /kanbanAssignee: String\(row\.kanban_assignee/);
assert.match(stylesCss, /\.todo-kanban-board/);
assert.match(stylesCss, /\.todo-kanban-switcher/);
assert.match(stylesCss, /\.todo-kanban-tab/);
assert.match(stylesCss, /\.todo-kanban-current/);
assert.match(stylesCss, /\.todo-kanban-lane/);
assert.match(stylesCss, /\.todo-kanban-card/);
assert.match(serverJs, /THREAD_MESSAGE_INITIAL_LIMIT/);
assert.match(serverJs, /function threadMessagesPage\(thread, options = \{\}\)/);
assert.match(serverJs, /function searchThreadMessages\(thread, options = \{\}\)/);
assert.match(serverJs, /compactThreadWithMessagePage\(thread/);
assert.match(serverJs, /threadMessagesRead && req\.method === "GET"/);
assert.match(appJs, /const CHAT_MESSAGE_INITIAL_LIMIT = 60/);
assert.match(appJs, /function loadOlderChatMessages\(\)/);
assert.match(appJs, /maybeLoadOlderChatMessages\(\)/);
assert.match(appJs, /\/messages\?\$\{params\}/);
assert.match(appJs, /function renderChatHistoryPager\(thread\)/);
assert.match(appJs, /body\.messageLimit = CHAT_MESSAGE_INITIAL_LIMIT/);
assert.match(stylesCss, /\.chat-history-pager/);

console.log("task list UI tests passed");
