"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const repoRoot = path.resolve(__dirname, "..");
const indexHtml = fs.readFileSync(path.join(repoRoot, "public", "index.html"), "utf8");
const accessKeyManagerUi = fs.readFileSync(path.join(repoRoot, "public", "app-access-key-manager-ui.js"), "utf8");
const appJs = fs.readFileSync(path.join(repoRoot, "public", "app.js"), "utf8");
const workspaceAdminUi = fs.readFileSync(path.join(repoRoot, "public", "app-workspace-admin-ui.js"), "utf8");
const stylesCss = fs.readFileSync(path.join(repoRoot, "public", "styles.css"), "utf8");

assert.match(appJs, /workspaceOnboardingPlan: null/);
assert.match(appJs, /workspaceOnboardingResult: null/);
assert.match(appJs, /workspaceOnboardingLoading: false/);
assert.match(appJs, /workspaceOnboardingError: ""/);
assert.match(appJs, /workspaceOnboardingDraft: null/);
assert.match(appJs, /workspaceOnboardingRun: null/);
assert.match(appJs, /workspaceOnboardingPendingAction: ""/);

assert.match(accessKeyManagerUi, /WORKSPACE_ONBOARDING_PLUGIN_OPTIONS/);
assert.match(accessKeyManagerUi, /ACCESS_KEY_MANAGER_MODEL_ESM_PATH/);
assert.match(accessKeyManagerUi, /\/vite-islands\/access-key-manager-model\/access-key-manager-model\.js/);
assert.match(accessKeyManagerUi, /function importAccessKeyManagerModel/);
assert.match(accessKeyManagerUi, /function currentAccessKeyManagerModel/);
assert.match(accessKeyManagerUi, /__homeAiImportAccessKeyManagerModel/);
for (const pluginId of ["wardrobe", "health", "finance", "email", "note", "growth"]) {
  assert.ok(accessKeyManagerUi.includes(`id: "${pluginId}"`), `${pluginId} plugin option must be selectable`);
}

assert.match(accessKeyManagerUi, /data-workspace-onboarding-plan/);
assert.match(accessKeyManagerUi, /data-workspace-onboarding-apply/);
assert.match(accessKeyManagerUi, /bindWorkspaceOnboardingAction/);
assert.match(accessKeyManagerUi, /button\.addEventListener\("pointerup", activate\)/);
assert.match(accessKeyManagerUi, /button\.addEventListener\("touchend", activate\)/);
assert.match(accessKeyManagerUi, /button\.addEventListener\("click", activate\)/);
assert.match(accessKeyManagerUi, /预览中\.\.\./);
assert.match(accessKeyManagerUi, /开通中\.\.\./);
assert.match(accessKeyManagerUi, /Owner 工作区开通/);
assert.match(accessKeyManagerUi, /data-workspace-config-section open/);
assert.match(accessKeyManagerUi, /基础配置 \/ 影音账号/);
assert.match(accessKeyManagerUi, /影音账号从这里创建/);
assert.match(accessKeyManagerUi, /创建影音账号时选择“账号类型=影音”/);
assert.match(accessKeyManagerUi, /普通新账号仍使用上方“Owner 工作区开通”/);
assert.match(accessKeyManagerUi, /保存基础配置/);
assert.match(accessKeyManagerUi, /id="newWorkspaceAccountType"/);
assert.match(accessKeyManagerUi, /<option value="media">影音<\/option>/);
assert.match(accessKeyManagerUi, /workspaceExistsPlan/);
assert.match(accessKeyManagerUi, /\(state\.workspaces \|\| \[\]\)\.some/);
assert.match(accessKeyManagerUi, /if \(!workspaceExists && accountType !== "media"\) \{/);
assert.match(accessKeyManagerUi, /allowedOwnerSpecialPlugins = accountType === "media" \? \["music", "movie"\] : \[\]/);
assert.match(accessKeyManagerUi, /JSON\.stringify\(\{ workspaceId, label, defaultWorkspace, allowedRoots, allowedToolsets, accountType, allowedOwnerSpecialPlugins \}\)/);
assert.match(accessKeyManagerUi, /pluginIds: WORKSPACE_ONBOARDING_PLUGIN_OPTIONS\.map\(\(item\) => item\.id\)/);
assert.match(accessKeyManagerUi, /新账号需要先完整开通，才能自动创建 Finance 等插件绑定。/);
assert.match(accessKeyManagerUi, /data-workspace-onboarding-section/);
assert.match(accessKeyManagerUi, /\/api\/workspace-onboarding\/plan/);
assert.match(accessKeyManagerUi, /\/api\/workspace-onboarding\/apply/);
assert.match(accessKeyManagerUi, /runSmokes: true/);
assert.match(accessKeyManagerUi, /workspaceOnboardingPayloadPlan/);
assert.match(accessKeyManagerUi, /workspaceOnboardingPlanMatchesPayload/);
assert.match(accessKeyManagerUi, /workspaceOnboardingPlanMatchesPayloadPlan/);
assert.match(accessKeyManagerUi, /async function requestWorkspaceOnboardingPlan\(payload = \{\}\)/);
assert.match(accessKeyManagerUi, /await requestWorkspaceOnboardingPlan\(payload\)/);
assert.doesNotMatch(accessKeyManagerUi, /请先预览当前工作区的开通计划/);
assert.match(accessKeyManagerUi, /function slugWorkspaceOnboardingId\(value = ""\)/);
assert.match(accessKeyManagerUi, /const rawWorkspaceId = inputs\.workspaceId\?\.value\?\.trim\(\) \|\| ""/);
assert.match(accessKeyManagerUi, /const workspaceId = slugWorkspaceOnboardingId\(rawWorkspaceId\)/);
assert.match(accessKeyManagerUi, /const displayName = inputs\.displayName\?\.value\?\.trim\(\) \|\| rawWorkspaceId \|\| workspaceId/);
assert.match(accessKeyManagerUi, /\.toLowerCase\(\)/);
assert.match(accessKeyManagerUi, /createWorkspaceOnboardingRunState\(state\.workspaceOnboardingPlan \|\| \{\}, payload\)/);
assert.match(accessKeyManagerUi, /createWorkspaceOnboardingRunStatePlan/);
assert.match(accessKeyManagerUi, /workspaceOnboardingPlanMatchesPayload\(state\.workspaceOnboardingPlan, payload\)[\s\S]*?await requestWorkspaceOnboardingPlan\(payload\)/);
assert.match(accessKeyManagerUi, /state\.workspaceOnboardingRun = createWorkspaceOnboardingRunState\(plan, payload\)/);
assert.match(accessKeyManagerUi, /state\.workspaceOnboardingResult \|\| state\.workspaceOnboardingRun \|\| state\.workspaceOnboardingPlan/);
assert.match(accessKeyManagerUi, /progressMessage: "请求已发送/);
assert.match(accessKeyManagerUi, /progressHint: index === 0 \? "已开始" : "等待后端回执"/);
assert.match(accessKeyManagerUi, /failWorkspaceOnboardingRunState/);
const applyFunctionMatch = accessKeyManagerUi.match(/async function applyWorkspaceOnboardingFromAccessKeyManager\(\) \{[\s\S]*?\n\}/);
assert.ok(applyFunctionMatch, "apply function must exist");
assert.doesNotMatch(applyFunctionMatch[0], /window\.confirm/);

assert.match(accessKeyManagerUi, /redactedWorkspaceOnboardingResult\(result = \{\}\)/);
assert.match(accessKeyManagerUi, /redactedWorkspaceOnboardingResultPlan/);
assert.match(accessKeyManagerUi, /homeAiAccessKey: Boolean\(safe\.credentials\.homeAiAccessKey\)/);
assert.match(accessKeyManagerUi, /const oneTimeKey = result\?\.credentials\?\.homeAiAccessKey \|\| ""/);
assert.match(accessKeyManagerUi, /state\.workspaceOnboardingResult = redactedWorkspaceOnboardingResult\(result\)/);
assert.match(accessKeyManagerUi, /state\.generatedAccessKey = \{[\s\S]*key: oneTimeKey/);
assert.doesNotMatch(accessKeyManagerUi, /console\.(log|info|warn|error)\([^)]*homeAiAccessKey/);
assert.doesNotMatch(accessKeyManagerUi, /window\.confirm/);
assert.match(accessKeyManagerUi, /function openAccessKeyConfirmDialog\(options = \{\}\)/);
assert.match(indexHtml, /id="accessKeyConfirmOverlay"/);
assert.match(accessKeyManagerUi, /const overlay = \$\("accessKeyConfirmOverlay"\)/);
assert.match(accessKeyManagerUi, /id="accessKeyConfirmTitle"/);
assert.match(workspaceAdminUi, /#accessKeyOverlay,#accessKeyConfirmOverlay,#runtimeConfigOverlay/);
assert.match(accessKeyManagerUi, /data-access-key-confirm-approve/);
assert.match(accessKeyManagerUi, /data-access-key-confirm-cancel/);
assert.match(accessKeyManagerUi, /ownerAccessKeyConfirmationPlan/);
assert.match(accessKeyManagerUi, /workspaceAccessKeyConfirmationPlan/);
assert.match(accessKeyManagerUi, /deleteWorkspaceConfirmationPlan/);
assert.match(accessKeyManagerUi, /async function rotateWebAccessKey\(\)[\s\S]*?title: "更换 Owner Key"[\s\S]*?await openAccessKeyConfirmDialog\(confirmPlan\)/);
assert.match(accessKeyManagerUi, /async function generateWorkspaceAccessKey\(workspaceId\)[\s\S]*?title: "更换 Workspace Key"[\s\S]*?await openAccessKeyConfirmDialog\(confirmPlan\)/);
assert.match(accessKeyManagerUi, /async function revokeWorkspaceAccessKey\(workspaceId\)[\s\S]*?title: "撤销 Workspace Key"[\s\S]*?await openAccessKeyConfirmDialog\(confirmPlan\)/);
assert.match(accessKeyManagerUi, /async function deleteWorkspaceFromAccessKeyManager\(workspaceId\)[\s\S]*?title: "删除本地用户工作区"[\s\S]*?await openAccessKeyConfirmDialog\(confirmPlan\)/);

assert.match(stylesCss, /\.workspace-onboarding-section/);
assert.match(stylesCss, /\.workspace-onboarding-plugins/);
assert.match(stylesCss, /\.workspace-onboarding-status\.ok/);
assert.match(stylesCss, /\.workspace-onboarding-status\.running/);
assert.match(stylesCss, /\.workspace-onboarding-progress/);
assert.match(stylesCss, /\.workspace-onboarding-step/);
assert.match(stylesCss, /\.workspace-onboarding-step small/);
assert.match(stylesCss, /\.access-key-confirm-sheet/);
assert.match(stylesCss, /\.access-key-confirm-actions/);
assert.match(stylesCss, /\.access-key-confirm-approve\.danger/);

console.log("workspace onboarding UI harness passed");
